.....
----------------------------------------------------------------------
Ran 5 tests in 0.001s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.001s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.010s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.001s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.002s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.001s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.001s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.001s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.006s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.001s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.002s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.001s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.001s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.001s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.002s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.001s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.005s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.001s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.001s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.001s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.001s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.001s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.001s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.001s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.002s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.001s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.001s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.001s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.001s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.002s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.002s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.001s

OK
.....F.F
======================================================================
FAIL: test_calculate_6 (ClassEval_16_0.CalculatorTestCalculate)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_16_0.py", line 152, in test_calculate_6
    self.assertEqual(res, 6)
AssertionError: None != 6

======================================================================
FAIL: test_calculate_8 (ClassEval_16_0.CalculatorTestCalculate)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_16_0.py", line 162, in test_calculate_8
    self.assertEqual(res, 3)
AssertionError: None != 3

----------------------------------------------------------------------
Ran 8 tests in 0.001s

FAILED (failures=2)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.001s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....F.F
======================================================================
FAIL: test_calculate_6 (ClassEval_16_1.CalculatorTestCalculate)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_16_1.py", line 146, in test_calculate_6
    self.assertEqual(res, 6)
AssertionError: None != 6

======================================================================
FAIL: test_calculate_8 (ClassEval_16_1.CalculatorTestCalculate)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_16_1.py", line 156, in test_calculate_8
    self.assertEqual(res, 3)
AssertionError: None != 3

----------------------------------------------------------------------
Ran 8 tests in 0.002s

FAILED (failures=2)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.001s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.001s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.001s

OK
.....F.F
======================================================================
FAIL: test_calculate_6 (ClassEval_16_2.CalculatorTestCalculate)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_16_2.py", line 160, in test_calculate_6
    self.assertEqual(res, 6)
AssertionError: None != 6

======================================================================
FAIL: test_calculate_8 (ClassEval_16_2.CalculatorTestCalculate)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_16_2.py", line 170, in test_calculate_8
    self.assertEqual(res, 3)
AssertionError: None != 3

----------------------------------------------------------------------
Ran 8 tests in 0.001s

FAILED (failures=2)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.......F
======================================================================
FAIL: test_calculate_8 (ClassEval_16_3.CalculatorTestCalculate)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_16_3.py", line 163, in test_calculate_8
    self.assertEqual(res, 3)
AssertionError: None != 3

----------------------------------------------------------------------
Ran 8 tests in 0.001s

FAILED (failures=1)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....F.F
======================================================================
FAIL: test_calculate_6 (ClassEval_16_4.CalculatorTestCalculate)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_16_4.py", line 154, in test_calculate_6
    self.assertEqual(res, 6)
AssertionError: None != 6

======================================================================
FAIL: test_calculate_8 (ClassEval_16_4.CalculatorTestCalculate)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_16_4.py", line 164, in test_calculate_8
    self.assertEqual(res, 3)
AssertionError: None != 3

----------------------------------------------------------------------
Ran 8 tests in 0.001s

FAILED (failures=2)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.001s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.002s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.001s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.001s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.001s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
..F.F
======================================================================
FAIL: test_count_all_3 (ClassEval_23_0.CombinationCalculatorTestCountAll)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_23_0.py", line 125, in test_count_all_3
    self.assertEqual(CombinationCalculator.count_all(65), False)
AssertionError: inf != False

======================================================================
FAIL: test_count_all_5 (ClassEval_23_0.CombinationCalculatorTestCountAll)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_23_0.py", line 131, in test_count_all_5
    self.assertEqual(CombinationCalculator.count_all(63), float("inf"))
AssertionError: 9223372036854775807 != inf

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=2)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.EF.F
======================================================================
ERROR: test_count_all_2 (ClassEval_23_1.CombinationCalculatorTestCountAll)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_23_1.py", line 143, in test_count_all_2
    self.assertEqual(CombinationCalculator.count_all(-1), False)
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_23_1.py", line 48, in count_all
    total = (1 << n) - 1
ValueError: negative shift count

======================================================================
FAIL: test_count_all_3 (ClassEval_23_1.CombinationCalculatorTestCountAll)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_23_1.py", line 146, in test_count_all_3
    self.assertEqual(CombinationCalculator.count_all(65), False)
AssertionError: inf != False

======================================================================
FAIL: test_count_all_5 (ClassEval_23_1.CombinationCalculatorTestCountAll)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_23_1.py", line 152, in test_count_all_5
    self.assertEqual(CombinationCalculator.count_all(63), float("inf"))
AssertionError: 9223372036854775807 != inf

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=2, errors=1)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.EF.F
======================================================================
ERROR: test_count_all_2 (ClassEval_23_2.CombinationCalculatorTestCountAll)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_23_2.py", line 134, in test_count_all_2
    self.assertEqual(CombinationCalculator.count_all(-1), False)
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_23_2.py", line 51, in count_all
    total = (1 << n) - 1
ValueError: negative shift count

======================================================================
FAIL: test_count_all_3 (ClassEval_23_2.CombinationCalculatorTestCountAll)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_23_2.py", line 137, in test_count_all_3
    self.assertEqual(CombinationCalculator.count_all(65), False)
AssertionError: inf != False

======================================================================
FAIL: test_count_all_5 (ClassEval_23_2.CombinationCalculatorTestCountAll)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_23_2.py", line 143, in test_count_all_5
    self.assertEqual(CombinationCalculator.count_all(63), float("inf"))
AssertionError: 9223372036854775807 != inf

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=2, errors=1)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
..F.F
======================================================================
FAIL: test_count_all_3 (ClassEval_23_3.CombinationCalculatorTestCountAll)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_23_3.py", line 131, in test_count_all_3
    self.assertEqual(CombinationCalculator.count_all(65), False)
AssertionError: inf != False

======================================================================
FAIL: test_count_all_5 (ClassEval_23_3.CombinationCalculatorTestCountAll)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_23_3.py", line 137, in test_count_all_5
    self.assertEqual(CombinationCalculator.count_all(63), float("inf"))
AssertionError: 9223372036854775807 != inf

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=2)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
..F.F
======================================================================
FAIL: test_count_all_3 (ClassEval_23_4.CombinationCalculatorTestCountAll)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_23_4.py", line 147, in test_count_all_3
    self.assertEqual(CombinationCalculator.count_all(65), False)
AssertionError: inf != False

======================================================================
FAIL: test_count_all_5 (ClassEval_23_4.CombinationCalculatorTestCountAll)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_23_4.py", line 153, in test_count_all_5
    self.assertEqual(CombinationCalculator.count_all(63), float("inf"))
AssertionError: 9223372036854775807 != inf

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=2)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.001s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.001s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.001s

OK
.FFFF
======================================================================
FAIL: test_get_correlation_2 (ClassEval_30_0.DataStatistics2TestGetCorrelation)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_30_0.py", line 239, in test_get_correlation_2
    self.assertEqual(res, 1.0)
AssertionError: -0.49 != 1.0

======================================================================
FAIL: test_get_correlation_3 (ClassEval_30_0.DataStatistics2TestGetCorrelation)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_30_0.py", line 244, in test_get_correlation_3
    self.assertEqual(res, 1.0)
AssertionError: -0.65 != 1.0

======================================================================
FAIL: test_get_correlation_4 (ClassEval_30_0.DataStatistics2TestGetCorrelation)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_30_0.py", line 249, in test_get_correlation_4
    self.assertEqual(res, 1.0)
AssertionError: -0.65 != 1.0

======================================================================
FAIL: test_get_correlation_5 (ClassEval_30_0.DataStatistics2TestGetCorrelation)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_30_0.py", line 254, in test_get_correlation_5
    self.assertEqual(res, 1.0)
AssertionError: -0.65 != 1.0

----------------------------------------------------------------------
Ran 5 tests in 0.005s

FAILED (failures=4)
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.001s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.001s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.001s

OK
.FFFF
======================================================================
FAIL: test_get_correlation_2 (ClassEval_30_2.DataStatistics2TestGetCorrelation)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_30_2.py", line 238, in test_get_correlation_2
    self.assertEqual(res, 1.0)
AssertionError: np.float64(0.27) != 1.0

======================================================================
FAIL: test_get_correlation_3 (ClassEval_30_2.DataStatistics2TestGetCorrelation)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_30_2.py", line 243, in test_get_correlation_3
    self.assertEqual(res, 1.0)
AssertionError: np.float64(0.2) != 1.0

======================================================================
FAIL: test_get_correlation_4 (ClassEval_30_2.DataStatistics2TestGetCorrelation)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_30_2.py", line 248, in test_get_correlation_4
    self.assertEqual(res, 1.0)
AssertionError: np.float64(0.2) != 1.0

======================================================================
FAIL: test_get_correlation_5 (ClassEval_30_2.DataStatistics2TestGetCorrelation)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_30_2.py", line 253, in test_get_correlation_5
    self.assertEqual(res, 1.0)
AssertionError: np.float64(0.2) != 1.0

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=4)
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.001s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.001s

OK
.FFFF
======================================================================
FAIL: test_get_correlation_2 (ClassEval_30_4.DataStatistics2TestGetCorrelation)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_30_4.py", line 238, in test_get_correlation_2
    self.assertEqual(res, 1.0)
AssertionError: 0.27 != 1.0

======================================================================
FAIL: test_get_correlation_3 (ClassEval_30_4.DataStatistics2TestGetCorrelation)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_30_4.py", line 243, in test_get_correlation_3
    self.assertEqual(res, 1.0)
AssertionError: 0.2 != 1.0

======================================================================
FAIL: test_get_correlation_4 (ClassEval_30_4.DataStatistics2TestGetCorrelation)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_30_4.py", line 248, in test_get_correlation_4
    self.assertEqual(res, 1.0)
AssertionError: 0.2 != 1.0

======================================================================
FAIL: test_get_correlation_5 (ClassEval_30_4.DataStatistics2TestGetCorrelation)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_30_4.py", line 253, in test_get_correlation_5
    self.assertEqual(res, 1.0)
AssertionError: 0.2 != 1.0

----------------------------------------------------------------------
Ran 5 tests in 0.002s

FAILED (failures=4)
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
FEF.F
======================================================================
ERROR: test_correlation_coefficient_2 (ClassEval_31_0.DataStatistics4TestCorrelationCoefficient)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_31_0.py", line 124, in test_correlation_coefficient_2
    self.assertEqual(DataStatistics4.correlation_coefficient([1, 1, 1], [2, 2, 2]), 0)
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_31_0.py", line 39, in correlation_coefficient
    raise ValueError("division by zero in correlation calculation")
ValueError: division by zero in correlation calculation

======================================================================
FAIL: test_correlation_coefficient (ClassEval_31_0.DataStatistics4TestCorrelationCoefficient)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_31_0.py", line 121, in test_correlation_coefficient
    self.assertEqual(DataStatistics4.correlation_coefficient([1, 2, 3], [4, 5, 6]), 0.9999999999999998)
AssertionError: 1.0 != 0.9999999999999998

======================================================================
FAIL: test_correlation_coefficient_3 (ClassEval_31_0.DataStatistics4TestCorrelationCoefficient)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_31_0.py", line 127, in test_correlation_coefficient_3
    self.assertEqual(DataStatistics4.correlation_coefficient([1, 2, 3], [1, 2, 3]), 0.9999999999999998)
AssertionError: 1.0 != 0.9999999999999998

======================================================================
FAIL: test_correlation_coefficient_5 (ClassEval_31_0.DataStatistics4TestCorrelationCoefficient)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_31_0.py", line 133, in test_correlation_coefficient_5
    self.assertEqual(DataStatistics4.correlation_coefficient([1, 2, 3], [1, 5, 3]), 0.4999999999999999)
AssertionError: 0.5 != 0.4999999999999999

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=3, errors=1)
F..F.
======================================================================
FAIL: test_skewness (ClassEval_31_0.DataStatistics4TestSkewness)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_31_0.py", line 138, in test_skewness
    self.assertEqual(DataStatistics4.skewness([1, 2, 5]), 2.3760224064818463)
AssertionError: 2.3760224064818467 != 2.3760224064818463

======================================================================
FAIL: test_skewness_4 (ClassEval_31_0.DataStatistics4TestSkewness)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_31_0.py", line 147, in test_skewness_4
    self.assertEqual(DataStatistics4.skewness([1, 2, 4]), 1.7181079837227264)
AssertionError: 1.7181079837227267 != 1.7181079837227264

----------------------------------------------------------------------
Ran 5 tests in 0.000s

FAILED (failures=2)
F.F.F
======================================================================
FAIL: test_kurtosis (ClassEval_31_0.DataStatistics4TestKurtosis)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_31_0.py", line 155, in test_kurtosis
    self.assertEqual(DataStatistics4.kurtosis([1, 2, 5]), -1.5000000000000002)
AssertionError: -1.5 != -1.5000000000000002

======================================================================
FAIL: test_kurtosis_3 (ClassEval_31_0.DataStatistics4TestKurtosis)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_31_0.py", line 161, in test_kurtosis_3
    self.assertEqual(DataStatistics4.kurtosis([1, 2, 3]), -1.5000000000000002)
AssertionError: -1.5 != -1.5000000000000002

======================================================================
FAIL: test_kurtosis_5 (ClassEval_31_0.DataStatistics4TestKurtosis)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_31_0.py", line 167, in test_kurtosis_5
    self.assertEqual(DataStatistics4.kurtosis([1, 5, 3]), -1.5000000000000002)
AssertionError: -1.5 != -1.5000000000000002

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=3)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
F
======================================================================
FAIL: test_main (ClassEval_31_0.DataStatistics4TestMain)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_31_0.py", line 194, in test_main
    self.assertEqual(DataStatistics4.correlation_coefficient([1, 2, 3], [4, 5, 6]), 0.9999999999999998)
AssertionError: 1.0 != 0.9999999999999998

----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (failures=1)
F.F.F
======================================================================
FAIL: test_correlation_coefficient (ClassEval_31_1.DataStatistics4TestCorrelationCoefficient)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_31_1.py", line 109, in test_correlation_coefficient
    self.assertEqual(DataStatistics4.correlation_coefficient([1, 2, 3], [4, 5, 6]), 0.9999999999999998)
AssertionError: 1.0 != 0.9999999999999998

======================================================================
FAIL: test_correlation_coefficient_3 (ClassEval_31_1.DataStatistics4TestCorrelationCoefficient)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_31_1.py", line 115, in test_correlation_coefficient_3
    self.assertEqual(DataStatistics4.correlation_coefficient([1, 2, 3], [1, 2, 3]), 0.9999999999999998)
AssertionError: 1.0 != 0.9999999999999998

======================================================================
FAIL: test_correlation_coefficient_5 (ClassEval_31_1.DataStatistics4TestCorrelationCoefficient)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_31_1.py", line 121, in test_correlation_coefficient_5
    self.assertEqual(DataStatistics4.correlation_coefficient([1, 2, 3], [1, 5, 3]), 0.4999999999999999)
AssertionError: 0.5 != 0.4999999999999999

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=3)
F..F.
======================================================================
FAIL: test_skewness (ClassEval_31_1.DataStatistics4TestSkewness)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_31_1.py", line 126, in test_skewness
    self.assertEqual(DataStatistics4.skewness([1, 2, 5]), 2.3760224064818463)
AssertionError: 2.3760224064818454 != 2.3760224064818463

======================================================================
FAIL: test_skewness_4 (ClassEval_31_1.DataStatistics4TestSkewness)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_31_1.py", line 135, in test_skewness_4
    self.assertEqual(DataStatistics4.skewness([1, 2, 4]), 1.7181079837227264)
AssertionError: 1.7181079837227267 != 1.7181079837227264

----------------------------------------------------------------------
Ran 5 tests in 0.000s

FAILED (failures=2)
.FFFF
======================================================================
FAIL: test_kurtosis_2 (ClassEval_31_1.DataStatistics4TestKurtosis)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_31_1.py", line 146, in test_kurtosis_2
    self.assertTrue(math.isnan(DataStatistics4.kurtosis([1, 1, 1])))
AssertionError: False is not true

======================================================================
FAIL: test_kurtosis_3 (ClassEval_31_1.DataStatistics4TestKurtosis)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_31_1.py", line 149, in test_kurtosis_3
    self.assertEqual(DataStatistics4.kurtosis([1, 2, 3]), -1.5000000000000002)
AssertionError: -1.5 != -1.5000000000000002

======================================================================
FAIL: test_kurtosis_4 (ClassEval_31_1.DataStatistics4TestKurtosis)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_31_1.py", line 152, in test_kurtosis_4
    self.assertEqual(DataStatistics4.kurtosis([1, 2, 4]), -1.4999999999999996)
AssertionError: -1.4999999999999998 != -1.4999999999999996

======================================================================
FAIL: test_kurtosis_5 (ClassEval_31_1.DataStatistics4TestKurtosis)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_31_1.py", line 155, in test_kurtosis_5
    self.assertEqual(DataStatistics4.kurtosis([1, 5, 3]), -1.5000000000000002)
AssertionError: -1.5 != -1.5000000000000002

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=4)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
F
======================================================================
FAIL: test_main (ClassEval_31_1.DataStatistics4TestMain)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_31_1.py", line 182, in test_main
    self.assertEqual(DataStatistics4.correlation_coefficient([1, 2, 3], [4, 5, 6]), 0.9999999999999998)
AssertionError: 1.0 != 0.9999999999999998

----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (failures=1)
F.F.F
======================================================================
FAIL: test_correlation_coefficient (ClassEval_31_2.DataStatistics4TestCorrelationCoefficient)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_31_2.py", line 89, in test_correlation_coefficient
    self.assertEqual(DataStatistics4.correlation_coefficient([1, 2, 3], [4, 5, 6]), 0.9999999999999998)
AssertionError: 1.0 != 0.9999999999999998

======================================================================
FAIL: test_correlation_coefficient_3 (ClassEval_31_2.DataStatistics4TestCorrelationCoefficient)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_31_2.py", line 95, in test_correlation_coefficient_3
    self.assertEqual(DataStatistics4.correlation_coefficient([1, 2, 3], [1, 2, 3]), 0.9999999999999998)
AssertionError: 1.0 != 0.9999999999999998

======================================================================
FAIL: test_correlation_coefficient_5 (ClassEval_31_2.DataStatistics4TestCorrelationCoefficient)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_31_2.py", line 101, in test_correlation_coefficient_5
    self.assertEqual(DataStatistics4.correlation_coefficient([1, 2, 3], [1, 5, 3]), 0.4999999999999999)
AssertionError: 0.5 != 0.4999999999999999

----------------------------------------------------------------------
Ran 5 tests in 0.002s

FAILED (failures=3)
F..F.
======================================================================
FAIL: test_skewness (ClassEval_31_2.DataStatistics4TestSkewness)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_31_2.py", line 106, in test_skewness
    self.assertEqual(DataStatistics4.skewness([1, 2, 5]), 2.3760224064818463)
AssertionError: 2.3760224064818454 != 2.3760224064818463

======================================================================
FAIL: test_skewness_4 (ClassEval_31_2.DataStatistics4TestSkewness)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_31_2.py", line 115, in test_skewness_4
    self.assertEqual(DataStatistics4.skewness([1, 2, 4]), 1.7181079837227264)
AssertionError: 1.7181079837227267 != 1.7181079837227264

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=2)
.FF.F
======================================================================
FAIL: test_kurtosis_2 (ClassEval_31_2.DataStatistics4TestKurtosis)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_31_2.py", line 126, in test_kurtosis_2
    self.assertTrue(math.isnan(DataStatistics4.kurtosis([1, 1, 1])))
AssertionError: False is not true

======================================================================
FAIL: test_kurtosis_3 (ClassEval_31_2.DataStatistics4TestKurtosis)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_31_2.py", line 129, in test_kurtosis_3
    self.assertEqual(DataStatistics4.kurtosis([1, 2, 3]), -1.5000000000000002)
AssertionError: -1.5 != -1.5000000000000002

======================================================================
FAIL: test_kurtosis_5 (ClassEval_31_2.DataStatistics4TestKurtosis)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_31_2.py", line 135, in test_kurtosis_5
    self.assertEqual(DataStatistics4.kurtosis([1, 5, 3]), -1.5000000000000002)
AssertionError: -1.5 != -1.5000000000000002

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=3)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
F
======================================================================
FAIL: test_main (ClassEval_31_2.DataStatistics4TestMain)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_31_2.py", line 162, in test_main
    self.assertEqual(DataStatistics4.correlation_coefficient([1, 2, 3], [4, 5, 6]), 0.9999999999999998)
AssertionError: 1.0 != 0.9999999999999998

----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (failures=1)
F.F.F
======================================================================
FAIL: test_correlation_coefficient (ClassEval_31_3.DataStatistics4TestCorrelationCoefficient)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_31_3.py", line 91, in test_correlation_coefficient
    self.assertEqual(DataStatistics4.correlation_coefficient([1, 2, 3], [4, 5, 6]), 0.9999999999999998)
AssertionError: 1.0 != 0.9999999999999998

======================================================================
FAIL: test_correlation_coefficient_3 (ClassEval_31_3.DataStatistics4TestCorrelationCoefficient)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_31_3.py", line 97, in test_correlation_coefficient_3
    self.assertEqual(DataStatistics4.correlation_coefficient([1, 2, 3], [1, 2, 3]), 0.9999999999999998)
AssertionError: 1.0 != 0.9999999999999998

======================================================================
FAIL: test_correlation_coefficient_5 (ClassEval_31_3.DataStatistics4TestCorrelationCoefficient)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_31_3.py", line 103, in test_correlation_coefficient_5
    self.assertEqual(DataStatistics4.correlation_coefficient([1, 2, 3], [1, 5, 3]), 0.4999999999999999)
AssertionError: 0.5 != 0.4999999999999999

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=3)
F..F.
======================================================================
FAIL: test_skewness (ClassEval_31_3.DataStatistics4TestSkewness)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_31_3.py", line 108, in test_skewness
    self.assertEqual(DataStatistics4.skewness([1, 2, 5]), 2.3760224064818463)
AssertionError: 2.3760224064818454 != 2.3760224064818463

======================================================================
FAIL: test_skewness_4 (ClassEval_31_3.DataStatistics4TestSkewness)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_31_3.py", line 117, in test_skewness_4
    self.assertEqual(DataStatistics4.skewness([1, 2, 4]), 1.7181079837227264)
AssertionError: 1.7181079837227267 != 1.7181079837227264

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=2)
..F.F
======================================================================
FAIL: test_kurtosis_3 (ClassEval_31_3.DataStatistics4TestKurtosis)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_31_3.py", line 131, in test_kurtosis_3
    self.assertEqual(DataStatistics4.kurtosis([1, 2, 3]), -1.5000000000000002)
AssertionError: -1.5 != -1.5000000000000002

======================================================================
FAIL: test_kurtosis_5 (ClassEval_31_3.DataStatistics4TestKurtosis)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_31_3.py", line 137, in test_kurtosis_5
    self.assertEqual(DataStatistics4.kurtosis([1, 5, 3]), -1.5000000000000002)
AssertionError: -1.5 != -1.5000000000000002

----------------------------------------------------------------------
Ran 5 tests in 0.000s

FAILED (failures=2)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
F
======================================================================
FAIL: test_main (ClassEval_31_3.DataStatistics4TestMain)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_31_3.py", line 164, in test_main
    self.assertEqual(DataStatistics4.correlation_coefficient([1, 2, 3], [4, 5, 6]), 0.9999999999999998)
AssertionError: 1.0 != 0.9999999999999998

----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (failures=1)
F.F.F
======================================================================
FAIL: test_correlation_coefficient (ClassEval_31_4.DataStatistics4TestCorrelationCoefficient)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_31_4.py", line 118, in test_correlation_coefficient
    self.assertEqual(DataStatistics4.correlation_coefficient([1, 2, 3], [4, 5, 6]), 0.9999999999999998)
AssertionError: 1.0 != 0.9999999999999998

======================================================================
FAIL: test_correlation_coefficient_3 (ClassEval_31_4.DataStatistics4TestCorrelationCoefficient)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_31_4.py", line 124, in test_correlation_coefficient_3
    self.assertEqual(DataStatistics4.correlation_coefficient([1, 2, 3], [1, 2, 3]), 0.9999999999999998)
AssertionError: 1.0 != 0.9999999999999998

======================================================================
FAIL: test_correlation_coefficient_5 (ClassEval_31_4.DataStatistics4TestCorrelationCoefficient)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_31_4.py", line 130, in test_correlation_coefficient_5
    self.assertEqual(DataStatistics4.correlation_coefficient([1, 2, 3], [1, 5, 3]), 0.4999999999999999)
AssertionError: 0.5 != 0.4999999999999999

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=3)
F..F.
======================================================================
FAIL: test_skewness (ClassEval_31_4.DataStatistics4TestSkewness)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_31_4.py", line 135, in test_skewness
    self.assertEqual(DataStatistics4.skewness([1, 2, 5]), 2.3760224064818463)
AssertionError: 2.3760224064818467 != 2.3760224064818463

======================================================================
FAIL: test_skewness_4 (ClassEval_31_4.DataStatistics4TestSkewness)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_31_4.py", line 144, in test_skewness_4
    self.assertEqual(DataStatistics4.skewness([1, 2, 4]), 1.7181079837227264)
AssertionError: 1.7181079837227267 != 1.7181079837227264

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=2)
FFFFF
======================================================================
FAIL: test_kurtosis (ClassEval_31_4.DataStatistics4TestKurtosis)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_31_4.py", line 152, in test_kurtosis
    self.assertEqual(DataStatistics4.kurtosis([1, 2, 5]), -1.5000000000000002)
AssertionError: -1.5 != -1.5000000000000002

======================================================================
FAIL: test_kurtosis_2 (ClassEval_31_4.DataStatistics4TestKurtosis)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_31_4.py", line 155, in test_kurtosis_2
    self.assertTrue(math.isnan(DataStatistics4.kurtosis([1, 1, 1])))
AssertionError: False is not true

======================================================================
FAIL: test_kurtosis_3 (ClassEval_31_4.DataStatistics4TestKurtosis)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_31_4.py", line 158, in test_kurtosis_3
    self.assertEqual(DataStatistics4.kurtosis([1, 2, 3]), -1.5000000000000002)
AssertionError: -1.5 != -1.5000000000000002

======================================================================
FAIL: test_kurtosis_4 (ClassEval_31_4.DataStatistics4TestKurtosis)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_31_4.py", line 161, in test_kurtosis_4
    self.assertEqual(DataStatistics4.kurtosis([1, 2, 4]), -1.4999999999999996)
AssertionError: -1.4999999999999998 != -1.4999999999999996

======================================================================
FAIL: test_kurtosis_5 (ClassEval_31_4.DataStatistics4TestKurtosis)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_31_4.py", line 164, in test_kurtosis_5
    self.assertEqual(DataStatistics4.kurtosis([1, 5, 3]), -1.5000000000000002)
AssertionError: -1.5 != -1.5000000000000002

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=5)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
F
======================================================================
FAIL: test_main (ClassEval_31_4.DataStatistics4TestMain)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_31_4.py", line 191, in test_main
    self.assertEqual(DataStatistics4.correlation_coefficient([1, 2, 3], [4, 5, 6]), 0.9999999999999998)
AssertionError: 1.0 != 0.9999999999999998

----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (failures=1)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
..FFFFF
======================================================================
FAIL: test_compare_3 (ClassEval_39_0.ExpressionCalculatorTestCompare)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_39_0.py", line 251, in test_compare_3
    self.assertTrue(result)
AssertionError: False is not true

======================================================================
FAIL: test_compare_4 (ClassEval_39_0.ExpressionCalculatorTestCompare)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_39_0.py", line 255, in test_compare_4
    self.assertFalse(result)
AssertionError: True is not false

======================================================================
FAIL: test_compare_5 (ClassEval_39_0.ExpressionCalculatorTestCompare)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_39_0.py", line 259, in test_compare_5
    self.assertFalse(result)
AssertionError: True is not false

======================================================================
FAIL: test_compare_6 (ClassEval_39_0.ExpressionCalculatorTestCompare)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_39_0.py", line 263, in test_compare_6
    self.assertFalse(result)
AssertionError: True is not false

======================================================================
FAIL: test_compare_7 (ClassEval_39_0.ExpressionCalculatorTestCompare)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_39_0.py", line 267, in test_compare_7
    self.assertTrue(result)
AssertionError: False is not true

----------------------------------------------------------------------
Ran 7 tests in 0.001s

FAILED (failures=5)
.......
----------------------------------------------------------------------
Ran 7 tests in 0.000s

OK
....FF
======================================================================
FAIL: test_transform_5 (ClassEval_39_0.ExpressionCalculatorTestTransform)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_39_0.py", line 327, in test_transform_5
    self.assertEqual(result, "~2+(~3)*4")
AssertionError: '-2+(-3)*4' != '~2+(~3)*4'
- -2+(-3)*4
? ^   ^
+ ~2+(~3)*4
? ^   ^


======================================================================
FAIL: test_transform_6 (ClassEval_39_0.ExpressionCalculatorTestTransform)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_39_0.py", line 331, in test_transform_6
    self.assertEqual(result, "0-(1+1)")
AssertionError: '~(1+1)' != '0-(1+1)'
- ~(1+1)
? ^
+ 0-(1+1)
? ^^


----------------------------------------------------------------------
Ran 6 tests in 0.001s

FAILED (failures=2)
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
FFFFFF
======================================================================
FAIL: test_prepare_1 (ClassEval_39_1.ExpressionCalculatorTestPrepare)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_39_1.py", line 208, in test_prepare_1
    self.assertEqual(self.expression_calculator.postfix_stack, deque(['2', '3', '4', '*', '+']))
AssertionError: ['2', '3', '4', '*', '+'] != deque(['2', '3', '4', '*', '+'])

======================================================================
FAIL: test_prepare_2 (ClassEval_39_1.ExpressionCalculatorTestPrepare)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_39_1.py", line 212, in test_prepare_2
    self.assertEqual(self.expression_calculator.postfix_stack, deque(['2', '3', '4', '/', '+']))
AssertionError: ['2', '3', '4', '/', '+'] != deque(['2', '3', '4', '/', '+'])

======================================================================
FAIL: test_prepare_3 (ClassEval_39_1.ExpressionCalculatorTestPrepare)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_39_1.py", line 216, in test_prepare_3
    self.assertEqual(self.expression_calculator.postfix_stack, deque(['2', '3', '4', '*', '-']))
AssertionError: ['2', '3', '4', '*', '-'] != deque(['2', '3', '4', '*', '-'])

======================================================================
FAIL: test_prepare_4 (ClassEval_39_1.ExpressionCalculatorTestPrepare)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_39_1.py", line 220, in test_prepare_4
    self.assertEqual(self.expression_calculator.postfix_stack, deque(['1', '3', '4', '*', '+']))
AssertionError: ['1', '3', '4', '*', '+'] != deque(['1', '3', '4', '*', '+'])

======================================================================
FAIL: test_prepare_5 (ClassEval_39_1.ExpressionCalculatorTestPrepare)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_39_1.py", line 224, in test_prepare_5
    self.assertEqual(self.expression_calculator.postfix_stack, deque(['2', '3', '+', '4', '*']))
AssertionError: ['2', '3', '+', '4', '*'] != deque(['2', '3', '+', '4', '*'])

======================================================================
FAIL: test_prepare_6 (ClassEval_39_1.ExpressionCalculatorTestPrepare)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_39_1.py", line 228, in test_prepare_6
    self.assertEqual(self.expression_calculator.postfix_stack, deque([]))
AssertionError: [] != deque([])

----------------------------------------------------------------------
Ran 6 tests in 0.001s

FAILED (failures=6)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
..FFFFF
======================================================================
FAIL: test_compare_3 (ClassEval_39_1.ExpressionCalculatorTestCompare)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_39_1.py", line 265, in test_compare_3
    self.assertTrue(result)
AssertionError: False is not true

======================================================================
FAIL: test_compare_4 (ClassEval_39_1.ExpressionCalculatorTestCompare)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_39_1.py", line 269, in test_compare_4
    self.assertFalse(result)
AssertionError: True is not false

======================================================================
FAIL: test_compare_5 (ClassEval_39_1.ExpressionCalculatorTestCompare)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_39_1.py", line 273, in test_compare_5
    self.assertFalse(result)
AssertionError: True is not false

======================================================================
FAIL: test_compare_6 (ClassEval_39_1.ExpressionCalculatorTestCompare)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_39_1.py", line 277, in test_compare_6
    self.assertFalse(result)
AssertionError: True is not false

======================================================================
FAIL: test_compare_7 (ClassEval_39_1.ExpressionCalculatorTestCompare)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_39_1.py", line 281, in test_compare_7
    self.assertTrue(result)
AssertionError: False is not true

----------------------------------------------------------------------
Ran 7 tests in 0.001s

FAILED (failures=5)
.......
----------------------------------------------------------------------
Ran 7 tests in 0.000s

OK
....FF
======================================================================
FAIL: test_transform_5 (ClassEval_39_1.ExpressionCalculatorTestTransform)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_39_1.py", line 341, in test_transform_5
    self.assertEqual(result, "~2+(~3)*4")
AssertionError: '-2+(-3)*4' != '~2+(~3)*4'
- -2+(-3)*4
? ^   ^
+ ~2+(~3)*4
? ^   ^


======================================================================
FAIL: test_transform_6 (ClassEval_39_1.ExpressionCalculatorTestTransform)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_39_1.py", line 345, in test_transform_6
    self.assertEqual(result, "0-(1+1)")
AssertionError: '~(1+1)' != '0-(1+1)'
- ~(1+1)
? ^
+ 0-(1+1)
? ^^


----------------------------------------------------------------------
Ran 6 tests in 0.001s

FAILED (failures=2)
F
======================================================================
FAIL: test_ExpressionCalculator (ClassEval_39_1.ExpressionCalculatorTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_39_1.py", line 357, in test_ExpressionCalculator
    self.assertEqual(self.expression_calculator.postfix_stack, deque(['2', '3', '4', '*', '+']))
AssertionError: ['2', '3', '4', '*', '+'] != deque(['2', '3', '4', '*', '+'])

----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (failures=1)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
..FFFFF
======================================================================
FAIL: test_compare_3 (ClassEval_39_2.ExpressionCalculatorTestCompare)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_39_2.py", line 269, in test_compare_3
    self.assertTrue(result)
AssertionError: False is not true

======================================================================
FAIL: test_compare_4 (ClassEval_39_2.ExpressionCalculatorTestCompare)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_39_2.py", line 273, in test_compare_4
    self.assertFalse(result)
AssertionError: True is not false

======================================================================
FAIL: test_compare_5 (ClassEval_39_2.ExpressionCalculatorTestCompare)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_39_2.py", line 277, in test_compare_5
    self.assertFalse(result)
AssertionError: True is not false

======================================================================
FAIL: test_compare_6 (ClassEval_39_2.ExpressionCalculatorTestCompare)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_39_2.py", line 281, in test_compare_6
    self.assertFalse(result)
AssertionError: True is not false

======================================================================
FAIL: test_compare_7 (ClassEval_39_2.ExpressionCalculatorTestCompare)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_39_2.py", line 285, in test_compare_7
    self.assertTrue(result)
AssertionError: False is not true

----------------------------------------------------------------------
Ran 7 tests in 0.001s

FAILED (failures=5)
FEEEEE.
======================================================================
ERROR: test_calculate_method_2 (ClassEval_39_2.ExpressionCalculatorTestCalculateMethod)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_39_2.py", line 297, in test_calculate_method_2
    result = self.expression_calculator._calculate("3", "2", "-")
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_39_2.py", line 154, in _calculate
    return a - b
TypeError: unsupported operand type(s) for -: 'str' and 'str'

======================================================================
ERROR: test_calculate_method_3 (ClassEval_39_2.ExpressionCalculatorTestCalculateMethod)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_39_2.py", line 301, in test_calculate_method_3
    result = self.expression_calculator._calculate("2", "3", "*")
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_39_2.py", line 156, in _calculate
    return a * b
TypeError: can't multiply sequence by non-int of type 'str'

======================================================================
ERROR: test_calculate_method_4 (ClassEval_39_2.ExpressionCalculatorTestCalculateMethod)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_39_2.py", line 305, in test_calculate_method_4
    result = self.expression_calculator._calculate("3", "3", "/")
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_39_2.py", line 160, in _calculate
    return a / b
TypeError: unsupported operand type(s) for /: 'str' and 'str'

======================================================================
ERROR: test_calculate_method_5 (ClassEval_39_2.ExpressionCalculatorTestCalculateMethod)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_39_2.py", line 309, in test_calculate_method_5
    result = self.expression_calculator._calculate("6", "2", "/")
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_39_2.py", line 160, in _calculate
    return a / b
TypeError: unsupported operand type(s) for /: 'str' and 'str'

======================================================================
ERROR: test_calculate_method_6 (ClassEval_39_2.ExpressionCalculatorTestCalculateMethod)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_39_2.py", line 313, in test_calculate_method_6
    result = self.expression_calculator._calculate("6", "2", "%")
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_39_2.py", line 162, in _calculate
    return a % b
TypeError: not all arguments converted during string formatting

======================================================================
FAIL: test_calculate_method_1 (ClassEval_39_2.ExpressionCalculatorTestCalculateMethod)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_39_2.py", line 294, in test_calculate_method_1
    self.assertEqual(result, Decimal(5.0))
AssertionError: '23' != Decimal('5')

----------------------------------------------------------------------
Ran 7 tests in 0.001s

FAILED (failures=1, errors=5)
....FF
======================================================================
FAIL: test_transform_5 (ClassEval_39_2.ExpressionCalculatorTestTransform)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_39_2.py", line 345, in test_transform_5
    self.assertEqual(result, "~2+(~3)*4")
AssertionError: '-2+(-3)*4' != '~2+(~3)*4'
- -2+(-3)*4
? ^   ^
+ ~2+(~3)*4
? ^   ^


======================================================================
FAIL: test_transform_6 (ClassEval_39_2.ExpressionCalculatorTestTransform)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_39_2.py", line 349, in test_transform_6
    self.assertEqual(result, "0-(1+1)")
AssertionError: '~(1+1)' != '0-(1+1)'
- ~(1+1)
? ^
+ 0-(1+1)
? ^^


----------------------------------------------------------------------
Ran 6 tests in 0.001s

FAILED (failures=2)
F
======================================================================
FAIL: test_ExpressionCalculator (ClassEval_39_2.ExpressionCalculatorTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_39_2.py", line 369, in test_ExpressionCalculator
    self.assertEqual(result, Decimal(5.0))
AssertionError: '23' != Decimal('5')

----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (failures=1)
EEEEE
======================================================================
ERROR: test_calculate_1 (ClassEval_39_3.ExpressionCalculatorTestCalculate)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_39_3.py", line 12, in setUp
    self.expression_calculator = ExpressionCalculator()
NameError: name 'ExpressionCalculator' is not defined

======================================================================
ERROR: test_calculate_2 (ClassEval_39_3.ExpressionCalculatorTestCalculate)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_39_3.py", line 12, in setUp
    self.expression_calculator = ExpressionCalculator()
NameError: name 'ExpressionCalculator' is not defined

======================================================================
ERROR: test_calculate_3 (ClassEval_39_3.ExpressionCalculatorTestCalculate)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_39_3.py", line 12, in setUp
    self.expression_calculator = ExpressionCalculator()
NameError: name 'ExpressionCalculator' is not defined

======================================================================
ERROR: test_calculate_4 (ClassEval_39_3.ExpressionCalculatorTestCalculate)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_39_3.py", line 12, in setUp
    self.expression_calculator = ExpressionCalculator()
NameError: name 'ExpressionCalculator' is not defined

======================================================================
ERROR: test_calculate_5 (ClassEval_39_3.ExpressionCalculatorTestCalculate)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_39_3.py", line 12, in setUp
    self.expression_calculator = ExpressionCalculator()
NameError: name 'ExpressionCalculator' is not defined

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (errors=5)
EEEEEE
======================================================================
ERROR: test_prepare_1 (ClassEval_39_3.ExpressionCalculatorTestPrepare)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_39_3.py", line 37, in setUp
    self.expression_calculator = ExpressionCalculator()
NameError: name 'ExpressionCalculator' is not defined

======================================================================
ERROR: test_prepare_2 (ClassEval_39_3.ExpressionCalculatorTestPrepare)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_39_3.py", line 37, in setUp
    self.expression_calculator = ExpressionCalculator()
NameError: name 'ExpressionCalculator' is not defined

======================================================================
ERROR: test_prepare_3 (ClassEval_39_3.ExpressionCalculatorTestPrepare)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_39_3.py", line 37, in setUp
    self.expression_calculator = ExpressionCalculator()
NameError: name 'ExpressionCalculator' is not defined

======================================================================
ERROR: test_prepare_4 (ClassEval_39_3.ExpressionCalculatorTestPrepare)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_39_3.py", line 37, in setUp
    self.expression_calculator = ExpressionCalculator()
NameError: name 'ExpressionCalculator' is not defined

======================================================================
ERROR: test_prepare_5 (ClassEval_39_3.ExpressionCalculatorTestPrepare)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_39_3.py", line 37, in setUp
    self.expression_calculator = ExpressionCalculator()
NameError: name 'ExpressionCalculator' is not defined

======================================================================
ERROR: test_prepare_6 (ClassEval_39_3.ExpressionCalculatorTestPrepare)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_39_3.py", line 37, in setUp
    self.expression_calculator = ExpressionCalculator()
NameError: name 'ExpressionCalculator' is not defined

----------------------------------------------------------------------
Ran 6 tests in 0.001s

FAILED (errors=6)
EEEEE
======================================================================
ERROR: test_is_operator_1 (ClassEval_39_3.ExpressionCalculatorTestIsOperator)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_39_3.py", line 66, in setUp
    self.expression_calculator = ExpressionCalculator()
NameError: name 'ExpressionCalculator' is not defined

======================================================================
ERROR: test_is_operator_2 (ClassEval_39_3.ExpressionCalculatorTestIsOperator)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_39_3.py", line 66, in setUp
    self.expression_calculator = ExpressionCalculator()
NameError: name 'ExpressionCalculator' is not defined

======================================================================
ERROR: test_is_operator_3 (ClassEval_39_3.ExpressionCalculatorTestIsOperator)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_39_3.py", line 66, in setUp
    self.expression_calculator = ExpressionCalculator()
NameError: name 'ExpressionCalculator' is not defined

======================================================================
ERROR: test_is_operator_4 (ClassEval_39_3.ExpressionCalculatorTestIsOperator)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_39_3.py", line 66, in setUp
    self.expression_calculator = ExpressionCalculator()
NameError: name 'ExpressionCalculator' is not defined

======================================================================
ERROR: test_is_operator_5 (ClassEval_39_3.ExpressionCalculatorTestIsOperator)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_39_3.py", line 66, in setUp
    self.expression_calculator = ExpressionCalculator()
NameError: name 'ExpressionCalculator' is not defined

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (errors=5)
EEEEEEE
======================================================================
ERROR: test_compare_1 (ClassEval_39_3.ExpressionCalculatorTestCompare)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_39_3.py", line 86, in setUp
    self.expression_calculator = ExpressionCalculator()
NameError: name 'ExpressionCalculator' is not defined

======================================================================
ERROR: test_compare_2 (ClassEval_39_3.ExpressionCalculatorTestCompare)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_39_3.py", line 86, in setUp
    self.expression_calculator = ExpressionCalculator()
NameError: name 'ExpressionCalculator' is not defined

======================================================================
ERROR: test_compare_3 (ClassEval_39_3.ExpressionCalculatorTestCompare)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_39_3.py", line 86, in setUp
    self.expression_calculator = ExpressionCalculator()
NameError: name 'ExpressionCalculator' is not defined

======================================================================
ERROR: test_compare_4 (ClassEval_39_3.ExpressionCalculatorTestCompare)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_39_3.py", line 86, in setUp
    self.expression_calculator = ExpressionCalculator()
NameError: name 'ExpressionCalculator' is not defined

======================================================================
ERROR: test_compare_5 (ClassEval_39_3.ExpressionCalculatorTestCompare)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_39_3.py", line 86, in setUp
    self.expression_calculator = ExpressionCalculator()
NameError: name 'ExpressionCalculator' is not defined

======================================================================
ERROR: test_compare_6 (ClassEval_39_3.ExpressionCalculatorTestCompare)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_39_3.py", line 86, in setUp
    self.expression_calculator = ExpressionCalculator()
NameError: name 'ExpressionCalculator' is not defined

======================================================================
ERROR: test_compare_7 (ClassEval_39_3.ExpressionCalculatorTestCompare)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_39_3.py", line 86, in setUp
    self.expression_calculator = ExpressionCalculator()
NameError: name 'ExpressionCalculator' is not defined

----------------------------------------------------------------------
Ran 7 tests in 0.001s

FAILED (errors=7)
EEEEEEE
======================================================================
ERROR: test_calculate_method_1 (ClassEval_39_3.ExpressionCalculatorTestCalculateMethod)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_39_3.py", line 119, in setUp
    self.expression_calculator = ExpressionCalculator()
NameError: name 'ExpressionCalculator' is not defined

======================================================================
ERROR: test_calculate_method_2 (ClassEval_39_3.ExpressionCalculatorTestCalculateMethod)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_39_3.py", line 119, in setUp
    self.expression_calculator = ExpressionCalculator()
NameError: name 'ExpressionCalculator' is not defined

======================================================================
ERROR: test_calculate_method_3 (ClassEval_39_3.ExpressionCalculatorTestCalculateMethod)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_39_3.py", line 119, in setUp
    self.expression_calculator = ExpressionCalculator()
NameError: name 'ExpressionCalculator' is not defined

======================================================================
ERROR: test_calculate_method_4 (ClassEval_39_3.ExpressionCalculatorTestCalculateMethod)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_39_3.py", line 119, in setUp
    self.expression_calculator = ExpressionCalculator()
NameError: name 'ExpressionCalculator' is not defined

======================================================================
ERROR: test_calculate_method_5 (ClassEval_39_3.ExpressionCalculatorTestCalculateMethod)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_39_3.py", line 119, in setUp
    self.expression_calculator = ExpressionCalculator()
NameError: name 'ExpressionCalculator' is not defined

======================================================================
ERROR: test_calculate_method_6 (ClassEval_39_3.ExpressionCalculatorTestCalculateMethod)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_39_3.py", line 119, in setUp
    self.expression_calculator = ExpressionCalculator()
NameError: name 'ExpressionCalculator' is not defined

======================================================================
ERROR: test_calculate_method_7 (ClassEval_39_3.ExpressionCalculatorTestCalculateMethod)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_39_3.py", line 119, in setUp
    self.expression_calculator = ExpressionCalculator()
NameError: name 'ExpressionCalculator' is not defined

----------------------------------------------------------------------
Ran 7 tests in 0.001s

FAILED (errors=7)
EEEEEE
======================================================================
ERROR: test_transform_1 (ClassEval_39_3.ExpressionCalculatorTestTransform)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_39_3.py", line 154, in setUp
    self.expression_calculator = ExpressionCalculator()
NameError: name 'ExpressionCalculator' is not defined

======================================================================
ERROR: test_transform_2 (ClassEval_39_3.ExpressionCalculatorTestTransform)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_39_3.py", line 154, in setUp
    self.expression_calculator = ExpressionCalculator()
NameError: name 'ExpressionCalculator' is not defined

======================================================================
ERROR: test_transform_3 (ClassEval_39_3.ExpressionCalculatorTestTransform)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_39_3.py", line 154, in setUp
    self.expression_calculator = ExpressionCalculator()
NameError: name 'ExpressionCalculator' is not defined

======================================================================
ERROR: test_transform_4 (ClassEval_39_3.ExpressionCalculatorTestTransform)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_39_3.py", line 154, in setUp
    self.expression_calculator = ExpressionCalculator()
NameError: name 'ExpressionCalculator' is not defined

======================================================================
ERROR: test_transform_5 (ClassEval_39_3.ExpressionCalculatorTestTransform)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_39_3.py", line 154, in setUp
    self.expression_calculator = ExpressionCalculator()
NameError: name 'ExpressionCalculator' is not defined

======================================================================
ERROR: test_transform_6 (ClassEval_39_3.ExpressionCalculatorTestTransform)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_39_3.py", line 154, in setUp
    self.expression_calculator = ExpressionCalculator()
NameError: name 'ExpressionCalculator' is not defined

----------------------------------------------------------------------
Ran 6 tests in 0.001s

FAILED (errors=6)
E
======================================================================
ERROR: test_ExpressionCalculator (ClassEval_39_3.ExpressionCalculatorTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_39_3.py", line 183, in setUp
    self.expression_calculator = ExpressionCalculator()
NameError: name 'ExpressionCalculator' is not defined

----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (errors=1)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
..FFFFF
======================================================================
FAIL: test_compare_3 (ClassEval_39_4.ExpressionCalculatorTestCompare)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_39_4.py", line 261, in test_compare_3
    self.assertTrue(result)
AssertionError: False is not true

======================================================================
FAIL: test_compare_4 (ClassEval_39_4.ExpressionCalculatorTestCompare)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_39_4.py", line 265, in test_compare_4
    self.assertFalse(result)
AssertionError: True is not false

======================================================================
FAIL: test_compare_5 (ClassEval_39_4.ExpressionCalculatorTestCompare)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_39_4.py", line 269, in test_compare_5
    self.assertFalse(result)
AssertionError: True is not false

======================================================================
FAIL: test_compare_6 (ClassEval_39_4.ExpressionCalculatorTestCompare)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_39_4.py", line 273, in test_compare_6
    self.assertFalse(result)
AssertionError: True is not false

======================================================================
FAIL: test_compare_7 (ClassEval_39_4.ExpressionCalculatorTestCompare)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_39_4.py", line 277, in test_compare_7
    self.assertTrue(result)
AssertionError: False is not true

----------------------------------------------------------------------
Ran 7 tests in 0.001s

FAILED (failures=5)
.......
----------------------------------------------------------------------
Ran 7 tests in 0.000s

OK
....FF
======================================================================
FAIL: test_transform_5 (ClassEval_39_4.ExpressionCalculatorTestTransform)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_39_4.py", line 337, in test_transform_5
    self.assertEqual(result, "~2+(~3)*4")
AssertionError: '-2+(-3)*4' != '~2+(~3)*4'
- -2+(-3)*4
? ^   ^
+ ~2+(~3)*4
? ^   ^


======================================================================
FAIL: test_transform_6 (ClassEval_39_4.ExpressionCalculatorTestTransform)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_39_4.py", line 341, in test_transform_6
    self.assertEqual(result, "0-(1+1)")
AssertionError: '~(1+1)' != '0-(1+1)'
- ~(1+1)
? ^
+ 0-(1+1)
? ^^


----------------------------------------------------------------------
Ran 6 tests in 0.001s

FAILED (failures=2)
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.FFFF
======================================================================
FAIL: test_fleiss_kappa_2 (ClassEval_51_0.KappaCalculatorTestFleissKappa)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_51_0.py", line 113, in test_fleiss_kappa_2
    self.assertEqual(KappaCalculator.fleiss_kappa([[1, 0, 0, 0, 14],
AssertionError: np.float64(0.20852557021248944) != 0.2115748928799344

======================================================================
FAIL: test_fleiss_kappa_3 (ClassEval_51_0.KappaCalculatorTestFleissKappa)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_51_0.py", line 125, in test_fleiss_kappa_3
    self.assertEqual(KappaCalculator.fleiss_kappa([[0, 1, 0, 0, 14],
AssertionError: np.float64(0.20770181487022701) != 0.21076904123090398

======================================================================
FAIL: test_fleiss_kappa_4 (ClassEval_51_0.KappaCalculatorTestFleissKappa)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_51_0.py", line 137, in test_fleiss_kappa_4
    self.assertEqual(KappaCalculator.fleiss_kappa([[0, 0, 1, 0, 14],
AssertionError: np.float64(0.20656634746922026) != 0.2096583016522883

======================================================================
FAIL: test_fleiss_kappa_5 (ClassEval_51_0.KappaCalculatorTestFleissKappa)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_51_0.py", line 149, in test_fleiss_kappa_5
    self.assertEqual(KappaCalculator.fleiss_kappa([[0, 0, 0, 1, 14],
AssertionError: np.float64(0.2084226944823552) != 0.21147425143148907

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=4)
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.001s

OK
.FFFF
======================================================================
FAIL: test_fleiss_kappa_2 (ClassEval_51_1.KappaCalculatorTestFleissKappa)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_51_1.py", line 116, in test_fleiss_kappa_2
    self.assertEqual(KappaCalculator.fleiss_kappa([[1, 0, 0, 0, 14],
AssertionError: np.float64(0.20852557021248944) != 0.2115748928799344

======================================================================
FAIL: test_fleiss_kappa_3 (ClassEval_51_1.KappaCalculatorTestFleissKappa)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_51_1.py", line 128, in test_fleiss_kappa_3
    self.assertEqual(KappaCalculator.fleiss_kappa([[0, 1, 0, 0, 14],
AssertionError: np.float64(0.20770181487022701) != 0.21076904123090398

======================================================================
FAIL: test_fleiss_kappa_4 (ClassEval_51_1.KappaCalculatorTestFleissKappa)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_51_1.py", line 140, in test_fleiss_kappa_4
    self.assertEqual(KappaCalculator.fleiss_kappa([[0, 0, 1, 0, 14],
AssertionError: np.float64(0.20656634746922026) != 0.2096583016522883

======================================================================
FAIL: test_fleiss_kappa_5 (ClassEval_51_1.KappaCalculatorTestFleissKappa)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_51_1.py", line 152, in test_fleiss_kappa_5
    self.assertEqual(KappaCalculator.fleiss_kappa([[0, 0, 0, 1, 14],
AssertionError: np.float64(0.2084226944823552) != 0.21147425143148907

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=4)
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.FFFF
======================================================================
FAIL: test_fleiss_kappa_2 (ClassEval_51_2.KappaCalculatorTestFleissKappa)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_51_2.py", line 111, in test_fleiss_kappa_2
    self.assertEqual(KappaCalculator.fleiss_kappa([[1, 0, 0, 0, 14],
AssertionError: np.float64(0.20782576965564814) != 0.2115748928799344

======================================================================
FAIL: test_fleiss_kappa_3 (ClassEval_51_2.KappaCalculatorTestFleissKappa)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_51_2.py", line 123, in test_fleiss_kappa_3
    self.assertEqual(KappaCalculator.fleiss_kappa([[0, 1, 0, 0, 14],
AssertionError: np.float64(0.20700128597090803) != 0.21076904123090398

======================================================================
FAIL: test_fleiss_kappa_4 (ClassEval_51_2.KappaCalculatorTestFleissKappa)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_51_2.py", line 135, in test_fleiss_kappa_4
    self.assertEqual(KappaCalculator.fleiss_kappa([[0, 0, 1, 0, 14],
AssertionError: np.float64(0.2058648146199446) != 0.2096583016522883

======================================================================
FAIL: test_fleiss_kappa_5 (ClassEval_51_2.KappaCalculatorTestFleissKappa)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_51_2.py", line 147, in test_fleiss_kappa_5
    self.assertEqual(KappaCalculator.fleiss_kappa([[0, 0, 0, 1, 14],
AssertionError: np.float64(0.20772280296554033) != 0.21147425143148907

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=4)
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.EEEE
======================================================================
ERROR: test_fleiss_kappa_2 (ClassEval_51_3.KappaCalculatorTestFleissKappa)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_51_3.py", line 131, in test_fleiss_kappa_2
    self.assertEqual(KappaCalculator.fleiss_kappa([[1, 0, 0, 0, 14],
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_51_3.py", line 78, in fleiss_kappa
    raise ValueError("Each row of testData must sum to n")
ValueError: Each row of testData must sum to n

======================================================================
ERROR: test_fleiss_kappa_3 (ClassEval_51_3.KappaCalculatorTestFleissKappa)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_51_3.py", line 143, in test_fleiss_kappa_3
    self.assertEqual(KappaCalculator.fleiss_kappa([[0, 1, 0, 0, 14],
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_51_3.py", line 78, in fleiss_kappa
    raise ValueError("Each row of testData must sum to n")
ValueError: Each row of testData must sum to n

======================================================================
ERROR: test_fleiss_kappa_4 (ClassEval_51_3.KappaCalculatorTestFleissKappa)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_51_3.py", line 155, in test_fleiss_kappa_4
    self.assertEqual(KappaCalculator.fleiss_kappa([[0, 0, 1, 0, 14],
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_51_3.py", line 78, in fleiss_kappa
    raise ValueError("Each row of testData must sum to n")
ValueError: Each row of testData must sum to n

======================================================================
ERROR: test_fleiss_kappa_5 (ClassEval_51_3.KappaCalculatorTestFleissKappa)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_51_3.py", line 167, in test_fleiss_kappa_5
    self.assertEqual(KappaCalculator.fleiss_kappa([[0, 0, 0, 1, 14],
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_51_3.py", line 78, in fleiss_kappa
    raise ValueError("Each row of testData must sum to n")
ValueError: Each row of testData must sum to n

----------------------------------------------------------------------
Ran 5 tests in 0.002s

FAILED (errors=4)
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.001s

OK
.EEEE
======================================================================
ERROR: test_fleiss_kappa_2 (ClassEval_51_4.KappaCalculatorTestFleissKappa)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_51_4.py", line 129, in test_fleiss_kappa_2
    self.assertEqual(KappaCalculator.fleiss_kappa([[1, 0, 0, 0, 14],
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_51_4.py", line 74, in fleiss_kappa
    raise ValueError("Each row of testData must sum to n (number of raters)")
ValueError: Each row of testData must sum to n (number of raters)

======================================================================
ERROR: test_fleiss_kappa_3 (ClassEval_51_4.KappaCalculatorTestFleissKappa)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_51_4.py", line 141, in test_fleiss_kappa_3
    self.assertEqual(KappaCalculator.fleiss_kappa([[0, 1, 0, 0, 14],
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_51_4.py", line 74, in fleiss_kappa
    raise ValueError("Each row of testData must sum to n (number of raters)")
ValueError: Each row of testData must sum to n (number of raters)

======================================================================
ERROR: test_fleiss_kappa_4 (ClassEval_51_4.KappaCalculatorTestFleissKappa)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_51_4.py", line 153, in test_fleiss_kappa_4
    self.assertEqual(KappaCalculator.fleiss_kappa([[0, 0, 1, 0, 14],
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_51_4.py", line 74, in fleiss_kappa
    raise ValueError("Each row of testData must sum to n (number of raters)")
ValueError: Each row of testData must sum to n (number of raters)

======================================================================
ERROR: test_fleiss_kappa_5 (ClassEval_51_4.KappaCalculatorTestFleissKappa)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_51_4.py", line 165, in test_fleiss_kappa_5
    self.assertEqual(KappaCalculator.fleiss_kappa([[0, 0, 0, 1, 14],
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_51_4.py", line 74, in fleiss_kappa
    raise ValueError("Each row of testData must sum to n (number of raters)")
ValueError: Each row of testData must sum to n (number of raters)

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (errors=4)
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.000s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.000s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.000s

OK
.F....
======================================================================
FAIL: test_accuracy_2 (ClassEval_56_0.MetricsCalculatorTestAccuracy)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_56_0.py", line 229, in test_accuracy_2
    self.assertAlmostEqual(temp, 0.3333333333333333)
AssertionError: 0.25 != 0.3333333333333333 within 7 places (0.08333333333333331 difference)

----------------------------------------------------------------------
Ran 6 tests in 0.001s

FAILED (failures=1)
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.000s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.000s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.000s

OK
.E....
======================================================================
ERROR: test_accuracy_2 (ClassEval_56_1.MetricsCalculatorTestAccuracy)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_56_1.py", line 251, in test_accuracy_2
    temp = mc.accuracy([1, 1, 2, 0], [1, 0, 0, 1])
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_56_1.py", line 104, in accuracy
    self.update(predicted_labels, true_labels)
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_56_1.py", line 39, in update
    raise ValueError(f"Unsupported label pair: pred={pred}, true={true}")
ValueError: Unsupported label pair: pred=2, true=0

----------------------------------------------------------------------
Ran 6 tests in 0.001s

FAILED (errors=1)
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.000s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.000s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.000s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.000s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.000s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.000s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.000s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.000s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.000s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
......FF
======================================================================
FAIL: test_mrr_7 (ClassEval_57_0.MetricsCalculator2TestMrr)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_57_0.py", line 133, in test_mrr_7
    self.assertEqual(res1, 0.0)
AssertionError: nan != 0.0

======================================================================
FAIL: test_mrr_8 (ClassEval_57_0.MetricsCalculator2TestMrr)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_57_0.py", line 138, in test_mrr_8
    self.assertEqual(res1, 0.0)
AssertionError: 0.75 != 0.0

----------------------------------------------------------------------
Ran 8 tests in 0.003s

FAILED (failures=2)
......F.
======================================================================
FAIL: test_map_7 (ClassEval_57_0.MetricsCalculator2TestMap)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_57_0.py", line 176, in test_map_7
    self.assertEqual(res1, 0.0)
AssertionError: nan != 0.0

----------------------------------------------------------------------
Ran 8 tests in 0.001s

FAILED (failures=1)
....
----------------------------------------------------------------------
Ran 4 tests in 0.000s

OK
......FF
======================================================================
FAIL: test_mrr_7 (ClassEval_57_1.MetricsCalculator2TestMrr)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_57_1.py", line 129, in test_mrr_7
    self.assertEqual(res2, [0.0])
AssertionError: Lists differ: [] != [0.0]

Second list contains 1 additional elements.
First extra element 0:
0.0

- []
+ [0.0]

======================================================================
FAIL: test_mrr_8 (ClassEval_57_1.MetricsCalculator2TestMrr)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_57_1.py", line 133, in test_mrr_8
    self.assertEqual(res1, 0.0)
AssertionError: 0.75 != 0.0

----------------------------------------------------------------------
Ran 8 tests in 0.001s

FAILED (failures=2)
......F.
======================================================================
FAIL: test_map_7 (ClassEval_57_1.MetricsCalculator2TestMap)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_57_1.py", line 172, in test_map_7
    self.assertEqual(res2, [0.0])
AssertionError: Lists differ: [] != [0.0]

Second list contains 1 additional elements.
First extra element 0:
0.0

- []
+ [0.0]

----------------------------------------------------------------------
Ran 8 tests in 0.001s

FAILED (failures=1)
....
----------------------------------------------------------------------
Ran 4 tests in 0.001s

OK
......FF
======================================================================
FAIL: test_mrr_7 (ClassEval_57_2.MetricsCalculator2TestMrr)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_57_2.py", line 117, in test_mrr_7
    self.assertEqual(res2, [0.0])
AssertionError: Lists differ: [] != [0.0]

Second list contains 1 additional elements.
First extra element 0:
0.0

- []
+ [0.0]

======================================================================
FAIL: test_mrr_8 (ClassEval_57_2.MetricsCalculator2TestMrr)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_57_2.py", line 121, in test_mrr_8
    self.assertEqual(res1, 0.0)
AssertionError: 0.75 != 0.0

----------------------------------------------------------------------
Ran 8 tests in 0.001s

FAILED (failures=2)
......F.
======================================================================
FAIL: test_map_7 (ClassEval_57_2.MetricsCalculator2TestMap)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_57_2.py", line 160, in test_map_7
    self.assertEqual(res2, [0.0])
AssertionError: Lists differ: [] != [0.0]

Second list contains 1 additional elements.
First extra element 0:
0.0

- []
+ [0.0]

----------------------------------------------------------------------
Ran 8 tests in 0.001s

FAILED (failures=1)
....
----------------------------------------------------------------------
Ran 4 tests in 0.000s

OK
......FF
======================================================================
FAIL: test_mrr_7 (ClassEval_57_3.MetricsCalculator2TestMrr)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_57_3.py", line 132, in test_mrr_7
    self.assertEqual(res2, [0.0])
AssertionError: Lists differ: [] != [0.0]

Second list contains 1 additional elements.
First extra element 0:
0.0

- []
+ [0.0]

======================================================================
FAIL: test_mrr_8 (ClassEval_57_3.MetricsCalculator2TestMrr)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_57_3.py", line 136, in test_mrr_8
    self.assertEqual(res1, 0.0)
AssertionError: 0.75 != 0.0

----------------------------------------------------------------------
Ran 8 tests in 0.005s

FAILED (failures=2)
......F.
======================================================================
FAIL: test_map_7 (ClassEval_57_3.MetricsCalculator2TestMap)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_57_3.py", line 175, in test_map_7
    self.assertEqual(res2, [0.0])
AssertionError: Lists differ: [] != [0.0]

Second list contains 1 additional elements.
First extra element 0:
0.0

- []
+ [0.0]

----------------------------------------------------------------------
Ran 8 tests in 0.001s

FAILED (failures=1)
....
----------------------------------------------------------------------
Ran 4 tests in 0.000s

OK
......FF
======================================================================
FAIL: test_mrr_7 (ClassEval_57_4.MetricsCalculator2TestMrr)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_57_4.py", line 130, in test_mrr_7
    self.assertEqual(res2, [0.0])
AssertionError: Lists differ: [] != [0.0]

Second list contains 1 additional elements.
First extra element 0:
0.0

- []
+ [0.0]

======================================================================
FAIL: test_mrr_8 (ClassEval_57_4.MetricsCalculator2TestMrr)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_57_4.py", line 134, in test_mrr_8
    self.assertEqual(res1, 0.0)
AssertionError: 0.75 != 0.0

----------------------------------------------------------------------
Ran 8 tests in 0.001s

FAILED (failures=2)
......F.
======================================================================
FAIL: test_map_7 (ClassEval_57_4.MetricsCalculator2TestMap)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_57_4.py", line 173, in test_map_7
    self.assertEqual(res2, [0.0])
AssertionError: Lists differ: [] != [0.0]

Second list contains 1 additional elements.
First extra element 0:
0.0

- []
+ [0.0]

----------------------------------------------------------------------
Ran 8 tests in 0.001s

FAILED (failures=1)
....
----------------------------------------------------------------------
Ran 4 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.001s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
...EE
======================================================================
ERROR: test_correlation_4 (ClassEval_81_0.Statistics3TestCorrelation)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_81_0.py", line 214, in test_correlation_4
    self.assertEqual(statistics3.correlation([1, 1,1], [2,2,2]), None)
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_81_0.py", line 104, in correlation
    raise ValueError("division by zero in correlation calculation")
ValueError: division by zero in correlation calculation

======================================================================
ERROR: test_correlation_5 (ClassEval_81_0.Statistics3TestCorrelation)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_81_0.py", line 218, in test_correlation_5
    self.assertEqual(statistics3.correlation([1, 1,1], [1,1,1]), None)
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_81_0.py", line 104, in correlation
    raise ValueError("division by zero in correlation calculation")
ValueError: division by zero in correlation calculation

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (errors=2)
.E...
======================================================================
ERROR: test_mean_2 (ClassEval_81_0.Statistics3TestMean)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_81_0.py", line 227, in test_mean_2
    self.assertEqual(statistics3.mean([]), None)
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_81_0.py", line 60, in mean
    raise ValueError("mean requires at least one data point")
ValueError: mean requires at least one data point

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (errors=1)
.FFFF
======================================================================
FAIL: test_correlation_matrix_2 (ClassEval_81_0.Statistics3TestCorrelationMatrix)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_81_0.py", line 248, in test_correlation_matrix_2
    self.assertEqual(statistics3.correlation_matrix([[1, 2, 3], [4, 5, 6]]), [[1.0, 1.0, 1.0], [1.0, 1.0, 1.0], [1.0, 1.0, 1.0]])
AssertionError: Lists differ: [[1.0, 1.0], [1.0, 1.0]] != [[1.0, 1.0, 1.0], [1.0, 1.0, 1.0], [1.0, 1.0, 1.0]]

First differing element 0:
[1.0, 1.0]
[1.0, 1.0, 1.0]

Second list contains 1 additional elements.
First extra element 2:
[1.0, 1.0, 1.0]

- [[1.0, 1.0], [1.0, 1.0]]
+ [[1.0, 1.0, 1.0], [1.0, 1.0, 1.0], [1.0, 1.0, 1.0]]

======================================================================
FAIL: test_correlation_matrix_3 (ClassEval_81_0.Statistics3TestCorrelationMatrix)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_81_0.py", line 252, in test_correlation_matrix_3
    self.assertEqual(statistics3.correlation_matrix([[1, 2, 3]]), [[None, None, None], [None, None, None], [None, None, None]])
AssertionError: Lists differ: [[1.0]] != [[None, None, None], [None, None, None], [None, None, None]]

First differing element 0:
[1.0]
[None, None, None]

Second list contains 2 additional elements.
First extra element 1:
[None, None, None]

- [[1.0]]
+ [[None, None, None], [None, None, None], [None, None, None]]

======================================================================
FAIL: test_correlation_matrix_4 (ClassEval_81_0.Statistics3TestCorrelationMatrix)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_81_0.py", line 256, in test_correlation_matrix_4
    self.assertEqual(statistics3.correlation_matrix([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11,12]]), [[1.0, 1.0, 1.0], [1.0, 1.0, 1.0], [1.0, 1.0, 1.0]])
AssertionError: Lists differ: [[1.0, 1.0, 1.0, 1.0], [1.0, 1.0, 1.0, 1.0], [1.0, 1.0, [27 chars]1.0]] != [[1.0, 1.0, 1.0], [1.0, 1.0, 1.0], [1.0, 1.0, 1.0]]

First differing element 0:
[1.0, 1.0, 1.0, 1.0]
[1.0, 1.0, 1.0]

First list contains 1 additional elements.
First extra element 3:
[1.0, 1.0, 1.0, 1.0]

+ [[1.0, 1.0, 1.0], [1.0, 1.0, 1.0], [1.0, 1.0, 1.0]]
- [[1.0, 1.0, 1.0, 1.0],
-  [1.0, 1.0, 1.0, 1.0],
-  [1.0, 1.0, 1.0, 1.0],
-  [1.0, 1.0, 1.0, 1.0]]

======================================================================
FAIL: test_correlation_matrix_5 (ClassEval_81_0.Statistics3TestCorrelationMatrix)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_81_0.py", line 260, in test_correlation_matrix_5
    self.assertEqual(statistics3.correlation_matrix([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11,12], [13, 14, 15]]), [[1.0, 1.0, 1.0], [1.0, 1.0, 1.0], [1.0, 1.0, 1.0]])
AssertionError: Lists differ: [[1.0, 1.0, 1.0, 1.0, 1.0], [1.0, 1.0, 1.0, 1.0, 1.0], [[74 chars]1.0]] != [[1.0, 1.0, 1.0], [1.0, 1.0, 1.0], [1.0, 1.0, 1.0]]

First differing element 0:
[1.0, 1.0, 1.0, 1.0, 1.0]
[1.0, 1.0, 1.0]

First list contains 2 additional elements.
First extra element 3:
[1.0, 1.0, 1.0, 1.0, 1.0]

+ [[1.0, 1.0, 1.0], [1.0, 1.0, 1.0], [1.0, 1.0, 1.0]]
- [[1.0, 1.0, 1.0, 1.0, 1.0],
-  [1.0, 1.0, 1.0, 1.0, 1.0],
-  [1.0, 1.0, 1.0, 1.0, 1.0],
-  [1.0, 1.0, 1.0, 1.0, 1.0],
-  [1.0, 1.0, 1.0, 1.0, 1.0]]

----------------------------------------------------------------------
Ran 5 tests in 0.002s

FAILED (failures=4)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.EE.E
======================================================================
ERROR: test_z_score_2 (ClassEval_81_0.Statistics3TestZScore)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_81_0.py", line 291, in test_z_score_2
    self.assertEqual(statistics3.z_score([1, 1, 1, 1]), None)
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_81_0.py", line 152, in z_score
    raise ValueError("standard deviation is zero, z-score undefined")
ValueError: standard deviation is zero, z-score undefined

======================================================================
ERROR: test_z_score_3 (ClassEval_81_0.Statistics3TestZScore)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_81_0.py", line 295, in test_z_score_3
    self.assertEqual(statistics3.z_score([1]),None)
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_81_0.py", line 148, in z_score
    raise ValueError("z-score requires at least two data points")
ValueError: z-score requires at least two data points

======================================================================
ERROR: test_z_score_5 (ClassEval_81_0.Statistics3TestZScore)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_81_0.py", line 303, in test_z_score_5
    self.assertEqual(statistics3.z_score([1, 1, 1, 1, 1]), None)
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_81_0.py", line 152, in z_score
    raise ValueError("standard deviation is zero, z-score undefined")
ValueError: standard deviation is zero, z-score undefined

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (errors=3)
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
...FF
======================================================================
FAIL: test_correlation_4 (ClassEval_81_1.Statistics3TestCorrelation)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_81_1.py", line 185, in test_correlation_4
    self.assertEqual(statistics3.correlation([1, 1,1], [2,2,2]), None)
AssertionError: 0.0 != None

======================================================================
FAIL: test_correlation_5 (ClassEval_81_1.Statistics3TestCorrelation)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_81_1.py", line 189, in test_correlation_5
    self.assertEqual(statistics3.correlation([1, 1,1], [1,1,1]), None)
AssertionError: 0.0 != None

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=2)
.E...
======================================================================
ERROR: test_mean_2 (ClassEval_81_1.Statistics3TestMean)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_81_1.py", line 198, in test_mean_2
    self.assertEqual(statistics3.mean([]), None)
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_81_1.py", line 17, in mean
    raise ValueError("mean requires at least one data point")
ValueError: mean requires at least one data point

----------------------------------------------------------------------
Ran 5 tests in 0.000s

FAILED (errors=1)
.FFFF
======================================================================
FAIL: test_correlation_matrix_2 (ClassEval_81_1.Statistics3TestCorrelationMatrix)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_81_1.py", line 219, in test_correlation_matrix_2
    self.assertEqual(statistics3.correlation_matrix([[1, 2, 3], [4, 5, 6]]), [[1.0, 1.0, 1.0], [1.0, 1.0, 1.0], [1.0, 1.0, 1.0]])
AssertionError: Lists differ: [[1.0, 1.0], [1.0, 1.0]] != [[1.0, 1.0, 1.0], [1.0, 1.0, 1.0], [1.0, 1.0, 1.0]]

First differing element 0:
[1.0, 1.0]
[1.0, 1.0, 1.0]

Second list contains 1 additional elements.
First extra element 2:
[1.0, 1.0, 1.0]

- [[1.0, 1.0], [1.0, 1.0]]
+ [[1.0, 1.0, 1.0], [1.0, 1.0, 1.0], [1.0, 1.0, 1.0]]

======================================================================
FAIL: test_correlation_matrix_3 (ClassEval_81_1.Statistics3TestCorrelationMatrix)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_81_1.py", line 223, in test_correlation_matrix_3
    self.assertEqual(statistics3.correlation_matrix([[1, 2, 3]]), [[None, None, None], [None, None, None], [None, None, None]])
AssertionError: Lists differ: [[1.0]] != [[None, None, None], [None, None, None], [None, None, None]]

First differing element 0:
[1.0]
[None, None, None]

Second list contains 2 additional elements.
First extra element 1:
[None, None, None]

- [[1.0]]
+ [[None, None, None], [None, None, None], [None, None, None]]

======================================================================
FAIL: test_correlation_matrix_4 (ClassEval_81_1.Statistics3TestCorrelationMatrix)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_81_1.py", line 227, in test_correlation_matrix_4
    self.assertEqual(statistics3.correlation_matrix([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11,12]]), [[1.0, 1.0, 1.0], [1.0, 1.0, 1.0], [1.0, 1.0, 1.0]])
AssertionError: Lists differ: [[1.0, 1.0, 1.0, 1.0], [1.0, 1.0, 1.0, 1.0], [1.0, 1.0, [27 chars]1.0]] != [[1.0, 1.0, 1.0], [1.0, 1.0, 1.0], [1.0, 1.0, 1.0]]

First differing element 0:
[1.0, 1.0, 1.0, 1.0]
[1.0, 1.0, 1.0]

First list contains 1 additional elements.
First extra element 3:
[1.0, 1.0, 1.0, 1.0]

+ [[1.0, 1.0, 1.0], [1.0, 1.0, 1.0], [1.0, 1.0, 1.0]]
- [[1.0, 1.0, 1.0, 1.0],
-  [1.0, 1.0, 1.0, 1.0],
-  [1.0, 1.0, 1.0, 1.0],
-  [1.0, 1.0, 1.0, 1.0]]

======================================================================
FAIL: test_correlation_matrix_5 (ClassEval_81_1.Statistics3TestCorrelationMatrix)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_81_1.py", line 231, in test_correlation_matrix_5
    self.assertEqual(statistics3.correlation_matrix([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11,12], [13, 14, 15]]), [[1.0, 1.0, 1.0], [1.0, 1.0, 1.0], [1.0, 1.0, 1.0]])
AssertionError: Lists differ: [[1.0, 1.0, 1.0, 1.0, 1.0], [1.0, 1.0, 1.0, 1.0, 1.0], [[74 chars]1.0]] != [[1.0, 1.0, 1.0], [1.0, 1.0, 1.0], [1.0, 1.0, 1.0]]

First differing element 0:
[1.0, 1.0, 1.0, 1.0, 1.0]
[1.0, 1.0, 1.0]

First list contains 2 additional elements.
First extra element 3:
[1.0, 1.0, 1.0, 1.0, 1.0]

+ [[1.0, 1.0, 1.0], [1.0, 1.0, 1.0], [1.0, 1.0, 1.0]]
- [[1.0, 1.0, 1.0, 1.0, 1.0],
-  [1.0, 1.0, 1.0, 1.0, 1.0],
-  [1.0, 1.0, 1.0, 1.0, 1.0],
-  [1.0, 1.0, 1.0, 1.0, 1.0],
-  [1.0, 1.0, 1.0, 1.0, 1.0]]

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=4)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.FE.F
======================================================================
ERROR: test_z_score_3 (ClassEval_81_1.Statistics3TestZScore)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_81_1.py", line 266, in test_z_score_3
    self.assertEqual(statistics3.z_score([1]),None)
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_81_1.py", line 71, in z_score
    raise ValueError("z_score requires at least two data points")
ValueError: z_score requires at least two data points

======================================================================
FAIL: test_z_score_2 (ClassEval_81_1.Statistics3TestZScore)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_81_1.py", line 262, in test_z_score_2
    self.assertEqual(statistics3.z_score([1, 1, 1, 1]), None)
AssertionError: [0.0, 0.0, 0.0, 0.0] != None

======================================================================
FAIL: test_z_score_5 (ClassEval_81_1.Statistics3TestZScore)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_81_1.py", line 274, in test_z_score_5
    self.assertEqual(statistics3.z_score([1, 1, 1, 1, 1]), None)
AssertionError: [0.0, 0.0, 0.0, 0.0, 0.0] != None

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=2, errors=1)
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.F.FF
======================================================================
FAIL: test_correlation_2 (ClassEval_81_2.Statistics3TestCorrelation)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_81_2.py", line 171, in test_correlation_2
    self.assertEqual(statistics3.correlation([1, 2, 3, 4], [5, 6, 7, 8]), 1.0)
AssertionError: 1.0000000000000002 != 1.0

======================================================================
FAIL: test_correlation_4 (ClassEval_81_2.Statistics3TestCorrelation)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_81_2.py", line 179, in test_correlation_4
    self.assertEqual(statistics3.correlation([1, 1,1], [2,2,2]), None)
AssertionError: 0.0 != None

======================================================================
FAIL: test_correlation_5 (ClassEval_81_2.Statistics3TestCorrelation)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_81_2.py", line 183, in test_correlation_5
    self.assertEqual(statistics3.correlation([1, 1,1], [1,1,1]), None)
AssertionError: 0.0 != None

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=3)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.FFFF
======================================================================
FAIL: test_correlation_matrix_2 (ClassEval_81_2.Statistics3TestCorrelationMatrix)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_81_2.py", line 213, in test_correlation_matrix_2
    self.assertEqual(statistics3.correlation_matrix([[1, 2, 3], [4, 5, 6]]), [[1.0, 1.0, 1.0], [1.0, 1.0, 1.0], [1.0, 1.0, 1.0]])
AssertionError: Lists differ: [[1.0, 1.0], [1.0, 1.0]] != [[1.0, 1.0, 1.0], [1.0, 1.0, 1.0], [1.0, 1.0, 1.0]]

First differing element 0:
[1.0, 1.0]
[1.0, 1.0, 1.0]

Second list contains 1 additional elements.
First extra element 2:
[1.0, 1.0, 1.0]

- [[1.0, 1.0], [1.0, 1.0]]
+ [[1.0, 1.0, 1.0], [1.0, 1.0, 1.0], [1.0, 1.0, 1.0]]

======================================================================
FAIL: test_correlation_matrix_3 (ClassEval_81_2.Statistics3TestCorrelationMatrix)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_81_2.py", line 217, in test_correlation_matrix_3
    self.assertEqual(statistics3.correlation_matrix([[1, 2, 3]]), [[None, None, None], [None, None, None], [None, None, None]])
AssertionError: Lists differ: [[1.0]] != [[None, None, None], [None, None, None], [None, None, None]]

First differing element 0:
[1.0]
[None, None, None]

Second list contains 2 additional elements.
First extra element 1:
[None, None, None]

- [[1.0]]
+ [[None, None, None], [None, None, None], [None, None, None]]

======================================================================
FAIL: test_correlation_matrix_4 (ClassEval_81_2.Statistics3TestCorrelationMatrix)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_81_2.py", line 221, in test_correlation_matrix_4
    self.assertEqual(statistics3.correlation_matrix([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11,12]]), [[1.0, 1.0, 1.0], [1.0, 1.0, 1.0], [1.0, 1.0, 1.0]])
AssertionError: Lists differ: [[1.0, 1.0, 1.0, 1.0], [1.0, 1.0, 1.0, 1.0], [1.0, 1.0, [27 chars]1.0]] != [[1.0, 1.0, 1.0], [1.0, 1.0, 1.0], [1.0, 1.0, 1.0]]

First differing element 0:
[1.0, 1.0, 1.0, 1.0]
[1.0, 1.0, 1.0]

First list contains 1 additional elements.
First extra element 3:
[1.0, 1.0, 1.0, 1.0]

+ [[1.0, 1.0, 1.0], [1.0, 1.0, 1.0], [1.0, 1.0, 1.0]]
- [[1.0, 1.0, 1.0, 1.0],
-  [1.0, 1.0, 1.0, 1.0],
-  [1.0, 1.0, 1.0, 1.0],
-  [1.0, 1.0, 1.0, 1.0]]

======================================================================
FAIL: test_correlation_matrix_5 (ClassEval_81_2.Statistics3TestCorrelationMatrix)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_81_2.py", line 225, in test_correlation_matrix_5
    self.assertEqual(statistics3.correlation_matrix([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11,12], [13, 14, 15]]), [[1.0, 1.0, 1.0], [1.0, 1.0, 1.0], [1.0, 1.0, 1.0]])
AssertionError: Lists differ: [[1.0, 1.0, 1.0, 1.0, 1.0], [1.0, 1.0, 1.0, 1.0, 1.0], [[74 chars]1.0]] != [[1.0, 1.0, 1.0], [1.0, 1.0, 1.0], [1.0, 1.0, 1.0]]

First differing element 0:
[1.0, 1.0, 1.0, 1.0, 1.0]
[1.0, 1.0, 1.0]

First list contains 2 additional elements.
First extra element 3:
[1.0, 1.0, 1.0, 1.0, 1.0]

+ [[1.0, 1.0, 1.0], [1.0, 1.0, 1.0], [1.0, 1.0, 1.0]]
- [[1.0, 1.0, 1.0, 1.0, 1.0],
-  [1.0, 1.0, 1.0, 1.0, 1.0],
-  [1.0, 1.0, 1.0, 1.0, 1.0],
-  [1.0, 1.0, 1.0, 1.0, 1.0],
-  [1.0, 1.0, 1.0, 1.0, 1.0]]

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=4)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.FF.F
======================================================================
FAIL: test_z_score_2 (ClassEval_81_2.Statistics3TestZScore)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_81_2.py", line 256, in test_z_score_2
    self.assertEqual(statistics3.z_score([1, 1, 1, 1]), None)
AssertionError: [0.0, 0.0, 0.0, 0.0] != None

======================================================================
FAIL: test_z_score_3 (ClassEval_81_2.Statistics3TestZScore)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_81_2.py", line 260, in test_z_score_3
    self.assertEqual(statistics3.z_score([1]),None)
AssertionError: [0.0] != None

======================================================================
FAIL: test_z_score_5 (ClassEval_81_2.Statistics3TestZScore)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_81_2.py", line 268, in test_z_score_5
    self.assertEqual(statistics3.z_score([1, 1, 1, 1, 1]), None)
AssertionError: [0.0, 0.0, 0.0, 0.0, 0.0] != None

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=3)
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.F.FF
======================================================================
FAIL: test_correlation_2 (ClassEval_81_3.Statistics3TestCorrelation)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_81_3.py", line 147, in test_correlation_2
    self.assertEqual(statistics3.correlation([1, 2, 3, 4], [5, 6, 7, 8]), 1.0)
AssertionError: 1.0000000000000002 != 1.0

======================================================================
FAIL: test_correlation_4 (ClassEval_81_3.Statistics3TestCorrelation)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_81_3.py", line 155, in test_correlation_4
    self.assertEqual(statistics3.correlation([1, 1,1], [2,2,2]), None)
AssertionError: 0.0 != None

======================================================================
FAIL: test_correlation_5 (ClassEval_81_3.Statistics3TestCorrelation)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_81_3.py", line 159, in test_correlation_5
    self.assertEqual(statistics3.correlation([1, 1,1], [1,1,1]), None)
AssertionError: 0.0 != None

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=3)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.FFFF
======================================================================
FAIL: test_correlation_matrix_2 (ClassEval_81_3.Statistics3TestCorrelationMatrix)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_81_3.py", line 189, in test_correlation_matrix_2
    self.assertEqual(statistics3.correlation_matrix([[1, 2, 3], [4, 5, 6]]), [[1.0, 1.0, 1.0], [1.0, 1.0, 1.0], [1.0, 1.0, 1.0]])
AssertionError: Lists differ: [[1.0, 1.0], [1.0, 1.0]] != [[1.0, 1.0, 1.0], [1.0, 1.0, 1.0], [1.0, 1.0, 1.0]]

First differing element 0:
[1.0, 1.0]
[1.0, 1.0, 1.0]

Second list contains 1 additional elements.
First extra element 2:
[1.0, 1.0, 1.0]

- [[1.0, 1.0], [1.0, 1.0]]
+ [[1.0, 1.0, 1.0], [1.0, 1.0, 1.0], [1.0, 1.0, 1.0]]

======================================================================
FAIL: test_correlation_matrix_3 (ClassEval_81_3.Statistics3TestCorrelationMatrix)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_81_3.py", line 193, in test_correlation_matrix_3
    self.assertEqual(statistics3.correlation_matrix([[1, 2, 3]]), [[None, None, None], [None, None, None], [None, None, None]])
AssertionError: Lists differ: [[1.0]] != [[None, None, None], [None, None, None], [None, None, None]]

First differing element 0:
[1.0]
[None, None, None]

Second list contains 2 additional elements.
First extra element 1:
[None, None, None]

- [[1.0]]
+ [[None, None, None], [None, None, None], [None, None, None]]

======================================================================
FAIL: test_correlation_matrix_4 (ClassEval_81_3.Statistics3TestCorrelationMatrix)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_81_3.py", line 197, in test_correlation_matrix_4
    self.assertEqual(statistics3.correlation_matrix([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11,12]]), [[1.0, 1.0, 1.0], [1.0, 1.0, 1.0], [1.0, 1.0, 1.0]])
AssertionError: Lists differ: [[1.0, 1.0, 1.0, 1.0], [1.0, 1.0, 1.0, 1.0], [1.0, 1.0, [27 chars]1.0]] != [[1.0, 1.0, 1.0], [1.0, 1.0, 1.0], [1.0, 1.0, 1.0]]

First differing element 0:
[1.0, 1.0, 1.0, 1.0]
[1.0, 1.0, 1.0]

First list contains 1 additional elements.
First extra element 3:
[1.0, 1.0, 1.0, 1.0]

+ [[1.0, 1.0, 1.0], [1.0, 1.0, 1.0], [1.0, 1.0, 1.0]]
- [[1.0, 1.0, 1.0, 1.0],
-  [1.0, 1.0, 1.0, 1.0],
-  [1.0, 1.0, 1.0, 1.0],
-  [1.0, 1.0, 1.0, 1.0]]

======================================================================
FAIL: test_correlation_matrix_5 (ClassEval_81_3.Statistics3TestCorrelationMatrix)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_81_3.py", line 201, in test_correlation_matrix_5
    self.assertEqual(statistics3.correlation_matrix([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11,12], [13, 14, 15]]), [[1.0, 1.0, 1.0], [1.0, 1.0, 1.0], [1.0, 1.0, 1.0]])
AssertionError: Lists differ: [[1.0, 1.0, 1.0, 1.0, 1.0], [1.0, 1.0, 1.0, 1.0, 1.0], [[74 chars]1.0]] != [[1.0, 1.0, 1.0], [1.0, 1.0, 1.0], [1.0, 1.0, 1.0]]

First differing element 0:
[1.0, 1.0, 1.0, 1.0, 1.0]
[1.0, 1.0, 1.0]

First list contains 2 additional elements.
First extra element 3:
[1.0, 1.0, 1.0, 1.0, 1.0]

+ [[1.0, 1.0, 1.0], [1.0, 1.0, 1.0], [1.0, 1.0, 1.0]]
- [[1.0, 1.0, 1.0, 1.0, 1.0],
-  [1.0, 1.0, 1.0, 1.0, 1.0],
-  [1.0, 1.0, 1.0, 1.0, 1.0],
-  [1.0, 1.0, 1.0, 1.0, 1.0],
-  [1.0, 1.0, 1.0, 1.0, 1.0]]

----------------------------------------------------------------------
Ran 5 tests in 0.002s

FAILED (failures=4)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.FF.F
======================================================================
FAIL: test_z_score_2 (ClassEval_81_3.Statistics3TestZScore)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_81_3.py", line 232, in test_z_score_2
    self.assertEqual(statistics3.z_score([1, 1, 1, 1]), None)
AssertionError: [0.0, 0.0, 0.0, 0.0] != None

======================================================================
FAIL: test_z_score_3 (ClassEval_81_3.Statistics3TestZScore)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_81_3.py", line 236, in test_z_score_3
    self.assertEqual(statistics3.z_score([1]),None)
AssertionError: [0.0] != None

======================================================================
FAIL: test_z_score_5 (ClassEval_81_3.Statistics3TestZScore)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_81_3.py", line 244, in test_z_score_5
    self.assertEqual(statistics3.z_score([1, 1, 1, 1, 1]), None)
AssertionError: [0.0, 0.0, 0.0, 0.0, 0.0] != None

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=3)
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
...FF
======================================================================
FAIL: test_correlation_4 (ClassEval_81_4.Statistics3TestCorrelation)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_81_4.py", line 179, in test_correlation_4
    self.assertEqual(statistics3.correlation([1, 1,1], [2,2,2]), None)
AssertionError: 0.0 != None

======================================================================
FAIL: test_correlation_5 (ClassEval_81_4.Statistics3TestCorrelation)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_81_4.py", line 183, in test_correlation_5
    self.assertEqual(statistics3.correlation([1, 1,1], [1,1,1]), None)
AssertionError: 0.0 != None

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=2)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.FFFF
======================================================================
FAIL: test_correlation_matrix_2 (ClassEval_81_4.Statistics3TestCorrelationMatrix)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_81_4.py", line 213, in test_correlation_matrix_2
    self.assertEqual(statistics3.correlation_matrix([[1, 2, 3], [4, 5, 6]]), [[1.0, 1.0, 1.0], [1.0, 1.0, 1.0], [1.0, 1.0, 1.0]])
AssertionError: Lists differ: [[1.0, 1.0], [1.0, 1.0]] != [[1.0, 1.0, 1.0], [1.0, 1.0, 1.0], [1.0, 1.0, 1.0]]

First differing element 0:
[1.0, 1.0]
[1.0, 1.0, 1.0]

Second list contains 1 additional elements.
First extra element 2:
[1.0, 1.0, 1.0]

- [[1.0, 1.0], [1.0, 1.0]]
+ [[1.0, 1.0, 1.0], [1.0, 1.0, 1.0], [1.0, 1.0, 1.0]]

======================================================================
FAIL: test_correlation_matrix_3 (ClassEval_81_4.Statistics3TestCorrelationMatrix)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_81_4.py", line 217, in test_correlation_matrix_3
    self.assertEqual(statistics3.correlation_matrix([[1, 2, 3]]), [[None, None, None], [None, None, None], [None, None, None]])
AssertionError: Lists differ: [[1.0]] != [[None, None, None], [None, None, None], [None, None, None]]

First differing element 0:
[1.0]
[None, None, None]

Second list contains 2 additional elements.
First extra element 1:
[None, None, None]

- [[1.0]]
+ [[None, None, None], [None, None, None], [None, None, None]]

======================================================================
FAIL: test_correlation_matrix_4 (ClassEval_81_4.Statistics3TestCorrelationMatrix)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_81_4.py", line 221, in test_correlation_matrix_4
    self.assertEqual(statistics3.correlation_matrix([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11,12]]), [[1.0, 1.0, 1.0], [1.0, 1.0, 1.0], [1.0, 1.0, 1.0]])
AssertionError: Lists differ: [[1.0, 1.0, 1.0, 1.0], [1.0, 1.0, 1.0, 1.0], [1.0, 1.0, [27 chars]1.0]] != [[1.0, 1.0, 1.0], [1.0, 1.0, 1.0], [1.0, 1.0, 1.0]]

First differing element 0:
[1.0, 1.0, 1.0, 1.0]
[1.0, 1.0, 1.0]

First list contains 1 additional elements.
First extra element 3:
[1.0, 1.0, 1.0, 1.0]

+ [[1.0, 1.0, 1.0], [1.0, 1.0, 1.0], [1.0, 1.0, 1.0]]
- [[1.0, 1.0, 1.0, 1.0],
-  [1.0, 1.0, 1.0, 1.0],
-  [1.0, 1.0, 1.0, 1.0],
-  [1.0, 1.0, 1.0, 1.0]]

======================================================================
FAIL: test_correlation_matrix_5 (ClassEval_81_4.Statistics3TestCorrelationMatrix)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_81_4.py", line 225, in test_correlation_matrix_5
    self.assertEqual(statistics3.correlation_matrix([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11,12], [13, 14, 15]]), [[1.0, 1.0, 1.0], [1.0, 1.0, 1.0], [1.0, 1.0, 1.0]])
AssertionError: Lists differ: [[1.0, 1.0, 1.0, 1.0, 1.0], [1.0, 1.0, 1.0, 1.0, 1.0], [[74 chars]1.0]] != [[1.0, 1.0, 1.0], [1.0, 1.0, 1.0], [1.0, 1.0, 1.0]]

First differing element 0:
[1.0, 1.0, 1.0, 1.0, 1.0]
[1.0, 1.0, 1.0]

First list contains 2 additional elements.
First extra element 3:
[1.0, 1.0, 1.0, 1.0, 1.0]

+ [[1.0, 1.0, 1.0], [1.0, 1.0, 1.0], [1.0, 1.0, 1.0]]
- [[1.0, 1.0, 1.0, 1.0, 1.0],
-  [1.0, 1.0, 1.0, 1.0, 1.0],
-  [1.0, 1.0, 1.0, 1.0, 1.0],
-  [1.0, 1.0, 1.0, 1.0, 1.0],
-  [1.0, 1.0, 1.0, 1.0, 1.0]]

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=4)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.FF.F
======================================================================
FAIL: test_z_score_2 (ClassEval_81_4.Statistics3TestZScore)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_81_4.py", line 256, in test_z_score_2
    self.assertEqual(statistics3.z_score([1, 1, 1, 1]), None)
AssertionError: [0.0, 0.0, 0.0, 0.0] != None

======================================================================
FAIL: test_z_score_3 (ClassEval_81_4.Statistics3TestZScore)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_81_4.py", line 260, in test_z_score_3
    self.assertEqual(statistics3.z_score([1]),None)
AssertionError: [0.0] != None

======================================================================
FAIL: test_z_score_5 (ClassEval_81_4.Statistics3TestZScore)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_81_4.py", line 268, in test_z_score_5
    self.assertEqual(statistics3.z_score([1, 1, 1, 1, 1]), None)
AssertionError: [0.0, 0.0, 0.0, 0.0, 0.0] != None

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=3)
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
F..F.
======================================================================
FAIL: test_cos_1 (ClassEval_88_0.TriCalculatorTestCos)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_88_0.py", line 115, in test_cos_1
    self.assertEqual(tricalculator.cos(60), 0.5)
AssertionError: 0.49999999999990047 != 0.5

======================================================================
FAIL: test_cos_4 (ClassEval_88_0.TriCalculatorTestCos)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_88_0.py", line 127, in test_cos_4
    self.assertEqual(tricalculator.cos(90), 0.0)
AssertionError: 5.260664662720962e-13 != 0.0

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=2)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.001s

OK
F..F.
======================================================================
FAIL: test_sin_1 (ClassEval_88_0.TriCalculatorTestSin)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_88_0.py", line 181, in test_sin_1
    self.assertEqual(tricalculator.sin(30), 0.5)
AssertionError: 0.4999999999999643 != 0.5

======================================================================
FAIL: test_sin_4 (ClassEval_88_0.TriCalculatorTestSin)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_88_0.py", line 193, in test_sin_4
    self.assertEqual(tricalculator.sin(90), 1.0)
AssertionError: 1.0000000000000437 != 1.0

----------------------------------------------------------------------
Ran 5 tests in 0.000s

FAILED (failures=2)
FE...
======================================================================
ERROR: test_tan_2 (ClassEval_88_0.TriCalculatorTestTan)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_88_0.py", line 207, in test_tan_2
    self.assertEqual(tricalculator.tan(90), False)
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_88_0.py", line 106, in tan
    raise ValueError(f"Tangent undefined for angle {x}")
ValueError: Tangent undefined for angle 90

======================================================================
FAIL: test_tan_1 (ClassEval_88_0.TriCalculatorTestTan)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_88_0.py", line 203, in test_tan_1
    self.assertEqual(tricalculator.tan(45), 1.0)
AssertionError: 0.9999999999994791 != 1.0

----------------------------------------------------------------------
Ran 5 tests in 0.000s

FAILED (failures=1, errors=1)
F
======================================================================
FAIL: test_tricalculator (ClassEval_88_0.TriCalculatorTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_88_0.py", line 225, in test_tricalculator
    self.assertEqual(tricalculator.cos(60), 0.5)
AssertionError: 0.49999999999990047 != 0.5

----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (failures=1)
F..F.
======================================================================
FAIL: test_cos_1 (ClassEval_88_1.TriCalculatorTestCos)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_88_1.py", line 84, in test_cos_1
    self.assertEqual(tricalculator.cos(60), 0.5)
AssertionError: 0.5000000000000001 != 0.5

======================================================================
FAIL: test_cos_4 (ClassEval_88_1.TriCalculatorTestCos)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_88_1.py", line 96, in test_cos_4
    self.assertEqual(tricalculator.cos(90), 0.0)
AssertionError: 4.2539467343847745e-17 != 0.0

----------------------------------------------------------------------
Ran 5 tests in 0.002s

FAILED (failures=2)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.001s

OK
F.F..
======================================================================
FAIL: test_sin_1 (ClassEval_88_1.TriCalculatorTestSin)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_88_1.py", line 150, in test_sin_1
    self.assertEqual(tricalculator.sin(30), 0.5)
AssertionError: 0.5000000000000001 != 0.5

======================================================================
FAIL: test_sin_3 (ClassEval_88_1.TriCalculatorTestSin)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_88_1.py", line 158, in test_sin_3
    self.assertEqual(tricalculator.sin(0), 0.0)
AssertionError: 4.2539467343847745e-17 != 0.0

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=2)
.E..F
======================================================================
ERROR: test_tan_2 (ClassEval_88_1.TriCalculatorTestTan)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_88_1.py", line 176, in test_tan_2
    self.assertEqual(tricalculator.tan(90), False)
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_88_1.py", line 76, in tan
    raise ValueError("Tangent undefined for angle {}° (cosine too close to zero)".format(x))
ValueError: Tangent undefined for angle 90° (cosine too close to zero)

======================================================================
FAIL: test_tan_5 (ClassEval_88_1.TriCalculatorTestTan)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_88_1.py", line 188, in test_tan_5
    self.assertEqual(tricalculator.tan(0), 0.0)
AssertionError: 4.2539467343847745e-17 != 0.0

----------------------------------------------------------------------
Ran 5 tests in 0.003s

FAILED (failures=1, errors=1)
F
======================================================================
FAIL: test_tricalculator (ClassEval_88_1.TriCalculatorTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_88_1.py", line 194, in test_tricalculator
    self.assertEqual(tricalculator.cos(60), 0.5)
AssertionError: 0.5000000000000001 != 0.5

----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (failures=1)
F..F.
======================================================================
FAIL: test_cos_1 (ClassEval_88_2.TriCalculatorTestCos)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_88_2.py", line 100, in test_cos_1
    self.assertEqual(tricalculator.cos(60), 0.5)
AssertionError: 0.5000000000000001 != 0.5

======================================================================
FAIL: test_cos_4 (ClassEval_88_2.TriCalculatorTestCos)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_88_2.py", line 112, in test_cos_4
    self.assertEqual(tricalculator.cos(90), 0.0)
AssertionError: 4.2539467343847745e-17 != 0.0

----------------------------------------------------------------------
Ran 5 tests in 0.002s

FAILED (failures=2)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.001s

OK
F..F.
======================================================================
FAIL: test_sin_1 (ClassEval_88_2.TriCalculatorTestSin)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_88_2.py", line 166, in test_sin_1
    self.assertEqual(tricalculator.sin(30), 0.5)
AssertionError: 0.49999999999999994 != 0.5

======================================================================
FAIL: test_sin_4 (ClassEval_88_2.TriCalculatorTestSin)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_88_2.py", line 178, in test_sin_4
    self.assertEqual(tricalculator.sin(90), 1.0)
AssertionError: 1.0000000000000002 != 1.0

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=2)
.E...
======================================================================
ERROR: test_tan_2 (ClassEval_88_2.TriCalculatorTestTan)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_88_2.py", line 192, in test_tan_2
    self.assertEqual(tricalculator.tan(90), False)
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_88_2.py", line 91, in tan
    raise ValueError("tan undefined for angle %r (cos too close to zero)" % x)
ValueError: tan undefined for angle 90 (cos too close to zero)

----------------------------------------------------------------------
Ran 5 tests in 0.002s

FAILED (errors=1)
F
======================================================================
FAIL: test_tricalculator (ClassEval_88_2.TriCalculatorTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_88_2.py", line 210, in test_tricalculator
    self.assertEqual(tricalculator.cos(60), 0.5)
AssertionError: 0.5000000000000001 != 0.5

----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (failures=1)
F..F.
======================================================================
FAIL: test_cos_1 (ClassEval_88_3.TriCalculatorTestCos)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_88_3.py", line 101, in test_cos_1
    self.assertEqual(tricalculator.cos(60), 0.5)
AssertionError: 0.5000000000000001 != 0.5

======================================================================
FAIL: test_cos_4 (ClassEval_88_3.TriCalculatorTestCos)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_88_3.py", line 113, in test_cos_4
    self.assertEqual(tricalculator.cos(90), 0.0)
AssertionError: 4.2539467343847745e-17 != 0.0

----------------------------------------------------------------------
Ran 5 tests in 0.002s

FAILED (failures=2)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.002s

OK
F..F.
======================================================================
FAIL: test_sin_1 (ClassEval_88_3.TriCalculatorTestSin)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_88_3.py", line 167, in test_sin_1
    self.assertEqual(tricalculator.sin(30), 0.5)
AssertionError: 0.49999999999999994 != 0.5

======================================================================
FAIL: test_sin_4 (ClassEval_88_3.TriCalculatorTestSin)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_88_3.py", line 179, in test_sin_4
    self.assertEqual(tricalculator.sin(90), 1.0)
AssertionError: 1.0000000000000002 != 1.0

----------------------------------------------------------------------
Ran 5 tests in 0.002s

FAILED (failures=2)
.E...
======================================================================
ERROR: test_tan_2 (ClassEval_88_3.TriCalculatorTestTan)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_88_3.py", line 193, in test_tan_2
    self.assertEqual(tricalculator.tan(90), False)
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_88_3.py", line 92, in tan
    raise ZeroDivisionError(f"tan({x}) is undefined (cos({x}) is zero).")
ZeroDivisionError: tan(90) is undefined (cos(90) is zero).

----------------------------------------------------------------------
Ran 5 tests in 0.002s

FAILED (errors=1)
F
======================================================================
FAIL: test_tricalculator (ClassEval_88_3.TriCalculatorTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_88_3.py", line 211, in test_tricalculator
    self.assertEqual(tricalculator.cos(60), 0.5)
AssertionError: 0.5000000000000001 != 0.5

----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (failures=1)
F..F.
======================================================================
FAIL: test_cos_1 (ClassEval_88_4.TriCalculatorTestCos)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_88_4.py", line 93, in test_cos_1
    self.assertEqual(tricalculator.cos(60), 0.5)
AssertionError: 0.5000000000000001 != 0.5

======================================================================
FAIL: test_cos_4 (ClassEval_88_4.TriCalculatorTestCos)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_88_4.py", line 105, in test_cos_4
    self.assertEqual(tricalculator.cos(90), 0.0)
AssertionError: 4.2539467343847745e-17 != 0.0

----------------------------------------------------------------------
Ran 5 tests in 0.002s

FAILED (failures=2)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.001s

OK
F.F..
======================================================================
FAIL: test_sin_1 (ClassEval_88_4.TriCalculatorTestSin)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_88_4.py", line 159, in test_sin_1
    self.assertEqual(tricalculator.sin(30), 0.5)
AssertionError: 0.5000000000000001 != 0.5

======================================================================
FAIL: test_sin_3 (ClassEval_88_4.TriCalculatorTestSin)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_88_4.py", line 167, in test_sin_3
    self.assertEqual(tricalculator.sin(0), 0.0)
AssertionError: 4.2539467343847745e-17 != 0.0

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=2)
.E..F
======================================================================
ERROR: test_tan_2 (ClassEval_88_4.TriCalculatorTestTan)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_88_4.py", line 185, in test_tan_2
    self.assertEqual(tricalculator.tan(90), False)
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_88_4.py", line 84, in tan
    raise ValueError(f"Tangent undefined for angle {x}° (cosine too close to zero)")
ValueError: Tangent undefined for angle 90° (cosine too close to zero)

======================================================================
FAIL: test_tan_5 (ClassEval_88_4.TriCalculatorTestTan)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_88_4.py", line 197, in test_tan_5
    self.assertEqual(tricalculator.tan(0), 0.0)
AssertionError: 4.2539467343847745e-17 != 0.0

----------------------------------------------------------------------
Ran 5 tests in 0.002s

FAILED (failures=1, errors=1)
F
======================================================================
FAIL: test_tricalculator (ClassEval_88_4.TriCalculatorTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_88_4.py", line 203, in test_tricalculator
    self.assertEqual(tricalculator.cos(60), 0.5)
AssertionError: 0.5000000000000001 != 0.5

----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (failures=1)
