FFFFF..F
======================================================================
FAIL: test_filter_1 (ClassEval_0_0.AccessGatewayFilterTestFilter.test_filter_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_0_0.py", line 65, in test_filter_1
    self.assertTrue(res)
AssertionError: None is not true

======================================================================
FAIL: test_filter_2 (ClassEval_0_0.AccessGatewayFilterTestFilter.test_filter_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_0_0.py", line 71, in test_filter_2
    self.assertTrue(res)
AssertionError: None is not true

======================================================================
FAIL: test_filter_3 (ClassEval_0_0.AccessGatewayFilterTestFilter.test_filter_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_0_0.py", line 77, in test_filter_3
    self.assertTrue(res)
AssertionError: None is not true

======================================================================
FAIL: test_filter_4 (ClassEval_0_0.AccessGatewayFilterTestFilter.test_filter_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_0_0.py", line 83, in test_filter_4
    self.assertTrue(res)
AssertionError: None is not true

======================================================================
FAIL: test_filter_5 (ClassEval_0_0.AccessGatewayFilterTestFilter.test_filter_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_0_0.py", line 92, in test_filter_5
    self.assertTrue(res)
AssertionError: None is not true

======================================================================
FAIL: test_filter_8 (ClassEval_0_0.AccessGatewayFilterTestFilter.test_filter_8)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_0_0.py", line 119, in test_filter_8
    self.assertTrue(res)
AssertionError: None is not true

----------------------------------------------------------------------
Ran 8 tests in 0.002s

FAILED (failures=6)
F.F..
======================================================================
FAIL: test_is_start_with_1 (ClassEval_0_0.AccessGatewayFilterTestIsStartWith.test_is_start_with_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_0_0.py", line 127, in test_is_start_with_1
    self.assertTrue(res)
AssertionError: None is not true

======================================================================
FAIL: test_is_start_with_3 (ClassEval_0_0.AccessGatewayFilterTestIsStartWith.test_is_start_with_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_0_0.py", line 139, in test_is_start_with_3
    self.assertTrue(res)
AssertionError: None is not true

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=2)
FFFF.
======================================================================
FAIL: test_get_jwt_user_1 (ClassEval_0_0.AccessGatewayFilterTestGetJwtUser.test_get_jwt_user_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_0_0.py", line 160, in test_get_jwt_user_1
    self.assertIsNotNone(res)
AssertionError: unexpectedly None

======================================================================
FAIL: test_get_jwt_user_2 (ClassEval_0_0.AccessGatewayFilterTestGetJwtUser.test_get_jwt_user_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_0_0.py", line 167, in test_get_jwt_user_2
    self.assertIsNotNone(res)
AssertionError: unexpectedly None

======================================================================
FAIL: test_get_jwt_user_3 (ClassEval_0_0.AccessGatewayFilterTestGetJwtUser.test_get_jwt_user_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_0_0.py", line 174, in test_get_jwt_user_3
    self.assertIsNotNone(res)
AssertionError: unexpectedly None

======================================================================
FAIL: test_get_jwt_user_4 (ClassEval_0_0.AccessGatewayFilterTestGetJwtUser.test_get_jwt_user_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_0_0.py", line 181, in test_get_jwt_user_4
    self.assertIsNotNone(res)
AssertionError: unexpectedly None

----------------------------------------------------------------------
Ran 5 tests in 0.002s

FAILED (failures=4)
F
======================================================================
FAIL: test_AccessGatewayFilter (ClassEval_0_0.AccessGatewayFilterTest.test_AccessGatewayFilter)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_0_0.py", line 196, in test_AccessGatewayFilter
    self.assertTrue(res)
AssertionError: None is not true

----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (failures=1)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.E...
======================================================================
ERROR: test_get_course_average_2 (ClassEval_4_0.AssessmentSystemTestGetCourseAverage.test_get_course_average_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_4_0.py", line 285, in test_get_course_average_2
    self.assertEqual(assessment_system.get_course_average('Physics'), 85)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_4_0.py", line 83, in get_course_average
    return sum(scores) / len(scores)
           ^^^^^^^^^^^
TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (errors=1)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.001s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
FF.FF.FF.
======================================================================
FAIL: test_interpret_1 (ClassEval_5_0.AutomaticGuitarSimulatorTestInterpret.test_interpret_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_5_0.py", line 56, in test_interpret_1
    self.assertEqual(play_list, [{'Chord': 'C', 'Tune': '53231323'}])
AssertionError: Lists differ: [{'Chord': 'C5', 'Tune': '3231323'}] != [{'Chord': 'C', 'Tune': '53231323'}]

First differing element 0:
{'Chord': 'C5', 'Tune': '3231323'}
{'Chord': 'C', 'Tune': '53231323'}

- [{'Chord': 'C5', 'Tune': '3231323'}]
?              -

+ [{'Chord': 'C', 'Tune': '53231323'}]
?                          +


======================================================================
FAIL: test_interpret_2 (ClassEval_5_0.AutomaticGuitarSimulatorTestInterpret.test_interpret_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_5_0.py", line 61, in test_interpret_2
    self.assertEqual(play_list, [{'Chord': 'F', 'Tune': '43231323'}])
AssertionError: Lists differ: [{'Chord': 'F4', 'Tune': '3231323'}] != [{'Chord': 'F', 'Tune': '43231323'}]

First differing element 0:
{'Chord': 'F4', 'Tune': '3231323'}
{'Chord': 'F', 'Tune': '43231323'}

- [{'Chord': 'F4', 'Tune': '3231323'}]
?              -

+ [{'Chord': 'F', 'Tune': '43231323'}]
?                          +


======================================================================
FAIL: test_interpret_4 (ClassEval_5_0.AutomaticGuitarSimulatorTestInterpret.test_interpret_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_5_0.py", line 71, in test_interpret_4
    self.assertEqual(play_list, [{'Chord': 'G', 'Tune': '63231323'}])
AssertionError: Lists differ: [{'Chord': 'G6', 'Tune': '3231323'}] != [{'Chord': 'G', 'Tune': '63231323'}]

First differing element 0:
{'Chord': 'G6', 'Tune': '3231323'}
{'Chord': 'G', 'Tune': '63231323'}

- [{'Chord': 'G6', 'Tune': '3231323'}]
?              -

+ [{'Chord': 'G', 'Tune': '63231323'}]
?                          +


======================================================================
FAIL: test_interpret_5 (ClassEval_5_0.AutomaticGuitarSimulatorTestInterpret.test_interpret_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_5_0.py", line 76, in test_interpret_5
    self.assertEqual(play_list, [{'Chord': 'F', 'Tune': '43231323'}, {'Chord': 'G', 'Tune': '63231323'}])
AssertionError: Lists differ: [{'Chord': 'F4', 'Tune': '3231323'}, {'Chord': 'G6', 'Tune': '3231323'}] != [{'Chord': 'F', 'Tune': '43231323'}, {'Chord': 'G', 'Tune': '63231323'}]

First differing element 0:
{'Chord': 'F4', 'Tune': '3231323'}
{'Chord': 'F', 'Tune': '43231323'}

- [{'Chord': 'F4', 'Tune': '3231323'}, {'Chord': 'G6', 'Tune': '3231323'}]
?              -                                   -

+ [{'Chord': 'F', 'Tune': '43231323'}, {'Chord': 'G', 'Tune': '63231323'}]
?                          +                                   +


======================================================================
FAIL: test_interpret_7 (ClassEval_5_0.AutomaticGuitarSimulatorTestInterpret.test_interpret_7)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_5_0.py", line 86, in test_interpret_7
    self.assertEqual(play_list, [{'Chord': 'ABC', 'Tune': '43231323'}, {'Chord': 'DEF', 'Tune': '63231323'}])
AssertionError: Lists differ: [{'Chord': 'AB', 'Tune': 'C43231323'}, {'Chord': 'DE', 'Tune': 'F63231323'}] != [{'Chord': 'ABC', 'Tune': '43231323'}, {'Chord': 'DEF', 'Tune': '63231323'}]

First differing element 0:
{'Chord': 'AB', 'Tune': 'C43231323'}
{'Chord': 'ABC', 'Tune': '43231323'}

- [{'Chord': 'AB', 'Tune': 'C43231323'}, {'Chord': 'DE', 'Tune': 'F63231323'}]
?                           -                                     -

+ [{'Chord': 'ABC', 'Tune': '43231323'}, {'Chord': 'DEF', 'Tune': '63231323'}]
?               +                                     +


======================================================================
FAIL: test_interpret_8 (ClassEval_5_0.AutomaticGuitarSimulatorTestInterpret.test_interpret_8)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_5_0.py", line 91, in test_interpret_8
    self.assertEqual(play_list, [{'Chord': 'C', 'Tune': '53231323'}])
AssertionError: Lists differ: [{'Chord': 'C5', 'Tune': '3231323'}] != [{'Chord': 'C', 'Tune': '53231323'}]

First differing element 0:
{'Chord': 'C5', 'Tune': '3231323'}
{'Chord': 'C', 'Tune': '53231323'}

- [{'Chord': 'C5', 'Tune': '3231323'}]
?              -

+ [{'Chord': 'C', 'Tune': '53231323'}]
?                          +


----------------------------------------------------------------------
Ran 9 tests in 0.004s

FAILED (failures=6)
FFFFF
======================================================================
FAIL: test_display_1 (ClassEval_5_0.AutomaticGuitarSimulatorTestDisplay.test_display_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_5_0.py", line 104, in test_display_1
    self.assertEqual(str, "Normal Guitar Playing -- Chord: C, Play Tune: 53231323")
AssertionError: None != 'Normal Guitar Playing -- Chord: C, Play Tune: 53231323'

======================================================================
FAIL: test_display_2 (ClassEval_5_0.AutomaticGuitarSimulatorTestDisplay.test_display_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_5_0.py", line 110, in test_display_2
    self.assertEqual(str, "Normal Guitar Playing -- Chord: Em, Play Tune: 43231323")
AssertionError: None != 'Normal Guitar Playing -- Chord: Em, Play Tune: 43231323'

======================================================================
FAIL: test_display_3 (ClassEval_5_0.AutomaticGuitarSimulatorTestDisplay.test_display_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_5_0.py", line 116, in test_display_3
    self.assertEqual(str, "Normal Guitar Playing -- Chord: F, Play Tune: 43231323")
AssertionError: None != 'Normal Guitar Playing -- Chord: F, Play Tune: 43231323'

======================================================================
FAIL: test_display_4 (ClassEval_5_0.AutomaticGuitarSimulatorTestDisplay.test_display_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_5_0.py", line 122, in test_display_4
    self.assertEqual(str, "Normal Guitar Playing -- Chord: G, Play Tune: 63231323")
AssertionError: None != 'Normal Guitar Playing -- Chord: G, Play Tune: 63231323'

======================================================================
FAIL: test_display_5 (ClassEval_5_0.AutomaticGuitarSimulatorTestDisplay.test_display_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_5_0.py", line 127, in test_display_5
    self.assertEqual(str, "Normal Guitar Playing -- Chord: , Play Tune: ")
AssertionError: None != 'Normal Guitar Playing -- Chord: , Play Tune: '

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=5)
F
======================================================================
FAIL: test_AutomaticGuitarSimulator (ClassEval_5_0.AutomaticGuitarSimulatorTest.test_AutomaticGuitarSimulator)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_5_0.py", line 134, in test_AutomaticGuitarSimulator
    self.assertEqual(play_list, [{'Chord': 'C', 'Tune': '53231323'}])
AssertionError: Lists differ: [{'Chord': 'C5', 'Tune': '3231323'}] != [{'Chord': 'C', 'Tune': '53231323'}]

First differing element 0:
{'Chord': 'C5', 'Tune': '3231323'}
{'Chord': 'C', 'Tune': '53231323'}

- [{'Chord': 'C5', 'Tune': '3231323'}]
?              -

+ [{'Chord': 'C', 'Tune': '53231323'}]
?                          +


----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (failures=1)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
..
----------------------------------------------------------------------
Ran 2 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
..FFF
======================================================================
FAIL: test_remove_book_3 (ClassEval_13_0.BookManagementTestRemoveBook.test_remove_book_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_13_0.py", line 118, in test_remove_book_3
    with self.assertRaises(Exception):
AssertionError: Exception not raised

======================================================================
FAIL: test_remove_book_4 (ClassEval_13_0.BookManagementTestRemoveBook.test_remove_book_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_13_0.py", line 123, in test_remove_book_4
    with self.assertRaises(Exception):
AssertionError: Exception not raised

======================================================================
FAIL: test_remove_book_5 (ClassEval_13_0.BookManagementTestRemoveBook.test_remove_book_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_13_0.py", line 127, in test_remove_book_5
    with self.assertRaises(Exception):
AssertionError: Exception not raised

----------------------------------------------------------------------
Ran 5 tests in 0.003s

FAILED (failures=3)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....E
======================================================================
ERROR: test_remove_event_6 (ClassEval_17_0.CalendarTestRemoveEvent.test_remove_event_6)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_17_0.py", line 196, in test_remove_event_6
    calendar.remove_event({'date': datetime(2023, 1, 1, 0, 0), 'start_time': datetime(2023, 1, 1, 0, 0),
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_17_0.py", line 28, in remove_event
    self.events.remove(event)
ValueError: list.remove(x): x not in list

----------------------------------------------------------------------
Ran 6 tests in 0.001s

FAILED (errors=1)
..
----------------------------------------------------------------------
Ran 2 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.001s

OK
EEEEE
======================================================================
ERROR: test_get_upcoming_events (ClassEval_17_0.CalendarTestGetUpcomingEvents.test_get_upcoming_events)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_17_0.py", line 287, in test_get_upcoming_events
    self.assertEqual(calendar.get_upcoming_events(1), [])
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: CalendarUtil.get_upcoming_events() missing 1 required positional argument: 'n'

======================================================================
ERROR: test_get_upcoming_events_2 (ClassEval_17_0.CalendarTestGetUpcomingEvents.test_get_upcoming_events_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_17_0.py", line 293, in test_get_upcoming_events_2
    self.assertEqual(calendar.get_upcoming_events(1), [])
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: CalendarUtil.get_upcoming_events() missing 1 required positional argument: 'n'

======================================================================
ERROR: test_get_upcoming_events_3 (ClassEval_17_0.CalendarTestGetUpcomingEvents.test_get_upcoming_events_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_17_0.py", line 299, in test_get_upcoming_events_3
    self.assertEqual(calendar.get_upcoming_events(1), [])
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: CalendarUtil.get_upcoming_events() missing 1 required positional argument: 'n'

======================================================================
ERROR: test_get_upcoming_events_4 (ClassEval_17_0.CalendarTestGetUpcomingEvents.test_get_upcoming_events_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_17_0.py", line 305, in test_get_upcoming_events_4
    self.assertEqual(calendar.get_upcoming_events(2), [])
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: CalendarUtil.get_upcoming_events() missing 1 required positional argument: 'n'

======================================================================
ERROR: test_get_upcoming_events_5 (ClassEval_17_0.CalendarTestGetUpcomingEvents.test_get_upcoming_events_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_17_0.py", line 314, in test_get_upcoming_events_5
    self.assertEqual(calendar.get_upcoming_events(1), [
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: CalendarUtil.get_upcoming_events() missing 1 required positional argument: 'n'

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (errors=5)
E
======================================================================
ERROR: test_main (ClassEval_17_0.CalendarTestMain.test_main)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_17_0.py", line 338, in test_main
    self.assertEqual(calendar.get_upcoming_events(1), [])
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: CalendarUtil.get_upcoming_events() missing 1 required positional argument: 'n'

----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (errors=1)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
F....
======================================================================
FAIL: test_send_message (ClassEval_20_0.ChatTestSendMessage.test_send_message)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_20_0.py", line 162, in test_send_message
    self.assertEqual(chat.users, {'John': [{'sender': 'John', 'receiver': 'Mary', 'message': 'Hello', 'timestamp': timestamp}], 'Mary': [{'sender': 'John', 'receiver': 'Mary', 'message': 'Hello', 'timestamp': timestamp}]})
AssertionError: {'Joh[106 chars]y': []} != {'Joh[106 chars]y': [{'sender': 'John', 'receiver': 'Mary', 'm[50 chars]6'}]}
  {'John': [{'message': 'Hello',
             'receiver': 'Mary',
             'sender': 'John',
             'timestamp': '2025-04-22 01:26:36'}],
-  'Mary': []}
+  'Mary': [{'message': 'Hello',
+            'receiver': 'Mary',
+            'sender': 'John',
+            'timestamp': '2025-04-22 01:26:36'}]}

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=1)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
FF
======================================================================
FAIL: test_main (ClassEval_20_0.ChatTestMain.test_main)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_20_0.py", line 230, in test_main
    self.assertEqual(chat.users, {'John': [{'sender': 'John', 'receiver': 'Mary', 'message': 'Hello', 'timestamp': timestamp}], 'Mary': [{'sender': 'John', 'receiver': 'Mary', 'message': 'Hello', 'timestamp': timestamp}]})
AssertionError: {'Joh[106 chars]y': []} != {'Joh[106 chars]y': [{'sender': 'John', 'receiver': 'Mary', 'm[50 chars]6'}]}
  {'John': [{'message': 'Hello',
             'receiver': 'Mary',
             'sender': 'John',
             'timestamp': '2025-04-22 01:26:36'}],
-  'Mary': []}
+  'Mary': [{'message': 'Hello',
+            'receiver': 'Mary',
+            'sender': 'John',
+            'timestamp': '2025-04-22 01:26:36'}]}

======================================================================
FAIL: test_main_2 (ClassEval_20_0.ChatTestMain.test_main_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_20_0.py", line 245, in test_main_2
    self.assertEqual(chat.users, {'John': [{'sender': 'John', 'receiver': 'Mary', 'message': 'Hello', 'timestamp': timestamp}], 'Mary': [{'sender': 'John', 'receiver': 'Mary', 'message': 'Hello', 'timestamp': timestamp}]})
AssertionError: {'Joh[106 chars]y': []} != {'Joh[106 chars]y': [{'sender': 'John', 'receiver': 'Mary', 'm[50 chars]6'}]}
  {'John': [{'message': 'Hello',
             'receiver': 'Mary',
             'sender': 'John',
             'timestamp': '2025-04-22 01:26:36'}],
-  'Mary': []}
+  'Mary': [{'message': 'Hello',
+            'receiver': 'Mary',
+            'sender': 'John',
+            'timestamp': '2025-04-22 01:26:36'}]}

----------------------------------------------------------------------
Ran 2 tests in 0.001s

FAILED (failures=2)
......
----------------------------------------------------------------------
Ran 6 tests in 0.000s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.004s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.001s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
...
----------------------------------------------------------------------
Ran 3 tests in 0.000s

OK
...
----------------------------------------------------------------------
Ran 3 tests in 0.000s

OK
....
----------------------------------------------------------------------
Ran 4 tests in 0.000s

OK
...
----------------------------------------------------------------------
Ran 3 tests in 0.000s

OK
EE
======================================================================
ERROR: test_get_most_popular_class_in_major (ClassEval_22_0.ClassRegistrationSystemTestPopularClass.test_get_most_popular_class_in_major)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_22_0.py", line 219, in test_get_most_popular_class_in_major
    cs_most_popular_class = self.registration_system.get_most_popular_class_in_major("Computer Science")
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_22_0.py", line 78, in get_most_popular_class_in_major
    most_popular_class = max(class_enrollment, key=class_enrollment.get)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: max() iterable argument is empty

======================================================================
ERROR: test_get_most_popular_class_in_major2 (ClassEval_22_0.ClassRegistrationSystemTestPopularClass.test_get_most_popular_class_in_major2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_22_0.py", line 238, in test_get_most_popular_class_in_major2
    cs_most_popular_class = self.registration_system.get_most_popular_class_in_major("Computer Science")
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_22_0.py", line 78, in get_most_popular_class_in_major
    most_popular_class = max(class_enrollment, key=class_enrollment.get)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: max() iterable argument is empty

----------------------------------------------------------------------
Ran 2 tests in 0.001s

FAILED (errors=2)
E
======================================================================
ERROR: test (ClassEval_22_0.ClassRegistrationSystemTest.test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_22_0.py", line 264, in test
    self.assertEqual(self.registration_system.get_most_popular_class_in_major("Computer Science"), "Data Structures")
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_22_0.py", line 78, in get_most_popular_class_in_major
    most_popular_class = max(class_enrollment, key=class_enrollment.get)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: max() iterable argument is empty

----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (errors=1)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.002s

OK
.....E
======================================================================
ERROR: test_load_cookies_6 (ClassEval_25_0.CookiesUtilTestLoadCookies.test_load_cookies_6)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_25_0.py", line 131, in test_load_cookies_6
    self.assertEqual(self.cookies_util.load_cookies(), {})
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_25_0.py", line 33, in load_cookies
    with open(self.cookies_file, 'r') as file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: ''

----------------------------------------------------------------------
Ran 6 tests in 0.001s

FAILED (errors=1)
......
----------------------------------------------------------------------
Ran 6 tests in 0.002s

OK
E
======================================================================
ERROR: test_set_cookies (ClassEval_25_0.CookiesUtilTestSetCookies.test_set_cookies)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_25_0.py", line 180, in test_set_cookies
    self.cookies_util.set_cookies(request)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'CookiesUtil' object has no attribute 'set_cookies'. Did you mean: 'get_cookies'?

----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (errors=1)
.
----------------------------------------------------------------------
Ran 1 test in 0.001s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
F....
======================================================================
FAIL: test_fidelity_promo_1 (ClassEval_33_0.DiscountStrategyTestFidelityPromo.test_fidelity_promo_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_33_0.py", line 221, in test_fidelity_promo_1
    self.assertEqual(actual_discount, expected_discount)
AssertionError: 0 != 12.5

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=1)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.001s

OK
F
======================================================================
FAIL: test_DiscountStrategy (ClassEval_33_0.DiscountStrategyTest.test_DiscountStrategy)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_33_0.py", line 373, in test_DiscountStrategy
    self.assertEqual(actual_discount, expected_discount)
AssertionError: 0 != 12.5

----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (failures=1)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
..F.F
======================================================================
FAIL: test_fetch_3 (ClassEval_36_0.EmailClientTestFetch.test_fetch_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_36_0.py", line 175, in test_fetch_3
    self.assertEqual(receiver.fetch(), None)
AssertionError: {'sender': 'sender@example.com', 'receive[102 chars]ead'} != None

======================================================================
FAIL: test_fetch_5 (ClassEval_36_0.EmailClientTestFetch.test_fetch_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_36_0.py", line 198, in test_fetch_5
    self.assertEqual(receiver.fetch(), {'sender': 'sender@example.com', 'receiver': 'receiver@example.com', 'content': 'Hello', 'size': 10,
AssertionError: {'sen[80 chars]o', 'size': 10, 'time': '2021-01-01 00:00:00', 'state': 'read'} != {'sen[80 chars]o', 'size': 10, 'time': '2025-04-22 01:26:36', 'state': 'read'}
  {'content': 'Hello',
   'receiver': 'receiver@example.com',
   'sender': 'sender@example.com',
   'size': 10,
   'state': 'read',
-  'time': '2021-01-01 00:00:00'}
+  'time': '2025-04-22 01:26:36'}

----------------------------------------------------------------------
Ran 5 tests in 0.002s

FAILED (failures=2)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
EEEEE
======================================================================
ERROR: test_clear_inbox (ClassEval_36_0.EmailClientTestClearInbox.test_clear_inbox)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_36_0.py", line 273, in test_clear_inbox
    receiver.clear_inbox(30)
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_36_0.py", line 113, in clear_inbox
    oldest_email = min(self.inbox, key=lambda email: email['time'])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_36_0.py", line 113, in <lambda>
    oldest_email = min(self.inbox, key=lambda email: email['time'])
                                                     ~~~~~^^^^^^^^
KeyError: 'time'

======================================================================
ERROR: test_clear_inbox_2 (ClassEval_36_0.EmailClientTestClearInbox.test_clear_inbox_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_36_0.py", line 280, in test_clear_inbox_2
    self.assertEqual(receiver.clear_inbox(30),None)
                     ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_36_0.py", line 113, in clear_inbox
    oldest_email = min(self.inbox, key=lambda email: email['time'])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_36_0.py", line 113, in <lambda>
    oldest_email = min(self.inbox, key=lambda email: email['time'])
                                                     ~~~~~^^^^^^^^
KeyError: 'time'

======================================================================
ERROR: test_clear_inbox_3 (ClassEval_36_0.EmailClientTestClearInbox.test_clear_inbox_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_36_0.py", line 287, in test_clear_inbox_3
    self.assertEqual(receiver.clear_inbox(50), None)
                     ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_36_0.py", line 113, in clear_inbox
    oldest_email = min(self.inbox, key=lambda email: email['time'])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_36_0.py", line 113, in <lambda>
    oldest_email = min(self.inbox, key=lambda email: email['time'])
                                                     ~~~~~^^^^^^^^
KeyError: 'time'

======================================================================
ERROR: test_clear_inbox_4 (ClassEval_36_0.EmailClientTestClearInbox.test_clear_inbox_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_36_0.py", line 293, in test_clear_inbox_4
    receiver.clear_inbox(45)
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_36_0.py", line 113, in clear_inbox
    oldest_email = min(self.inbox, key=lambda email: email['time'])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_36_0.py", line 113, in <lambda>
    oldest_email = min(self.inbox, key=lambda email: email['time'])
                                                     ~~~~~^^^^^^^^
KeyError: 'time'

======================================================================
ERROR: test_clear_inbox_5 (ClassEval_36_0.EmailClientTestClearInbox.test_clear_inbox_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_36_0.py", line 299, in test_clear_inbox_5
    receiver.clear_inbox(10)
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_36_0.py", line 113, in clear_inbox
    oldest_email = min(self.inbox, key=lambda email: email['time'])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_36_0.py", line 113, in <lambda>
    oldest_email = min(self.inbox, key=lambda email: email['time'])
                                                     ~~~~~^^^^^^^^
KeyError: 'time'

----------------------------------------------------------------------
Ran 5 tests in 0.002s

FAILED (errors=5)
E
======================================================================
ERROR: test_main (ClassEval_36_0.EmailClientTestMain.test_main)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_36_0.py", line 316, in test_main
    receiver.clear_inbox(30)
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_36_0.py", line 113, in clear_inbox
    oldest_email = min(self.inbox, key=lambda email: email['time'])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_36_0.py", line 113, in <lambda>
    oldest_email = min(self.inbox, key=lambda email: email['time'])
                                                     ~~~~~^^^^^^^^
KeyError: 'time'

----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (errors=1)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.001s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.000s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.001s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....F
======================================================================
FAIL: test_update_employee_6 (ClassEval_43_0.HRManagementSystemTestUpdateEmployee.test_update_employee_6)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_43_0.py", line 208, in test_update_employee_6
    self.assertEqual(hr_system.update_employee(1, {'Name': 'John', 'position': 'Manager', 'department': 'Sales', 'salary': 20000}), False)
AssertionError: True != False

----------------------------------------------------------------------
Ran 6 tests in 0.001s

FAILED (failures=1)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
F.FFF
======================================================================
FAIL: test_list_employees (ClassEval_43_0.HRManagementSystemTestListEmployees.test_list_employees)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_43_0.py", line 243, in test_list_employees
    self.assertEqual(hr_system.list_employees(), {1: {'employee_ID':1,'name': 'John', 'position': 'Manager', 'department': 'Sales', 'salary': 100000}})
AssertionError: {1: {'name': 'John', 'position': 'Manager', 'de[33 chars]000}} != {1: {'employee_ID': 1, 'name': 'John', 'positio[51 chars]000}}
  {1: {'department': 'Sales',
+      'employee_ID': 1,
       'name': 'John',
       'position': 'Manager',
       'salary': 100000}}

======================================================================
FAIL: test_list_employees_3 (ClassEval_43_0.HRManagementSystemTestListEmployees.test_list_employees_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_43_0.py", line 253, in test_list_employees_3
    self.assertEqual(hr_system.list_employees(), {1: {'employee_ID':1,'name': 'John', 'position': 'Manager', 'department': 'Sales', 'salary': 100000}, 2: {'employee_ID':2,'name': 'Jane', 'position': 'Manager', 'department': 'Sales', 'salary': 100000}})
AssertionError: {1: {'name': 'John', 'position': 'Manager', 'de[118 chars]000}} != {1: {'employee_ID': 1, 'name': 'John', 'positio[154 chars]000}}
  {1: {'department': 'Sales',
+      'employee_ID': 1,
       'name': 'John',
       'position': 'Manager',
       'salary': 100000},
   2: {'department': 'Sales',
+      'employee_ID': 2,
       'name': 'Jane',
       'position': 'Manager',
       'salary': 100000}}

======================================================================
FAIL: test_list_employees_4 (ClassEval_43_0.HRManagementSystemTestListEmployees.test_list_employees_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_43_0.py", line 258, in test_list_employees_4
    self.assertEqual(hr_system.list_employees(), {1: {'employee_ID':1,'name': 'John', 'position': 'Manager', 'department': 'Sales', 'salary': 100000}, 2: {'employee_ID':2,'name': 'Jane', 'position': 'Manager', 'department': 'Sales', 'salary': 100000}})
AssertionError: {1: {'name': 'John', 'position': 'Manager', 'de[118 chars]000}} != {1: {'employee_ID': 1, 'name': 'John', 'positio[154 chars]000}}
  {1: {'department': 'Sales',
+      'employee_ID': 1,
       'name': 'John',
       'position': 'Manager',
       'salary': 100000},
   2: {'department': 'Sales',
+      'employee_ID': 2,
       'name': 'Jane',
       'position': 'Manager',
       'salary': 100000}}

======================================================================
FAIL: test_list_employees_5 (ClassEval_43_0.HRManagementSystemTestListEmployees.test_list_employees_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_43_0.py", line 265, in test_list_employees_5
    self.assertEqual(hr_system.list_employees(), {1: {'employee_ID':1,'name': 'John', 'position': 'Manager', 'department': 'Sales', 'salary': 100000}, 2: {'employee_ID':2,'name': 'Jane', 'position': 'Manager', 'department': 'Sales', 'salary': 100000}})
AssertionError: {1: {'name': 'John', 'position': 'Manager', 'de[118 chars]000}} != {1: {'employee_ID': 1, 'name': 'John', 'positio[154 chars]000}}
  {1: {'department': 'Sales',
+      'employee_ID': 1,
       'name': 'John',
       'position': 'Manager',
       'salary': 100000},
   2: {'department': 'Sales',
+      'employee_ID': 2,
       'name': 'Jane',
       'position': 'Manager',
       'salary': 100000}}

----------------------------------------------------------------------
Ran 5 tests in 0.004s

FAILED (failures=4)
FF
======================================================================
FAIL: test_main (ClassEval_43_0.HRManagementSystemTestMain.test_main)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_43_0.py", line 273, in test_main
    self.assertEqual(hr_system.list_employees(), {1: {'employee_ID': 1, 'name': 'John Doe', 'position': 'Manager', 'department': 'HR', 'salary': 5000}, 2: {'employee_ID': 2, 'name': 'Jane Smith', 'position': 'Developer', 'department': 'IT', 'salary': 4000}})
AssertionError: {1: {'name': 'John Doe', 'position': 'Manager',[120 chars]000}} != {1: {'employee_ID': 1, 'name': 'John Doe', 'pos[156 chars]000}}
  {1: {'department': 'HR',
+      'employee_ID': 1,
       'name': 'John Doe',
       'position': 'Manager',
       'salary': 5000},
   2: {'department': 'IT',
+      'employee_ID': 2,
       'name': 'Jane Smith',
       'position': 'Developer',
       'salary': 4000}}

======================================================================
FAIL: test_main_2 (ClassEval_43_0.HRManagementSystemTestMain.test_main_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_43_0.py", line 290, in test_main_2
    self.assertEqual(hr_system.list_employees(), {
AssertionError: {1: {'name': 'John Doe', 'position': 'Manager',[120 chars]000}} != {1: {'employee_ID': 1, 'name': 'John Doe', 'pos[156 chars]000}}
  {1: {'department': 'HR',
+      'employee_ID': 1,
       'name': 'John Doe',
       'position': 'Manager',
       'salary': 5000},
   2: {'department': 'IT',
+      'employee_ID': 2,
       'name': 'Jane Smith',
       'position': 'Developer',
       'salary': 4000}}

----------------------------------------------------------------------
Ran 2 tests in 0.001s

FAILED (failures=2)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
EEEEE
======================================================================
ERROR: test_matches_requirements (ClassEval_49_0.JobMarketplaceTestMatchesRequirements.test_matches_requirements)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_49_0.py", line 318, in test_matches_requirements
    self.assertEqual(jobMarketplace.matches_requirements({"name": "Tom", "skills": ['skill1', 'skill2'], "experience": "experience"}, ['skill1', 'skill2']), True)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_49_0.py", line 112, in matches_requirements
    for requirement in job['requirements']:
                       ~~~^^^^^^^^^^^^^^^^
TypeError: list indices must be integers or slices, not str

======================================================================
ERROR: test_matches_requirements_2 (ClassEval_49_0.JobMarketplaceTestMatchesRequirements.test_matches_requirements_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_49_0.py", line 322, in test_matches_requirements_2
    self.assertEqual(jobMarketplace.matches_requirements({"name": "Tom", "skills": ['skill1', 'skill2'], "experience": "experience"}, ['skill3', 'skill4']), False)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_49_0.py", line 112, in matches_requirements
    for requirement in job['requirements']:
                       ~~~^^^^^^^^^^^^^^^^
TypeError: list indices must be integers or slices, not str

======================================================================
ERROR: test_matches_requirements_3 (ClassEval_49_0.JobMarketplaceTestMatchesRequirements.test_matches_requirements_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_49_0.py", line 326, in test_matches_requirements_3
    self.assertEqual(jobMarketplace.matches_requirements({"name": "Tom", "skills": ['skill1', 'skill2'], "experience": "experience"}, ['skill5', 'skill6']), False)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_49_0.py", line 112, in matches_requirements
    for requirement in job['requirements']:
                       ~~~^^^^^^^^^^^^^^^^
TypeError: list indices must be integers or slices, not str

======================================================================
ERROR: test_matches_requirements_4 (ClassEval_49_0.JobMarketplaceTestMatchesRequirements.test_matches_requirements_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_49_0.py", line 330, in test_matches_requirements_4
    self.assertEqual(jobMarketplace.matches_requirements({"name": "Tom", "skills": ['skill1', 'skill2'], "experience": "experience"}, ['skill1', 'skill3']), False)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_49_0.py", line 112, in matches_requirements
    for requirement in job['requirements']:
                       ~~~^^^^^^^^^^^^^^^^
TypeError: list indices must be integers or slices, not str

======================================================================
ERROR: test_matches_requirements_5 (ClassEval_49_0.JobMarketplaceTestMatchesRequirements.test_matches_requirements_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_49_0.py", line 334, in test_matches_requirements_5
    self.assertEqual(jobMarketplace.matches_requirements({"name": "Tom", "skills": ['skill1', 'skill2'], "experience": "experience"}, ['skill1']), False)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_49_0.py", line 112, in matches_requirements
    for requirement in job['requirements']:
                       ~~~^^^^^^^^^^^^^^^^
TypeError: list indices must be integers or slices, not str

----------------------------------------------------------------------
Ran 5 tests in 0.002s

FAILED (errors=5)
E
======================================================================
ERROR: test_main (ClassEval_49_0.JobMarketplaceTestMain.test_main)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_49_0.py", line 351, in test_main
    self.assertEqual(jobMarketplace.matches_requirements({"name": "Tom", "skills": ['skill1', 'skill2'], "experience": "experience"}, ['skill1', 'skill2']), True)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_49_0.py", line 112, in matches_requirements
    for requirement in job['requirements']:
                       ~~~^^^^^^^^^^^^^^^^
TypeError: list indices must be integers or slices, not str

----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (errors=1)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.001s

OK
..F..
======================================================================
FAIL: test_book_ticket_3 (ClassEval_59_0.MovieBookingSystemTestBookTicket.test_book_ticket_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_59_0.py", line 164, in test_book_ticket_3
    self.assertEqual(result, 'Movie not found.')
AssertionError: 'Booking success.' != 'Movie not found.'
- Booking success.
+ Movie not found.


----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=1)
F.FFF
======================================================================
FAIL: test_available_movies_1 (ClassEval_59_0.MovieBookingSystemTestAvailableMovies.test_available_movies_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_59_0.py", line 187, in test_available_movies_1
    self.assertEqual(result, ['Batman', 'Spiderman'])
AssertionError: Lists differ: [] != ['Batman', 'Spiderman']

Second list contains 2 additional elements.
First extra element 0:
'Batman'

- []
+ ['Batman', 'Spiderman']

======================================================================
FAIL: test_available_movies_3 (ClassEval_59_0.MovieBookingSystemTestAvailableMovies.test_available_movies_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_59_0.py", line 195, in test_available_movies_3
    self.assertEqual(result, ['Batman'])
AssertionError: Lists differ: [] != ['Batman']

Second list contains 1 additional elements.
First extra element 0:
'Batman'

- []
+ ['Batman']

======================================================================
FAIL: test_available_movies_4 (ClassEval_59_0.MovieBookingSystemTestAvailableMovies.test_available_movies_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_59_0.py", line 199, in test_available_movies_4
    self.assertEqual(result, ['Batman', 'Spiderman'])
AssertionError: Lists differ: [] != ['Batman', 'Spiderman']

Second list contains 2 additional elements.
First extra element 0:
'Batman'

- []
+ ['Batman', 'Spiderman']

======================================================================
FAIL: test_available_movies_5 (ClassEval_59_0.MovieBookingSystemTestAvailableMovies.test_available_movies_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_59_0.py", line 203, in test_available_movies_5
    self.assertEqual(result, ['Spiderman'])
AssertionError: Lists differ: [] != ['Spiderman']

Second list contains 1 additional elements.
First extra element 0:
'Spiderman'

- []
+ ['Spiderman']

----------------------------------------------------------------------
Ran 5 tests in 0.002s

FAILED (failures=4)
F
======================================================================
FAIL: test_main (ClassEval_59_0.MovieBookingSystemTestMain.test_main)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_59_0.py", line 224, in test_main
    self.assertEqual(result, ['Batman'])
AssertionError: Lists differ: [] != ['Batman']

Second list contains 1 additional elements.
First extra element 0:
'Batman'

- []
+ ['Batman']

----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (failures=1)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....E
======================================================================
ERROR: test_remove_song6 (ClassEval_61_0.MusicPlayerTestRemoveSong.test_remove_song6)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_61_0.py", line 210, in test_remove_song6
    musicPlayer.remove_song("song1")
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_61_0.py", line 37, in remove_song
    self.playlist.remove(song)
ValueError: list.remove(x): x not in list

----------------------------------------------------------------------
Ran 6 tests in 0.001s

FAILED (errors=1)
.F.F.
======================================================================
FAIL: test_play_2 (ClassEval_61_0.MusicPlayerTestPlay.test_play_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_61_0.py", line 225, in test_play_2
    self.assertEqual(musicPlayer.play(), None)
AssertionError: 'song2' != None

======================================================================
FAIL: test_play_4 (ClassEval_61_0.MusicPlayerTestPlay.test_play_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_61_0.py", line 236, in test_play_4
    self.assertEqual(musicPlayer.play(), "song1")
AssertionError: 'song3' != 'song1'
- song3
?     ^
+ song1
?     ^


----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=2)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
FFF..
======================================================================
FAIL: test_set_volume (ClassEval_61_0.MusicPlayerTestSetVolume.test_set_volume)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_61_0.py", line 335, in test_set_volume
    self.assertEqual(musicPlayer.set_volume(50), None)
AssertionError: True != None

======================================================================
FAIL: test_set_volume2 (ClassEval_61_0.MusicPlayerTestSetVolume.test_set_volume2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_61_0.py", line 340, in test_set_volume2
    self.assertEqual(musicPlayer.set_volume(100), None)
AssertionError: True != None

======================================================================
FAIL: test_set_volume3 (ClassEval_61_0.MusicPlayerTestSetVolume.test_set_volume3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_61_0.py", line 345, in test_set_volume3
    self.assertEqual(musicPlayer.set_volume(0), None)
AssertionError: True != None

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=3)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....F
======================================================================
FAIL: test_add_dish_6 (ClassEval_67_0.OrderTestAddDish.test_add_dish_6)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_67_0.py", line 166, in test_add_dish_6
    self.assertTrue(result)
AssertionError: False is not true

----------------------------------------------------------------------
Ran 6 tests in 0.001s

FAILED (failures=1)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
F.FFF
======================================================================
FAIL: test_checkout_1 (ClassEval_67_0.OrderTestCheckout.test_checkout_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_67_0.py", line 231, in test_checkout_1
    self.assertEqual([], self.order.selected_dishes)
AssertionError: Lists differ: [] != [{'dish': 'dish1', 'price': 10, 'count': 2[41 chars]: 2}]

Second list contains 2 additional elements.
First extra element 0:
{'dish': 'dish1', 'price': 10, 'count': 2}

- []
+ [{'count': 2, 'dish': 'dish1', 'price': 10},
+  {'count': 2, 'dish': 'dish3', 'price': 20}]

======================================================================
FAIL: test_checkout_3 (ClassEval_67_0.OrderTestCheckout.test_checkout_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_67_0.py", line 253, in test_checkout_3
    self.assertEqual([], self.order.selected_dishes)
AssertionError: Lists differ: [] != [{'dish': 'dish1', 'price': 10, 'count': 1[41 chars]: 1}]

Second list contains 2 additional elements.
First extra element 0:
{'dish': 'dish1', 'price': 10, 'count': 1}

- []
+ [{'count': 1, 'dish': 'dish1', 'price': 10},
+  {'count': 1, 'dish': 'dish3', 'price': 20}]

======================================================================
FAIL: test_checkout_4 (ClassEval_67_0.OrderTestCheckout.test_checkout_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_67_0.py", line 269, in test_checkout_4
    self.assertEqual([], self.order.selected_dishes)
AssertionError: Lists differ: [] != [{'dish': 'dish1', 'price': 10, 'count': 3[41 chars]: 3}]

Second list contains 2 additional elements.
First extra element 0:
{'dish': 'dish1', 'price': 10, 'count': 3}

- []
+ [{'count': 3, 'dish': 'dish1', 'price': 10},
+  {'count': 3, 'dish': 'dish3', 'price': 20}]

======================================================================
FAIL: test_checkout_5 (ClassEval_67_0.OrderTestCheckout.test_checkout_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_67_0.py", line 285, in test_checkout_5
    self.assertEqual([], self.order.selected_dishes)
AssertionError: Lists differ: [] != [{'dish': 'dish1', 'price': 10, 'count': 5[41 chars]: 5}]

Second list contains 2 additional elements.
First extra element 0:
{'dish': 'dish1', 'price': 10, 'count': 5}

- []
+ [{'count': 5, 'dish': 'dish1', 'price': 10},
+  {'count': 5, 'dish': 'dish3', 'price': 20}]

----------------------------------------------------------------------
Ran 5 tests in 0.002s

FAILED (failures=4)
F
======================================================================
FAIL: test_order (ClassEval_67_0.OrderTest.test_order)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_67_0.py", line 311, in test_order
    self.assertEqual([], self.order.selected_dishes)
AssertionError: Lists differ: [] != [{'dish': 'dish1', 'price': 10, 'count': 2[41 chars]: 2}]

Second list contains 2 additional elements.
First extra element 0:
{'dish': 'dish1', 'price': 10, 'count': 2}

- []
+ [{'count': 2, 'dish': 'dish1', 'price': 10},
+  {'count': 2, 'dish': 'dish3', 'price': 20}]

----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (failures=1)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
....F
======================================================================
FAIL: test_get_page_info_5 (ClassEval_68_0.PageUtilTestGetPageInfo.test_get_page_info_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_68_0.py", line 194, in test_get_page_info_5
    self.assertEqual(actual_info, empty_info)
AssertionError: {'current_page': 5, 'per_page': 3, 'total_[77 chars]: []} != {}
+ {}
- {'current_page': 5,
-  'data': [],
-  'has_next': False,
-  'has_previous': True,
-  'per_page': 3,
-  'total_items': 10,
-  'total_pages': 4}

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=1)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
F.EEE
======================================================================
ERROR: test_recv_3 (ClassEval_74_0.ServerTestRecv.test_recv_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_74_0.py", line 166, in test_recv_3
    flag = server.recv([88])
           ^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_74_0.py", line 56, in recv
    addr = info["addr"]
           ~~~~^^^^^^^^
TypeError: list indices must be integers or slices, not str

======================================================================
ERROR: test_recv_4 (ClassEval_74_0.ServerTestRecv.test_recv_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_74_0.py", line 172, in test_recv_4
    flag = server.recv({"addr": 88})
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_74_0.py", line 57, in recv
    content = info["content"]
              ~~~~^^^^^^^^^^^
KeyError: 'content'

======================================================================
ERROR: test_recv_5 (ClassEval_74_0.ServerTestRecv.test_recv_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_74_0.py", line 178, in test_recv_5
    flag = server.recv({"content": "abc"})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_74_0.py", line 56, in recv
    addr = info["addr"]
           ~~~~^^^^^^^^
KeyError: 'addr'

======================================================================
FAIL: test_recv_1 (ClassEval_74_0.ServerTestRecv.test_recv_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_74_0.py", line 155, in test_recv_1
    self.assertEqual(server.receive_struct, {"addr": 88, "content": "abc"})
AssertionError: {} != {'addr': 88, 'content': 'abc'}
- {}
+ {'addr': 88, 'content': 'abc'}

----------------------------------------------------------------------
Ran 5 tests in 0.002s

FAILED (failures=1, errors=3)
.FFF.
======================================================================
FAIL: test_send_2 (ClassEval_74_0.ServerTestSend.test_send_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_74_0.py", line 192, in test_send_2
    self.assertEqual(flag, "info structure is not correct")
AssertionError: None != 'info structure is not correct'

======================================================================
FAIL: test_send_3 (ClassEval_74_0.ServerTestSend.test_send_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_74_0.py", line 197, in test_send_3
    self.assertEqual(flag, "info structure is not correct")
AssertionError: None != 'info structure is not correct'

======================================================================
FAIL: test_send_4 (ClassEval_74_0.ServerTestSend.test_send_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_74_0.py", line 202, in test_send_4
    self.assertEqual(flag, "info structure is not correct")
AssertionError: None != 'info structure is not correct'

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=3)
.F...
======================================================================
FAIL: test_show_2 (ClassEval_74_0.ServerTestShow.test_show_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_74_0.py", line 223, in test_show_2
    self.assertEqual(server.show("receive"), {"addr": 66, "content": "ABC"})
AssertionError: {} != {'addr': 66, 'content': 'ABC'}
- {}
+ {'addr': 66, 'content': 'ABC'}

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=1)
F
======================================================================
FAIL: test_server (ClassEval_74_0.ServerTest.test_server)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_74_0.py", line 256, in test_server
    self.assertEqual(server.receive_struct, {"addr": 88, "content": "abc"})
AssertionError: {} != {'addr': 88, 'content': 'abc'}
- {}
+ {'addr': 88, 'content': 'abc'}

----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (failures=1)
......
----------------------------------------------------------------------
Ran 6 tests in 0.000s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
....F
======================================================================
FAIL: test_auto_check_conflict_5 (ClassEval_85_0.ThermostatTestAutoCheckConflict.test_auto_check_conflict_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_85_0.py", line 245, in test_auto_check_conflict_5
    self.assertFalse(t.auto_check_conflict())
AssertionError: True is not false

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=1)
FE...
======================================================================
ERROR: test_simulate_operation_2 (ClassEval_85_0.ThermostatTestSimulateOperation.test_simulate_operation_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_85_0.py", line 258, in test_simulate_operation_2
    self.assertEqual(t.simulate_operation(), 6)
                     ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_85_0.py", line 91, in simulate_operation
    while self.current_temperature != self.target_temperature:
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
func_timeout.dafunc.FunctionTimedOut-7517440176399073444: Function run_unit_test (args=(<test_pipeline.AutoTest object at 0x10dbce9c0>, 'ClassEval_85_0', 'ThermostatTestSimulateOperation', 'ChatGPT_greedy_Management_Systems')) (kwargs={}) timed out after 5.000000 seconds.


======================================================================
FAIL: test_simulate_operation_1 (ClassEval_85_0.ThermostatTestSimulateOperation.test_simulate_operation_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_85_0.py", line 252, in test_simulate_operation_1
    self.assertEqual(t.simulate_operation(), 5)
AssertionError: 0 != 5

----------------------------------------------------------------------
Ran 5 tests in 5.017s

FAILED (failures=1, errors=1)
F
======================================================================
FAIL: test_main (ClassEval_85_0.ThermostatTestMain.test_main)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_85_0.py", line 291, in test_main
    self.assertFalse(t.auto_check_conflict())
AssertionError: True is not false

----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (failures=1)
.F.FF
======================================================================
FAIL: test_add_item_2 (ClassEval_94_0.VendingMachineTestAddItem.test_add_item_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_94_0.py", line 116, in test_add_item_2
    self.assertEqual(vendingMachine.inventory, {'Coke': {'price': 1.25, 'quantity': 20}})
AssertionError: {'Coke': {'price': 1.25, 'quantity': 10}} != {'Coke': {'price': 1.25, 'quantity': 20}}
- {'Coke': {'price': 1.25, 'quantity': 10}}
?                                      ^

+ {'Coke': {'price': 1.25, 'quantity': 20}}
?                                      ^


======================================================================
FAIL: test_add_item_4 (ClassEval_94_0.VendingMachineTestAddItem.test_add_item_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_94_0.py", line 129, in test_add_item_4
    self.assertEqual(vendingMachine.inventory, {'Coke': {'price': 1.25, 'quantity': 10}, 'Pizza': {'price': 1.25, 'quantity': 20}})
AssertionError: {'Cok[15 chars].25, 'quantity': 10}, 'Pizza': {'price': 1.25, 'quantity': 10}} != {'Cok[15 chars].25, 'quantity': 10}, 'Pizza': {'price': 1.25, 'quantity': 20}}
  {'Coke': {'price': 1.25, 'quantity': 10},
-  'Pizza': {'price': 1.25, 'quantity': 10}}
?                                       ^

+  'Pizza': {'price': 1.25, 'quantity': 20}}
?                                       ^


======================================================================
FAIL: test_add_item_5 (ClassEval_94_0.VendingMachineTestAddItem.test_add_item_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_94_0.py", line 137, in test_add_item_5
    self.assertEqual(vendingMachine.inventory, {'Coke': {'price': 1.25, 'quantity': 20}, 'Pizza': {'price': 1.25, 'quantity': 20}})
AssertionError: {'Cok[15 chars].25, 'quantity': 10}, 'Pizza': {'price': 1.25, 'quantity': 10}} != {'Cok[15 chars].25, 'quantity': 20}, 'Pizza': {'price': 1.25, 'quantity': 20}}
- {'Coke': {'price': 1.25, 'quantity': 10},
?                                      ^

+ {'Coke': {'price': 1.25, 'quantity': 20},
?                                      ^

-  'Pizza': {'price': 1.25, 'quantity': 10}}
?                                       ^

+  'Pizza': {'price': 1.25, 'quantity': 20}}
?                                       ^


----------------------------------------------------------------------
Ran 5 tests in 0.002s

FAILED (failures=3)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
..F..
======================================================================
FAIL: test_purchase_item_3 (ClassEval_94_0.VendingMachineTestPurchaseItem.test_purchase_item_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_94_0.py", line 190, in test_purchase_item_3
    self.assertEqual(vendingMachine.purchase_item('Coke'), False)
AssertionError: -1.25 != False

----------------------------------------------------------------------
Ran 5 tests in 0.000s

FAILED (failures=1)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
..F.F
======================================================================
FAIL: test_display_items_3 (ClassEval_94_0.VendingMachineTestDisplayItems.test_display_items_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_94_0.py", line 250, in test_display_items_3
    self.assertEqual(vendingMachine.display_items(),"Coke - $1.25 [10]\nPizza - $1.25 [10]")
AssertionError: 'Coke - $1.25 [10], Pizza - $1.25 [10]' != 'Coke - $1.25 [10]\nPizza - $1.25 [10]'
- Coke - $1.25 [10], Pizza - $1.25 [10]
+ Coke - $1.25 [10]
+ Pizza - $1.25 [10]


======================================================================
FAIL: test_display_items_5 (ClassEval_94_0.VendingMachineTestDisplayItems.test_display_items_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_94_0.py", line 260, in test_display_items_5
    self.assertEqual(vendingMachine.display_items(), 'Coke - $1.25 [0]\nPizza - $1.25 [10]')
AssertionError: 'Coke - $1.25 [0], Pizza - $1.25 [10]' != 'Coke - $1.25 [0]\nPizza - $1.25 [10]'
- Coke - $1.25 [0], Pizza - $1.25 [10]
+ Coke - $1.25 [0]
+ Pizza - $1.25 [10]


----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=2)
..
----------------------------------------------------------------------
Ran 2 tests in 0.000s

OK
.....F
======================================================================
FAIL: test_add_product_6 (ClassEval_95_0.WarehouseTestAddProduct.test_add_product_6)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_95_0.py", line 146, in test_add_product_6
    self.assertEqual(warehouse.inventory, {1: {'name': 'product 5', 'quantity': 20}})
AssertionError: {1: {'name': 'product 5', 'quantity': 10}} != {1: {'name': 'product 5', 'quantity': 20}}
- {1: {'name': 'product 5', 'quantity': 10}}
?                                       ^

+ {1: {'name': 'product 5', 'quantity': 20}}
?                                       ^


----------------------------------------------------------------------
Ran 6 tests in 0.001s

FAILED (failures=1)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.F.FF.
======================================================================
FAIL: test_query_2 (ClassEval_96_0.WeatherSystemTestQuery.test_query_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_96_0.py", line 104, in test_query_2
    self.assertEqual(weatherSystem.query(weather_list), False)
AssertionError: (None, None) != False

======================================================================
FAIL: test_query_4 (ClassEval_96_0.WeatherSystemTestQuery.test_query_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_96_0.py", line 136, in test_query_4
    self.assertEqual(weatherSystem.query(weather_list, 'celsius'), (23.000000000000004, 'cloudy'))
AssertionError: Tuples differ: (73.4, 'cloudy') != (23.000000000000004, 'cloudy')

First differing element 0:
73.4
23.000000000000004

- (73.4, 'cloudy')
+ (23.000000000000004, 'cloudy')

======================================================================
FAIL: test_query_5 (ClassEval_96_0.WeatherSystemTestQuery.test_query_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_96_0.py", line 152, in test_query_5
    self.assertEqual(weatherSystem.query(weather_list, tmp_units='celsius'), (26.999999999999996, 'sunny'))
AssertionError: Tuples differ: (80.6, 'sunny') != (26.999999999999996, 'sunny')

First differing element 0:
80.6
26.999999999999996

- (80.6, 'sunny')
+ (26.999999999999996, 'sunny')

----------------------------------------------------------------------
Ran 6 tests in 0.001s

FAILED (failures=3)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
