.....
----------------------------------------------------------------------
Ran 5 tests in 0.001s

OK
.....E
======================================================================
ERROR: test_calculate_hand_value_6 (ClassEval_12_0.BlackjackGameTestCalculateHandValue.test_calculate_hand_value_6)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_12_0.py", line 159, in test_calculate_hand_value_6
    self.assertEqual(blackjackGame.calculate_hand_value(hand), 20)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_12_0.py", line 53, in calculate_hand_value
    total += int(rank)
             ^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'B'

----------------------------------------------------------------------
Ran 6 tests in 0.001s

FAILED (errors=1)
......
----------------------------------------------------------------------
Ran 6 tests in 0.001s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.001s

OK
.....E
======================================================================
ERROR: test_calculate_hand_value_6 (ClassEval_12_1.BlackjackGameTestCalculateHandValue.test_calculate_hand_value_6)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_12_1.py", line 159, in test_calculate_hand_value_6
    self.assertEqual(blackjackGame.calculate_hand_value(hand), 20)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_12_1.py", line 53, in calculate_hand_value
    total += int(rank)
             ^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'B'

----------------------------------------------------------------------
Ran 6 tests in 0.001s

FAILED (errors=1)
......
----------------------------------------------------------------------
Ran 6 tests in 0.001s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.001s

OK
.....E
======================================================================
ERROR: test_calculate_hand_value_6 (ClassEval_12_2.BlackjackGameTestCalculateHandValue.test_calculate_hand_value_6)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_12_2.py", line 120, in test_calculate_hand_value_6
    self.assertEqual(blackjackGame.calculate_hand_value(hand), 20)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_12_2.py", line 32, in calculate_hand_value
    total += int(rank)
             ^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'B'

----------------------------------------------------------------------
Ran 6 tests in 0.001s

FAILED (errors=1)
......
----------------------------------------------------------------------
Ran 6 tests in 0.001s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.001s

OK
.....E
======================================================================
ERROR: test_calculate_hand_value_6 (ClassEval_12_3.BlackjackGameTestCalculateHandValue.test_calculate_hand_value_6)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_12_3.py", line 153, in test_calculate_hand_value_6
    self.assertEqual(blackjackGame.calculate_hand_value(hand), 20)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_12_3.py", line 56, in calculate_hand_value
    total += int(rank)
             ^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'B'

----------------------------------------------------------------------
Ran 6 tests in 0.001s

FAILED (errors=1)
......
----------------------------------------------------------------------
Ran 6 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.001s

OK
.....E
======================================================================
ERROR: test_calculate_hand_value_6 (ClassEval_12_4.BlackjackGameTestCalculateHandValue.test_calculate_hand_value_6)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_12_4.py", line 120, in test_calculate_hand_value_6
    self.assertEqual(blackjackGame.calculate_hand_value(hand), 20)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_12_4.py", line 32, in calculate_hand_value
    total += int(rank)
             ^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'B'

----------------------------------------------------------------------
Ran 6 tests in 0.001s

FAILED (errors=1)
......
----------------------------------------------------------------------
Ran 6 tests in 0.001s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....F
======================================================================
FAIL: test_solve_6 (ClassEval_35_0.EightPuzzleTestSolve.test_solve_6)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_35_0.py", line 238, in test_solve_6
    self.assertEqual(result, expected)
AssertionError: [] != None

----------------------------------------------------------------------
Ran 6 tests in 0.116s

FAILED (failures=1)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....F
======================================================================
FAIL: test_solve_6 (ClassEval_35_1.EightPuzzleTestSolve.test_solve_6)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_35_1.py", line 252, in test_solve_6
    self.assertEqual(result, expected)
AssertionError: [] != None

----------------------------------------------------------------------
Ran 6 tests in 0.275s

FAILED (failures=1)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.001s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....F
======================================================================
FAIL: test_solve_6 (ClassEval_35_2.EightPuzzleTestSolve.test_solve_6)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_35_2.py", line 200, in test_solve_6
    self.assertEqual(result, expected)
AssertionError: [] != None

----------------------------------------------------------------------
Ran 6 tests in 0.554s

FAILED (failures=1)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.001s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....F
======================================================================
FAIL: test_solve_6 (ClassEval_35_3.EightPuzzleTestSolve.test_solve_6)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_35_3.py", line 206, in test_solve_6
    self.assertEqual(result, expected)
AssertionError: [] != None

----------------------------------------------------------------------
Ran 6 tests in 0.115s

FAILED (failures=1)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....F
======================================================================
FAIL: test_solve_6 (ClassEval_35_4.EightPuzzleTestSolve.test_solve_6)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_35_4.py", line 265, in test_solve_6
    self.assertEqual(result, expected)
AssertionError: [] != None

----------------------------------------------------------------------
Ran 6 tests in 0.120s

FAILED (failures=1)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.001s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.002s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....F
======================================================================
FAIL: test_is_valid_move_6 (ClassEval_54_0.MahjongConnectTestIsValidMove.test_is_valid_move_6)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_54_0.py", line 163, in test_is_valid_move_6
    self.assertEqual(res, False)
AssertionError: True != False

----------------------------------------------------------------------
Ran 6 tests in 0.001s

FAILED (failures=1)
...F..
======================================================================
FAIL: test_has_path_4 (ClassEval_54_0.MahjongConnectTestHasPath.test_has_path_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_54_0.py", line 201, in test_has_path_4
    self.assertEqual(res, False)
AssertionError: True != False

----------------------------------------------------------------------
Ran 6 tests in 0.001s

FAILED (failures=1)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.000s

OK
...FE.
======================================================================
ERROR: test_has_path_5 (ClassEval_54_1.MahjongConnectTestHasPath.test_has_path_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_54_1.py", line 297, in test_has_path_5
    res = mc.has_path((300, 0), (1, 1))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_54_1.py", line 98, in has_path
    icon = self.board[pos1[0]][pos1[1]]
           ~~~~~~~~~~^^^^^^^^^
IndexError: list index out of range

======================================================================
FAIL: test_has_path_4 (ClassEval_54_1.MahjongConnectTestHasPath.test_has_path_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_54_1.py", line 289, in test_has_path_4
    self.assertEqual(res, False)
AssertionError: True != False

----------------------------------------------------------------------
Ran 6 tests in 0.001s

FAILED (failures=1, errors=1)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.000s

OK
..F.EF
======================================================================
ERROR: test_has_path_5 (ClassEval_54_2.MahjongConnectTestHasPath.test_has_path_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_54_2.py", line 211, in test_has_path_5
    res = mc.has_path((300, 0), (1, 1))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_54_2.py", line 39, in has_path
    visited[pos1[0]][pos1[1]] = True
    ~~~~~~~^^^^^^^^^
IndexError: list index out of range

======================================================================
FAIL: test_has_path_3 (ClassEval_54_2.MahjongConnectTestHasPath.test_has_path_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_54_2.py", line 194, in test_has_path_3
    self.assertEqual(res, True)
AssertionError: False != True

======================================================================
FAIL: test_has_path_6 (ClassEval_54_2.MahjongConnectTestHasPath.test_has_path_6)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_54_2.py", line 221, in test_has_path_6
    self.assertEqual(res, True)
AssertionError: False != True

----------------------------------------------------------------------
Ran 6 tests in 0.001s

FAILED (failures=2, errors=1)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.001s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.000s

OK
..F..F
======================================================================
FAIL: test_has_path_3 (ClassEval_54_3.MahjongConnectTestHasPath.test_has_path_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_54_3.py", line 193, in test_has_path_3
    self.assertEqual(res, True)
AssertionError: False != True

======================================================================
FAIL: test_has_path_6 (ClassEval_54_3.MahjongConnectTestHasPath.test_has_path_6)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_54_3.py", line 220, in test_has_path_6
    self.assertEqual(res, True)
AssertionError: False != True

----------------------------------------------------------------------
Ran 6 tests in 0.001s

FAILED (failures=2)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.000s

OK
...FE.
======================================================================
ERROR: test_has_path_5 (ClassEval_54_4.MahjongConnectTestHasPath.test_has_path_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_54_4.py", line 213, in test_has_path_5
    res = mc.has_path((300, 0), (1, 1))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_54_4.py", line 39, in has_path
    target_icon = self.board[pos1[0]][pos1[1]]
                  ~~~~~~~~~~^^^^^^^^^
IndexError: list index out of range

======================================================================
FAIL: test_has_path_4 (ClassEval_54_4.MahjongConnectTestHasPath.test_has_path_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_54_4.py", line 205, in test_has_path_4
    self.assertEqual(res, False)
AssertionError: True != False

----------------------------------------------------------------------
Ran 6 tests in 0.001s

FAILED (failures=1, errors=1)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.001s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.001s

OK
F.FFF
======================================================================
FAIL: test_sweep (ClassEval_58_0.MinesweeperGameTestSweep.test_sweep)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_58_0.py", line 224, in test_sweep
    self.assertEqual(minesweeper_game.score, 1)
AssertionError: 0 != 1

======================================================================
FAIL: test_sweep_3 (ClassEval_58_0.MinesweeperGameTestSweep.test_sweep_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_58_0.py", line 238, in test_sweep_3
    self.assertEqual(minesweeper_game.score, 1)
AssertionError: 0 != 1

======================================================================
FAIL: test_sweep_4 (ClassEval_58_0.MinesweeperGameTestSweep.test_sweep_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_58_0.py", line 244, in test_sweep_4
    self.assertEqual(minesweeper_game.sweep(0,2), [['-', '-', 0], ['-', '-', '0'], ['0', '0', '0']])
AssertionError: Lists differ: [['-', 1, 0], ['-', 1, '0'], ['0', '0', '0']] != [['-', '-', 0], ['-', '-', '0'], ['0', '0', '0']]

First differing element 0:
['-', 1, 0]
['-', '-', 0]

- [['-', 1, 0], ['-', 1, '0'], ['0', '0', '0']]
?        ^            ^

+ [['-', '-', 0], ['-', '-', '0'], ['0', '0', '0']]
?        ^^^            ^^^


======================================================================
FAIL: test_sweep_5 (ClassEval_58_0.MinesweeperGameTestSweep.test_sweep_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_58_0.py", line 252, in test_sweep_5
    self.assertEqual(minesweeper_game.score, 1)
AssertionError: 0 != 1

----------------------------------------------------------------------
Ran 5 tests in 0.003s

FAILED (failures=4)
FF
======================================================================
FAIL: test_minesweeper_main (ClassEval_58_0.MinesweeperGameTestMain.test_minesweeper_main)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_58_0.py", line 270, in test_minesweeper_main
    self.assertEqual(minesweeper_game.score, 1)
AssertionError: 0 != 1

======================================================================
FAIL: test_minesweeper_main_2 (ClassEval_58_0.MinesweeperGameTestMain.test_minesweeper_main_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_58_0.py", line 286, in test_minesweeper_main_2
    self.assertEqual(minesweeper_game.score, 1)
AssertionError: 0 != 1

----------------------------------------------------------------------
Ran 2 tests in 0.001s

FAILED (failures=2)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.001s

OK
...EE
======================================================================
ERROR: test_generate_playerMap_4 (ClassEval_58_1.MinesweeperGameTestGeneratePlayerMap.test_generate_playerMap_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_58_1.py", line 175, in test_generate_playerMap_4
    minesweeper_game = MinesweeperGame(1, 4)
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_58_1.py", line 19, in __init__
    self.minesweeper_map = self.generate_mine_sweeper_map()
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_58_1.py", line 30, in generate_mine_sweeper_map
    mines = random.sample([(i, j) for i in range(self.n) for j in range(self.n)], self.k)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/lib/python3.12/random.py", line 430, in sample
    raise ValueError("Sample larger than population or is negative")
ValueError: Sample larger than population or is negative

======================================================================
ERROR: test_generate_playerMap_5 (ClassEval_58_1.MinesweeperGameTestGeneratePlayerMap.test_generate_playerMap_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_58_1.py", line 179, in test_generate_playerMap_5
    minesweeper_game = MinesweeperGame(2, 5)
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_58_1.py", line 19, in __init__
    self.minesweeper_map = self.generate_mine_sweeper_map()
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_58_1.py", line 30, in generate_mine_sweeper_map
    mines = random.sample([(i, j) for i in range(self.n) for j in range(self.n)], self.k)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/lib/python3.12/random.py", line 430, in sample
    raise ValueError("Sample larger than population or is negative")
ValueError: Sample larger than population or is negative

----------------------------------------------------------------------
Ran 5 tests in 0.002s

FAILED (errors=2)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
F.FFF
======================================================================
FAIL: test_sweep (ClassEval_58_1.MinesweeperGameTestSweep.test_sweep)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_58_1.py", line 219, in test_sweep
    self.assertEqual(minesweeper_game.score, 1)
AssertionError: 0 != 1

======================================================================
FAIL: test_sweep_3 (ClassEval_58_1.MinesweeperGameTestSweep.test_sweep_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_58_1.py", line 233, in test_sweep_3
    self.assertEqual(minesweeper_game.score, 1)
AssertionError: 0 != 1

======================================================================
FAIL: test_sweep_4 (ClassEval_58_1.MinesweeperGameTestSweep.test_sweep_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_58_1.py", line 239, in test_sweep_4
    self.assertEqual(minesweeper_game.sweep(0,2), [['-', '-', 0], ['-', '-', '0'], ['0', '0', '0']])
AssertionError: Lists differ: [['-', 1, 0], ['-', 1, '0'], ['0', '0', '0']] != [['-', '-', 0], ['-', '-', '0'], ['0', '0', '0']]

First differing element 0:
['-', 1, 0]
['-', '-', 0]

- [['-', 1, 0], ['-', 1, '0'], ['0', '0', '0']]
?        ^            ^

+ [['-', '-', 0], ['-', '-', '0'], ['0', '0', '0']]
?        ^^^            ^^^


======================================================================
FAIL: test_sweep_5 (ClassEval_58_1.MinesweeperGameTestSweep.test_sweep_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_58_1.py", line 247, in test_sweep_5
    self.assertEqual(minesweeper_game.score, 1)
AssertionError: 0 != 1

----------------------------------------------------------------------
Ran 5 tests in 0.002s

FAILED (failures=4)
FF
======================================================================
FAIL: test_minesweeper_main (ClassEval_58_1.MinesweeperGameTestMain.test_minesweeper_main)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_58_1.py", line 265, in test_minesweeper_main
    self.assertEqual(minesweeper_game.score, 1)
AssertionError: 0 != 1

======================================================================
FAIL: test_minesweeper_main_2 (ClassEval_58_1.MinesweeperGameTestMain.test_minesweeper_main_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_58_1.py", line 281, in test_minesweeper_main_2
    self.assertEqual(minesweeper_game.score, 1)
AssertionError: 0 != 1

----------------------------------------------------------------------
Ran 2 tests in 0.001s

FAILED (failures=2)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.001s

OK
...EE
======================================================================
ERROR: test_generate_playerMap_4 (ClassEval_58_2.MinesweeperGameTestGeneratePlayerMap.test_generate_playerMap_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_58_2.py", line 191, in test_generate_playerMap_4
    minesweeper_game = MinesweeperGame(1, 4)
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_58_2.py", line 18, in __init__
    self.minesweeper_map = self.generate_mine_sweeper_map()
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_58_2.py", line 35, in generate_mine_sweeper_map
    mine_coords = random.sample(coords, k)
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/lib/python3.12/random.py", line 430, in sample
    raise ValueError("Sample larger than population or is negative")
ValueError: Sample larger than population or is negative

======================================================================
ERROR: test_generate_playerMap_5 (ClassEval_58_2.MinesweeperGameTestGeneratePlayerMap.test_generate_playerMap_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_58_2.py", line 195, in test_generate_playerMap_5
    minesweeper_game = MinesweeperGame(2, 5)
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_58_2.py", line 18, in __init__
    self.minesweeper_map = self.generate_mine_sweeper_map()
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_58_2.py", line 35, in generate_mine_sweeper_map
    mine_coords = random.sample(coords, k)
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/lib/python3.12/random.py", line 430, in sample
    raise ValueError("Sample larger than population or is negative")
ValueError: Sample larger than population or is negative

----------------------------------------------------------------------
Ran 5 tests in 0.002s

FAILED (errors=2)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.001s

OK
F.FFF
======================================================================
FAIL: test_sweep (ClassEval_58_2.MinesweeperGameTestSweep.test_sweep)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_58_2.py", line 235, in test_sweep
    self.assertEqual(minesweeper_game.score, 1)
AssertionError: 0 != 1

======================================================================
FAIL: test_sweep_3 (ClassEval_58_2.MinesweeperGameTestSweep.test_sweep_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_58_2.py", line 249, in test_sweep_3
    self.assertEqual(minesweeper_game.score, 1)
AssertionError: 0 != 1

======================================================================
FAIL: test_sweep_4 (ClassEval_58_2.MinesweeperGameTestSweep.test_sweep_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_58_2.py", line 255, in test_sweep_4
    self.assertEqual(minesweeper_game.sweep(0,2), [['-', '-', 0], ['-', '-', '0'], ['0', '0', '0']])
AssertionError: Lists differ: [['-', 1, 0], ['-', 1, '0'], ['0', '0', '0']] != [['-', '-', 0], ['-', '-', '0'], ['0', '0', '0']]

First differing element 0:
['-', 1, 0]
['-', '-', 0]

- [['-', 1, 0], ['-', 1, '0'], ['0', '0', '0']]
?        ^            ^

+ [['-', '-', 0], ['-', '-', '0'], ['0', '0', '0']]
?        ^^^            ^^^


======================================================================
FAIL: test_sweep_5 (ClassEval_58_2.MinesweeperGameTestSweep.test_sweep_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_58_2.py", line 263, in test_sweep_5
    self.assertEqual(minesweeper_game.score, 1)
AssertionError: 0 != 1

----------------------------------------------------------------------
Ran 5 tests in 0.002s

FAILED (failures=4)
FF
======================================================================
FAIL: test_minesweeper_main (ClassEval_58_2.MinesweeperGameTestMain.test_minesweeper_main)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_58_2.py", line 281, in test_minesweeper_main
    self.assertEqual(minesweeper_game.score, 1)
AssertionError: 0 != 1

======================================================================
FAIL: test_minesweeper_main_2 (ClassEval_58_2.MinesweeperGameTestMain.test_minesweeper_main_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_58_2.py", line 297, in test_minesweeper_main_2
    self.assertEqual(minesweeper_game.score, 1)
AssertionError: 0 != 1

----------------------------------------------------------------------
Ran 2 tests in 0.001s

FAILED (failures=2)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
...EE
======================================================================
ERROR: test_generate_playerMap_4 (ClassEval_58_3.MinesweeperGameTestGeneratePlayerMap.test_generate_playerMap_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_58_3.py", line 160, in test_generate_playerMap_4
    minesweeper_game = MinesweeperGame(1, 4)
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_58_3.py", line 18, in __init__
    self.minesweeper_map = self.generate_mine_sweeper_map()
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_58_3.py", line 29, in generate_mine_sweeper_map
    mine_positions = random.sample(positions, self.k)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/lib/python3.12/random.py", line 430, in sample
    raise ValueError("Sample larger than population or is negative")
ValueError: Sample larger than population or is negative

======================================================================
ERROR: test_generate_playerMap_5 (ClassEval_58_3.MinesweeperGameTestGeneratePlayerMap.test_generate_playerMap_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_58_3.py", line 164, in test_generate_playerMap_5
    minesweeper_game = MinesweeperGame(2, 5)
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_58_3.py", line 18, in __init__
    self.minesweeper_map = self.generate_mine_sweeper_map()
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_58_3.py", line 29, in generate_mine_sweeper_map
    mine_positions = random.sample(positions, self.k)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/lib/python3.12/random.py", line 430, in sample
    raise ValueError("Sample larger than population or is negative")
ValueError: Sample larger than population or is negative

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (errors=2)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
F.FFF
======================================================================
FAIL: test_sweep (ClassEval_58_3.MinesweeperGameTestSweep.test_sweep)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_58_3.py", line 204, in test_sweep
    self.assertEqual(minesweeper_game.score, 1)
AssertionError: 0 != 1

======================================================================
FAIL: test_sweep_3 (ClassEval_58_3.MinesweeperGameTestSweep.test_sweep_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_58_3.py", line 218, in test_sweep_3
    self.assertEqual(minesweeper_game.score, 1)
AssertionError: 0 != 1

======================================================================
FAIL: test_sweep_4 (ClassEval_58_3.MinesweeperGameTestSweep.test_sweep_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_58_3.py", line 225, in test_sweep_4
    self.assertEqual(minesweeper_game.score, 1)
AssertionError: 0 != 1

======================================================================
FAIL: test_sweep_5 (ClassEval_58_3.MinesweeperGameTestSweep.test_sweep_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_58_3.py", line 232, in test_sweep_5
    self.assertEqual(minesweeper_game.score, 1)
AssertionError: 0 != 1

----------------------------------------------------------------------
Ran 5 tests in 0.002s

FAILED (failures=4)
FF
======================================================================
FAIL: test_minesweeper_main (ClassEval_58_3.MinesweeperGameTestMain.test_minesweeper_main)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_58_3.py", line 250, in test_minesweeper_main
    self.assertEqual(minesweeper_game.score, 1)
AssertionError: 0 != 1

======================================================================
FAIL: test_minesweeper_main_2 (ClassEval_58_3.MinesweeperGameTestMain.test_minesweeper_main_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_58_3.py", line 266, in test_minesweeper_main_2
    self.assertEqual(minesweeper_game.score, 1)
AssertionError: 0 != 1

----------------------------------------------------------------------
Ran 2 tests in 0.001s

FAILED (failures=2)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
...EE
======================================================================
ERROR: test_generate_playerMap_4 (ClassEval_58_4.MinesweeperGameTestGeneratePlayerMap.test_generate_playerMap_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_58_4.py", line 176, in test_generate_playerMap_4
    minesweeper_game = MinesweeperGame(1, 4)
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_58_4.py", line 18, in __init__
    self.minesweeper_map = self.generate_mine_sweeper_map()
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_58_4.py", line 30, in generate_mine_sweeper_map
    mines = random.sample([(i, j) for i in range(n) for j in range(n)], k)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/lib/python3.12/random.py", line 430, in sample
    raise ValueError("Sample larger than population or is negative")
ValueError: Sample larger than population or is negative

======================================================================
ERROR: test_generate_playerMap_5 (ClassEval_58_4.MinesweeperGameTestGeneratePlayerMap.test_generate_playerMap_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_58_4.py", line 180, in test_generate_playerMap_5
    minesweeper_game = MinesweeperGame(2, 5)
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_58_4.py", line 18, in __init__
    self.minesweeper_map = self.generate_mine_sweeper_map()
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_58_4.py", line 30, in generate_mine_sweeper_map
    mines = random.sample([(i, j) for i in range(n) for j in range(n)], k)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/lib/python3.12/random.py", line 430, in sample
    raise ValueError("Sample larger than population or is negative")
ValueError: Sample larger than population or is negative

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (errors=2)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
F.FFF
======================================================================
FAIL: test_sweep (ClassEval_58_4.MinesweeperGameTestSweep.test_sweep)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_58_4.py", line 220, in test_sweep
    self.assertEqual(minesweeper_game.score, 1)
AssertionError: 0 != 1

======================================================================
FAIL: test_sweep_3 (ClassEval_58_4.MinesweeperGameTestSweep.test_sweep_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_58_4.py", line 234, in test_sweep_3
    self.assertEqual(minesweeper_game.score, 1)
AssertionError: 0 != 1

======================================================================
FAIL: test_sweep_4 (ClassEval_58_4.MinesweeperGameTestSweep.test_sweep_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_58_4.py", line 241, in test_sweep_4
    self.assertEqual(minesweeper_game.score, 1)
AssertionError: 0 != 1

======================================================================
FAIL: test_sweep_5 (ClassEval_58_4.MinesweeperGameTestSweep.test_sweep_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_58_4.py", line 248, in test_sweep_5
    self.assertEqual(minesweeper_game.score, 1)
AssertionError: 0 != 1

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=4)
FF
======================================================================
FAIL: test_minesweeper_main (ClassEval_58_4.MinesweeperGameTestMain.test_minesweeper_main)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_58_4.py", line 266, in test_minesweeper_main
    self.assertEqual(minesweeper_game.score, 1)
AssertionError: 0 != 1

======================================================================
FAIL: test_minesweeper_main_2 (ClassEval_58_4.MinesweeperGameTestMain.test_minesweeper_main_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_58_4.py", line 282, in test_minesweeper_main_2
    self.assertEqual(minesweeper_game.score, 1)
AssertionError: 0 != 1

----------------------------------------------------------------------
Ran 2 tests in 0.001s

FAILED (failures=2)
.......
----------------------------------------------------------------------
Ran 7 tests in 0.001s

OK
.F
======================================================================
FAIL: test_check_win_2 (ClassEval_71_0.PushBoxGameTestCheckWin.test_check_win_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_71_0.py", line 180, in test_check_win_2
    self.assertTrue(self.game.check_win())
AssertionError: False is not true

----------------------------------------------------------------------
Ran 2 tests in 0.001s

FAILED (failures=1)
F......
======================================================================
FAIL: test_move_1 (ClassEval_71_0.PushBoxGameTestMove.test_move_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_71_0.py", line 197, in test_move_1
    self.assertTrue(self.game.move('d'))
AssertionError: False is not true

----------------------------------------------------------------------
Ran 7 tests in 0.001s

FAILED (failures=1)
.......
----------------------------------------------------------------------
Ran 7 tests in 0.001s

OK
.F
======================================================================
FAIL: test_check_win_2 (ClassEval_71_1.PushBoxGameTestCheckWin.test_check_win_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_71_1.py", line 181, in test_check_win_2
    self.assertTrue(self.game.check_win())
AssertionError: False is not true

----------------------------------------------------------------------
Ran 2 tests in 0.001s

FAILED (failures=1)
F......
======================================================================
FAIL: test_move_1 (ClassEval_71_1.PushBoxGameTestMove.test_move_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_71_1.py", line 198, in test_move_1
    self.assertTrue(self.game.move('d'))
AssertionError: False is not true

----------------------------------------------------------------------
Ran 7 tests in 0.001s

FAILED (failures=1)
.......
----------------------------------------------------------------------
Ran 7 tests in 0.001s

OK
..
----------------------------------------------------------------------
Ran 2 tests in 0.000s

OK
.......
----------------------------------------------------------------------
Ran 7 tests in 0.000s

OK
.......
----------------------------------------------------------------------
Ran 7 tests in 0.000s

OK
..
----------------------------------------------------------------------
Ran 2 tests in 0.000s

OK
.......
----------------------------------------------------------------------
Ran 7 tests in 0.000s

OK
.......
----------------------------------------------------------------------
Ran 7 tests in 0.001s

OK
..
----------------------------------------------------------------------
Ran 2 tests in 0.000s

OK
.....E.
======================================================================
ERROR: test_move_6 (ClassEval_71_4.PushBoxGameTestMove.test_move_6)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_71_4.py", line 239, in test_move_6
    self.game.move('?')
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_71_4.py", line 98, in move
    dr, dc = direction_map[direction]
             ~~~~~~~~~~~~~^^^^^^^^^^^
KeyError: '?'

----------------------------------------------------------------------
Ran 7 tests in 0.001s

FAILED (errors=1)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.F...
======================================================================
FAIL: test_level_up_2 (ClassEval_73_2.RPGCharacterTestLevelUp.test_level_up_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_73_2.py", line 194, in test_level_up_2
    self.assertEqual(character.level, 100)
AssertionError: 101 != 100

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=1)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.FFFF
======================================================================
FAIL: test_gain_exp_2 (ClassEval_73_3.RPGCharacterTestGainExp.test_gain_exp_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_73_3.py", line 158, in test_gain_exp_2
    self.assertEqual(character.level, 5)
AssertionError: 2 != 5

======================================================================
FAIL: test_gain_exp_3 (ClassEval_73_3.RPGCharacterTestGainExp.test_gain_exp_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_73_3.py", line 165, in test_gain_exp_3
    self.assertEqual(character.exp, 100)
AssertionError: 0 != 100

======================================================================
FAIL: test_gain_exp_4 (ClassEval_73_3.RPGCharacterTestGainExp.test_gain_exp_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_73_3.py", line 170, in test_gain_exp_4
    self.assertEqual(character.level, 3)
AssertionError: 2 != 3

======================================================================
FAIL: test_gain_exp_5 (ClassEval_73_3.RPGCharacterTestGainExp.test_gain_exp_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_73_3.py", line 176, in test_gain_exp_5
    self.assertEqual(character.level, 3)
AssertionError: 2 != 3

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=4)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
F
======================================================================
FAIL: test_main (ClassEval_73_3.RPGCharacterTestMain.test_main)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_73_3.py", line 258, in test_main
    self.assertEqual(character1.exp, 100)
AssertionError: 0 != 100

----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (failures=1)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
F....
======================================================================
FAIL: test_move_1 (ClassEval_77_1.SnakeTestMove.test_move_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_77_1.py", line 85, in test_move_1
    self.assertEqual(snake.positions[0], (51, 51))
AssertionError: Tuples differ: (50, 50) != (51, 51)

First differing element 0:
50
51

- (50, 50)
?   ^   ^

+ (51, 51)
?   ^   ^


----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=1)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
F
======================================================================
FAIL: test_snake (ClassEval_77_1.SnakeTest.test_snake)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_77_1.py", line 276, in test_snake
    self.assertEqual(snake.positions[0], (51, 51))
AssertionError: Tuples differ: (50, 50) != (51, 51)

First differing element 0:
50
51

- (50, 50)
?   ^   ^

+ (51, 51)
?   ^   ^


----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (failures=1)
F....
======================================================================
FAIL: test_move_1 (ClassEval_77_2.SnakeTestMove.test_move_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_77_2.py", line 89, in test_move_1
    self.assertEqual(snake.positions[0], (51, 51))
AssertionError: Tuples differ: (50, 50) != (51, 51)

First differing element 0:
50
51

- (50, 50)
?   ^   ^

+ (51, 51)
?   ^   ^


----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=1)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
FFFFF
======================================================================
FAIL: test_eat_food_1 (ClassEval_77_2.SnakeTestEatFood.test_eat_food_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_77_2.py", line 223, in test_eat_food_1
    self.assertEqual(snake.score, 100)
AssertionError: 10 != 100

======================================================================
FAIL: test_eat_food_2 (ClassEval_77_2.SnakeTestEatFood.test_eat_food_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_77_2.py", line 232, in test_eat_food_2
    self.assertEqual(snake.score, 200)
AssertionError: 20 != 200

======================================================================
FAIL: test_eat_food_3 (ClassEval_77_2.SnakeTestEatFood.test_eat_food_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_77_2.py", line 242, in test_eat_food_3
    self.assertEqual(snake.score, 300)
AssertionError: 30 != 300

======================================================================
FAIL: test_eat_food_4 (ClassEval_77_2.SnakeTestEatFood.test_eat_food_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_77_2.py", line 253, in test_eat_food_4
    self.assertEqual(snake.score, 400)
AssertionError: 40 != 400

======================================================================
FAIL: test_eat_food_5 (ClassEval_77_2.SnakeTestEatFood.test_eat_food_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_77_2.py", line 265, in test_eat_food_5
    self.assertEqual(snake.score, 500)
AssertionError: 50 != 500

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=5)
F
======================================================================
FAIL: test_snake (ClassEval_77_2.SnakeTest.test_snake)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_77_2.py", line 280, in test_snake
    self.assertEqual(snake.positions[0], (51, 51))
AssertionError: Tuples differ: (50, 50) != (51, 51)

First differing element 0:
50
51

- (50, 50)
?   ^   ^

+ (51, 51)
?   ^   ^


----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (failures=1)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
F....
======================================================================
FAIL: test_move_1 (ClassEval_77_4.SnakeTestMove.test_move_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_77_4.py", line 102, in test_move_1
    self.assertEqual(snake.positions[0], (51, 51))
AssertionError: Tuples differ: (50.0, 50.0) != (51, 51)

First differing element 0:
50.0
51

- (50.0, 50.0)
+ (51, 51)

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=1)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
FFFFF
======================================================================
FAIL: test_eat_food_1 (ClassEval_77_4.SnakeTestEatFood.test_eat_food_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_77_4.py", line 236, in test_eat_food_1
    self.assertEqual(snake.score, 100)
AssertionError: 10 != 100

======================================================================
FAIL: test_eat_food_2 (ClassEval_77_4.SnakeTestEatFood.test_eat_food_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_77_4.py", line 245, in test_eat_food_2
    self.assertEqual(snake.score, 200)
AssertionError: 20 != 200

======================================================================
FAIL: test_eat_food_3 (ClassEval_77_4.SnakeTestEatFood.test_eat_food_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_77_4.py", line 255, in test_eat_food_3
    self.assertEqual(snake.score, 300)
AssertionError: 30 != 300

======================================================================
FAIL: test_eat_food_4 (ClassEval_77_4.SnakeTestEatFood.test_eat_food_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_77_4.py", line 266, in test_eat_food_4
    self.assertEqual(snake.score, 400)
AssertionError: 40 != 400

======================================================================
FAIL: test_eat_food_5 (ClassEval_77_4.SnakeTestEatFood.test_eat_food_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_77_4.py", line 278, in test_eat_food_5
    self.assertEqual(snake.score, 500)
AssertionError: 50 != 500

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=5)
F
======================================================================
FAIL: test_snake (ClassEval_77_4.SnakeTest.test_snake)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_77_4.py", line 293, in test_snake
    self.assertEqual(snake.positions[0], (51, 51))
AssertionError: Tuples differ: (50.0, 50.0) != (51, 51)

First differing element 0:
50.0
51

- (50.0, 50.0)
+ (51, 51)

----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (failures=1)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.001s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
EF.....
======================================================================
ERROR: test_answer_1 (ClassEval_89_0.TwentyFourPointGameTestAnswer.test_answer_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_89_0.py", line 110, in test_answer_1
    self.assertEqual(len(cards), 4)
                     ^^^^^^^^^^
TypeError: object of type 'bool' has no len()

======================================================================
FAIL: test_answer_2 (ClassEval_89_0.TwentyFourPointGameTestAnswer.test_answer_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_89_0.py", line 115, in test_answer_2
    self.assertTrue(result)
AssertionError: False is not true

----------------------------------------------------------------------
Ran 7 tests in 0.001s

FAILED (failures=1, errors=1)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.001s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.002s

OK
EF.....
======================================================================
ERROR: test_answer_1 (ClassEval_89_1.TwentyFourPointGameTestAnswer.test_answer_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_89_1.py", line 110, in test_answer_1
    self.assertEqual(len(cards), 4)
                     ^^^^^^^^^^
TypeError: object of type 'bool' has no len()

======================================================================
FAIL: test_answer_2 (ClassEval_89_1.TwentyFourPointGameTestAnswer.test_answer_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_89_1.py", line 115, in test_answer_2
    self.assertTrue(result)
AssertionError: False is not true

----------------------------------------------------------------------
Ran 7 tests in 0.002s

FAILED (failures=1, errors=1)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.001s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
E......
======================================================================
ERROR: test_answer_1 (ClassEval_89_2.TwentyFourPointGameTestAnswer.test_answer_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_89_2.py", line 93, in test_answer_1
    self.assertEqual(len(cards), 4)
                     ^^^^^^^^^^
TypeError: object of type 'bool' has no len()

----------------------------------------------------------------------
Ran 7 tests in 0.003s

FAILED (errors=1)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.001s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
E......
======================================================================
ERROR: test_answer_1 (ClassEval_89_3.TwentyFourPointGameTestAnswer.test_answer_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_89_3.py", line 95, in test_answer_1
    self.assertEqual(len(cards), 4)
                     ^^^^^^^^^^
TypeError: object of type 'bool' has no len()

----------------------------------------------------------------------
Ran 7 tests in 0.001s

FAILED (errors=1)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.001s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
EF.....
======================================================================
ERROR: test_answer_1 (ClassEval_89_4.TwentyFourPointGameTestAnswer.test_answer_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_89_4.py", line 98, in test_answer_1
    self.assertEqual(len(cards), 4)
                     ^^^^^^^^^^
TypeError: object of type 'bool' has no len()

======================================================================
FAIL: test_answer_2 (ClassEval_89_4.TwentyFourPointGameTestAnswer.test_answer_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_89_4.py", line 103, in test_answer_2
    self.assertTrue(result)
AssertionError: False is not true

----------------------------------------------------------------------
Ran 7 tests in 0.001s

FAILED (failures=1, errors=1)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.001s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
