FFFFF.FF
======================================================================
FAIL: test_filter_1 (ClassEval_0_0.AccessGatewayFilterTestFilter.test_filter_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_0_0.py", line 76, in test_filter_1
    self.assertTrue(res)
AssertionError: False is not true

======================================================================
FAIL: test_filter_2 (ClassEval_0_0.AccessGatewayFilterTestFilter.test_filter_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_0_0.py", line 82, in test_filter_2
    self.assertTrue(res)
AssertionError: False is not true

======================================================================
FAIL: test_filter_3 (ClassEval_0_0.AccessGatewayFilterTestFilter.test_filter_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_0_0.py", line 88, in test_filter_3
    self.assertTrue(res)
AssertionError: False is not true

======================================================================
FAIL: test_filter_4 (ClassEval_0_0.AccessGatewayFilterTestFilter.test_filter_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_0_0.py", line 94, in test_filter_4
    self.assertTrue(res)
AssertionError: False is not true

======================================================================
FAIL: test_filter_5 (ClassEval_0_0.AccessGatewayFilterTestFilter.test_filter_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_0_0.py", line 103, in test_filter_5
    self.assertTrue(res)
AssertionError: False is not true

======================================================================
FAIL: test_filter_7 (ClassEval_0_0.AccessGatewayFilterTestFilter.test_filter_7)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_0_0.py", line 121, in test_filter_7
    self.assertIsNone(res)
AssertionError: False is not None

======================================================================
FAIL: test_filter_8 (ClassEval_0_0.AccessGatewayFilterTestFilter.test_filter_8)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_0_0.py", line 130, in test_filter_8
    self.assertTrue(res)
AssertionError: False is not true

----------------------------------------------------------------------
Ran 8 tests in 0.003s

FAILED (failures=7)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
....F
======================================================================
FAIL: test_get_jwt_user_5 (ClassEval_0_0.AccessGatewayFilterTestGetJwtUser.test_get_jwt_user_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_0_0.py", line 199, in test_get_jwt_user_5
    self.assertIsNone(res)
AssertionError: {'name': 'user1'} is not None

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=1)
F
======================================================================
FAIL: test_AccessGatewayFilter (ClassEval_0_0.AccessGatewayFilterTest.test_AccessGatewayFilter)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_0_0.py", line 207, in test_AccessGatewayFilter
    self.assertTrue(res)
AssertionError: False is not true

----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (failures=1)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.E...
======================================================================
ERROR: test_get_course_average_2 (ClassEval_4_0.AssessmentSystemTestGetCourseAverage.test_get_course_average_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_4_0.py", line 230, in test_get_course_average_2
    self.assertEqual(assessment_system.get_course_average('Physics'), 85)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_4_0.py", line 40, in get_course_average
    return sum(scores) / len(scores)
           ^^^^^^^^^^^
TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (errors=1)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.........
----------------------------------------------------------------------
Ran 9 tests in 0.001s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.001s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.000s

OK
..
----------------------------------------------------------------------
Ran 2 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.FFFF
======================================================================
FAIL: test_get_available_slots_2 (ClassEval_17_0.CalendarTestGetAvailableSlots.test_get_available_slots_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_17_0.py", line 262, in test_get_available_slots_2
    self.assertEqual(len(calendar.get_available_slots(datetime(2023, 1, 1))), 23)
AssertionError: 2 != 23

======================================================================
FAIL: test_get_available_slots_3 (ClassEval_17_0.CalendarTestGetAvailableSlots.test_get_available_slots_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_17_0.py", line 268, in test_get_available_slots_3
    self.assertEqual(len(calendar.get_available_slots(datetime(2023, 1, 1))), 24)
AssertionError: 1 != 24

======================================================================
FAIL: test_get_available_slots_4 (ClassEval_17_0.CalendarTestGetAvailableSlots.test_get_available_slots_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_17_0.py", line 274, in test_get_available_slots_4
    self.assertEqual(len(calendar.get_available_slots(datetime(2023, 1, 1))), 24)
AssertionError: 1 != 24

======================================================================
FAIL: test_get_available_slots_5 (ClassEval_17_0.CalendarTestGetAvailableSlots.test_get_available_slots_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_17_0.py", line 280, in test_get_available_slots_5
    self.assertEqual(len(calendar.get_available_slots(datetime(2023, 1, 1))), 24)
AssertionError: 1 != 24

----------------------------------------------------------------------
Ran 5 tests in 0.002s

FAILED (failures=4)
FFFFF
======================================================================
FAIL: test_get_upcoming_events (ClassEval_17_0.CalendarTestGetUpcomingEvents.test_get_upcoming_events)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_17_0.py", line 288, in test_get_upcoming_events
    self.assertEqual(calendar.get_upcoming_events(1), [])
AssertionError: Lists differ: [{'date': datetime.datetime(2023, 1, 1, 0,[128 chars]ar'}] != []

First list contains 1 additional elements.
First extra element 0:
{'date': datetime.datetime(2023, 1, 1, 0, 0), 'start_time': datetime.datetime(2023, 1, 1, 0, 0), 'end_time': datetime.datetime(2023, 1, 1, 23, 0), 'description': 'New Year'}

+ []
- [{'date': datetime.datetime(2023, 1, 1, 0, 0),
-   'description': 'New Year',
-   'end_time': datetime.datetime(2023, 1, 1, 23, 0),
-   'start_time': datetime.datetime(2023, 1, 1, 0, 0)}]

======================================================================
FAIL: test_get_upcoming_events_2 (ClassEval_17_0.CalendarTestGetUpcomingEvents.test_get_upcoming_events_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_17_0.py", line 294, in test_get_upcoming_events_2
    self.assertEqual(calendar.get_upcoming_events(1), [])
AssertionError: Lists differ: [{'date': datetime.datetime(2023, 1, 1, 0,[127 chars]ar'}] != []

First list contains 1 additional elements.
First extra element 0:
{'date': datetime.datetime(2023, 1, 1, 0, 0), 'start_time': datetime.datetime(2023, 1, 1, 1, 0), 'end_time': datetime.datetime(2023, 1, 1, 2, 0), 'description': 'New Year'}

+ []
- [{'date': datetime.datetime(2023, 1, 1, 0, 0),
-   'description': 'New Year',
-   'end_time': datetime.datetime(2023, 1, 1, 2, 0),
-   'start_time': datetime.datetime(2023, 1, 1, 1, 0)}]

======================================================================
FAIL: test_get_upcoming_events_3 (ClassEval_17_0.CalendarTestGetUpcomingEvents.test_get_upcoming_events_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_17_0.py", line 300, in test_get_upcoming_events_3
    self.assertEqual(calendar.get_upcoming_events(1), [])
AssertionError: Lists differ: [{'date': datetime.datetime(2023, 1, 1, 0,[127 chars]ar'}] != []

First list contains 1 additional elements.
First extra element 0:
{'date': datetime.datetime(2023, 1, 1, 0, 0), 'start_time': datetime.datetime(2023, 1, 2, 1, 0), 'end_time': datetime.datetime(2023, 1, 2, 2, 0), 'description': 'New Year'}

+ []
- [{'date': datetime.datetime(2023, 1, 1, 0, 0),
-   'description': 'New Year',
-   'end_time': datetime.datetime(2023, 1, 2, 2, 0),
-   'start_time': datetime.datetime(2023, 1, 2, 1, 0)}]

======================================================================
FAIL: test_get_upcoming_events_4 (ClassEval_17_0.CalendarTestGetUpcomingEvents.test_get_upcoming_events_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_17_0.py", line 306, in test_get_upcoming_events_4
    self.assertEqual(calendar.get_upcoming_events(2), [])
AssertionError: Lists differ: [{'date': datetime.datetime(2023, 1, 1, 0,[127 chars]ar'}] != []

First list contains 1 additional elements.
First extra element 0:
{'date': datetime.datetime(2023, 1, 1, 0, 0), 'start_time': datetime.datetime(2023, 1, 2, 1, 0), 'end_time': datetime.datetime(2023, 1, 2, 2, 0), 'description': 'New Year'}

+ []
- [{'date': datetime.datetime(2023, 1, 1, 0, 0),
-   'description': 'New Year',
-   'end_time': datetime.datetime(2023, 1, 2, 2, 0),
-   'start_time': datetime.datetime(2023, 1, 2, 1, 0)}]

======================================================================
FAIL: test_get_upcoming_events_5 (ClassEval_17_0.CalendarTestGetUpcomingEvents.test_get_upcoming_events_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_17_0.py", line 315, in test_get_upcoming_events_5
    self.assertEqual(calendar.get_upcoming_events(1), [
AssertionError: Lists differ: [{'da[21 chars]e(2023, 1, 1, 0, 0), 'start_time': datetime.da[98 chars]ar'}] != [{'da[21 chars]e(2024, 1, 2, 0, 0), 'start_time': datetime.da[99 chars] 2'}]

First differing element 0:
{'dat[20 chars]e(2023, 1, 1, 0, 0), 'start_time': datetime.da[97 chars]ear'}
{'dat[20 chars]e(2024, 1, 2, 0, 0), 'start_time': datetime.da[98 chars]r 2'}

Diff is 695 characters long. Set self.maxDiff to None to see it.

----------------------------------------------------------------------
Ran 5 tests in 0.004s

FAILED (failures=5)
F
======================================================================
FAIL: test_main (ClassEval_17_0.CalendarTestMain.test_main)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_17_0.py", line 339, in test_main
    self.assertEqual(calendar.get_upcoming_events(1), [])
AssertionError: Lists differ: [{'date': datetime.datetime(2023, 1, 1, 0,[128 chars]ar'}] != []

First list contains 1 additional elements.
First extra element 0:
{'date': datetime.datetime(2023, 1, 1, 0, 0), 'start_time': datetime.datetime(2023, 1, 1, 0, 0), 'end_time': datetime.datetime(2023, 1, 1, 23, 0), 'description': 'New Year'}

+ []
- [{'date': datetime.datetime(2023, 1, 1, 0, 0),
-   'description': 'New Year',
-   'end_time': datetime.datetime(2023, 1, 1, 23, 0),
-   'start_time': datetime.datetime(2023, 1, 1, 0, 0)}]

----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (failures=1)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.001s

OK
F....
======================================================================
FAIL: test_send_message (ClassEval_20_0.ChatTestSendMessage.test_send_message)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_20_0.py", line 133, in test_send_message
    self.assertEqual(chat.users, {'John': [{'sender': 'John', 'receiver': 'Mary', 'message': 'Hello', 'timestamp': timestamp}], 'Mary': [{'sender': 'John', 'receiver': 'Mary', 'message': 'Hello', 'timestamp': timestamp}]})
AssertionError: {'Joh[106 chars]y': []} != {'Joh[106 chars]y': [{'sender': 'John', 'receiver': 'Mary', 'm[50 chars]0'}]}
  {'John': [{'message': 'Hello',
             'receiver': 'Mary',
             'sender': 'John',
             'timestamp': '2025-04-22 01:27:20'}],
-  'Mary': []}
+  'Mary': [{'message': 'Hello',
+            'receiver': 'Mary',
+            'sender': 'John',
+            'timestamp': '2025-04-22 01:27:20'}]}

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=1)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
FF
======================================================================
FAIL: test_main (ClassEval_20_0.ChatTestMain.test_main)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_20_0.py", line 201, in test_main
    self.assertEqual(chat.users, {'John': [{'sender': 'John', 'receiver': 'Mary', 'message': 'Hello', 'timestamp': timestamp}], 'Mary': [{'sender': 'John', 'receiver': 'Mary', 'message': 'Hello', 'timestamp': timestamp}]})
AssertionError: {'Joh[106 chars]y': []} != {'Joh[106 chars]y': [{'sender': 'John', 'receiver': 'Mary', 'm[50 chars]0'}]}
  {'John': [{'message': 'Hello',
             'receiver': 'Mary',
             'sender': 'John',
             'timestamp': '2025-04-22 01:27:20'}],
-  'Mary': []}
+  'Mary': [{'message': 'Hello',
+            'receiver': 'Mary',
+            'sender': 'John',
+            'timestamp': '2025-04-22 01:27:20'}]}

======================================================================
FAIL: test_main_2 (ClassEval_20_0.ChatTestMain.test_main_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_20_0.py", line 216, in test_main_2
    self.assertEqual(chat.users, {'John': [{'sender': 'John', 'receiver': 'Mary', 'message': 'Hello', 'timestamp': timestamp}], 'Mary': [{'sender': 'John', 'receiver': 'Mary', 'message': 'Hello', 'timestamp': timestamp}]})
AssertionError: {'Joh[106 chars]y': []} != {'Joh[106 chars]y': [{'sender': 'John', 'receiver': 'Mary', 'm[50 chars]0'}]}
  {'John': [{'message': 'Hello',
             'receiver': 'Mary',
             'sender': 'John',
             'timestamp': '2025-04-22 01:27:20'}],
-  'Mary': []}
+  'Mary': [{'message': 'Hello',
+            'receiver': 'Mary',
+            'sender': 'John',
+            'timestamp': '2025-04-22 01:27:20'}]}

----------------------------------------------------------------------
Ran 2 tests in 0.002s

FAILED (failures=2)
......
----------------------------------------------------------------------
Ran 6 tests in 0.001s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.001s

OK
...
----------------------------------------------------------------------
Ran 3 tests in 0.000s

OK
...
----------------------------------------------------------------------
Ran 3 tests in 0.000s

OK
....
----------------------------------------------------------------------
Ran 4 tests in 0.001s

OK
..F
======================================================================
FAIL: test_get_all_major3 (ClassEval_22_0.ClassRegistrationSystemTestGetMajor.test_get_all_major3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_22_0.py", line 203, in test_get_all_major3
    self.assertEqual(majors, ["Computer Science", "Mathematics", "Physics"])
AssertionError: Lists differ: ['Computer Science', 'Physics', 'Mathematics'] != ['Computer Science', 'Mathematics', 'Physics']

First differing element 1:
'Physics'
'Mathematics'

- ['Computer Science', 'Physics', 'Mathematics']
?                     -----------

+ ['Computer Science', 'Mathematics', 'Physics']
?                                   +++++++++++


----------------------------------------------------------------------
Ran 3 tests in 0.001s

FAILED (failures=1)
..
----------------------------------------------------------------------
Ran 2 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.005s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.001s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.002s

OK
E
======================================================================
ERROR: test_set_cookies (ClassEval_25_0.CookiesUtilTestSetCookies.test_set_cookies)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_25_0.py", line 168, in test_set_cookies
    self.cookies_util.set_cookies(request)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'CookiesUtil' object has no attribute 'set_cookies'. Did you mean: 'get_cookies'?

----------------------------------------------------------------------
Ran 1 test in 0.002s

FAILED (errors=1)
.
----------------------------------------------------------------------
Ran 1 test in 0.001s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
F....
======================================================================
FAIL: test_fidelity_promo_1 (ClassEval_33_0.DiscountStrategyTestFidelityPromo.test_fidelity_promo_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_33_0.py", line 211, in test_fidelity_promo_1
    self.assertEqual(actual_discount, expected_discount)
AssertionError: 0.0 != 12.5

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=1)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.001s

OK
F
======================================================================
FAIL: test_DiscountStrategy (ClassEval_33_0.DiscountStrategyTest.test_DiscountStrategy)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_33_0.py", line 363, in test_DiscountStrategy
    self.assertEqual(actual_discount, expected_discount)
AssertionError: 0.0 != 12.5

----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (failures=1)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.001s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
..F.F
======================================================================
FAIL: test_is_full_with_one_more_email_3 (ClassEval_36_0.EmailClientTestIsFullWithOneMoreEmail.test_is_full_with_one_more_email_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_36_0.py", line 146, in test_is_full_with_one_more_email_3
    self.assertFalse(receiver.is_full_with_one_more_email(10))
AssertionError: True is not false

======================================================================
FAIL: test_is_full_with_one_more_email_5 (ClassEval_36_0.EmailClientTestIsFullWithOneMoreEmail.test_is_full_with_one_more_email_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_36_0.py", line 156, in test_is_full_with_one_more_email_5
    self.assertFalse(receiver.is_full_with_one_more_email(20))
AssertionError: True is not false

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=2)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.F...
======================================================================
FAIL: test_clear_inbox_2 (ClassEval_36_0.EmailClientTestClearInbox.test_clear_inbox_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_36_0.py", line 212, in test_clear_inbox_2
    self.assertEqual(receiver.inbox, [{'size': 10},{'size': 20},{'size': 15}])
AssertionError: Lists differ: [{'size': 15}] != [{'size': 10}, {'size': 20}, {'size': 15}]

First differing element 0:
{'size': 15}
{'size': 10}

Second list contains 2 additional elements.
First extra element 1:
{'size': 20}

- [{'size': 15}]
+ [{'size': 10}, {'size': 20}, {'size': 15}]

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=1)
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.000s

OK
...F..
======================================================================
FAIL: test_check_in_4 (ClassEval_42_0.HotelTestCheckIn.test_check_in_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_42_0.py", line 188, in test_check_in_4
    self.assertEqual(self.hotel.booked_rooms, {'double': {}, 'single': {'guest 1': 2}})
AssertionError: {'single': {'guest 1': 2}} != {'double': {}, 'single': {'guest 1': 2}}
- {'single': {'guest 1': 2}}
+ {'double': {}, 'single': {'guest 1': 2}}
?  ++++++++++++++


----------------------------------------------------------------------
Ran 6 tests in 0.001s

FAILED (failures=1)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
F
======================================================================
FAIL: test_main (ClassEval_42_0.HotelTestMain.test_main)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_42_0.py", line 270, in test_main
    self.assertEqual(self.hotel.booked_rooms, {'single': {}})
AssertionError: {} != {'single': {}}
- {}
+ {'single': {}}

----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (failures=1)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....F
======================================================================
FAIL: test_update_employee_6 (ClassEval_43_0.HRManagementSystemTestUpdateEmployee.test_update_employee_6)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_43_0.py", line 188, in test_update_employee_6
    self.assertEqual(hr_system.update_employee(1, {'Name': 'John', 'position': 'Manager', 'department': 'Sales', 'salary': 20000}), False)
AssertionError: True != False

----------------------------------------------------------------------
Ran 6 tests in 0.001s

FAILED (failures=1)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
..
----------------------------------------------------------------------
Ran 2 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
EEEEE
======================================================================
ERROR: test_matches_requirements (ClassEval_49_0.JobMarketplaceTestMatchesRequirements.test_matches_requirements)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_49_0.py", line 248, in test_matches_requirements
    self.assertEqual(jobMarketplace.matches_requirements({"name": "Tom", "skills": ['skill1', 'skill2'], "experience": "experience"}, ['skill1', 'skill2']), True)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'JobMarketplace' object has no attribute 'matches_requirements'

======================================================================
ERROR: test_matches_requirements_2 (ClassEval_49_0.JobMarketplaceTestMatchesRequirements.test_matches_requirements_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_49_0.py", line 252, in test_matches_requirements_2
    self.assertEqual(jobMarketplace.matches_requirements({"name": "Tom", "skills": ['skill1', 'skill2'], "experience": "experience"}, ['skill3', 'skill4']), False)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'JobMarketplace' object has no attribute 'matches_requirements'

======================================================================
ERROR: test_matches_requirements_3 (ClassEval_49_0.JobMarketplaceTestMatchesRequirements.test_matches_requirements_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_49_0.py", line 256, in test_matches_requirements_3
    self.assertEqual(jobMarketplace.matches_requirements({"name": "Tom", "skills": ['skill1', 'skill2'], "experience": "experience"}, ['skill5', 'skill6']), False)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'JobMarketplace' object has no attribute 'matches_requirements'

======================================================================
ERROR: test_matches_requirements_4 (ClassEval_49_0.JobMarketplaceTestMatchesRequirements.test_matches_requirements_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_49_0.py", line 260, in test_matches_requirements_4
    self.assertEqual(jobMarketplace.matches_requirements({"name": "Tom", "skills": ['skill1', 'skill2'], "experience": "experience"}, ['skill1', 'skill3']), False)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'JobMarketplace' object has no attribute 'matches_requirements'

======================================================================
ERROR: test_matches_requirements_5 (ClassEval_49_0.JobMarketplaceTestMatchesRequirements.test_matches_requirements_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_49_0.py", line 264, in test_matches_requirements_5
    self.assertEqual(jobMarketplace.matches_requirements({"name": "Tom", "skills": ['skill1', 'skill2'], "experience": "experience"}, ['skill1']), False)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'JobMarketplace' object has no attribute 'matches_requirements'

----------------------------------------------------------------------
Ran 5 tests in 0.005s

FAILED (errors=5)
E
======================================================================
ERROR: test_main (ClassEval_49_0.JobMarketplaceTestMain.test_main)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_49_0.py", line 281, in test_main
    self.assertEqual(jobMarketplace.matches_requirements({"name": "Tom", "skills": ['skill1', 'skill2'], "experience": "experience"}, ['skill1', 'skill2']), True)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'JobMarketplace' object has no attribute 'matches_requirements'

----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (errors=1)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.004s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.001s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.001s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.000s

OK
.F.F.
======================================================================
FAIL: test_play_2 (ClassEval_61_0.MusicPlayerTestPlay.test_play_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_61_0.py", line 159, in test_play_2
    self.assertEqual(musicPlayer.play(), None)
AssertionError: 'song2' != None

======================================================================
FAIL: test_play_4 (ClassEval_61_0.MusicPlayerTestPlay.test_play_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_61_0.py", line 170, in test_play_4
    self.assertEqual(musicPlayer.play(), "song1")
AssertionError: 'song3' != 'song1'
- song3
?     ^
+ song1
?     ^


----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=2)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
FFF..
======================================================================
FAIL: test_set_volume (ClassEval_61_0.MusicPlayerTestSetVolume.test_set_volume)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_61_0.py", line 269, in test_set_volume
    self.assertEqual(musicPlayer.set_volume(50), None)
AssertionError: True != None

======================================================================
FAIL: test_set_volume2 (ClassEval_61_0.MusicPlayerTestSetVolume.test_set_volume2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_61_0.py", line 274, in test_set_volume2
    self.assertEqual(musicPlayer.set_volume(100), None)
AssertionError: True != None

======================================================================
FAIL: test_set_volume3 (ClassEval_61_0.MusicPlayerTestSetVolume.test_set_volume3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_61_0.py", line 279, in test_set_volume3
    self.assertEqual(musicPlayer.set_volume(0), None)
AssertionError: True != None

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=3)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....F
======================================================================
FAIL: test_add_dish_6 (ClassEval_67_0.OrderTestAddDish.test_add_dish_6)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_67_0.py", line 176, in test_add_dish_6
    self.assertTrue(result)
AssertionError: False is not true

----------------------------------------------------------------------
Ran 6 tests in 0.001s

FAILED (failures=1)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
F.FFF
======================================================================
FAIL: test_checkout_1 (ClassEval_67_0.OrderTestCheckout.test_checkout_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_67_0.py", line 241, in test_checkout_1
    self.assertEqual([], self.order.selected_dishes)
AssertionError: Lists differ: [] != [{'dish': 'dish1', 'count': 2, 'price': 10[41 chars] 20}]

Second list contains 2 additional elements.
First extra element 0:
{'dish': 'dish1', 'count': 2, 'price': 10}

- []
+ [{'count': 2, 'dish': 'dish1', 'price': 10},
+  {'count': 2, 'dish': 'dish3', 'price': 20}]

======================================================================
FAIL: test_checkout_3 (ClassEval_67_0.OrderTestCheckout.test_checkout_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_67_0.py", line 263, in test_checkout_3
    self.assertEqual([], self.order.selected_dishes)
AssertionError: Lists differ: [] != [{'dish': 'dish1', 'count': 1, 'price': 10[41 chars] 20}]

Second list contains 2 additional elements.
First extra element 0:
{'dish': 'dish1', 'count': 1, 'price': 10}

- []
+ [{'count': 1, 'dish': 'dish1', 'price': 10},
+  {'count': 1, 'dish': 'dish3', 'price': 20}]

======================================================================
FAIL: test_checkout_4 (ClassEval_67_0.OrderTestCheckout.test_checkout_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_67_0.py", line 279, in test_checkout_4
    self.assertEqual([], self.order.selected_dishes)
AssertionError: Lists differ: [] != [{'dish': 'dish1', 'count': 3, 'price': 10[41 chars] 20}]

Second list contains 2 additional elements.
First extra element 0:
{'dish': 'dish1', 'count': 3, 'price': 10}

- []
+ [{'count': 3, 'dish': 'dish1', 'price': 10},
+  {'count': 3, 'dish': 'dish3', 'price': 20}]

======================================================================
FAIL: test_checkout_5 (ClassEval_67_0.OrderTestCheckout.test_checkout_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_67_0.py", line 295, in test_checkout_5
    self.assertEqual([], self.order.selected_dishes)
AssertionError: Lists differ: [] != [{'dish': 'dish1', 'count': 5, 'price': 10[41 chars] 20}]

Second list contains 2 additional elements.
First extra element 0:
{'dish': 'dish1', 'count': 5, 'price': 10}

- []
+ [{'count': 5, 'dish': 'dish1', 'price': 10},
+  {'count': 5, 'dish': 'dish3', 'price': 20}]

----------------------------------------------------------------------
Ran 5 tests in 0.003s

FAILED (failures=4)
F
======================================================================
FAIL: test_order (ClassEval_67_0.OrderTest.test_order)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_67_0.py", line 321, in test_order
    self.assertEqual([], self.order.selected_dishes)
AssertionError: Lists differ: [] != [{'dish': 'dish1', 'count': 2, 'price': 10[41 chars] 20}]

Second list contains 2 additional elements.
First extra element 0:
{'dish': 'dish1', 'count': 2, 'price': 10}

- []
+ [{'count': 2, 'dish': 'dish1', 'price': 10},
+  {'count': 2, 'dish': 'dish3', 'price': 20}]

----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (failures=1)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
....F
======================================================================
FAIL: test_get_page_info_5 (ClassEval_68_0.PageUtilTestGetPageInfo.test_get_page_info_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_68_0.py", line 175, in test_get_page_info_5
    self.assertEqual(actual_info, empty_info)
AssertionError: {'current_page': 5, 'per_page': 3, 'total_[77 chars]: []} != {}
+ {}
- {'current_page': 5,
-  'data': [],
-  'has_next': False,
-  'has_previous': True,
-  'per_page': 3,
-  'total_items': 10,
-  'total_pages': 4}

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=1)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
..EFF
======================================================================
ERROR: test_recv_3 (ClassEval_74_0.ServerTestRecv.test_recv_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_74_0.py", line 162, in test_recv_3
    flag = server.recv([88])
           ^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_74_0.py", line 54, in recv
    addr = info.get('addr')
           ^^^^^^^^
AttributeError: 'list' object has no attribute 'get'

======================================================================
FAIL: test_recv_4 (ClassEval_74_0.ServerTestRecv.test_recv_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_74_0.py", line 170, in test_recv_4
    self.assertEqual(flag, -1)
AssertionError: False != -1

======================================================================
FAIL: test_recv_5 (ClassEval_74_0.ServerTestRecv.test_recv_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_74_0.py", line 176, in test_recv_5
    self.assertEqual(flag, -1)
AssertionError: False != -1

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=2, errors=1)
.FFF.
======================================================================
FAIL: test_send_2 (ClassEval_74_0.ServerTestSend.test_send_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_74_0.py", line 188, in test_send_2
    self.assertEqual(flag, "info structure is not correct")
AssertionError: None != 'info structure is not correct'

======================================================================
FAIL: test_send_3 (ClassEval_74_0.ServerTestSend.test_send_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_74_0.py", line 193, in test_send_3
    self.assertEqual(flag, "info structure is not correct")
AssertionError: None != 'info structure is not correct'

======================================================================
FAIL: test_send_4 (ClassEval_74_0.ServerTestSend.test_send_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_74_0.py", line 198, in test_send_4
    self.assertEqual(flag, "info structure is not correct")
AssertionError: None != 'info structure is not correct'

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=3)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.000s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.E...
======================================================================
ERROR: test_set_mode_2 (ClassEval_85_0.ThermostatTestSetMode.test_set_mode_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_85_0.py", line 196, in test_set_mode_2
    self.assertFalse(t.set_mode('test'))
                     ^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_85_0.py", line 58, in set_mode
    raise ValueError("Invalid mode. Mode must be 'heat' or 'cool'.")
ValueError: Invalid mode. Mode must be 'heat' or 'cool'.

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (errors=1)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
F
======================================================================
FAIL: test_main (ClassEval_85_0.ThermostatTestMain.test_main)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_85_0.py", line 299, in test_main
    self.assertEqual(t.get_target_temperature(), 37.5)
AssertionError: 37 != 37.5

----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (failures=1)
.F.FF
======================================================================
FAIL: test_add_item_2 (ClassEval_94_0.VendingMachineTestAddItem.test_add_item_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_94_0.py", line 88, in test_add_item_2
    self.assertEqual(vendingMachine.inventory, {'Coke': {'price': 1.25, 'quantity': 20}})
AssertionError: {'Coke': {'price': 1.25, 'quantity': 10}} != {'Coke': {'price': 1.25, 'quantity': 20}}
- {'Coke': {'price': 1.25, 'quantity': 10}}
?                                      ^

+ {'Coke': {'price': 1.25, 'quantity': 20}}
?                                      ^


======================================================================
FAIL: test_add_item_4 (ClassEval_94_0.VendingMachineTestAddItem.test_add_item_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_94_0.py", line 101, in test_add_item_4
    self.assertEqual(vendingMachine.inventory, {'Coke': {'price': 1.25, 'quantity': 10}, 'Pizza': {'price': 1.25, 'quantity': 20}})
AssertionError: {'Cok[15 chars].25, 'quantity': 10}, 'Pizza': {'price': 1.25, 'quantity': 10}} != {'Cok[15 chars].25, 'quantity': 10}, 'Pizza': {'price': 1.25, 'quantity': 20}}
  {'Coke': {'price': 1.25, 'quantity': 10},
-  'Pizza': {'price': 1.25, 'quantity': 10}}
?                                       ^

+  'Pizza': {'price': 1.25, 'quantity': 20}}
?                                       ^


======================================================================
FAIL: test_add_item_5 (ClassEval_94_0.VendingMachineTestAddItem.test_add_item_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_94_0.py", line 109, in test_add_item_5
    self.assertEqual(vendingMachine.inventory, {'Coke': {'price': 1.25, 'quantity': 20}, 'Pizza': {'price': 1.25, 'quantity': 20}})
AssertionError: {'Cok[15 chars].25, 'quantity': 10}, 'Pizza': {'price': 1.25, 'quantity': 10}} != {'Cok[15 chars].25, 'quantity': 20}, 'Pizza': {'price': 1.25, 'quantity': 20}}
- {'Coke': {'price': 1.25, 'quantity': 10},
?                                      ^

+ {'Coke': {'price': 1.25, 'quantity': 20},
?                                      ^

-  'Pizza': {'price': 1.25, 'quantity': 10}}
?                                       ^

+  'Pizza': {'price': 1.25, 'quantity': 20}}
?                                       ^


----------------------------------------------------------------------
Ran 5 tests in 0.003s

FAILED (failures=3)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.001s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
..F.F
======================================================================
FAIL: test_display_items_3 (ClassEval_94_0.VendingMachineTestDisplayItems.test_display_items_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_94_0.py", line 222, in test_display_items_3
    self.assertEqual(vendingMachine.display_items(),"Coke - $1.25 [10]\nPizza - $1.25 [10]")
AssertionError: 'Coke - $1.25 [10], Pizza - $1.25 [10]' != 'Coke - $1.25 [10]\nPizza - $1.25 [10]'
- Coke - $1.25 [10], Pizza - $1.25 [10]
+ Coke - $1.25 [10]
+ Pizza - $1.25 [10]


======================================================================
FAIL: test_display_items_5 (ClassEval_94_0.VendingMachineTestDisplayItems.test_display_items_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_94_0.py", line 232, in test_display_items_5
    self.assertEqual(vendingMachine.display_items(), 'Coke - $1.25 [0]\nPizza - $1.25 [10]')
AssertionError: 'Coke - $1.25 [0], Pizza - $1.25 [10]' != 'Coke - $1.25 [0]\nPizza - $1.25 [10]'
- Coke - $1.25 [0], Pizza - $1.25 [10]
+ Coke - $1.25 [0]
+ Pizza - $1.25 [10]


----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=2)
..
----------------------------------------------------------------------
Ran 2 tests in 0.000s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.F....
======================================================================
FAIL: test_query_2 (ClassEval_96_0.WeatherSystemTestQuery.test_query_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_96_0.py", line 102, in test_query_2
    self.assertEqual(weatherSystem.query(weather_list), False)
AssertionError: None != False

----------------------------------------------------------------------
Ran 6 tests in 0.001s

FAILED (failures=1)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.002s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.001s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
