.....
----------------------------------------------------------------------
Ran 5 tests in 0.002s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.003s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.005s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.002s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.044s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.012s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.007s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.006s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.008s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.002s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.002s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.003s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.004s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.002s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.006s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.006s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.004s

OK
EEEEE
======================================================================
ERROR: test_process_file_1 (ClassEval_84_0.TextFileProcessorTestProcessFile.test_process_file_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_84_0.py", line 205, in test_process_file_1
    result = textFileProcessor.process_file()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_84_0.py", line 50, in process_file
    with open(self.file_path, 'r') as file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'test.txt'

======================================================================
ERROR: test_process_file_2 (ClassEval_84_0.TextFileProcessorTestProcessFile.test_process_file_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_84_0.py", line 219, in test_process_file_2
    result = textFileProcessor.process_file()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_84_0.py", line 50, in process_file
    with open(self.file_path, 'r') as file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'test.txt'

======================================================================
ERROR: test_process_file_3 (ClassEval_84_0.TextFileProcessorTestProcessFile.test_process_file_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_84_0.py", line 233, in test_process_file_3
    result = textFileProcessor.process_file()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_84_0.py", line 50, in process_file
    with open(self.file_path, 'r') as file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'test.txt'

======================================================================
ERROR: test_process_file_4 (ClassEval_84_0.TextFileProcessorTestProcessFile.test_process_file_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_84_0.py", line 247, in test_process_file_4
    result = textFileProcessor.process_file()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_84_0.py", line 50, in process_file
    with open(self.file_path, 'r') as file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'test.txt'

======================================================================
ERROR: test_process_file_5 (ClassEval_84_0.TextFileProcessorTestProcessFile.test_process_file_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_84_0.py", line 261, in test_process_file_5
    result = textFileProcessor.process_file()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_84_0.py", line 50, in process_file
    with open(self.file_path, 'r') as file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'test.txt'

----------------------------------------------------------------------
Ran 5 tests in 0.005s

FAILED (errors=5)
.
----------------------------------------------------------------------
Ran 1 test in 0.001s

OK
.....E
======================================================================
ERROR: test_read_xml_6 (ClassEval_98_0.XMLProcessorTestReadXml.test_read_xml_6)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_98_0.py", line 153, in test_read_xml_6
    root = self.processor.read_xml()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_98_0.py", line 23, in read_xml
    tree = ET.parse(self.file_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/lib/python3.12/xml/etree/ElementTree.py", line 1204, in parse
    tree.parse(source, parser)
  File "/opt/miniconda3/lib/python3.12/xml/etree/ElementTree.py", line 558, in parse
    source = open(source, "rb")
             ^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: ''

----------------------------------------------------------------------
Ran 6 tests in 0.006s

FAILED (errors=1)
......
----------------------------------------------------------------------
Ran 6 tests in 0.007s

OK
E.....
----------------------------------------------------------------------
Ran 5 tests in 1.006s

OK
EEEE
======================================================================
ERROR: test_XMLProcessor (ClassEval_98_0.XMLProcessorTest.test_XMLProcessor)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_98_0.py", line 531, in test_XMLProcessor
    result = self.processor.process_xml_data(file_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_98_0.py", line 50, in process_xml_data
    new_elem = ET.Element("new_child")
               ^^^^^^^^^^^^^^^^^^^^^^^
func_timeout.dafunc.FunctionTimedOut926425144584947376: Function run_unit_test (args=(<test_pipeline.AutoTest object at 0x11afd6030>, 'ClassEval_98_0', 'XMLProcessorTest', 'GPT-4_greedy_File_Handling')) (kwargs={}) timed out after 5.000000 seconds.


----------------------------------------------------------------------
Ran 1 test in 5.028s

FAILED (errors=1)
..E
.======================================================================
ERROR: test_process_xml_data_1 (ClassEval_98_0.XMLProcessorTestProcessXmlData.test_process_xml_data_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_98_0.py", line 297, in test_process_xml_data_1
    result = self.processor.process_xml_data(file_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_98_0.py", line 52, in process_xml_data
    elem.append(new_elem)
func_timeout.dafunc.FunctionTimedOut-7950483019982622066: Function run_unit_test (args=(<test_pipeline.AutoTest object at 0x11afd6030>, 'ClassEval_98_0', 'XMLProcessorTestProcessXmlData', 'GPT-4_greedy_File_Handling')) (kwargs={}) timed out after 5.000000 seconds.


======================================================================
ERROR: test_process_xml_data_2 (ClassEval_98_0.XMLProcessorTestProcessXmlData.test_process_xml_data_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_98_0.py", line 322, in test_process_xml_data_2
    result = self.processor.process_xml_data(file_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_98_0.py", line 50, in process_xml_data
    new_elem = ET.Element("new_child")
               ^^^^^^^^^^^^^^^^^^^^^^^
func_timeout.dafunc.FunctionTimedOut-7950483019982622066: Function run_unit_test (args=(<test_pipeline.AutoTest object at 0x11afd6030>, 'ClassEval_98_0', 'XMLProcessorTestProcessXmlData', 'GPT-4_greedy_File_Handling')) (kwargs={}) timed out after 5.000000 seconds.


======================================================================
ERROR: test_process_xml_data_3 (ClassEval_98_0.XMLProcessorTestProcessXmlData.test_process_xml_data_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_98_0.py", line 346, in test_process_xml_data_3
    result = self.processor.process_xml_data(file_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_98_0.py", line 50, in process_xml_data
    new_elem = ET.Element("new_child")
               ^^^^^^^^^^^^^^^^^^^^^^^
func_timeout.dafunc.FunctionTimedOut-7950483019982622066: Function run_unit_test (args=(<test_pipeline.AutoTest object at 0x11afd6030>, 'ClassEval_98_0', 'XMLProcessorTestProcessXmlData', 'GPT-4_greedy_File_Handling')) (kwargs={}) timed out after 5.000000 seconds.


======================================================================
ERROR: test_process_xml_data_4 (ClassEval_98_0.XMLProcessorTestProcessXmlData.test_process_xml_data_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_98_0.py", line 369, in test_process_xml_data_4
    result = self.processor.process_xml_data(file_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_98_0.py", line 50, in process_xml_data
    new_elem = ET.Element("new_child")
               ^^^^^^^^^^^^^^^^^^^^^^^
func_timeout.dafunc.FunctionTimedOut-7950483019982622066: Function run_unit_test (args=(<test_pipeline.AutoTest object at 0x11afd6030>, 'ClassEval_98_0', 'XMLProcessorTestProcessXmlData', 'GPT-4_greedy_File_Handling')) (kwargs={}) timed out after 5.000000 seconds.


======================================================================
ERROR: test_process_xml_data_5 (ClassEval_98_0.XMLProcessorTestProcessXmlData.test_process_xml_data_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_98_0.py", line 393, in test_process_xml_data_5
    result = self.processor.process_xml_data(file_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_98_0.py", line 50, in process_xml_data
    new_elem = ET.Element("new_child")
               ^^^^^^^^^^^^^^^^^^^^^^^
func_timeout.dafunc.FunctionTimedOut-7950483019982622066: Function run_unit_test (args=(<test_pipeline.AutoTest object at 0x11afd6030>, 'ClassEval_98_0', 'XMLProcessorTestProcessXmlData', 'GPT-4_greedy_File_Handling')) (kwargs={}) timed out after 5.000000 seconds.


----------------------------------------------------------------------
Ran 5 tests in 13.290s

FAILED (errors=5)
...
----------------------------------------------------------------------
Ran 6 tests in 1.520s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.010s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.008s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.008s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.003s

OK
