FF...
======================================================================
FAIL: test_parse_arguments_1 (ClassEval_2_0.ArgumentParserTestParseArguments.test_parse_arguments_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_2_0.py", line 66, in test_parse_arguments_1
    self.assertEqual(self.parser.get_argument("name"), "John")
AssertionError: None != 'John'

======================================================================
FAIL: test_parse_arguments_2 (ClassEval_2_0.ArgumentParserTestParseArguments.test_parse_arguments_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_2_0.py", line 79, in test_parse_arguments_2
    self.assertEqual(self.parser.get_argument("verbose"), True)
AssertionError: None != True

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=2)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.E..F
======================================================================
ERROR: test_convert_type_2 (ClassEval_2_0.ArgumentParserTestConvertType.test_convert_type_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_2_0.py", line 210, in test_convert_type_2
    result = self.parser._convert_type("age", "twenty-five")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_2_0.py", line 43, in _convert_type
    return int(value)
           ^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'twenty-five'

======================================================================
FAIL: test_convert_type_5 (ClassEval_2_0.ArgumentParserTestConvertType.test_convert_type_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_2_0.py", line 226, in test_convert_type_5
    self.assertEqual(result, True)
AssertionError: False != True

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=1, errors=1)
E
======================================================================
ERROR: test_main (ClassEval_2_0.ArgumentParserTestMain.test_main)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_2_0.py", line 241, in test_main
    parser.parse_arguments(command)
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_2_0.py", line 14, in parse_arguments
    key, value = args[i][2:].split('=')
    ^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 1)

----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (errors=1)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.......
----------------------------------------------------------------------
Ran 7 tests in 0.000s

OK
...
----------------------------------------------------------------------
Ran 3 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
FFFFF
======================================================================
FAIL: test_convert_to_utf8 (ClassEval_10_0.BinaryDataProcessorTestConvertToUtf8.test_convert_to_utf8)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_10_0.py", line 112, in test_convert_to_utf8
    self.assertEqual(bdp.convert_to_utf8(), "hello")
AssertionError: '0110100001100101011011000110110001101111' != 'hello'
- 0110100001100101011011000110110001101111
+ hello


======================================================================
FAIL: test_convert_to_utf8_2 (ClassEval_10_0.BinaryDataProcessorTestConvertToUtf8.test_convert_to_utf8_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_10_0.py", line 116, in test_convert_to_utf8_2
    self.assertEqual(bdp.convert_to_utf8(), "helli")
AssertionError: '0110100001100101011011000110110001101001' != 'helli'
- 0110100001100101011011000110110001101001
+ helli


======================================================================
FAIL: test_convert_to_utf8_3 (ClassEval_10_0.BinaryDataProcessorTestConvertToUtf8.test_convert_to_utf8_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_10_0.py", line 120, in test_convert_to_utf8_3
    self.assertEqual(bdp.convert_to_utf8(), "`ello")
AssertionError: '0110000001100101011011000110110001101111' != '`ello'
- 0110000001100101011011000110110001101111
+ `ello


======================================================================
FAIL: test_convert_to_utf8_4 (ClassEval_10_0.BinaryDataProcessorTestConvertToUtf8.test_convert_to_utf8_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_10_0.py", line 124, in test_convert_to_utf8_4
    self.assertEqual(bdp.convert_to_utf8(), "kello")
AssertionError: '0110101101100101011011000110110001101111' != 'kello'
- 0110101101100101011011000110110001101111
+ kello


======================================================================
FAIL: test_convert_to_utf8_5 (ClassEval_10_0.BinaryDataProcessorTestConvertToUtf8.test_convert_to_utf8_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_10_0.py", line 128, in test_convert_to_utf8_5
    self.assertEqual(bdp.convert_to_utf8(), "kdllo")
AssertionError: '0110101101100100011011000110110001101111' != 'kdllo'
- 0110101101100100011011000110110001101111
+ kdllo


----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=5)
F
======================================================================
FAIL: test_main (ClassEval_10_0.BinaryDataProcessorTestMain.test_main)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_10_0.py", line 136, in test_main
    self.assertEqual(bdp.convert_to_utf8(), "hello")
AssertionError: '0110100001100101011011000110110001101111' != 'hello'
- 0110100001100101011011000110110001101111
+ hello


----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (failures=1)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.001s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.001s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.001s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
F.EF.
======================================================================
ERROR: test_bad_character_heuristic_3 (ClassEval_15_0.BoyerMooreSearchTestBadCharacterHeuristic.test_bad_character_heuristic_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_15_0.py", line 97, in test_bad_character_heuristic_3
    self.assertEqual(boyerMooreSearch.bad_character_heuristic(), [0, 1, 2, 3, 4, 5, 6])
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_15_0.py", line 31, in bad_character_heuristic
    while shift <= self.textLen - self.patLen:
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
func_timeout.dafunc.FunctionTimedOut4384177377754048365: Function run_unit_test (args=(<test_pipeline.AutoTest object at 0x10d054c80>, 'ClassEval_15_0', 'BoyerMooreSearchTestBadCharacterHeuristic', 'GPT-4_greedy_Data_Formatting')) (kwargs={}) timed out after 5.000000 seconds.


======================================================================
FAIL: test_bad_character_heuristic (ClassEval_15_0.BoyerMooreSearchTestBadCharacterHeuristic.test_bad_character_heuristic)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_15_0.py", line 89, in test_bad_character_heuristic
    self.assertEqual(boyerMooreSearch.bad_character_heuristic(), [0, 3])
AssertionError: Lists differ: [0] != [0, 3]

Second list contains 1 additional elements.
First extra element 1:
3

- [0]
+ [0, 3]

======================================================================
FAIL: test_bad_character_heuristic_4 (ClassEval_15_0.BoyerMooreSearchTestBadCharacterHeuristic.test_bad_character_heuristic_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_15_0.py", line 101, in test_bad_character_heuristic_4
    self.assertEqual(boyerMooreSearch.bad_character_heuristic(), [0, 4])
AssertionError: Lists differ: [0] != [0, 4]

Second list contains 1 additional elements.
First extra element 1:
4

- [0]
+ [0, 4]

----------------------------------------------------------------------
Ran 5 tests in 5.140s

FAILED (failures=2, errors=1)
F
======================================================================
FAIL: test_main (ClassEval_15_0.BoyerMooreSearchTestMain.test_main)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_15_0.py", line 112, in test_main
    self.assertEqual(boyerMooreSearch.bad_character_heuristic(), [0, 3])
AssertionError: Lists differ: [0] != [0, 3]

Second list contains 1 additional elements.
First extra element 1:
3

- [0]
+ [0, 3]

----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (failures=1)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.001s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.001s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....E
======================================================================
ERROR: test_convert_key_6 (ClassEval_18_0.CamelCaseMapTestConvertKey.test_convert_key_6)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_18_0.py", line 274, in test_convert_key_6
    self.assertEqual(camelize_map._convert_key(1234), 1234)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_18_0.py", line 57, in _convert_key
    return self._to_camel_case(key)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_18_0.py", line 66, in _to_camel_case
    words = key.split('_')
            ^^^^^^^^^
AttributeError: 'int' object has no attribute 'split'

----------------------------------------------------------------------
Ran 6 tests in 0.002s

FAILED (errors=1)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....E
======================================================================
ERROR: test_convert_6 (ClassEval_27_0.CurrencyConverterTestConvert.test_convert_6)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_27_0.py", line 94, in test_convert_6
    res = cc.convert(64, '???', 'USD')
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_27_0.py", line 30, in convert
    return (amount / self.rates[from_currency]) * self.rates[to_currency]
                     ~~~~~~~~~~^^^^^^^^^^^^^^^
KeyError: '???'

----------------------------------------------------------------------
Ran 6 tests in 0.001s

FAILED (errors=1)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.000s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.001s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.......
----------------------------------------------------------------------
Ran 7 tests in 0.001s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.001s

OK
FFFFF
======================================================================
FAIL: test_rail_fence_decipher (ClassEval_32_0.DecryptionUtilsTestRailFenceDecipher.test_rail_fence_decipher)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_32_0.py", line 134, in test_rail_fence_decipher
    self.assertEqual(d.rail_fence_decipher('Hoo!el,Wrdl l', 3), 'Hello, World!')
AssertionError: 'Herlo!lWd o,l' != 'Hello, World!'
- Herlo!lWd o,l
+ Hello, World!


======================================================================
FAIL: test_rail_fence_decipher_2 (ClassEval_32_0.DecryptionUtilsTestRailFenceDecipher.test_rail_fence_decipher_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_32_0.py", line 138, in test_rail_fence_decipher_2
    self.assertEqual(d.rail_fence_decipher('Hoo!el,Wrdl l', 4), 'H!W reoldll,o')
AssertionError: 'H,lolW oerl!d' != 'H!W reoldll,o'
- H,lolW oerl!d
+ H!W reoldll,o


======================================================================
FAIL: test_rail_fence_decipher_3 (ClassEval_32_0.DecryptionUtilsTestRailFenceDecipher.test_rail_fence_decipher_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_32_0.py", line 142, in test_rail_fence_decipher_3
    self.assertEqual(d.rail_fence_decipher('Hoo!el,Wrdl l', 5), 'Holr d,!oeWll')
AssertionError: 'HroWdo,l!l el' != 'Holr d,!oeWll'
- HroWdo,l!l el
+ Holr d,!oeWll


======================================================================
FAIL: test_rail_fence_decipher_4 (ClassEval_32_0.DecryptionUtilsTestRailFenceDecipher.test_rail_fence_decipher_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_32_0.py", line 146, in test_rail_fence_decipher_4
    self.assertEqual(d.rail_fence_decipher('Hoo!el,Wrdl l', 6), 'Holrll d,!oeW')
AssertionError: 'Hlod orl!We,l' != 'Holrll d,!oeW'
- Hlod orl!We,l
+ Holrll d,!oeW


======================================================================
FAIL: test_rail_fence_decipher_5 (ClassEval_32_0.DecryptionUtilsTestRailFenceDecipher.test_rail_fence_decipher_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_32_0.py", line 150, in test_rail_fence_decipher_5
    self.assertEqual(d.rail_fence_decipher('Hoo!el,Wrdl l', 7), 'Hoe,rll dWl!o')
AssertionError: 'Hlo ol!derlW,' != 'Hoe,rll dWl!o'
- Hlo ol!derlW,
+ Hoe,rll dWl!o


----------------------------------------------------------------------
Ran 5 tests in 0.003s

FAILED (failures=5)
F
======================================================================
FAIL: test_main (ClassEval_32_0.DecryptionUtilsTestMain.test_main)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_32_0.py", line 158, in test_main
    self.assertEqual(d.rail_fence_decipher('Hoo!el,Wrdl l', 3), 'Hello, World!')
AssertionError: 'Herlo!lWd o,l' != 'Hello, World!'
- Herlo!lWd o,l
+ Hello, World!


----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (failures=1)
......
----------------------------------------------------------------------
Ran 6 tests in 0.001s

OK
FFFF.
======================================================================
FAIL: test_vigenere_cipher (ClassEval_37_0.EncryptionUtilsTestVigenereCipher.test_vigenere_cipher)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_37_0.py", line 101, in test_vigenere_cipher
    self.assertEqual(encryption_utils.vigenere_cipher("abc"), "kfa")
AssertionError: 'WRM' != 'kfa'
- WRM
+ kfa


======================================================================
FAIL: test_vigenere_cipher_2 (ClassEval_37_0.EncryptionUtilsTestVigenereCipher.test_vigenere_cipher_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_37_0.py", line 105, in test_vigenere_cipher_2
    self.assertEqual(encryption_utils.vigenere_cipher("hello"), "rijvs")
AssertionError: 'DUVHE' != 'rijvs'
- DUVHE
+ rijvs


======================================================================
FAIL: test_vigenere_cipher_3 (ClassEval_37_0.EncryptionUtilsTestVigenereCipher.test_vigenere_cipher_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_37_0.py", line 109, in test_vigenere_cipher_3
    self.assertEqual(encryption_utils.vigenere_cipher("AbCdEfG"), "LpPjOjE")
AssertionError: 'RBVVUVK' != 'LpPjOjE'
- RBVVUVK
+ LpPjOjE


======================================================================
FAIL: test_vigenere_cipher_4 (ClassEval_37_0.EncryptionUtilsTestVigenereCipher.test_vigenere_cipher_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_37_0.py", line 113, in test_vigenere_cipher_4
    self.assertEqual(encryption_utils.vigenere_cipher("Hello, World! 123"), "Rijvs, Uyvjn! 123")
AssertionError: 'XUVHEJJGYNBNKDOBW' != 'Rijvs, Uyvjn! 123'
- XUVHEJJGYNBNKDOBW
+ Rijvs, Uyvjn! 123


----------------------------------------------------------------------
Ran 5 tests in 0.002s

FAILED (failures=4)
......
----------------------------------------------------------------------
Ran 6 tests in 0.001s

OK
F
======================================================================
FAIL: test_main (ClassEval_37_0.EncryptionUtilsTestMain.test_main)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_37_0.py", line 150, in test_main
    self.assertEqual(encryption_utils.vigenere_cipher("abc"), "kfa")
AssertionError: 'WRM' != 'kfa'
- WRM
+ kfa


----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (failures=1)
EEEEEFE
======================================================================
ERROR: test_interpolate_1d (ClassEval_46_0.InterpolationTestInterpolate1d.test_interpolate_1d)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_46_0.py", line 46, in test_interpolate_1d
    self.assertEqual(interpolation.interpolate_1d([1, 2, 3], [1, 2, 3], [1.5, 2.5]), [1.5, 2.5])
  File "/opt/miniconda3/lib/python3.12/unittest/case.py", line 885, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/opt/miniconda3/lib/python3.12/unittest/case.py", line 875, in _baseAssertEqual
    if not first == second:
           ^^^^^^^^^^^^^^^
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

======================================================================
ERROR: test_interpolate_1d_2 (ClassEval_46_0.InterpolationTestInterpolate1d.test_interpolate_1d_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_46_0.py", line 50, in test_interpolate_1d_2
    self.assertEqual(interpolation.interpolate_1d([1, 6, 4], [1, 2, 5], [1.5, 2.5]), [1.1, 1.3])
  File "/opt/miniconda3/lib/python3.12/unittest/case.py", line 885, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/opt/miniconda3/lib/python3.12/unittest/case.py", line 875, in _baseAssertEqual
    if not first == second:
           ^^^^^^^^^^^^^^^
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

======================================================================
ERROR: test_interpolate_1d_3 (ClassEval_46_0.InterpolationTestInterpolate1d.test_interpolate_1d_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_46_0.py", line 54, in test_interpolate_1d_3
    self.assertEqual(interpolation.interpolate_1d([1, 6, 4], [1, 7, 5], [1.5, 2.5]), [1.6, 2.8])
  File "/opt/miniconda3/lib/python3.12/unittest/case.py", line 885, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/opt/miniconda3/lib/python3.12/unittest/case.py", line 875, in _baseAssertEqual
    if not first == second:
           ^^^^^^^^^^^^^^^
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

======================================================================
ERROR: test_interpolate_1d_4 (ClassEval_46_0.InterpolationTestInterpolate1d.test_interpolate_1d_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_46_0.py", line 58, in test_interpolate_1d_4
    self.assertEqual(interpolation.interpolate_1d([1, 6, 4], [1, 2, 5], [2, 3]), [1.2, 1.4])
  File "/opt/miniconda3/lib/python3.12/unittest/case.py", line 885, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/opt/miniconda3/lib/python3.12/unittest/case.py", line 875, in _baseAssertEqual
    if not first == second:
           ^^^^^^^^^^^^^^^
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

======================================================================
ERROR: test_interpolate_1d_5 (ClassEval_46_0.InterpolationTestInterpolate1d.test_interpolate_1d_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_46_0.py", line 62, in test_interpolate_1d_5
    self.assertEqual(interpolation.interpolate_1d([1, 6, 4], [1, 7, 5], [2, 3]), [2.2, 3.4])
  File "/opt/miniconda3/lib/python3.12/unittest/case.py", line 885, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/opt/miniconda3/lib/python3.12/unittest/case.py", line 875, in _baseAssertEqual
    if not first == second:
           ^^^^^^^^^^^^^^^
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

======================================================================
ERROR: test_interpolate_1d_7 (ClassEval_46_0.InterpolationTestInterpolate1d.test_interpolate_1d_7)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_46_0.py", line 70, in test_interpolate_1d_7
    self.assertEqual(interpolation.interpolate_1d([], [], [[], []]), [])
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_46_0.py", line 23, in interpolate_1d
    f = interp1d(x, y)
        ^^^^^^^^^^^^^^
  File "/opt/miniconda3/lib/python3.12/site-packages/scipy/interpolate/_interpolate.py", line 543, in __init__
    self._y = self._reshape_yi(self.y)
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/lib/python3.12/site-packages/scipy/interpolate/_polyint.py", line 113, in _reshape_yi
    return yi.reshape((yi.shape[0], -1))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: cannot reshape array of size 0 into shape (0,newaxis)

======================================================================
FAIL: test_interpolate_1d_6 (ClassEval_46_0.InterpolationTestInterpolate1d.test_interpolate_1d_6)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_46_0.py", line 66, in test_interpolate_1d_6
    self.assertEqual(interpolation.interpolate_1d([1, 6, 4], [1, 7, 5], []), [])
AssertionError: array([], dtype=float64) != []

----------------------------------------------------------------------
Ran 7 tests in 0.008s

FAILED (failures=1, errors=6)
EEEEE
======================================================================
ERROR: test_interpolate_2d (ClassEval_46_0.InterpolationTestInterpolate2d.test_interpolate_2d)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_46_0.py", line 76, in test_interpolate_2d
    self.assertEqual(
  File "/opt/miniconda3/lib/python3.12/unittest/case.py", line 885, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/opt/miniconda3/lib/python3.12/unittest/case.py", line 875, in _baseAssertEqual
    if not first == second:
           ^^^^^^^^^^^^^^^
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

======================================================================
ERROR: test_interpolate_2d_2 (ClassEval_46_0.InterpolationTestInterpolate2d.test_interpolate_2d_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_46_0.py", line 82, in test_interpolate_2d_2
    self.assertEqual(
  File "/opt/miniconda3/lib/python3.12/unittest/case.py", line 885, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/opt/miniconda3/lib/python3.12/unittest/case.py", line 875, in _baseAssertEqual
    if not first == second:
           ^^^^^^^^^^^^^^^
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

======================================================================
ERROR: test_interpolate_2d_3 (ClassEval_46_0.InterpolationTestInterpolate2d.test_interpolate_2d_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_46_0.py", line 88, in test_interpolate_2d_3
    self.assertEqual(
  File "/opt/miniconda3/lib/python3.12/unittest/case.py", line 885, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/opt/miniconda3/lib/python3.12/unittest/case.py", line 875, in _baseAssertEqual
    if not first == second:
           ^^^^^^^^^^^^^^^
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

======================================================================
ERROR: test_interpolate_2d_4 (ClassEval_46_0.InterpolationTestInterpolate2d.test_interpolate_2d_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_46_0.py", line 94, in test_interpolate_2d_4
    self.assertEqual(
  File "/opt/miniconda3/lib/python3.12/unittest/case.py", line 885, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/opt/miniconda3/lib/python3.12/unittest/case.py", line 875, in _baseAssertEqual
    if not first == second:
           ^^^^^^^^^^^^^^^
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

======================================================================
ERROR: test_interpolate_2d_5 (ClassEval_46_0.InterpolationTestInterpolate2d.test_interpolate_2d_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_46_0.py", line 100, in test_interpolate_2d_5
    self.assertEqual(
  File "/opt/miniconda3/lib/python3.12/unittest/case.py", line 885, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/opt/miniconda3/lib/python3.12/unittest/case.py", line 875, in _baseAssertEqual
    if not first == second:
           ^^^^^^^^^^^^^^^
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

----------------------------------------------------------------------
Ran 5 tests in 0.003s

FAILED (errors=5)
E
======================================================================
ERROR: test_main (ClassEval_46_0.InterpolationTestMain.test_main)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_46_0.py", line 108, in test_main
    self.assertEqual(interpolation.interpolate_1d([1, 2, 3], [1, 2, 3], [1.5, 2.5]), [1.5, 2.5])
  File "/opt/miniconda3/lib/python3.12/unittest/case.py", line 885, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/opt/miniconda3/lib/python3.12/unittest/case.py", line 875, in _baseAssertEqual
    if not first == second:
           ^^^^^^^^^^^^^^^
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (errors=1)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
..FF.
======================================================================
FAIL: test_palindromic_length_3 (ClassEval_55_0.ManacherTestPalindromicLength.test_palindromic_length_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_55_0.py", line 59, in test_palindromic_length_3
    self.assertEqual(manacher.palindromic_length(2, 3, 'a|b|a|b|a|x'), 0)
AssertionError: 2 != 0

======================================================================
FAIL: test_palindromic_length_4 (ClassEval_55_0.ManacherTestPalindromicLength.test_palindromic_length_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_55_0.py", line 63, in test_palindromic_length_4
    self.assertEqual(manacher.palindromic_length(9, 2, 'a|b|a|b|a|x'), 0)
AssertionError: 1 != 0

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=2)
....F
======================================================================
FAIL: test_palindromic_string_5 (ClassEval_55_0.ManacherTestPalindromicString.test_palindromic_string_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_55_0.py", line 89, in test_palindromic_string_5
    self.assertEqual(manacher.palindromic_string(), 'aba')
AssertionError: 'bab' != 'aba'
- bab
?   -
+ aba
? +


----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=1)
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
FFFFFE
======================================================================
ERROR: test_format_6 (ClassEval_65_0.NumberWordFormatterTestFormat.test_format_6)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_65_0.py", line 72, in test_format_6
    self.assertEqual(formatter.format(None), "")
                     ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_65_0.py", line 20, in format
    return self.format_string(str(x))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_65_0.py", line 28, in format_string
    return ' '.join(self.trans_three(x[i:i+3]) + ' ' + self.parse_more(i//3) for i in range(0, 12, 3) if self.trans_three(x[i:i+3])) + ' ONLY'
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_65_0.py", line 28, in <genexpr>
    return ' '.join(self.trans_three(x[i:i+3]) + ' ' + self.parse_more(i//3) for i in range(0, 12, 3) if self.trans_three(x[i:i+3])) + ' ONLY'
                                                                                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_65_0.py", line 40, in trans_three
    return self.trans_two(s[1:])
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_65_0.py", line 34, in trans_two
    return self.NUMBER_TEN[int(s[0])] + ' ' + self.NUMBER[int(s[1])]
                                                          ^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'N'

======================================================================
FAIL: test_format_1 (ClassEval_65_0.NumberWordFormatterTestFormat.test_format_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_65_0.py", line 51, in test_format_1
    self.assertEqual(formatter.format(123456),
AssertionError: '     THOUSAND ONE HUNDRED TWENTY THREE MI[37 chars]ONLY' != 'ONE HUNDRED AND TWENTY THREE THOUSAND FOU[24 chars]ONLY'
-      THOUSAND ONE HUNDRED TWENTY THREE MILLION FOUR HUNDRED FIFTY SIX BILLION ONLY
+ ONE HUNDRED AND TWENTY THREE THOUSAND FOUR HUNDRED AND FIFTY SIX ONLY


======================================================================
FAIL: test_format_2 (ClassEval_65_0.NumberWordFormatterTestFormat.test_format_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_65_0.py", line 56, in test_format_2
    self.assertEqual(formatter.format(1000), "ONE THOUSAND ONLY")
AssertionError: '     THOUSAND  ONE MILLION   BILLION ONLY' != 'ONE THOUSAND ONLY'
-      THOUSAND  ONE MILLION   BILLION ONLY
+ ONE THOUSAND ONLY


======================================================================
FAIL: test_format_3 (ClassEval_65_0.NumberWordFormatterTestFormat.test_format_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_65_0.py", line 60, in test_format_3
    self.assertEqual(formatter.format(1000000), "ONE MILLION ONLY")
AssertionError: '    ONE THOUSAND   MILLION   BILLION ONLY' != 'ONE MILLION ONLY'
-     ONE THOUSAND   MILLION   BILLION ONLY
+ ONE MILLION ONLY


======================================================================
FAIL: test_format_4 (ClassEval_65_0.NumberWordFormatterTestFormat.test_format_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_65_0.py", line 64, in test_format_4
    self.assertEqual(formatter.format(1.23), "ONE AND CENTS TWENTY THREE ONLY")
AssertionError: '     THOUSAND   MILLION  ONE BILLION ONLY POINT TWO THREE ONLY' != 'ONE AND CENTS TWENTY THREE ONLY'
-      THOUSAND   MILLION  ONE BILLION ONLY POINT TWO THREE ONLY
+ ONE AND CENTS TWENTY THREE ONLY


======================================================================
FAIL: test_format_5 (ClassEval_65_0.NumberWordFormatterTestFormat.test_format_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_65_0.py", line 68, in test_format_5
    self.assertEqual(formatter.format(0), "ZERO ONLY")
AssertionError: '     THOUSAND   MILLION   BILLION ONLY' != 'ZERO ONLY'
-      THOUSAND   MILLION   BILLION ONLY
+ ZERO ONLY


----------------------------------------------------------------------
Ran 6 tests in 0.004s

FAILED (failures=5, errors=1)
FFFFFF
======================================================================
FAIL: test_format_string_1 (ClassEval_65_0.NumberWordFormatterTestFormatString.test_format_string_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_65_0.py", line 78, in test_format_string_1
    self.assertEqual(formatter.format_string('123456'),
AssertionError: '     THOUSAND ONE HUNDRED TWENTY THREE MI[37 chars]ONLY' != 'ONE HUNDRED AND TWENTY THREE THOUSAND FOU[24 chars]ONLY'
-      THOUSAND ONE HUNDRED TWENTY THREE MILLION FOUR HUNDRED FIFTY SIX BILLION ONLY
+ ONE HUNDRED AND TWENTY THREE THOUSAND FOUR HUNDRED AND FIFTY SIX ONLY


======================================================================
FAIL: test_format_string_2 (ClassEval_65_0.NumberWordFormatterTestFormatString.test_format_string_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_65_0.py", line 83, in test_format_string_2
    self.assertEqual(formatter.format_string('1000'), "ONE THOUSAND ONLY")
AssertionError: '     THOUSAND  ONE MILLION   BILLION ONLY' != 'ONE THOUSAND ONLY'
-      THOUSAND  ONE MILLION   BILLION ONLY
+ ONE THOUSAND ONLY


======================================================================
FAIL: test_format_string_3 (ClassEval_65_0.NumberWordFormatterTestFormatString.test_format_string_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_65_0.py", line 87, in test_format_string_3
    self.assertEqual(formatter.format_string('1000000'), "ONE MILLION ONLY")
AssertionError: '    ONE THOUSAND   MILLION   BILLION ONLY' != 'ONE MILLION ONLY'
-     ONE THOUSAND   MILLION   BILLION ONLY
+ ONE MILLION ONLY


======================================================================
FAIL: test_format_string_4 (ClassEval_65_0.NumberWordFormatterTestFormatString.test_format_string_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_65_0.py", line 91, in test_format_string_4
    self.assertEqual(formatter.format_string('1.23'), "ONE AND CENTS TWENTY THREE ONLY")
AssertionError: '     THOUSAND   MILLION  ONE BILLION ONLY POINT TWO THREE ONLY' != 'ONE AND CENTS TWENTY THREE ONLY'
-      THOUSAND   MILLION  ONE BILLION ONLY POINT TWO THREE ONLY
+ ONE AND CENTS TWENTY THREE ONLY


======================================================================
FAIL: test_format_string_5 (ClassEval_65_0.NumberWordFormatterTestFormatString.test_format_string_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_65_0.py", line 95, in test_format_string_5
    self.assertEqual(formatter.format_string('0'), "ZERO ONLY")
AssertionError: '     THOUSAND   MILLION   BILLION ONLY' != 'ZERO ONLY'
-      THOUSAND   MILLION   BILLION ONLY
+ ZERO ONLY


======================================================================
FAIL: test_format_string_6 (ClassEval_65_0.NumberWordFormatterTestFormatString.test_format_string_6)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_65_0.py", line 99, in test_format_string_6
    self.assertEqual(formatter.format_string('10'), "TEN ONLY")
AssertionError: '     THOUSAND   MILLION TEN BILLION ONLY' != 'TEN ONLY'
-      THOUSAND   MILLION TEN BILLION ONLY
+ TEN ONLY


----------------------------------------------------------------------
Ran 6 tests in 0.004s

FAILED (failures=6)
..FFFF
======================================================================
FAIL: test_trans_two_3 (ClassEval_65_0.NumberWordFormatterTestTransTwo.test_trans_two_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_65_0.py", line 113, in test_trans_two_3
    self.assertEqual(formatter.trans_two("05"), "FIVE")
AssertionError: ' FIVE' != 'FIVE'
-  FIVE
? -
+ FIVE


======================================================================
FAIL: test_trans_two_4 (ClassEval_65_0.NumberWordFormatterTestTransTwo.test_trans_two_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_65_0.py", line 117, in test_trans_two_4
    self.assertEqual(formatter.trans_two("00"), "")
AssertionError: ' ' != ''
-  


======================================================================
FAIL: test_trans_two_5 (ClassEval_65_0.NumberWordFormatterTestTransTwo.test_trans_two_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_65_0.py", line 121, in test_trans_two_5
    self.assertEqual(formatter.trans_two("01"), "ONE")
AssertionError: ' ONE' != 'ONE'
-  ONE
? -
+ ONE


======================================================================
FAIL: test_trans_two_6 (ClassEval_65_0.NumberWordFormatterTestTransTwo.test_trans_two_6)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_65_0.py", line 125, in test_trans_two_6
    self.assertEqual(formatter.trans_two("80"), "EIGHTY")
AssertionError: 'EIGHTY ' != 'EIGHTY'
- EIGHTY 
?       -
+ EIGHTY


----------------------------------------------------------------------
Ran 6 tests in 0.002s

FAILED (failures=4)
FFFFF
======================================================================
FAIL: test_trans_three_1 (ClassEval_65_0.NumberWordFormatterTestTransThree.test_trans_three_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_65_0.py", line 131, in test_trans_three_1
    self.assertEqual(formatter.trans_three("123"), "ONE HUNDRED AND TWENTY THREE")
AssertionError: 'ONE HUNDRED TWENTY THREE' != 'ONE HUNDRED AND TWENTY THREE'
- ONE HUNDRED TWENTY THREE
+ ONE HUNDRED AND TWENTY THREE
?             ++++


======================================================================
FAIL: test_trans_three_2 (ClassEval_65_0.NumberWordFormatterTestTransThree.test_trans_three_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_65_0.py", line 135, in test_trans_three_2
    self.assertEqual(formatter.trans_three("900"), "NINE HUNDRED")
AssertionError: 'NINE HUNDRED  ' != 'NINE HUNDRED'
- NINE HUNDRED  
?             --
+ NINE HUNDRED


======================================================================
FAIL: test_trans_three_3 (ClassEval_65_0.NumberWordFormatterTestTransThree.test_trans_three_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_65_0.py", line 139, in test_trans_three_3
    self.assertEqual(formatter.trans_three("007"), "SEVEN")
AssertionError: ' SEVEN' != 'SEVEN'
-  SEVEN
? -
+ SEVEN


======================================================================
FAIL: test_trans_three_4 (ClassEval_65_0.NumberWordFormatterTestTransThree.test_trans_three_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_65_0.py", line 143, in test_trans_three_4
    self.assertEqual(formatter.trans_three("001"), "ONE")
AssertionError: ' ONE' != 'ONE'
-  ONE
? -
+ ONE


======================================================================
FAIL: test_trans_three_5 (ClassEval_65_0.NumberWordFormatterTestTransThree.test_trans_three_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_65_0.py", line 147, in test_trans_three_5
    self.assertEqual(formatter.trans_three("006"), "SIX")
AssertionError: ' SIX' != 'SIX'
-  SIX
? -
+ SIX


----------------------------------------------------------------------
Ran 5 tests in 0.002s

FAILED (failures=5)
....
----------------------------------------------------------------------
Ran 4 tests in 0.000s

OK
F
======================================================================
FAIL: test_NumberWordFormatter (ClassEval_65_0.NumberWordFormatterTest.test_NumberWordFormatter)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_65_0.py", line 171, in test_NumberWordFormatter
    self.assertEqual(formatter.format(123456),
AssertionError: '     THOUSAND ONE HUNDRED TWENTY THREE MI[37 chars]ONLY' != 'ONE HUNDRED AND TWENTY THREE THOUSAND FOU[24 chars]ONLY'
-      THOUSAND ONE HUNDRED TWENTY THREE MILLION FOUR HUNDRED FIFTY SIX BILLION ONLY
+ ONE HUNDRED AND TWENTY THREE THOUSAND FOUR HUNDRED AND FIFTY SIX ONLY


----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (failures=1)
.FF....F..F
======================================================================
FAIL: test_replace_10 (ClassEval_66_0.NumericEntityUnescaperTestReplace.test_replace_10)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_66_0.py", line 83, in test_replace_10
    self.assertEqual(res, "")
AssertionError: '&#X' != ''
- &#X


======================================================================
FAIL: test_replace_11 (ClassEval_66_0.NumericEntityUnescaperTestReplace.test_replace_11)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_66_0.py", line 88, in test_replace_11
    self.assertEqual(res, "")
AssertionError: '&#c1d;BC' != ''
- &#c1d;BC


======================================================================
FAIL: test_replace_6 (ClassEval_66_0.NumericEntityUnescaperTestReplace.test_replace_6)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_66_0.py", line 63, in test_replace_6
    self.assertEqual(res, "")
AssertionError: '&#' != ''
- &#


======================================================================
FAIL: test_replace_9 (ClassEval_66_0.NumericEntityUnescaperTestReplace.test_replace_9)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_66_0.py", line 78, in test_replace_9
    self.assertEqual(res, "CCC")
AssertionError: 'CCC;' != 'CCC'
- CCC;
?    -
+ CCC


----------------------------------------------------------------------
Ran 11 tests in 0.002s

FAILED (failures=4)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.001s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.001s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.001s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.001s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.001s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.001s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.001s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.001s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.001s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.F...
======================================================================
FAIL: test_split_sentences_2 (ClassEval_78_0.SplitSentenceTestSplitSentences.test_split_sentences_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_78_0.py", line 48, in test_split_sentences_2
    self.assertEqual(lst, ['Who is Mr. Smith?', 'He is a teacher.'])
AssertionError: Lists differ: ['Who is Mr.', 'Smith?', 'He is a teacher.'] != ['Who is Mr. Smith?', 'He is a teacher.']

First differing element 0:
'Who is Mr.'
'Who is Mr. Smith?'

First list contains 1 additional elements.
First extra element 2:
'He is a teacher.'

- ['Who is Mr.', 'Smith?', 'He is a teacher.']
?             ^^^^

+ ['Who is Mr. Smith?', 'He is a teacher.']
?             ^


----------------------------------------------------------------------
Ran 5 tests in 0.002s

FAILED (failures=1)
.FF.F
======================================================================
FAIL: test_count_words_2 (ClassEval_78_0.SplitSentenceTestCountWords.test_count_words_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_78_0.py", line 75, in test_count_words_2
    self.assertEqual(cnt, 2)
AssertionError: 3 != 2

======================================================================
FAIL: test_count_words_3 (ClassEval_78_0.SplitSentenceTestCountWords.test_count_words_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_78_0.py", line 80, in test_count_words_3
    self.assertEqual(cnt, 1)
AssertionError: 2 != 1

======================================================================
FAIL: test_count_words_5 (ClassEval_78_0.SplitSentenceTestCountWords.test_count_words_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_78_0.py", line 90, in test_count_words_5
    self.assertEqual(cnt, 2)
AssertionError: 3 != 2

----------------------------------------------------------------------
Ran 5 tests in 0.002s

FAILED (failures=3)
.FF..
======================================================================
FAIL: test_process_text_file_2 (ClassEval_78_0.SplitSentenceTestProcessTextFile.test_process_text_file_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_78_0.py", line 102, in test_process_text_file_2
    self.assertEqual(cnt, 5)
AssertionError: 4 != 5

======================================================================
FAIL: test_process_text_file_3 (ClassEval_78_0.SplitSentenceTestProcessTextFile.test_process_text_file_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_78_0.py", line 107, in test_process_text_file_3
    self.assertEqual(cnt, 5)
AssertionError: 7 != 5

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=2)
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.F.FF
======================================================================
FAIL: test_add_stock_2 (ClassEval_82_0.StockPortfolioTrackerTestAddStock.test_add_stock_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_82_0.py", line 65, in test_add_stock_2
    self.assertEqual(tracker.portfolio, [{'name': 'AAPL', 'price': 150.0, 'quantity': 20}])
AssertionError: Lists differ: [{'na[32 chars]antity': 10}, {'name': 'AAPL', 'price': 150.0, 'quantity': 10}] != [{'na[32 chars]antity': 20}]

First differing element 0:
{'name': 'AAPL', 'price': 150.0, 'quantity': 10}
{'name': 'AAPL', 'price': 150.0, 'quantity': 20}

First list contains 1 additional elements.
First extra element 1:
{'name': 'AAPL', 'price': 150.0, 'quantity': 10}

- [{'name': 'AAPL', 'price': 150.0, 'quantity': 10},
?                                               ^  ^

+ [{'name': 'AAPL', 'price': 150.0, 'quantity': 20}]
?                                               ^  ^

-  {'name': 'AAPL', 'price': 150.0, 'quantity': 10}]

======================================================================
FAIL: test_add_stock_4 (ClassEval_82_0.StockPortfolioTrackerTestAddStock.test_add_stock_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_82_0.py", line 79, in test_add_stock_4
    self.assertEqual(tracker.portfolio, [{'name': 'AAPL', 'price': 150.0, 'quantity': 20},
AssertionError: Lists differ: [{'na[36 chars]ty': 10}, {'name': 'AAPL', 'price': 150.0, 'qu[58 chars] 10}] != [{'na[36 chars]ty': 20}, {'name': 'MSFT', 'price': 150.0, 'quantity': 10}]

First differing element 0:
{'name': 'AAPL', 'price': 150.0, 'quantity': 10}
{'name': 'AAPL', 'price': 150.0, 'quantity': 20}

First list contains 1 additional elements.
First extra element 2:
{'name': 'MSFT', 'price': 150.0, 'quantity': 10}

- [{'name': 'AAPL', 'price': 150.0, 'quantity': 10},
?                                               ^

+ [{'name': 'AAPL', 'price': 150.0, 'quantity': 20},
?                                               ^

-  {'name': 'AAPL', 'price': 150.0, 'quantity': 10},
   {'name': 'MSFT', 'price': 150.0, 'quantity': 10}]

======================================================================
FAIL: test_add_stock_5 (ClassEval_82_0.StockPortfolioTrackerTestAddStock.test_add_stock_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_82_0.py", line 88, in test_add_stock_5
    self.assertEqual(tracker.portfolio, [{'name': 'AAPL', 'price': 150.0, 'quantity': 20},
AssertionError: Lists differ: [{'na[36 chars]ty': 10}, {'name': 'AAPL', 'price': 150.0, 'qu[108 chars] 10}] != [{'na[36 chars]ty': 20}, {'name': 'MSFT', 'price': 150.0, 'quantity': 20}]

First differing element 0:
{'name': 'AAPL', 'price': 150.0, 'quantity': 10}
{'name': 'AAPL', 'price': 150.0, 'quantity': 20}

First list contains 2 additional elements.
First extra element 2:
{'name': 'MSFT', 'price': 150.0, 'quantity': 10}

- [{'name': 'AAPL', 'price': 150.0, 'quantity': 10},
?                                               ^

+ [{'name': 'AAPL', 'price': 150.0, 'quantity': 20},
?                                               ^

-  {'name': 'AAPL', 'price': 150.0, 'quantity': 10},
-  {'name': 'MSFT', 'price': 150.0, 'quantity': 10},
-  {'name': 'MSFT', 'price': 150.0, 'quantity': 10}]
?                                               ^

+  {'name': 'MSFT', 'price': 150.0, 'quantity': 20}]
?                                               ^


----------------------------------------------------------------------
Ran 5 tests in 0.004s

FAILED (failures=3)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
EEEEE
======================================================================
ERROR: test_buy_stock (ClassEval_82_0.StockPortfolioTrackerTestBuyStock.test_buy_stock)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_82_0.py", line 131, in test_buy_stock
    self.assertEqual(tracker.buy_stock({"name": "AAPL", "price": 150.0, "quantity": 10}), True)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: StockPortfolioTracker.buy_stock() missing 1 required positional argument: 'quantity'

======================================================================
ERROR: test_buy_stock_2 (ClassEval_82_0.StockPortfolioTrackerTestBuyStock.test_buy_stock_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_82_0.py", line 137, in test_buy_stock_2
    self.assertEqual(tracker.buy_stock({"name": "AAPL", "price": 150.0, "quantity": 10}), False)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: StockPortfolioTracker.buy_stock() missing 1 required positional argument: 'quantity'

======================================================================
ERROR: test_buy_stock_3 (ClassEval_82_0.StockPortfolioTrackerTestBuyStock.test_buy_stock_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_82_0.py", line 144, in test_buy_stock_3
    self.assertEqual(tracker.buy_stock({"name": "AAPL", "price": 150.0, "quantity": 10}), True)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: StockPortfolioTracker.buy_stock() missing 1 required positional argument: 'quantity'

======================================================================
ERROR: test_buy_stock_4 (ClassEval_82_0.StockPortfolioTrackerTestBuyStock.test_buy_stock_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_82_0.py", line 151, in test_buy_stock_4
    self.assertEqual(tracker.buy_stock({"name": "MSFT", "price": 150.0, "quantity": 10}), True)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: StockPortfolioTracker.buy_stock() missing 1 required positional argument: 'quantity'

======================================================================
ERROR: test_buy_stock_5 (ClassEval_82_0.StockPortfolioTrackerTestBuyStock.test_buy_stock_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_82_0.py", line 160, in test_buy_stock_5
    self.assertEqual(tracker.buy_stock({"name": "AAPL", "price": 150.0, "quantity": 10}), True)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: StockPortfolioTracker.buy_stock() missing 1 required positional argument: 'quantity'

----------------------------------------------------------------------
Ran 5 tests in 0.002s

FAILED (errors=5)
EEEEE
======================================================================
ERROR: test_sell_stock (ClassEval_82_0.StockPortfolioTrackerTestSellStock.test_sell_stock)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_82_0.py", line 171, in test_sell_stock
    self.assertEqual(tracker.sell_stock({"name": "AAPL", "price": 150.0, "quantity": 9}), True)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: StockPortfolioTracker.sell_stock() missing 1 required positional argument: 'quantity'

======================================================================
ERROR: test_sell_stock_2 (ClassEval_82_0.StockPortfolioTrackerTestSellStock.test_sell_stock_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_82_0.py", line 178, in test_sell_stock_2
    self.assertEqual(tracker.sell_stock({"name": "AAPL", "price": 150.0, "quantity": 20}), False)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: StockPortfolioTracker.sell_stock() missing 1 required positional argument: 'quantity'

======================================================================
ERROR: test_sell_stock_3 (ClassEval_82_0.StockPortfolioTrackerTestSellStock.test_sell_stock_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_82_0.py", line 184, in test_sell_stock_3
    self.assertEqual(tracker.sell_stock({"name": "AAPL", "price": 150.0, "quantity": 10}), False)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: StockPortfolioTracker.sell_stock() missing 1 required positional argument: 'quantity'

======================================================================
ERROR: test_sell_stock_4 (ClassEval_82_0.StockPortfolioTrackerTestSellStock.test_sell_stock_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_82_0.py", line 191, in test_sell_stock_4
    self.assertEqual(tracker.sell_stock({"name": "AAPL", "price": 150.0, "quantity": 20}), True)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: StockPortfolioTracker.sell_stock() missing 1 required positional argument: 'quantity'

======================================================================
ERROR: test_sell_stock_5 (ClassEval_82_0.StockPortfolioTrackerTestSellStock.test_sell_stock_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_82_0.py", line 199, in test_sell_stock_5
    self.assertEqual(tracker.sell_stock({"name": "AAPL", "price": 150.0, "quantity": 20}), True)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: StockPortfolioTracker.sell_stock() missing 1 required positional argument: 'quantity'

----------------------------------------------------------------------
Ran 5 tests in 0.002s

FAILED (errors=5)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.001s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
EEE
======================================================================
ERROR: test_main (ClassEval_82_0.StockPortfolioTrackerTestMain.test_main)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_82_0.py", line 286, in test_main
    self.assertEqual(tracker.buy_stock({"name": "MSFT", "price": 150.0, "quantity": 10}), True)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: StockPortfolioTracker.buy_stock() missing 1 required positional argument: 'quantity'

======================================================================
ERROR: test_main_2 (ClassEval_82_0.StockPortfolioTrackerTestMain.test_main_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_82_0.py", line 311, in test_main_2
    self.assertEqual(tracker.buy_stock({"name": "AAPL", "price": 150.0, "quantity": 10}), True)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: StockPortfolioTracker.buy_stock() missing 1 required positional argument: 'quantity'

======================================================================
ERROR: test_main_3 (ClassEval_82_0.StockPortfolioTrackerTestMain.test_main_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_82_0.py", line 321, in test_main_3
    self.assertEqual(tracker.buy_stock({"name": "AAPL", "price": 150.0, "quantity": 10}), True)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: StockPortfolioTracker.buy_stock() missing 1 required positional argument: 'quantity'

----------------------------------------------------------------------
Ran 3 tests in 0.001s

FAILED (errors=3)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.001s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.001s

OK
FFFFF
======================================================================
FAIL: test_add_seconds_1 (ClassEval_87_0.TimeUtilsTestAddSeconds.test_add_seconds_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_87_0.py", line 129, in test_add_seconds_1
    self.assertEqual(timeutils.add_seconds(600),
AssertionError: '01:07:22' != '01:17:22'
- 01:07:22
?    ^
+ 01:17:22
?    ^


======================================================================
FAIL: test_add_seconds_2 (ClassEval_87_0.TimeUtilsTestAddSeconds.test_add_seconds_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_87_0.py", line 134, in test_add_seconds_2
    self.assertEqual(timeutils.add_seconds(500),
AssertionError: '01:05:42' != '01:14:02'
- 01:05:42
+ 01:14:02


======================================================================
FAIL: test_add_seconds_3 (ClassEval_87_0.TimeUtilsTestAddSeconds.test_add_seconds_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_87_0.py", line 139, in test_add_seconds_3
    self.assertEqual(timeutils.add_seconds(400),
AssertionError: '01:04:02' != '01:10:42'
- 01:04:02
?      --
+ 01:10:42
?    + +


======================================================================
FAIL: test_add_seconds_4 (ClassEval_87_0.TimeUtilsTestAddSeconds.test_add_seconds_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_87_0.py", line 144, in test_add_seconds_4
    self.assertEqual(timeutils.add_seconds(300),
AssertionError: '01:02:22' != '01:07:22'
- 01:02:22
?     ^
+ 01:07:22
?     ^


======================================================================
FAIL: test_add_seconds_5 (ClassEval_87_0.TimeUtilsTestAddSeconds.test_add_seconds_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_87_0.py", line 149, in test_add_seconds_5
    self.assertEqual(timeutils.add_seconds(200),
AssertionError: '01:00:42' != '01:04:02'
- 01:00:42
?      --
+ 01:04:02
?     ++


----------------------------------------------------------------------
Ran 5 tests in 0.002s

FAILED (failures=5)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.006s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.001s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.001s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.001s

OK
F
======================================================================
FAIL: test_timeutils (ClassEval_87_0.TimeUtilsTest.test_timeutils)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_87_0.py", line 251, in test_timeutils
    self.assertEqual(timeutils.add_seconds(600),
AssertionError: '01:07:22' != '01:17:22'
- 01:07:22
?    ^
+ 01:17:22
?    ^


----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (failures=1)
.....F
======================================================================
FAIL: test_get_scheme_6 (ClassEval_90_0.URLHandlerTestGetScheme.test_get_scheme_6)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_90_0.py", line 84, in test_get_scheme_6
    self.assertIsNone(temp)
AssertionError: '' is not None

----------------------------------------------------------------------
Ran 6 tests in 0.001s

FAILED (failures=1)
.....F..
======================================================================
FAIL: test_get_host_6 (ClassEval_90_0.URLHandlerTestGetHost.test_get_host_6)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_90_0.py", line 117, in test_get_host_6
    self.assertIsNone(temp)
AssertionError: '' is not None

----------------------------------------------------------------------
Ran 8 tests in 0.001s

FAILED (failures=1)
FF...F
======================================================================
FAIL: test_get_path_1 (ClassEval_90_0.URLHandlerTestGetPath.test_get_path_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_90_0.py", line 134, in test_get_path_1
    self.assertEqual(temp, "/s?wd=aaa&rsv_spt=1#page")
AssertionError: '/s' != '/s?wd=aaa&rsv_spt=1#page'
- /s
+ /s?wd=aaa&rsv_spt=1#page


======================================================================
FAIL: test_get_path_2 (ClassEval_90_0.URLHandlerTestGetPath.test_get_path_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_90_0.py", line 140, in test_get_path_2
    self.assertEqual(temp,
AssertionError: '/search' != '/search?pglt=41&q=humaneval&cvid=4dc2da2bb4bc429[80 chars]h-CN'
- /search
+ /search?pglt=41&q=humaneval&cvid=4dc2da2bb4bc429eb498c85245ae5253&aqs=edge.0.0l7j69i61j69i60.10008j0j1&FORM=ANNTA1&PC=U531&mkt=zh-CN


======================================================================
FAIL: test_get_path_6 (ClassEval_90_0.URLHandlerTestGetPath.test_get_path_6)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_90_0.py", line 161, in test_get_path_6
    self.assertIsNone(temp)
AssertionError: 'abcdefg' is not None

----------------------------------------------------------------------
Ran 6 tests in 0.002s

FAILED (failures=3)
FFFFF.
======================================================================
FAIL: test_get_query_params_1 (ClassEval_90_0.URLHandlerTestGetQueryParams.test_get_query_params_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_90_0.py", line 168, in test_get_query_params_1
    self.assertEqual(temp, {"wd": "aaa", "rsv_spt": "1"})
AssertionError: {'wd': ['aaa'], 'rsv_spt': ['1']} != {'wd': 'aaa', 'rsv_spt': '1'}
- {'rsv_spt': ['1'], 'wd': ['aaa']}
?             -   -        -     -

+ {'rsv_spt': '1', 'wd': 'aaa'}

======================================================================
FAIL: test_get_query_params_2 (ClassEval_90_0.URLHandlerTestGetQueryParams.test_get_query_params_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_90_0.py", line 174, in test_get_query_params_2
    self.assertEqual(temp, {"pglt": "41", "q": "humaneval", "cvid": "4dc2da2bb4bc429eb498c85245ae5253",
AssertionError: {'pglt': ['41'], 'q': ['humaneval'], 'cvid': ['4dc[108 chars]31']} != {'pglt': '41', 'q': 'humaneval', 'cvid': '4dc2da2b[96 chars]531'}
- {'FORM': ['ANNTA1'],
?          -        -

+ {'FORM': 'ANNTA1',
-  'PC': ['U531'],
?        -      -

+  'PC': 'U531',
-  'aqs': ['edge.0.0l7j69i61j69i60.10008j0j1'],
?         -                                  -

+  'aqs': 'edge.0.0l7j69i61j69i60.10008j0j1',
-  'cvid': ['4dc2da2bb4bc429eb498c85245ae5253'],
?          -                                  -

+  'cvid': '4dc2da2bb4bc429eb498c85245ae5253',
-  'pglt': ['41'],
?          -    -

+  'pglt': '41',
-  'q': ['humaneval']}
?       -           -

+  'q': 'humaneval'}

======================================================================
FAIL: test_get_query_params_3 (ClassEval_90_0.URLHandlerTestGetQueryParams.test_get_query_params_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_90_0.py", line 180, in test_get_query_params_3
    self.assertEqual(temp, None)
AssertionError: {} != None

======================================================================
FAIL: test_get_query_params_4 (ClassEval_90_0.URLHandlerTestGetQueryParams.test_get_query_params_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_90_0.py", line 185, in test_get_query_params_4
    self.assertEqual(temp, {"wd": "bbb", "rsv_spt": "1"})
AssertionError: {'wd': ['bbb'], 'rsv_spt': ['1']} != {'wd': 'bbb', 'rsv_spt': '1'}
- {'rsv_spt': ['1'], 'wd': ['bbb']}
?             -   -        -     -

+ {'rsv_spt': '1', 'wd': 'bbb'}

======================================================================
FAIL: test_get_query_params_5 (ClassEval_90_0.URLHandlerTestGetQueryParams.test_get_query_params_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_90_0.py", line 190, in test_get_query_params_5
    self.assertEqual(temp, {"wd": "ccc", "rsv_spt": "1"})
AssertionError: {'wd': ['ccc'], 'rsv_spt': ['1']} != {'wd': 'ccc', 'rsv_spt': '1'}
- {'rsv_spt': ['1'], 'wd': ['ccc']}
?             -   -        -     -

+ {'rsv_spt': '1', 'wd': 'ccc'}

----------------------------------------------------------------------
Ran 6 tests in 0.005s

FAILED (failures=5)
.F...
======================================================================
FAIL: test_get_fragment_2 (ClassEval_90_0.URLHandlerTestGetFragment.test_get_fragment_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_90_0.py", line 208, in test_get_fragment_2
    self.assertEqual(temp, None)
AssertionError: '' != None

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=1)
F
======================================================================
FAIL: test_urlhandler (ClassEval_90_0.URLHandlerTest.test_urlhandler)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_90_0.py", line 234, in test_urlhandler
    self.assertEqual(temp, "/s?wd=aaa&rsv_spt=1#page")
AssertionError: '/s' != '/s?wd=aaa&rsv_spt=1#page'
- /s
+ /s?wd=aaa&rsv_spt=1#page


----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (failures=1)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
F.F..FF
======================================================================
FAIL: test_parse_1 (ClassEval_91_0.UrlPathTestParse.test_parse_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_91_0.py", line 81, in test_parse_1
    self.assertEqual(url_path.with_end_tag, True)
AssertionError: False != True

======================================================================
FAIL: test_parse_3 (ClassEval_91_0.UrlPathTestParse.test_parse_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_91_0.py", line 93, in test_parse_3
    self.assertEqual(url_path.with_end_tag, True)
AssertionError: False != True

======================================================================
FAIL: test_parse_6 (ClassEval_91_0.UrlPathTestParse.test_parse_6)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_91_0.py", line 110, in test_parse_6
    self.assertEqual(url_path.segments, [])
AssertionError: Lists differ: [''] != []

First list contains 1 additional elements.
First extra element 0:
''

- ['']
+ []

======================================================================
FAIL: test_parse_7 (ClassEval_91_0.UrlPathTestParse.test_parse_7)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_91_0.py", line 116, in test_parse_7
    self.assertEqual(url_path.segments, [])
AssertionError: Lists differ: [''] != []

First list contains 1 additional elements.
First extra element 0:
''

- ['']
+ []

----------------------------------------------------------------------
Ran 7 tests in 0.002s

FAILED (failures=4)
......
----------------------------------------------------------------------
Ran 6 tests in 0.000s

OK
F
======================================================================
FAIL: test_urlpath (ClassEval_91_0.UrlPathTest.test_urlpath)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_91_0.py", line 156, in test_urlpath
    self.assertEqual(url_path.with_end_tag, True)
AssertionError: False != True

----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (failures=1)
