.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
FFFFFF
======================================================================
FAIL: test_select_1 (ClassEval_3_0.ArrangementCalculatorTestSelect.test_select_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_3_0.py", line 122, in test_select_1
    self.assertEqual(res, expected)
AssertionError: Lists differ: [(1, 2), (1, 3), (1, 4), (2, 1), (2, 3), ([49 chars], 3)] != [[1, 2], [1, 3], [1, 4], [2, 1], [2, 3], [[49 chars], 3]]

First differing element 0:
(1, 2)
[1, 2]

- [(1, 2),
?  ^    ^

+ [[1, 2],
?  ^    ^

-  (1, 3),
?  ^    ^

+  [1, 3],
?  ^    ^

-  (1, 4),
?  ^    ^

+  [1, 4],
?  ^    ^

-  (2, 1),
?  ^    ^

+  [2, 1],
?  ^    ^

-  (2, 3),
?  ^    ^

+  [2, 3],
?  ^    ^

-  (2, 4),
?  ^    ^

+  [2, 4],
?  ^    ^

-  (3, 1),
?  ^    ^

+  [3, 1],
?  ^    ^

-  (3, 2),
?  ^    ^

+  [3, 2],
?  ^    ^

-  (3, 4),
?  ^    ^

+  [3, 4],
?  ^    ^

-  (4, 1),
?  ^    ^

+  [4, 1],
?  ^    ^

-  (4, 2),
?  ^    ^

+  [4, 2],
?  ^    ^

-  (4, 3)]
?  ^    -

+  [4, 3]]
?  ^     +


======================================================================
FAIL: test_select_2 (ClassEval_3_0.ArrangementCalculatorTestSelect.test_select_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_3_0.py", line 128, in test_select_2
    self.assertEqual(res, expected)
AssertionError: Lists differ: [(1, 2), (1, 3), (2, 1), (2, 3), (3, 1), (3, 2)] != [[1, 2], [1, 3], [2, 1], [2, 3], [3, 1], [3, 2]]

First differing element 0:
(1, 2)
[1, 2]

- [(1, 2), (1, 3), (2, 1), (2, 3), (3, 1), (3, 2)]
?  ^    ^  ^    ^  ^    ^  ^    ^  ^    ^  ^    -

+ [[1, 2], [1, 3], [2, 1], [2, 3], [3, 1], [3, 2]]
?  ^    ^  ^    ^  ^    ^  ^    ^  ^    ^  ^     +


======================================================================
FAIL: test_select_3 (ClassEval_3_0.ArrangementCalculatorTestSelect.test_select_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_3_0.py", line 134, in test_select_3
    self.assertEqual(res, expected)
AssertionError: Lists differ: [(2, 3), (2, 4), (3, 2), (3, 4), (4, 2), (4, 3)] != [[2, 3], [2, 4], [3, 2], [3, 4], [4, 2], [4, 3]]

First differing element 0:
(2, 3)
[2, 3]

- [(2, 3), (2, 4), (3, 2), (3, 4), (4, 2), (4, 3)]
?  ^    ^  ^    ^  ^    ^  ^    ^  ^    ^  ^    -

+ [[2, 3], [2, 4], [3, 2], [3, 4], [4, 2], [4, 3]]
?  ^    ^  ^    ^  ^    ^  ^    ^  ^    ^  ^     +


======================================================================
FAIL: test_select_4 (ClassEval_3_0.ArrangementCalculatorTestSelect.test_select_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_3_0.py", line 140, in test_select_4
    self.assertEqual(res, expected)
AssertionError: Lists differ: [(1, 2), (2, 1)] != [[1, 2], [2, 1]]

First differing element 0:
(1, 2)
[1, 2]

- [(1, 2), (2, 1)]
?  ^    ^  ^    -

+ [[1, 2], [2, 1]]
?  ^    ^  ^     +


======================================================================
FAIL: test_select_5 (ClassEval_3_0.ArrangementCalculatorTestSelect.test_select_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_3_0.py", line 146, in test_select_5
    self.assertEqual(res, expected)
AssertionError: Lists differ: [(1,), (2,), (3,), (4,)] != [[1], [2], [3], [4]]

First differing element 0:
(1,)
[1]

- [(1,), (2,), (3,), (4,)]
+ [[1], [2], [3], [4]]

======================================================================
FAIL: test_select_6 (ClassEval_3_0.ArrangementCalculatorTestSelect.test_select_6)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_3_0.py", line 152, in test_select_6
    self.assertEqual(res, expected)
AssertionError: Lists differ: [(1, 2), (2, 1)] != [[1, 2], [2, 1]]

First differing element 0:
(1, 2)
[1, 2]

- [(1, 2), (2, 1)]
?  ^    ^  ^    -

+ [[1, 2], [2, 1]]
?  ^    ^  ^     +


----------------------------------------------------------------------
Ran 6 tests in 0.008s

FAILED (failures=6)
FFFFF
======================================================================
FAIL: test_select_all_1 (ClassEval_3_0.ArrangementCalculatorTestSelectAll.test_select_all_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_3_0.py", line 161, in test_select_all_1
    self.assertEqual(res, expected)
AssertionError: Lists differ: [(1,), (2,), (3,), (1, 2), (1, 3), (2, 1),[85 chars], 1)] != [[1], [2], [3], [1, 2], [1, 3], [2, 1], [2[82 chars], 1]]

First differing element 0:
(1,)
[1]

Diff is 652 characters long. Set self.maxDiff to None to see it.

======================================================================
FAIL: test_select_all_2 (ClassEval_3_0.ArrangementCalculatorTestSelectAll.test_select_all_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_3_0.py", line 168, in test_select_all_2
    self.assertEqual(res, expected)
AssertionError: Lists differ: [(1,), (2,), (4,), (1, 2), (1, 4), (2, 1),[85 chars], 1)] != [[1], [2], [4], [1, 2], [1, 4], [2, 1], [2[82 chars], 1]]

First differing element 0:
(1,)
[1]

Diff is 652 characters long. Set self.maxDiff to None to see it.

======================================================================
FAIL: test_select_all_3 (ClassEval_3_0.ArrangementCalculatorTestSelectAll.test_select_all_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_3_0.py", line 174, in test_select_all_3
    self.assertEqual(res, expected)
AssertionError: Lists differ: [(1,), (2,), (1, 2), (2, 1)] != [[1], [2], [1, 2], [2, 1]]

First differing element 0:
(1,)
[1]

- [(1,), (2,), (1, 2), (2, 1)]
+ [[1], [2], [1, 2], [2, 1]]

======================================================================
FAIL: test_select_all_4 (ClassEval_3_0.ArrangementCalculatorTestSelectAll.test_select_all_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_3_0.py", line 180, in test_select_all_4
    self.assertEqual(res, expected)
AssertionError: Lists differ: [(1,), (3,), (1, 3), (3, 1)] != [[1], [3], [1, 3], [3, 1]]

First differing element 0:
(1,)
[1]

- [(1,), (3,), (1, 3), (3, 1)]
+ [[1], [3], [1, 3], [3, 1]]

======================================================================
FAIL: test_select_all_5 (ClassEval_3_0.ArrangementCalculatorTestSelectAll.test_select_all_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_3_0.py", line 186, in test_select_all_5
    self.assertEqual(res, expected)
AssertionError: Lists differ: [(1,)] != [[1]]

First differing element 0:
(1,)
[1]

- [(1,)]
+ [[1]]

----------------------------------------------------------------------
Ran 5 tests in 0.008s

FAILED (failures=5)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
F
======================================================================
FAIL: test_arrangementcalculator (ClassEval_3_0.ArrangementCalculatorTest.test_arrangementcalculator)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_3_0.py", line 222, in test_arrangementcalculator
    self.assertEqual(res, expected)
AssertionError: Lists differ: [(1, 2), (1, 3), (1, 4), (2, 1), (2, 3), ([49 chars], 3)] != [[1, 2], [1, 3], [1, 4], [2, 1], [2, 3], [[49 chars], 3]]

First differing element 0:
(1, 2)
[1, 2]

- [(1, 2),
?  ^    ^

+ [[1, 2],
?  ^    ^

-  (1, 3),
?  ^    ^

+  [1, 3],
?  ^    ^

-  (1, 4),
?  ^    ^

+  [1, 4],
?  ^    ^

-  (2, 1),
?  ^    ^

+  [2, 1],
?  ^    ^

-  (2, 3),
?  ^    ^

+  [2, 3],
?  ^    ^

-  (2, 4),
?  ^    ^

+  [2, 4],
?  ^    ^

-  (3, 1),
?  ^    ^

+  [3, 1],
?  ^    ^

-  (3, 2),
?  ^    ^

+  [3, 2],
?  ^    ^

-  (3, 4),
?  ^    ^

+  [3, 4],
?  ^    ^

-  (4, 1),
?  ^    ^

+  [4, 1],
?  ^    ^

-  (4, 2),
?  ^    ^

+  [4, 2],
?  ^    ^

-  (4, 3)]
?  ^    -

+  [4, 3]]
?  ^     +


----------------------------------------------------------------------
Ran 1 test in 0.005s

FAILED (failures=1)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....E.E
======================================================================
ERROR: test_calculate_6 (ClassEval_16_0.CalculatorTestCalculate.test_calculate_6)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_16_0.py", line 102, in test_calculate_6
    res = calculator.calculate('(1+2)+3')
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_16_0.py", line 36, in calculate
    operand_stack.append(int(expression[i]))
                         ^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '('

======================================================================
ERROR: test_calculate_8 (ClassEval_16_0.CalculatorTestCalculate.test_calculate_8)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_16_0.py", line 112, in test_calculate_8
    res = calculator.calculate('1+2?')
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_16_0.py", line 36, in calculate
    operand_stack.append(int(expression[i]))
                         ^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '?'

----------------------------------------------------------------------
Ran 8 tests in 0.001s

FAILED (errors=2)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
F.FFF
======================================================================
FAIL: test_count_all (ClassEval_23_0.CombinationCalculatorTestCountAll.test_count_all)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_23_0.py", line 72, in test_count_all
    self.assertEqual(CombinationCalculator.count_all(4), 15)
AssertionError: 16 != 15

======================================================================
FAIL: test_count_all_3 (ClassEval_23_0.CombinationCalculatorTestCountAll.test_count_all_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_23_0.py", line 78, in test_count_all_3
    self.assertEqual(CombinationCalculator.count_all(65), False)
AssertionError: 36893488147419103232 != False

======================================================================
FAIL: test_count_all_4 (ClassEval_23_0.CombinationCalculatorTestCountAll.test_count_all_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_23_0.py", line 81, in test_count_all_4
    self.assertEqual(CombinationCalculator.count_all(0), 0)
AssertionError: 1 != 0

======================================================================
FAIL: test_count_all_5 (ClassEval_23_0.CombinationCalculatorTestCountAll.test_count_all_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_23_0.py", line 84, in test_count_all_5
    self.assertEqual(CombinationCalculator.count_all(63), float("inf"))
AssertionError: 9223372036854775808 != inf

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=4)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
FFFFF
======================================================================
FAIL: test_select_all (ClassEval_23_0.CombinationCalculatorTestSelectAll.test_select_all)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_23_0.py", line 110, in test_select_all
    self.assertEqual(calc.select_all(), [['A']])
AssertionError: Lists differ: [[], ['A']] != [['A']]

First differing element 0:
[]
['A']

First list contains 1 additional elements.
First extra element 1:
['A']

- [[], ['A']]
?  ----

+ [['A']]

======================================================================
FAIL: test_select_all_2 (ClassEval_23_0.CombinationCalculatorTestSelectAll.test_select_all_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_23_0.py", line 114, in test_select_all_2
    self.assertEqual(calc.select_all(), [['A'], ['B'], ['A', 'B']])
AssertionError: Lists differ: [[], ['A'], ['B'], ['A', 'B']] != [['A'], ['B'], ['A', 'B']]

First differing element 0:
[]
['A']

First list contains 1 additional elements.
First extra element 3:
['A', 'B']

- [[], ['A'], ['B'], ['A', 'B']]
?  ----

+ [['A'], ['B'], ['A', 'B']]

======================================================================
FAIL: test_select_all_3 (ClassEval_23_0.CombinationCalculatorTestSelectAll.test_select_all_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_23_0.py", line 118, in test_select_all_3
    self.assertEqual(calc.select_all(),[['A'], ['B'], ['C'], ['A', 'B'], ['A', 'C'], ['B', 'C'], ['A', 'B', 'C']])
AssertionError: Lists differ: [[], ['A'], ['B'], ['C'], ['A', 'B'], ['A', 'C'], ['B', 'C'], ['A', 'B', 'C']] != [['A'], ['B'], ['C'], ['A', 'B'], ['A', 'C'], ['B', 'C'], ['A', 'B', 'C']]

First differing element 0:
[]
['A']

First list contains 1 additional elements.
First extra element 7:
['A', 'B', 'C']

- [[], ['A'], ['B'], ['C'], ['A', 'B'], ['A', 'C'], ['B', 'C'], ['A', 'B', 'C']]
?  ----

+ [['A'], ['B'], ['C'], ['A', 'B'], ['A', 'C'], ['B', 'C'], ['A', 'B', 'C']]

======================================================================
FAIL: test_select_all_4 (ClassEval_23_0.CombinationCalculatorTestSelectAll.test_select_all_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_23_0.py", line 122, in test_select_all_4
    self.assertEqual(calc.select_all(),[])
AssertionError: Lists differ: [[]] != []

First list contains 1 additional elements.
First extra element 0:
[]

- [[]]
+ []

======================================================================
FAIL: test_select_all_5 (ClassEval_23_0.CombinationCalculatorTestSelectAll.test_select_all_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_23_0.py", line 126, in test_select_all_5
    self.assertEqual(calc.select_all(),[['B']])
AssertionError: Lists differ: [[], ['B']] != [['B']]

First differing element 0:
[]
['B']

First list contains 1 additional elements.
First extra element 1:
['B']

- [[], ['B']]
?  ----

+ [['B']]

----------------------------------------------------------------------
Ran 5 tests in 0.004s

FAILED (failures=5)
EEEEE
======================================================================
ERROR: test_select2 (ClassEval_23_0.CombinationCalculatorTestSelect2.test_select2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_23_0.py", line 133, in test_select2
    calc._select(0, [None] * 2, 0, result)
    ^^^^^^^^^^^^
AttributeError: 'CombinationCalculator' object has no attribute '_select'. Did you mean: 'select'?

======================================================================
ERROR: test_select2_2 (ClassEval_23_0.CombinationCalculatorTestSelect2.test_select2_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_23_0.py", line 139, in test_select2_2
    calc._select(0, [None] * 3, 0, result)
    ^^^^^^^^^^^^
AttributeError: 'CombinationCalculator' object has no attribute '_select'. Did you mean: 'select'?

======================================================================
ERROR: test_select2_3 (ClassEval_23_0.CombinationCalculatorTestSelect2.test_select2_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_23_0.py", line 145, in test_select2_3
    calc._select(0, [None] * 1, 0, result)
    ^^^^^^^^^^^^
AttributeError: 'CombinationCalculator' object has no attribute '_select'. Did you mean: 'select'?

======================================================================
ERROR: test_select2_4 (ClassEval_23_0.CombinationCalculatorTestSelect2.test_select2_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_23_0.py", line 151, in test_select2_4
    calc._select(0, [None] * 0, 0, result)
    ^^^^^^^^^^^^
AttributeError: 'CombinationCalculator' object has no attribute '_select'. Did you mean: 'select'?

======================================================================
ERROR: test_select2_5 (ClassEval_23_0.CombinationCalculatorTestSelect2.test_select2_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_23_0.py", line 157, in test_select2_5
    calc._select(0, [None] * 4, 0, result)
    ^^^^^^^^^^^^
AttributeError: 'CombinationCalculator' object has no attribute '_select'. Did you mean: 'select'?

----------------------------------------------------------------------
Ran 5 tests in 0.003s

FAILED (errors=5)
F
======================================================================
FAIL: test_main (ClassEval_23_0.CombinationCalculatorTestMain.test_main)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_23_0.py", line 164, in test_main
    self.assertEqual(calc.count_all(4), 15)
AssertionError: 16 != 15

----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (failures=1)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.001s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.001s

OK
EEEEE
======================================================================
ERROR: test_get_correlation_1 (ClassEval_30_0.DataStatistics2TestGetCorrelation.test_get_correlation_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_30_0.py", line 200, in test_get_correlation_1
    res = ds2.get_correlation()
          ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_30_0.py", line 57, in get_correlation
    return np.corrcoef(self.data)[0, 1]
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^
IndexError: invalid index to scalar variable.

======================================================================
ERROR: test_get_correlation_2 (ClassEval_30_0.DataStatistics2TestGetCorrelation.test_get_correlation_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_30_0.py", line 205, in test_get_correlation_2
    res = ds2.get_correlation()
          ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_30_0.py", line 57, in get_correlation
    return np.corrcoef(self.data)[0, 1]
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^
IndexError: invalid index to scalar variable.

======================================================================
ERROR: test_get_correlation_3 (ClassEval_30_0.DataStatistics2TestGetCorrelation.test_get_correlation_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_30_0.py", line 210, in test_get_correlation_3
    res = ds2.get_correlation()
          ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_30_0.py", line 57, in get_correlation
    return np.corrcoef(self.data)[0, 1]
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^
IndexError: invalid index to scalar variable.

======================================================================
ERROR: test_get_correlation_4 (ClassEval_30_0.DataStatistics2TestGetCorrelation.test_get_correlation_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_30_0.py", line 215, in test_get_correlation_4
    res = ds2.get_correlation()
          ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_30_0.py", line 57, in get_correlation
    return np.corrcoef(self.data)[0, 1]
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^
IndexError: invalid index to scalar variable.

======================================================================
ERROR: test_get_correlation_5 (ClassEval_30_0.DataStatistics2TestGetCorrelation.test_get_correlation_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_30_0.py", line 220, in test_get_correlation_5
    res = ds2.get_correlation()
          ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_30_0.py", line 57, in get_correlation
    return np.corrcoef(self.data)[0, 1]
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^
IndexError: invalid index to scalar variable.

----------------------------------------------------------------------
Ran 5 tests in 0.003s

FAILED (errors=5)
E
======================================================================
ERROR: test_datastatistics2 (ClassEval_30_0.DataStatistics2Test.test_datastatistics2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_30_0.py", line 242, in test_datastatistics2
    res = ds2.get_correlation()
          ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_30_0.py", line 57, in get_correlation
    return np.corrcoef(self.data)[0, 1]
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^
IndexError: invalid index to scalar variable.

----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (errors=1)
FFFFF
======================================================================
FAIL: test_correlation_coefficient (ClassEval_31_0.DataStatistics4TestCorrelationCoefficient.test_correlation_coefficient)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_31_0.py", line 56, in test_correlation_coefficient
    self.assertEqual(DataStatistics4.correlation_coefficient([1, 2, 3], [4, 5, 6]), 0.9999999999999998)
AssertionError: 1.0 != 0.9999999999999998

======================================================================
FAIL: test_correlation_coefficient_2 (ClassEval_31_0.DataStatistics4TestCorrelationCoefficient.test_correlation_coefficient_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_31_0.py", line 59, in test_correlation_coefficient_2
    self.assertEqual(DataStatistics4.correlation_coefficient([1, 1, 1], [2, 2, 2]), 0)
AssertionError: nan != 0

======================================================================
FAIL: test_correlation_coefficient_3 (ClassEval_31_0.DataStatistics4TestCorrelationCoefficient.test_correlation_coefficient_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_31_0.py", line 62, in test_correlation_coefficient_3
    self.assertEqual(DataStatistics4.correlation_coefficient([1, 2, 3], [1, 2, 3]), 0.9999999999999998)
AssertionError: 1.0 != 0.9999999999999998

======================================================================
FAIL: test_correlation_coefficient_4 (ClassEval_31_0.DataStatistics4TestCorrelationCoefficient.test_correlation_coefficient_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_31_0.py", line 65, in test_correlation_coefficient_4
    self.assertEqual(DataStatistics4.correlation_coefficient([1, 2, 3], [1, 2, 4]), 0.9819805060619659)
AssertionError: 0.9819805060619656 != 0.9819805060619659

======================================================================
FAIL: test_correlation_coefficient_5 (ClassEval_31_0.DataStatistics4TestCorrelationCoefficient.test_correlation_coefficient_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_31_0.py", line 68, in test_correlation_coefficient_5
    self.assertEqual(DataStatistics4.correlation_coefficient([1, 2, 3], [1, 5, 3]), 0.4999999999999999)
AssertionError: 0.5 != 0.4999999999999999

----------------------------------------------------------------------
Ran 5 tests in 0.006s

FAILED (failures=5)
FF.F.
======================================================================
FAIL: test_skewness (ClassEval_31_0.DataStatistics4TestSkewness.test_skewness)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_31_0.py", line 73, in test_skewness
    self.assertEqual(DataStatistics4.skewness([1, 2, 5]), 2.3760224064818463)
AssertionError: 0.5280049792181881 != 2.3760224064818463

======================================================================
FAIL: test_skewness_2 (ClassEval_31_0.DataStatistics4TestSkewness.test_skewness_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_31_0.py", line 76, in test_skewness_2
    self.assertEqual(DataStatistics4.skewness([1, 1, 1]), 0)
AssertionError: nan != 0

======================================================================
FAIL: test_skewness_4 (ClassEval_31_0.DataStatistics4TestSkewness.test_skewness_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_31_0.py", line 82, in test_skewness_4
    self.assertEqual(DataStatistics4.skewness([1, 2, 4]), 1.7181079837227264)
AssertionError: 0.3818017741606059 != 1.7181079837227264

----------------------------------------------------------------------
Ran 5 tests in 0.012s

FAILED (failures=3)
F.F.F
======================================================================
FAIL: test_kurtosis (ClassEval_31_0.DataStatistics4TestKurtosis.test_kurtosis)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_31_0.py", line 90, in test_kurtosis
    self.assertEqual(DataStatistics4.kurtosis([1, 2, 5]), -1.5000000000000002)
AssertionError: -1.5 != -1.5000000000000002

======================================================================
FAIL: test_kurtosis_3 (ClassEval_31_0.DataStatistics4TestKurtosis.test_kurtosis_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_31_0.py", line 96, in test_kurtosis_3
    self.assertEqual(DataStatistics4.kurtosis([1, 2, 3]), -1.5000000000000002)
AssertionError: -1.5 != -1.5000000000000002

======================================================================
FAIL: test_kurtosis_5 (ClassEval_31_0.DataStatistics4TestKurtosis.test_kurtosis_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_31_0.py", line 102, in test_kurtosis_5
    self.assertEqual(DataStatistics4.kurtosis([1, 5, 3]), -1.5000000000000002)
AssertionError: -1.5 != -1.5000000000000002

----------------------------------------------------------------------
Ran 5 tests in 0.006s

FAILED (failures=3)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
F
======================================================================
FAIL: test_main (ClassEval_31_0.DataStatistics4TestMain.test_main)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_31_0.py", line 129, in test_main
    self.assertEqual(DataStatistics4.correlation_coefficient([1, 2, 3], [4, 5, 6]), 0.9999999999999998)
AssertionError: 1.0 != 0.9999999999999998

----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (failures=1)
E....F.
======================================================================
FAIL: test_prepare_5 (ClassEval_39_0.ExpressionCalculatorTestPrepare.test_prepare_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_39_0.py", line 106, in test_prepare_5
    self.assertEqual(self.expression_calculator.postfix_stack, deque(['2', '3', '+', '4', '*']))
AssertionError: deque(['2', '3', '+', '(', '4', '*', ')']) != deque(['2', '3', '+', '4', '*'])

----------------------------------------------------------------------
Ran 6 tests in 0.007s

FAILED (failures=1)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.031s

OK
.......
----------------------------------------------------------------------
Ran 7 tests in 0.000s

OK
FEEEEE.
======================================================================
ERROR: test_calculate_method_2 (ClassEval_39_0.ExpressionCalculatorTestCalculateMethod.test_calculate_method_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_39_0.py", line 175, in test_calculate_method_2
    result = self.expression_calculator._calculate("3", "2", "-")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_39_0.py", line 50, in _calculate
    return ops[current_op](first_value, second_value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: unsupported operand type(s) for -: 'str' and 'str'

======================================================================
ERROR: test_calculate_method_3 (ClassEval_39_0.ExpressionCalculatorTestCalculateMethod.test_calculate_method_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_39_0.py", line 179, in test_calculate_method_3
    result = self.expression_calculator._calculate("2", "3", "*")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_39_0.py", line 50, in _calculate
    return ops[current_op](first_value, second_value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: can't multiply sequence by non-int of type 'str'

======================================================================
ERROR: test_calculate_method_4 (ClassEval_39_0.ExpressionCalculatorTestCalculateMethod.test_calculate_method_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_39_0.py", line 183, in test_calculate_method_4
    result = self.expression_calculator._calculate("3", "3", "/")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_39_0.py", line 50, in _calculate
    return ops[current_op](first_value, second_value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: unsupported operand type(s) for /: 'str' and 'str'

======================================================================
ERROR: test_calculate_method_5 (ClassEval_39_0.ExpressionCalculatorTestCalculateMethod.test_calculate_method_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_39_0.py", line 187, in test_calculate_method_5
    result = self.expression_calculator._calculate("6", "2", "/")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_39_0.py", line 50, in _calculate
    return ops[current_op](first_value, second_value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: unsupported operand type(s) for /: 'str' and 'str'

======================================================================
ERROR: test_calculate_method_6 (ClassEval_39_0.ExpressionCalculatorTestCalculateMethod.test_calculate_method_6)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_39_0.py", line 191, in test_calculate_method_6
    result = self.expression_calculator._calculate("6", "2", "%")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_39_0.py", line 50, in _calculate
    return ops[current_op](first_value, second_value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: not all arguments converted during string formatting

======================================================================
FAIL: test_calculate_method_1 (ClassEval_39_0.ExpressionCalculatorTestCalculateMethod.test_calculate_method_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_39_0.py", line 172, in test_calculate_method_1
    self.assertEqual(result, Decimal(5.0))
AssertionError: '23' != Decimal('5')

----------------------------------------------------------------------
Ran 7 tests in 0.068s

FAILED (failures=1, errors=5)
....FF
======================================================================
FAIL: test_transform_5 (ClassEval_39_0.ExpressionCalculatorTestTransform.test_transform_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_39_0.py", line 223, in test_transform_5
    self.assertEqual(result, "~2+(~3)*4")
AssertionError: '-2+(-3)*4' != '~2+(~3)*4'
- -2+(-3)*4
? ^   ^
+ ~2+(~3)*4
? ^   ^


======================================================================
FAIL: test_transform_6 (ClassEval_39_0.ExpressionCalculatorTestTransform.test_transform_6)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_39_0.py", line 227, in test_transform_6
    self.assertEqual(result, "0-(1+1)")
AssertionError: '~(1+1)' != '0-(1+1)'
- ~(1+1)
? ^
+ 0-(1+1)
? ^^


----------------------------------------------------------------------
Ran 6 tests in 0.018s

FAILED (failures=2)
EEE
======================================================================
ERROR: test_ExpressionCalculator (ClassEval_39_0.ExpressionCalculatorTest.test_ExpressionCalculator)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_39_0.py", line 235, in test_ExpressionCalculator
    result = self.expression_calculator.calculate("2 + 3 * 4")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_39_0.py", line 18, in calculate
    if not self.is_operator(current):
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_39_0.py", line 40, in is_operator
    @staticmethod
    
func_timeout.dafunc.FunctionTimedOut-751375831688611430: Function run_unit_test (args=(<test_pipeline.AutoTest object at 0x10bfb8c80>, 'ClassEval_39_0', 'ExpressionCalculatorTest', 'GPT-4_greedy_Mathematical_Operations')) (kwargs={}) timed out after 5.000000 seconds.


----------------------------------------------------------------------
Ran 1 test in 5.041s

FAILED (errors=1)
EE
======================================================================
ERROR: test_calculate_1 (ClassEval_39_0.ExpressionCalculatorTestCalculate.test_calculate_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_39_0.py", line 64, in test_calculate_1
    result = self.expression_calculator.calculate("2 + 3 * 4")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_39_0.py", line 19, in calculate
    self.postfix_stack.appendleft(current)
func_timeout.dafunc.FunctionTimedOut7267861956081289783: Function run_unit_test (args=(<test_pipeline.AutoTest object at 0x10bfb8c80>, 'ClassEval_39_0', 'ExpressionCalculatorTestCalculate', 'GPT-4_greedy_Mathematical_Operations')) (kwargs={}) timed out after 5.000000 seconds.


======================================================================
ERROR: test_calculate_2 (ClassEval_39_0.ExpressionCalculatorTestCalculate.test_calculate_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_39_0.py", line 68, in test_calculate_2
    result = self.expression_calculator.calculate("2 + 3 + 4")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_39_0.py", line 17, in calculate
    current = self.postfix_stack.popleft()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
func_timeout.dafunc.FunctionTimedOut7267861956081289783: Function run_unit_test (args=(<test_pipeline.AutoTest object at 0x10bfb8c80>, 'ClassEval_39_0', 'ExpressionCalculatorTestCalculate', 'GPT-4_greedy_Mathematical_Operations')) (kwargs={}) timed out after 5.000000 seconds.


======================================================================
ERROR: test_calculate_3 (ClassEval_39_0.ExpressionCalculatorTestCalculate.test_calculate_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_39_0.py", line 72, in test_calculate_3
    result = self.expression_calculator.calculate("2 * 3 * 4")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_39_0.py", line 16, in calculate
    while self.postfix_stack:
          ^^^^^^^^^^^^^^^^^^
func_timeout.dafunc.FunctionTimedOut7267861956081289783: Function run_unit_test (args=(<test_pipeline.AutoTest object at 0x10bfb8c80>, 'ClassEval_39_0', 'ExpressionCalculatorTestCalculate', 'GPT-4_greedy_Mathematical_Operations')) (kwargs={}) timed out after 5.000000 seconds.


======================================================================
ERROR: test_calculate_4 (ClassEval_39_0.ExpressionCalculatorTestCalculate.test_calculate_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_39_0.py", line 76, in test_calculate_4
    result = self.expression_calculator.calculate("2 + 4 / 4")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_39_0.py", line 17, in calculate
    current = self.postfix_stack.popleft()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
func_timeout.dafunc.FunctionTimedOut7267861956081289783: Function run_unit_test (args=(<test_pipeline.AutoTest object at 0x10bfb8c80>, 'ClassEval_39_0', 'ExpressionCalculatorTestCalculate', 'GPT-4_greedy_Mathematical_Operations')) (kwargs={}) timed out after 5.000000 seconds.


======================================================================
ERROR: test_calculate_5 (ClassEval_39_0.ExpressionCalculatorTestCalculate.test_calculate_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_39_0.py", line 80, in test_calculate_5
    result = self.expression_calculator.calculate("(2 + 3) * 4")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_39_0.py", line 19, in calculate
    self.postfix_stack.appendleft(current)
func_timeout.dafunc.FunctionTimedOut7267861956081289783: Function run_unit_test (args=(<test_pipeline.AutoTest object at 0x10bfb8c80>, 'ClassEval_39_0', 'ExpressionCalculatorTestCalculate', 'GPT-4_greedy_Mathematical_Operations')) (kwargs={}) timed out after 5.000000 seconds.


----------------------------------------------------------------------
Ran 5 tests in 13.060s

FAILED (errors=5)
FFFFF
======================================================================
FAIL: test_kappa_1 (ClassEval_51_0.KappaCalculatorTestKappa.test_kappa_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_51_0.py", line 54, in test_kappa_1
    self.assertEqual(KappaCalculator.kappa([[2, 1, 1], [1, 2, 1], [1, 1, 2]], 3), 0.25)
AssertionError: -0.5 != 0.25

======================================================================
FAIL: test_kappa_2 (ClassEval_51_0.KappaCalculatorTestKappa.test_kappa_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_51_0.py", line 57, in test_kappa_2
    self.assertAlmostEqual(KappaCalculator.kappa([[2, 2, 1], [1, 2, 1], [1, 1, 2]], 3), 0.19469026548672572)
AssertionError: 0.3999999999999999 != 0.19469026548672572 within 7 places (0.2053097345132742 difference)

======================================================================
FAIL: test_kappa_3 (ClassEval_51_0.KappaCalculatorTestKappa.test_kappa_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_51_0.py", line 60, in test_kappa_3
    self.assertAlmostEqual(KappaCalculator.kappa([[2, 1, 2], [1, 2, 1], [1, 1, 2]], 3), 0.19469026548672572)
AssertionError: -0.8000000000000003 != 0.19469026548672572 within 7 places (0.994690265486726 difference)

======================================================================
FAIL: test_kappa_4 (ClassEval_51_0.KappaCalculatorTestKappa.test_kappa_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_51_0.py", line 63, in test_kappa_4
    self.assertAlmostEqual(KappaCalculator.kappa([[2, 1, 1], [2, 2, 1], [1, 1, 2]], 3), 0.19469026548672572)
AssertionError: 0.3999999999999999 != 0.19469026548672572 within 7 places (0.2053097345132742 difference)

======================================================================
FAIL: test_kappa_5 (ClassEval_51_0.KappaCalculatorTestKappa.test_kappa_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_51_0.py", line 66, in test_kappa_5
    self.assertAlmostEqual(KappaCalculator.kappa([[2, 1, 1], [1, 2, 2], [1, 1, 2]], 3), 0.19469026548672572)
AssertionError: -0.8000000000000003 != 0.19469026548672572 within 7 places (0.994690265486726 difference)

----------------------------------------------------------------------
Ran 5 tests in 0.008s

FAILED (failures=5)
EEEEE
======================================================================
ERROR: test_fleiss_kappa_1 (ClassEval_51_0.KappaCalculatorTestFleissKappa.test_fleiss_kappa_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_51_0.py", line 71, in test_fleiss_kappa_1
    self.assertEqual(KappaCalculator.fleiss_kappa([[0, 0, 0, 0, 14],
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_51_0.py", line 40, in fleiss_kappa
    P = (np.sum(testData * testData, axis=1) - n) / (n * (n - 1))
                ~~~~~~~~~^~~~~~~~~~
TypeError: can't multiply sequence by non-int of type 'list'

======================================================================
ERROR: test_fleiss_kappa_2 (ClassEval_51_0.KappaCalculatorTestFleissKappa.test_fleiss_kappa_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_51_0.py", line 83, in test_fleiss_kappa_2
    self.assertEqual(KappaCalculator.fleiss_kappa([[1, 0, 0, 0, 14],
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_51_0.py", line 40, in fleiss_kappa
    P = (np.sum(testData * testData, axis=1) - n) / (n * (n - 1))
                ~~~~~~~~~^~~~~~~~~~
TypeError: can't multiply sequence by non-int of type 'list'

======================================================================
ERROR: test_fleiss_kappa_3 (ClassEval_51_0.KappaCalculatorTestFleissKappa.test_fleiss_kappa_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_51_0.py", line 95, in test_fleiss_kappa_3
    self.assertEqual(KappaCalculator.fleiss_kappa([[0, 1, 0, 0, 14],
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_51_0.py", line 40, in fleiss_kappa
    P = (np.sum(testData * testData, axis=1) - n) / (n * (n - 1))
                ~~~~~~~~~^~~~~~~~~~
TypeError: can't multiply sequence by non-int of type 'list'

======================================================================
ERROR: test_fleiss_kappa_4 (ClassEval_51_0.KappaCalculatorTestFleissKappa.test_fleiss_kappa_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_51_0.py", line 107, in test_fleiss_kappa_4
    self.assertEqual(KappaCalculator.fleiss_kappa([[0, 0, 1, 0, 14],
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_51_0.py", line 40, in fleiss_kappa
    P = (np.sum(testData * testData, axis=1) - n) / (n * (n - 1))
                ~~~~~~~~~^~~~~~~~~~
TypeError: can't multiply sequence by non-int of type 'list'

======================================================================
ERROR: test_fleiss_kappa_5 (ClassEval_51_0.KappaCalculatorTestFleissKappa.test_fleiss_kappa_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_51_0.py", line 119, in test_fleiss_kappa_5
    self.assertEqual(KappaCalculator.fleiss_kappa([[0, 0, 0, 1, 14],
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_51_0.py", line 40, in fleiss_kappa
    P = (np.sum(testData * testData, axis=1) - n) / (n * (n - 1))
                ~~~~~~~~~^~~~~~~~~~
TypeError: can't multiply sequence by non-int of type 'list'

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (errors=5)
F
======================================================================
FAIL: test_kappacalculator (ClassEval_51_0.KappaCalculatorTest.test_kappacalculator)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_51_0.py", line 133, in test_kappacalculator
    self.assertEqual(KappaCalculator.kappa([[2, 1, 1], [1, 2, 1], [1, 1, 2]], 3), 0.25)
AssertionError: -0.5 != 0.25

----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (failures=1)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....E
======================================================================
ERROR: test_precision_6 (ClassEval_56_0.MetricsCalculatorTestPrecision.test_precision_6)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_56_0.py", line 103, in test_precision_6
    temp = mc.precision([0, 0, 0, 0], [1, 0, 1, 1])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_56_0.py", line 25, in precision
    return self.true_positives / (self.true_positives + self.false_positives)
           ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ZeroDivisionError: division by zero

----------------------------------------------------------------------
Ran 6 tests in 0.001s

FAILED (errors=1)
.....E
======================================================================
ERROR: test_recall_6 (ClassEval_56_0.MetricsCalculatorTestRecall.test_recall_6)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_56_0.py", line 135, in test_recall_6
    temp = mc.recall([1, 1, 0, 0], [0, 0, 0, 0])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_56_0.py", line 29, in recall
    return self.true_positives / (self.true_positives + self.false_negatives)
           ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ZeroDivisionError: division by zero

----------------------------------------------------------------------
Ran 6 tests in 0.001s

FAILED (errors=1)
.....E
======================================================================
ERROR: test_f1_score_6 (ClassEval_56_0.MetricsCalculatorTestF1Score.test_f1_score_6)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_56_0.py", line 167, in test_f1_score_6
    temp = mc.f1_score([0, 0, 0, 0], [0, 0, 0, 0])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_56_0.py", line 32, in f1_score
    precision = self.precision(predicted_labels, true_labels)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_56_0.py", line 25, in precision
    return self.true_positives / (self.true_positives + self.false_positives)
           ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ZeroDivisionError: division by zero

----------------------------------------------------------------------
Ran 6 tests in 0.001s

FAILED (errors=1)
.F...E
======================================================================
ERROR: test_accuracy_6 (ClassEval_56_0.MetricsCalculatorTestAccuracy.test_accuracy_6)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_56_0.py", line 199, in test_accuracy_6
    temp = mc.accuracy([], [])
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_56_0.py", line 38, in accuracy
    return (self.true_positives + self.true_negatives) / (self.true_positives + self.true_negatives + self.false_positives + self.false_negatives)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ZeroDivisionError: division by zero

======================================================================
FAIL: test_accuracy_2 (ClassEval_56_0.MetricsCalculatorTestAccuracy.test_accuracy_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_56_0.py", line 180, in test_accuracy_2
    self.assertAlmostEqual(temp, 0.3333333333333333)
AssertionError: 0.25 != 0.3333333333333333 within 7 places (0.08333333333333331 difference)

----------------------------------------------------------------------
Ran 6 tests in 0.002s

FAILED (failures=1, errors=1)
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
EEEEE.EE
======================================================================
ERROR: test_mrr_1 (ClassEval_57_0.MetricsCalculator2TestMrr.test_mrr_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_57_0.py", line 41, in test_mrr_1
    res1, res2 = MetricsCalculator2.mrr(([1, 0, 1, 0], 4))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_57_0.py", line 16, in mrr
    mrr_list = [MetricsCalculator2.mrr(d) for d in data]
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_57_0.py", line 15, in mrr
    if isinstance(data[0], list):
                  ~~~~^^^
TypeError: 'int' object is not subscriptable

======================================================================
ERROR: test_mrr_2 (ClassEval_57_0.MetricsCalculator2TestMrr.test_mrr_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_57_0.py", line 46, in test_mrr_2
    res1, res2 = MetricsCalculator2.mrr(([0, 0, 0, 1], 4))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_57_0.py", line 16, in mrr
    mrr_list = [MetricsCalculator2.mrr(d) for d in data]
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_57_0.py", line 15, in mrr
    if isinstance(data[0], list):
                  ~~~~^^^
TypeError: 'int' object is not subscriptable

======================================================================
ERROR: test_mrr_3 (ClassEval_57_0.MetricsCalculator2TestMrr.test_mrr_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_57_0.py", line 51, in test_mrr_3
    res1, res2 = MetricsCalculator2.mrr([([1, 0, 1, 0], 4), ([0, 1, 0, 1], 4)])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_57_0.py", line 19, in mrr
    ranks = np.where(np.array(data[0])==1)[0] + 1
                     ^^^^^^^^^^^^^^^^^
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

======================================================================
ERROR: test_mrr_4 (ClassEval_57_0.MetricsCalculator2TestMrr.test_mrr_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_57_0.py", line 56, in test_mrr_4
    res1, res2 = MetricsCalculator2.mrr([([1, 1, 1, 0], 4), ([0, 0, 0, 1], 4)])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_57_0.py", line 19, in mrr
    ranks = np.where(np.array(data[0])==1)[0] + 1
                     ^^^^^^^^^^^^^^^^^
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

======================================================================
ERROR: test_mrr_5 (ClassEval_57_0.MetricsCalculator2TestMrr.test_mrr_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_57_0.py", line 61, in test_mrr_5
    res1, res2 = MetricsCalculator2.mrr([([1, 0, 1, 1], 4), ([0, 1, 0, 0], 4)])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_57_0.py", line 19, in mrr
    ranks = np.where(np.array(data[0])==1)[0] + 1
                     ^^^^^^^^^^^^^^^^^
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

======================================================================
ERROR: test_mrr_7 (ClassEval_57_0.MetricsCalculator2TestMrr.test_mrr_7)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_57_0.py", line 72, in test_mrr_7
    res1, res2 = MetricsCalculator2.mrr([])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_57_0.py", line 15, in mrr
    if isinstance(data[0], list):
                  ~~~~^^^
IndexError: list index out of range

======================================================================
ERROR: test_mrr_8 (ClassEval_57_0.MetricsCalculator2TestMrr.test_mrr_8)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_57_0.py", line 77, in test_mrr_8
    res1, res2 = MetricsCalculator2.mrr([([1, 0, 1, 1], 0), ([0, 1, 0, 0], 0)])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_57_0.py", line 19, in mrr
    ranks = np.where(np.array(data[0])==1)[0] + 1
                     ^^^^^^^^^^^^^^^^^
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

----------------------------------------------------------------------
Ran 8 tests in 0.002s

FAILED (errors=7)
EEEEE.EE
======================================================================
ERROR: test_map_1 (ClassEval_57_0.MetricsCalculator2TestMap.test_map_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_57_0.py", line 84, in test_map_1
    res1, res2 = MetricsCalculator2.map(([1, 0, 1, 0], 4))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_57_0.py", line 25, in map
    map_list = [MetricsCalculator2.map(d) for d in data]
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_57_0.py", line 32, in map
    precisions = [MetricsCalculator2.mrr((data[0][:rank], data[1]))[0] for rank in ranks]
                                          ~~~~~~~^^^^^^^
TypeError: 'int' object is not subscriptable

======================================================================
ERROR: test_map_2 (ClassEval_57_0.MetricsCalculator2TestMap.test_map_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_57_0.py", line 89, in test_map_2
    res1, res2 = MetricsCalculator2.map(([0, 0, 0, 1], 4))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_57_0.py", line 25, in map
    map_list = [MetricsCalculator2.map(d) for d in data]
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_57_0.py", line 24, in map
    if isinstance(data[0], list):
                  ~~~~^^^
TypeError: 'int' object is not subscriptable

======================================================================
ERROR: test_map_3 (ClassEval_57_0.MetricsCalculator2TestMap.test_map_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_57_0.py", line 94, in test_map_3
    res1, res2 = MetricsCalculator2.map([([1, 0, 1, 0], 4), ([0, 1, 0, 1], 4)])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_57_0.py", line 28, in map
    ranks = np.where(np.array(data[0])==1)[0] + 1
                     ^^^^^^^^^^^^^^^^^
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

======================================================================
ERROR: test_map_4 (ClassEval_57_0.MetricsCalculator2TestMap.test_map_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_57_0.py", line 99, in test_map_4
    res1, res2 = MetricsCalculator2.map([([1, 1, 1, 0], 4), ([0, 0, 0, 1], 4)])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_57_0.py", line 28, in map
    ranks = np.where(np.array(data[0])==1)[0] + 1
                     ^^^^^^^^^^^^^^^^^
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

======================================================================
ERROR: test_map_5 (ClassEval_57_0.MetricsCalculator2TestMap.test_map_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_57_0.py", line 104, in test_map_5
    res1, res2 = MetricsCalculator2.map([([1, 0, 1, 1], 4), ([0, 1, 0, 0], 4)])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_57_0.py", line 28, in map
    ranks = np.where(np.array(data[0])==1)[0] + 1
                     ^^^^^^^^^^^^^^^^^
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

======================================================================
ERROR: test_map_7 (ClassEval_57_0.MetricsCalculator2TestMap.test_map_7)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_57_0.py", line 115, in test_map_7
    res1, res2 = MetricsCalculator2.map([])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_57_0.py", line 24, in map
    if isinstance(data[0], list):
                  ~~~~^^^
IndexError: list index out of range

======================================================================
ERROR: test_map_8 (ClassEval_57_0.MetricsCalculator2TestMap.test_map_8)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_57_0.py", line 120, in test_map_8
    res1, res2 = MetricsCalculator2.map([([1, 0, 1, 1], 0), ([0, 1, 0, 0], 0)])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_57_0.py", line 28, in map
    ranks = np.where(np.array(data[0])==1)[0] + 1
                     ^^^^^^^^^^^^^^^^^
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

----------------------------------------------------------------------
Ran 8 tests in 0.002s

FAILED (errors=7)
EEEE
======================================================================
ERROR: test_metricscalculator2_1 (ClassEval_57_0.MetricsCalculator2Test.test_metricscalculator2_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_57_0.py", line 127, in test_metricscalculator2_1
    res1, res2 = MetricsCalculator2.mrr(([1, 0, 1, 0], 4))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_57_0.py", line 16, in mrr
    mrr_list = [MetricsCalculator2.mrr(d) for d in data]
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_57_0.py", line 15, in mrr
    if isinstance(data[0], list):
                  ~~~~^^^
TypeError: 'int' object is not subscriptable

======================================================================
ERROR: test_metricscalculator2_2 (ClassEval_57_0.MetricsCalculator2Test.test_metricscalculator2_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_57_0.py", line 132, in test_metricscalculator2_2
    res1, res2 = MetricsCalculator2.mrr([([1, 0, 1, 0], 4), ([0, 1, 0, 1], 4)])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_57_0.py", line 19, in mrr
    ranks = np.where(np.array(data[0])==1)[0] + 1
                     ^^^^^^^^^^^^^^^^^
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

======================================================================
ERROR: test_metricscalculator2_3 (ClassEval_57_0.MetricsCalculator2Test.test_metricscalculator2_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_57_0.py", line 137, in test_metricscalculator2_3
    res1, res2 = MetricsCalculator2.map(([1, 0, 1, 0], 4))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_57_0.py", line 25, in map
    map_list = [MetricsCalculator2.map(d) for d in data]
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_57_0.py", line 32, in map
    precisions = [MetricsCalculator2.mrr((data[0][:rank], data[1]))[0] for rank in ranks]
                                          ~~~~~~~^^^^^^^
TypeError: 'int' object is not subscriptable

======================================================================
ERROR: test_metricscalculator2_4 (ClassEval_57_0.MetricsCalculator2Test.test_metricscalculator2_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_57_0.py", line 142, in test_metricscalculator2_4
    res1, res2 = MetricsCalculator2.map([([1, 0, 1, 0], 4), ([0, 1, 0, 1], 4)])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_57_0.py", line 28, in map
    ranks = np.where(np.array(data[0])==1)[0] + 1
                     ^^^^^^^^^^^^^^^^^
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

----------------------------------------------------------------------
Ran 4 tests in 0.001s

FAILED (errors=4)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
EEEEE
======================================================================
ERROR: test_mode (ClassEval_81_0.Statistics3TestMode.test_mode)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_81_0.py", line 70, in test_mode
    self.assertEqual(statistics3.mode([1, 2, 3, 3]), [3])
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_81_0.py", line 20, in mode
    return list(stats.mode(data)[0])
           ^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'numpy.int64' object is not iterable

======================================================================
ERROR: test_mode_2 (ClassEval_81_0.Statistics3TestMode.test_mode_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_81_0.py", line 74, in test_mode_2
    self.assertEqual(statistics3.mode([1, 2, 3, 3, 4, 4]), [3, 4])
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_81_0.py", line 20, in mode
    return list(stats.mode(data)[0])
           ^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'numpy.int64' object is not iterable

======================================================================
ERROR: test_mode_3 (ClassEval_81_0.Statistics3TestMode.test_mode_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_81_0.py", line 78, in test_mode_3
    self.assertEqual(statistics3.mode([1, 2, 3, 3, 4, 4, 5]), [3, 4])
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_81_0.py", line 20, in mode
    return list(stats.mode(data)[0])
           ^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'numpy.int64' object is not iterable

======================================================================
ERROR: test_mode_4 (ClassEval_81_0.Statistics3TestMode.test_mode_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_81_0.py", line 82, in test_mode_4
    self.assertEqual(statistics3.mode([1, 2, 3, 3, 4, 4, 5, 5]), [3, 4, 5])
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_81_0.py", line 20, in mode
    return list(stats.mode(data)[0])
           ^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'numpy.int64' object is not iterable

======================================================================
ERROR: test_mode_5 (ClassEval_81_0.Statistics3TestMode.test_mode_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_81_0.py", line 86, in test_mode_5
    self.assertEqual(statistics3.mode([1, 2, 3, 3, 4, 4, 5, 5, 6]), [3, 4, 5])
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_81_0.py", line 20, in mode
    return list(stats.mode(data)[0])
           ^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'numpy.int64' object is not iterable

----------------------------------------------------------------------
Ran 5 tests in 0.004s

FAILED (errors=5)
...FF
======================================================================
FAIL: test_correlation_4 (ClassEval_81_0.Statistics3TestCorrelation.test_correlation_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_81_0.py", line 103, in test_correlation_4
    self.assertEqual(statistics3.correlation([1, 1,1], [2,2,2]), None)
AssertionError: nan != None

======================================================================
FAIL: test_correlation_5 (ClassEval_81_0.Statistics3TestCorrelation.test_correlation_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_81_0.py", line 107, in test_correlation_5
    self.assertEqual(statistics3.correlation([1, 1,1], [1,1,1]), None)
AssertionError: nan != None

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=2)
.E...
======================================================================
ERROR: test_mean_2 (ClassEval_81_0.Statistics3TestMean.test_mean_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_81_0.py", line 116, in test_mean_2
    self.assertEqual(statistics3.mean([]), None)
                     ^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_81_0.py", line 28, in mean
    return sum(data) / len(data)
           ~~~~~~~~~~^~~~~~~~~~~
ZeroDivisionError: division by zero

----------------------------------------------------------------------
Ran 5 tests in 0.000s

FAILED (errors=1)
.FFFF
======================================================================
FAIL: test_correlation_matrix_2 (ClassEval_81_0.Statistics3TestCorrelationMatrix.test_correlation_matrix_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_81_0.py", line 137, in test_correlation_matrix_2
    self.assertEqual(statistics3.correlation_matrix([[1, 2, 3], [4, 5, 6]]), [[1.0, 1.0, 1.0], [1.0, 1.0, 1.0], [1.0, 1.0, 1.0]])
AssertionError: Lists differ: [[1.0, 1.0], [1.0, 1.0]] != [[1.0, 1.0, 1.0], [1.0, 1.0, 1.0], [1.0, 1.0, 1.0]]

First differing element 0:
[1.0, 1.0]
[1.0, 1.0, 1.0]

Second list contains 1 additional elements.
First extra element 2:
[1.0, 1.0, 1.0]

- [[1.0, 1.0], [1.0, 1.0]]
+ [[1.0, 1.0, 1.0], [1.0, 1.0, 1.0], [1.0, 1.0, 1.0]]

======================================================================
FAIL: test_correlation_matrix_3 (ClassEval_81_0.Statistics3TestCorrelationMatrix.test_correlation_matrix_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_81_0.py", line 141, in test_correlation_matrix_3
    self.assertEqual(statistics3.correlation_matrix([[1, 2, 3]]), [[None, None, None], [None, None, None], [None, None, None]])
AssertionError: 1.0 != [[None, None, None], [None, None, None], [None, None, None]]

======================================================================
FAIL: test_correlation_matrix_4 (ClassEval_81_0.Statistics3TestCorrelationMatrix.test_correlation_matrix_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_81_0.py", line 145, in test_correlation_matrix_4
    self.assertEqual(statistics3.correlation_matrix([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11,12]]), [[1.0, 1.0, 1.0], [1.0, 1.0, 1.0], [1.0, 1.0, 1.0]])
AssertionError: Lists differ: [[1.0, 1.0, 1.0, 1.0], [1.0, 1.0, 1.0, 1.0], [1.0, 1.0, [27 chars]1.0]] != [[1.0, 1.0, 1.0], [1.0, 1.0, 1.0], [1.0, 1.0, 1.0]]

First differing element 0:
[1.0, 1.0, 1.0, 1.0]
[1.0, 1.0, 1.0]

First list contains 1 additional elements.
First extra element 3:
[1.0, 1.0, 1.0, 1.0]

+ [[1.0, 1.0, 1.0], [1.0, 1.0, 1.0], [1.0, 1.0, 1.0]]
- [[1.0, 1.0, 1.0, 1.0],
-  [1.0, 1.0, 1.0, 1.0],
-  [1.0, 1.0, 1.0, 1.0],
-  [1.0, 1.0, 1.0, 1.0]]

======================================================================
FAIL: test_correlation_matrix_5 (ClassEval_81_0.Statistics3TestCorrelationMatrix.test_correlation_matrix_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_81_0.py", line 149, in test_correlation_matrix_5
    self.assertEqual(statistics3.correlation_matrix([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11,12], [13, 14, 15]]), [[1.0, 1.0, 1.0], [1.0, 1.0, 1.0], [1.0, 1.0, 1.0]])
AssertionError: Lists differ: [[1.0, 1.0, 1.0, 1.0, 1.0], [1.0, 1.0, 1.0, 1.0, 1.0], [[74 chars]1.0]] != [[1.0, 1.0, 1.0], [1.0, 1.0, 1.0], [1.0, 1.0, 1.0]]

First differing element 0:
[1.0, 1.0, 1.0, 1.0, 1.0]
[1.0, 1.0, 1.0]

First list contains 2 additional elements.
First extra element 3:
[1.0, 1.0, 1.0, 1.0, 1.0]

+ [[1.0, 1.0, 1.0], [1.0, 1.0, 1.0], [1.0, 1.0, 1.0]]
- [[1.0, 1.0, 1.0, 1.0, 1.0],
-  [1.0, 1.0, 1.0, 1.0, 1.0],
-  [1.0, 1.0, 1.0, 1.0, 1.0],
-  [1.0, 1.0, 1.0, 1.0, 1.0],
-  [1.0, 1.0, 1.0, 1.0, 1.0]]

----------------------------------------------------------------------
Ran 5 tests in 0.002s

FAILED (failures=4)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.001s

OK
.FF.F
======================================================================
FAIL: test_z_score_2 (ClassEval_81_0.Statistics3TestZScore.test_z_score_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_81_0.py", line 180, in test_z_score_2
    self.assertEqual(statistics3.z_score([1, 1, 1, 1]), None)
AssertionError: [nan, nan, nan, nan] != None

======================================================================
FAIL: test_z_score_3 (ClassEval_81_0.Statistics3TestZScore.test_z_score_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_81_0.py", line 184, in test_z_score_3
    self.assertEqual(statistics3.z_score([1]),None)
AssertionError: [nan] != None

======================================================================
FAIL: test_z_score_5 (ClassEval_81_0.Statistics3TestZScore.test_z_score_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_81_0.py", line 192, in test_z_score_5
    self.assertEqual(statistics3.z_score([1, 1, 1, 1, 1]), None)
AssertionError: [nan, nan, nan, nan, nan] != None

----------------------------------------------------------------------
Ran 5 tests in 0.002s

FAILED (failures=3)
E
======================================================================
ERROR: test_main (ClassEval_81_0.Statistics3TestMain.test_main)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_81_0.py", line 199, in test_main
    self.assertEqual(statistics3.mode([1, 2, 3, 3]), [3])
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_81_0.py", line 20, in mode
    return list(stats.mode(data)[0])
           ^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'numpy.int64' object is not iterable

----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (errors=1)
F..F.
======================================================================
FAIL: test_cos_1 (ClassEval_88_0.TriCalculatorTestCos.test_cos_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_88_0.py", line 69, in test_cos_1
    self.assertEqual(tricalculator.cos(60), 0.5)
AssertionError: 0.5000000000000001 != 0.5

======================================================================
FAIL: test_cos_4 (ClassEval_88_0.TriCalculatorTestCos.test_cos_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_88_0.py", line 81, in test_cos_4
    self.assertEqual(tricalculator.cos(90), 0.0)
AssertionError: 4.2539467343847745e-17 != 0.0

----------------------------------------------------------------------
Ran 5 tests in 0.002s

FAILED (failures=2)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
FFF.F
======================================================================
FAIL: test_taylor_1 (ClassEval_88_0.TriCalculatorTestTaylor.test_taylor_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_88_0.py", line 113, in test_taylor_1
    self.assertAlmostEqual(tricalculator.taylor(60, 50), 0.5)
AssertionError: -5.173908478048577e+19 != 0.5 within 7 places (5.173908478048577e+19 difference)

======================================================================
FAIL: test_taylor_2 (ClassEval_88_0.TriCalculatorTestTaylor.test_taylor_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_88_0.py", line 117, in test_taylor_2
    self.assertAlmostEqual(tricalculator.taylor(30, 50), 0.8660254037844386)
AssertionError: 0.15438458220655596 != 0.8660254037844386 within 7 places (0.7116408215778827 difference)

======================================================================
FAIL: test_taylor_3 (ClassEval_88_0.TriCalculatorTestTaylor.test_taylor_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_88_0.py", line 121, in test_taylor_3
    self.assertAlmostEqual(tricalculator.taylor(90, 50), 0.0)
AssertionError: -1.5810564435591132e+37 != 0.0 within 7 places (1.5810564435591132e+37 difference)

======================================================================
FAIL: test_taylor_5 (ClassEval_88_0.TriCalculatorTestTaylor.test_taylor_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_88_0.py", line 129, in test_taylor_5
    self.assertAlmostEqual(tricalculator.taylor(45, 50), 0.7071067811865475)
AssertionError: -18743817.76763372 != 0.7071067811865475 within 7 places (18743818.4747405 difference)

----------------------------------------------------------------------
Ran 5 tests in 0.002s

FAILED (failures=4)
..F..
======================================================================
FAIL: test_sin_3 (ClassEval_88_0.TriCalculatorTestSin.test_sin_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_88_0.py", line 143, in test_sin_3
    self.assertEqual(tricalculator.sin(0), 0.0)
AssertionError: 4.2539467343847745e-17 != 0.0

----------------------------------------------------------------------
Ran 5 tests in 0.002s

FAILED (failures=1)
.F..F
======================================================================
FAIL: test_tan_2 (ClassEval_88_0.TriCalculatorTestTan.test_tan_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_88_0.py", line 161, in test_tan_2
    self.assertEqual(tricalculator.tan(90), False)
AssertionError: 2.350758160455962e+16 != False

======================================================================
FAIL: test_tan_5 (ClassEval_88_0.TriCalculatorTestTan.test_tan_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_88_0.py", line 173, in test_tan_5
    self.assertEqual(tricalculator.tan(0), 0.0)
AssertionError: 4.2539467343847745e-17 != 0.0

----------------------------------------------------------------------
Ran 5 tests in 0.004s

FAILED (failures=2)
F
======================================================================
FAIL: test_tricalculator (ClassEval_88_0.TriCalculatorTest.test_tricalculator)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_88_0.py", line 179, in test_tricalculator
    self.assertEqual(tricalculator.cos(60), 0.5)
AssertionError: 0.5000000000000001 != 0.5

----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (failures=1)
