.....
----------------------------------------------------------------------
Ran 5 tests in 0.002s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.003s

OK
FFFFE
======================================================================
ERROR: test_process_csv_data_5 (ClassEval_26_0.CSVProcessorTestProcessCSVData.test_process_csv_data_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_26_0.py", line 279, in test_process_csv_data_5
    self.assertEqual(1, csvProcessor.process_csv_data(4, self.file))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_26_0.py", line 68, in process_csv_data
    new_title = [title[N]]
                 ~~~~~^^^
IndexError: list index out of range

======================================================================
FAIL: test_process_csv_data_1 (ClassEval_26_0.CSVProcessorTestProcessCSVData.test_process_csv_data_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_26_0.py", line 242, in test_process_csv_data_1
    self.assertEqual(read_title, title)
AssertionError: Lists differ: ['a'] != ['a', 'b', 'c', 'd']

Second list contains 3 additional elements.
First extra element 1:
'b'

- ['a']
+ ['a', 'b', 'c', 'd']

======================================================================
FAIL: test_process_csv_data_2 (ClassEval_26_0.CSVProcessorTestProcessCSVData.test_process_csv_data_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_26_0.py", line 252, in test_process_csv_data_2
    self.assertEqual(read_title, title)
AssertionError: Lists differ: ['b'] != ['a', 'b', 'c', 'd']

First differing element 0:
'b'
'a'

Second list contains 3 additional elements.
First extra element 1:
'b'

- ['b']
+ ['a', 'b', 'c', 'd']

======================================================================
FAIL: test_process_csv_data_3 (ClassEval_26_0.CSVProcessorTestProcessCSVData.test_process_csv_data_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_26_0.py", line 262, in test_process_csv_data_3
    self.assertEqual(read_title, title)
AssertionError: Lists differ: ['c'] != ['a', 'b', 'c', 'd']

First differing element 0:
'c'
'a'

Second list contains 3 additional elements.
First extra element 1:
'b'

- ['c']
+ ['a', 'b', 'c', 'd']

======================================================================
FAIL: test_process_csv_data_4 (ClassEval_26_0.CSVProcessorTestProcessCSVData.test_process_csv_data_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_26_0.py", line 272, in test_process_csv_data_4
    self.assertEqual(read_title, title)
AssertionError: Lists differ: ['d'] != ['a', 'b', 'c', 'd']

First differing element 0:
'd'
'a'

Second list contains 3 additional elements.
First extra element 1:
'b'

- ['d']
+ ['a', 'b', 'c', 'd']

----------------------------------------------------------------------
Ran 5 tests in 0.005s

FAILED (failures=4, errors=1)
F
======================================================================
FAIL: test_main (ClassEval_26_0.CSVProcessorTestMain.test_main)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_26_0.py", line 309, in test_main
    self.assertEqual(read_title, title)
AssertionError: Lists differ: ['a'] != ['a', 'b', 'c', 'd']

Second list contains 3 additional elements.
First extra element 1:
'b'

- ['a']
+ ['a', 'b', 'c', 'd']

----------------------------------------------------------------------
Ran 1 test in 0.002s

FAILED (failures=1)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.002s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.003s

OK
FFFFE
======================================================================
ERROR: test_process_csv_data_5 (ClassEval_26_1.CSVProcessorTestProcessCSVData.test_process_csv_data_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_26_1.py", line 279, in test_process_csv_data_5
    self.assertEqual(1, csvProcessor.process_csv_data(4, self.file))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_26_1.py", line 69, in process_csv_data
    new_title = [title[N]]
                 ~~~~~^^^
IndexError: list index out of range

======================================================================
FAIL: test_process_csv_data_1 (ClassEval_26_1.CSVProcessorTestProcessCSVData.test_process_csv_data_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_26_1.py", line 242, in test_process_csv_data_1
    self.assertEqual(read_title, title)
AssertionError: Lists differ: ['a'] != ['a', 'b', 'c', 'd']

Second list contains 3 additional elements.
First extra element 1:
'b'

- ['a']
+ ['a', 'b', 'c', 'd']

======================================================================
FAIL: test_process_csv_data_2 (ClassEval_26_1.CSVProcessorTestProcessCSVData.test_process_csv_data_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_26_1.py", line 252, in test_process_csv_data_2
    self.assertEqual(read_title, title)
AssertionError: Lists differ: ['b'] != ['a', 'b', 'c', 'd']

First differing element 0:
'b'
'a'

Second list contains 3 additional elements.
First extra element 1:
'b'

- ['b']
+ ['a', 'b', 'c', 'd']

======================================================================
FAIL: test_process_csv_data_3 (ClassEval_26_1.CSVProcessorTestProcessCSVData.test_process_csv_data_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_26_1.py", line 262, in test_process_csv_data_3
    self.assertEqual(read_title, title)
AssertionError: Lists differ: ['c'] != ['a', 'b', 'c', 'd']

First differing element 0:
'c'
'a'

Second list contains 3 additional elements.
First extra element 1:
'b'

- ['c']
+ ['a', 'b', 'c', 'd']

======================================================================
FAIL: test_process_csv_data_4 (ClassEval_26_1.CSVProcessorTestProcessCSVData.test_process_csv_data_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_26_1.py", line 272, in test_process_csv_data_4
    self.assertEqual(read_title, title)
AssertionError: Lists differ: ['d'] != ['a', 'b', 'c', 'd']

First differing element 0:
'd'
'a'

Second list contains 3 additional elements.
First extra element 1:
'b'

- ['d']
+ ['a', 'b', 'c', 'd']

----------------------------------------------------------------------
Ran 5 tests in 0.007s

FAILED (failures=4, errors=1)
F
======================================================================
FAIL: test_main (ClassEval_26_1.CSVProcessorTestMain.test_main)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_26_1.py", line 309, in test_main
    self.assertEqual(read_title, title)
AssertionError: Lists differ: ['a'] != ['a', 'b', 'c', 'd']

Second list contains 3 additional elements.
First extra element 1:
'b'

- ['a']
+ ['a', 'b', 'c', 'd']

----------------------------------------------------------------------
Ran 1 test in 0.002s

FAILED (failures=1)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.002s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.004s

OK
FFFFE
======================================================================
ERROR: test_process_csv_data_5 (ClassEval_26_2.CSVProcessorTestProcessCSVData.test_process_csv_data_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_26_2.py", line 287, in test_process_csv_data_5
    self.assertEqual(1, csvProcessor.process_csv_data(4, self.file))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_26_2.py", line 69, in process_csv_data
    new_title = [title[N]]
                 ~~~~~^^^
IndexError: list index out of range

======================================================================
FAIL: test_process_csv_data_1 (ClassEval_26_2.CSVProcessorTestProcessCSVData.test_process_csv_data_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_26_2.py", line 250, in test_process_csv_data_1
    self.assertEqual(read_title, title)
AssertionError: Lists differ: ['a'] != ['a', 'b', 'c', 'd']

Second list contains 3 additional elements.
First extra element 1:
'b'

- ['a']
+ ['a', 'b', 'c', 'd']

======================================================================
FAIL: test_process_csv_data_2 (ClassEval_26_2.CSVProcessorTestProcessCSVData.test_process_csv_data_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_26_2.py", line 260, in test_process_csv_data_2
    self.assertEqual(read_title, title)
AssertionError: Lists differ: ['b'] != ['a', 'b', 'c', 'd']

First differing element 0:
'b'
'a'

Second list contains 3 additional elements.
First extra element 1:
'b'

- ['b']
+ ['a', 'b', 'c', 'd']

======================================================================
FAIL: test_process_csv_data_3 (ClassEval_26_2.CSVProcessorTestProcessCSVData.test_process_csv_data_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_26_2.py", line 270, in test_process_csv_data_3
    self.assertEqual(read_title, title)
AssertionError: Lists differ: ['c'] != ['a', 'b', 'c', 'd']

First differing element 0:
'c'
'a'

Second list contains 3 additional elements.
First extra element 1:
'b'

- ['c']
+ ['a', 'b', 'c', 'd']

======================================================================
FAIL: test_process_csv_data_4 (ClassEval_26_2.CSVProcessorTestProcessCSVData.test_process_csv_data_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_26_2.py", line 280, in test_process_csv_data_4
    self.assertEqual(read_title, title)
AssertionError: Lists differ: ['d'] != ['a', 'b', 'c', 'd']

First differing element 0:
'd'
'a'

Second list contains 3 additional elements.
First extra element 1:
'b'

- ['d']
+ ['a', 'b', 'c', 'd']

----------------------------------------------------------------------
Ran 5 tests in 0.006s

FAILED (failures=4, errors=1)
F
======================================================================
FAIL: test_main (ClassEval_26_2.CSVProcessorTestMain.test_main)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_26_2.py", line 317, in test_main
    self.assertEqual(read_title, title)
AssertionError: Lists differ: ['a'] != ['a', 'b', 'c', 'd']

Second list contains 3 additional elements.
First extra element 1:
'b'

- ['a']
+ ['a', 'b', 'c', 'd']

----------------------------------------------------------------------
Ran 1 test in 0.002s

FAILED (failures=1)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.002s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.003s

OK
FFFFE
======================================================================
ERROR: test_process_csv_data_5 (ClassEval_26_3.CSVProcessorTestProcessCSVData.test_process_csv_data_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_26_3.py", line 292, in test_process_csv_data_5
    self.assertEqual(1, csvProcessor.process_csv_data(4, self.file))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_26_3.py", line 72, in process_csv_data
    new_title = [title[N]]
                 ~~~~~^^^
IndexError: list index out of range

======================================================================
FAIL: test_process_csv_data_1 (ClassEval_26_3.CSVProcessorTestProcessCSVData.test_process_csv_data_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_26_3.py", line 255, in test_process_csv_data_1
    self.assertEqual(read_title, title)
AssertionError: Lists differ: ['a'] != ['a', 'b', 'c', 'd']

Second list contains 3 additional elements.
First extra element 1:
'b'

- ['a']
+ ['a', 'b', 'c', 'd']

======================================================================
FAIL: test_process_csv_data_2 (ClassEval_26_3.CSVProcessorTestProcessCSVData.test_process_csv_data_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_26_3.py", line 265, in test_process_csv_data_2
    self.assertEqual(read_title, title)
AssertionError: Lists differ: ['b'] != ['a', 'b', 'c', 'd']

First differing element 0:
'b'
'a'

Second list contains 3 additional elements.
First extra element 1:
'b'

- ['b']
+ ['a', 'b', 'c', 'd']

======================================================================
FAIL: test_process_csv_data_3 (ClassEval_26_3.CSVProcessorTestProcessCSVData.test_process_csv_data_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_26_3.py", line 275, in test_process_csv_data_3
    self.assertEqual(read_title, title)
AssertionError: Lists differ: ['c'] != ['a', 'b', 'c', 'd']

First differing element 0:
'c'
'a'

Second list contains 3 additional elements.
First extra element 1:
'b'

- ['c']
+ ['a', 'b', 'c', 'd']

======================================================================
FAIL: test_process_csv_data_4 (ClassEval_26_3.CSVProcessorTestProcessCSVData.test_process_csv_data_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_26_3.py", line 285, in test_process_csv_data_4
    self.assertEqual(read_title, title)
AssertionError: Lists differ: ['d'] != ['a', 'b', 'c', 'd']

First differing element 0:
'd'
'a'

Second list contains 3 additional elements.
First extra element 1:
'b'

- ['d']
+ ['a', 'b', 'c', 'd']

----------------------------------------------------------------------
Ran 5 tests in 0.006s

FAILED (failures=4, errors=1)
F
======================================================================
FAIL: test_main (ClassEval_26_3.CSVProcessorTestMain.test_main)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_26_3.py", line 322, in test_main
    self.assertEqual(read_title, title)
AssertionError: Lists differ: ['a'] != ['a', 'b', 'c', 'd']

Second list contains 3 additional elements.
First extra element 1:
'b'

- ['a']
+ ['a', 'b', 'c', 'd']

----------------------------------------------------------------------
Ran 1 test in 0.002s

FAILED (failures=1)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.003s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.005s

OK
FFFFE
======================================================================
ERROR: test_process_csv_data_5 (ClassEval_26_4.CSVProcessorTestProcessCSVData.test_process_csv_data_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_26_4.py", line 295, in test_process_csv_data_5
    self.assertEqual(1, csvProcessor.process_csv_data(4, self.file))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_26_4.py", line 72, in process_csv_data
    new_title = [title[N]]
                 ~~~~~^^^
IndexError: list index out of range

======================================================================
FAIL: test_process_csv_data_1 (ClassEval_26_4.CSVProcessorTestProcessCSVData.test_process_csv_data_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_26_4.py", line 258, in test_process_csv_data_1
    self.assertEqual(read_title, title)
AssertionError: Lists differ: ['a'] != ['a', 'b', 'c', 'd']

Second list contains 3 additional elements.
First extra element 1:
'b'

- ['a']
+ ['a', 'b', 'c', 'd']

======================================================================
FAIL: test_process_csv_data_2 (ClassEval_26_4.CSVProcessorTestProcessCSVData.test_process_csv_data_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_26_4.py", line 268, in test_process_csv_data_2
    self.assertEqual(read_title, title)
AssertionError: Lists differ: ['b'] != ['a', 'b', 'c', 'd']

First differing element 0:
'b'
'a'

Second list contains 3 additional elements.
First extra element 1:
'b'

- ['b']
+ ['a', 'b', 'c', 'd']

======================================================================
FAIL: test_process_csv_data_3 (ClassEval_26_4.CSVProcessorTestProcessCSVData.test_process_csv_data_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_26_4.py", line 278, in test_process_csv_data_3
    self.assertEqual(read_title, title)
AssertionError: Lists differ: ['c'] != ['a', 'b', 'c', 'd']

First differing element 0:
'c'
'a'

Second list contains 3 additional elements.
First extra element 1:
'b'

- ['c']
+ ['a', 'b', 'c', 'd']

======================================================================
FAIL: test_process_csv_data_4 (ClassEval_26_4.CSVProcessorTestProcessCSVData.test_process_csv_data_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_26_4.py", line 288, in test_process_csv_data_4
    self.assertEqual(read_title, title)
AssertionError: Lists differ: ['d'] != ['a', 'b', 'c', 'd']

First differing element 0:
'd'
'a'

Second list contains 3 additional elements.
First extra element 1:
'b'

- ['d']
+ ['a', 'b', 'c', 'd']

----------------------------------------------------------------------
Ran 5 tests in 0.006s

FAILED (failures=4, errors=1)
F
======================================================================
FAIL: test_main (ClassEval_26_4.CSVProcessorTestMain.test_main)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_26_4.py", line 325, in test_main
    self.assertEqual(read_title, title)
AssertionError: Lists differ: ['a'] != ['a', 'b', 'c', 'd']

Second list contains 3 additional elements.
First extra element 1:
'b'

- ['a']
+ ['a', 'b', 'c', 'd']

----------------------------------------------------------------------
Ran 1 test in 0.002s

FAILED (failures=1)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.038s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.011s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.005s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.007s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.007s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.002s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.005s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.014s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.007s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.007s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.011s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.003s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.007s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.012s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.008s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.007s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.008s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.003s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.006s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.009s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.005s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.005s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.007s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.002s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.006s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.011s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.006s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.006s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.011s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.003s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.002s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.005s

OK
..F..
======================================================================
FAIL: test_process_json_3 (ClassEval_50_0.JSONProcessorTestProcessJsonExistingKey.test_process_json_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_50_0.py", line 255, in test_process_json_3
    self.assertEqual(self.processor.process_json(self.file_path, remove_key), 0)
AssertionError: -1 != 0

----------------------------------------------------------------------
Ran 5 tests in 0.005s

FAILED (failures=1)
.
----------------------------------------------------------------------
Ran 1 test in 0.001s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.003s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.007s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.015s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.003s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.002s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.005s

OK
..F..
======================================================================
FAIL: test_process_json_3 (ClassEval_50_2.JSONProcessorTestProcessJsonExistingKey.test_process_json_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_50_2.py", line 228, in test_process_json_3
    self.assertEqual(self.processor.process_json(self.file_path, remove_key), 0)
AssertionError: -1 != 0

----------------------------------------------------------------------
Ran 5 tests in 0.004s

FAILED (failures=1)
.
----------------------------------------------------------------------
Ran 1 test in 0.001s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.001s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.004s

OK
..F..
======================================================================
FAIL: test_process_json_3 (ClassEval_50_3.JSONProcessorTestProcessJsonExistingKey.test_process_json_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_50_3.py", line 242, in test_process_json_3
    self.assertEqual(self.processor.process_json(self.file_path, remove_key), 0)
AssertionError: -1 != 0

----------------------------------------------------------------------
Ran 5 tests in 0.004s

FAILED (failures=1)
.
----------------------------------------------------------------------
Ran 1 test in 0.001s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.002s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.004s

OK
..F..
======================================================================
FAIL: test_process_json_3 (ClassEval_50_4.JSONProcessorTestProcessJsonExistingKey.test_process_json_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_50_4.py", line 248, in test_process_json_3
    self.assertEqual(self.processor.process_json(self.file_path, remove_key), 0)
AssertionError: -1 != 0

----------------------------------------------------------------------
Ran 5 tests in 0.004s

FAILED (failures=1)
.
----------------------------------------------------------------------
Ran 1 test in 0.001s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.007s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.006s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.004s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.004s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.001s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.008s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.007s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.004s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.004s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.001s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.006s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.006s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.004s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.004s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.001s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.007s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.006s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.004s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.003s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.001s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.006s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.006s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.004s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.006s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.001s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.007s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.008s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.007s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.004s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.002s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.006s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.009s

OK
FFFFF
======================================================================
FAIL: test_process_xml_data_1 (ClassEval_98_1.XMLProcessorTestProcessXmlData.test_process_xml_data_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_98_1.py", line 363, in test_process_xml_data_1
    self.assertEqual(lst[0].text, 'APPLE')
AssertionError: 'apple_processed' != 'APPLE'
- apple_processed
+ APPLE


======================================================================
FAIL: test_process_xml_data_2 (ClassEval_98_1.XMLProcessorTestProcessXmlData.test_process_xml_data_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_98_1.py", line 388, in test_process_xml_data_2
    self.assertEqual(lst[0].text, 'APPLE')
AssertionError: 'apple_processed' != 'APPLE'
- apple_processed
+ APPLE


======================================================================
FAIL: test_process_xml_data_3 (ClassEval_98_1.XMLProcessorTestProcessXmlData.test_process_xml_data_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_98_1.py", line 412, in test_process_xml_data_3
    self.assertEqual(lst[0].text, 'APPLE')
AssertionError: 'apple_processed' != 'APPLE'
- apple_processed
+ APPLE


======================================================================
FAIL: test_process_xml_data_4 (ClassEval_98_1.XMLProcessorTestProcessXmlData.test_process_xml_data_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_98_1.py", line 435, in test_process_xml_data_4
    self.assertEqual(lst[0].text, 'APPLE')
AssertionError: 'apple_processed' != 'APPLE'
- apple_processed
+ APPLE


======================================================================
FAIL: test_process_xml_data_5 (ClassEval_98_1.XMLProcessorTestProcessXmlData.test_process_xml_data_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_98_1.py", line 459, in test_process_xml_data_5
    self.assertEqual(lst[0].text, 'AAA')
AssertionError: 'aaa_processed' != 'AAA'
- aaa_processed
+ AAA


----------------------------------------------------------------------
Ran 5 tests in 0.007s

FAILED (failures=5)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.003s

OK
F
======================================================================
FAIL: test_XMLProcessor (ClassEval_98_1.XMLProcessorTest.test_XMLProcessor)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_98_1.py", line 597, in test_XMLProcessor
    self.assertEqual(lst[0].text, 'APPLE')
AssertionError: 'apple_processed' != 'APPLE'
- apple_processed
+ APPLE


----------------------------------------------------------------------
Ran 1 test in 0.002s

FAILED (failures=1)
.....E
======================================================================
ERROR: test_read_xml_6 (ClassEval_98_2.XMLProcessorTestReadXml.test_read_xml_6)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_98_2.py", line 205, in test_read_xml_6
    root = self.processor.read_xml()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_98_2.py", line 29, in read_xml
    tree = ET.parse(self.file_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/lib/python3.12/xml/etree/ElementTree.py", line 1204, in parse
    tree.parse(source, parser)
  File "/opt/miniconda3/lib/python3.12/xml/etree/ElementTree.py", line 558, in parse
    source = open(source, "rb")
             ^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: ''

----------------------------------------------------------------------
Ran 6 tests in 0.006s

FAILED (errors=1)
......
----------------------------------------------------------------------
Ran 6 tests in 0.007s

OK
FFFFF
======================================================================
FAIL: test_process_xml_data_1 (ClassEval_98_2.XMLProcessorTestProcessXmlData.test_process_xml_data_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_98_2.py", line 358, in test_process_xml_data_1
    self.assertEqual(lst[0].text, 'APPLE')
AssertionError: 'apple_processed' != 'APPLE'
- apple_processed
+ APPLE


======================================================================
FAIL: test_process_xml_data_2 (ClassEval_98_2.XMLProcessorTestProcessXmlData.test_process_xml_data_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_98_2.py", line 383, in test_process_xml_data_2
    self.assertEqual(lst[0].text, 'APPLE')
AssertionError: 'apple_processed' != 'APPLE'
- apple_processed
+ APPLE


======================================================================
FAIL: test_process_xml_data_3 (ClassEval_98_2.XMLProcessorTestProcessXmlData.test_process_xml_data_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_98_2.py", line 407, in test_process_xml_data_3
    self.assertEqual(lst[0].text, 'APPLE')
AssertionError: 'apple_processed' != 'APPLE'
- apple_processed
+ APPLE


======================================================================
FAIL: test_process_xml_data_4 (ClassEval_98_2.XMLProcessorTestProcessXmlData.test_process_xml_data_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_98_2.py", line 430, in test_process_xml_data_4
    self.assertEqual(lst[0].text, 'APPLE')
AssertionError: 'apple_processed' != 'APPLE'
- apple_processed
+ APPLE


======================================================================
FAIL: test_process_xml_data_5 (ClassEval_98_2.XMLProcessorTestProcessXmlData.test_process_xml_data_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_98_2.py", line 454, in test_process_xml_data_5
    self.assertEqual(lst[0].text, 'AAA')
AssertionError: 'aaa_processed' != 'AAA'
- aaa_processed
+ AAA


----------------------------------------------------------------------
Ran 5 tests in 0.007s

FAILED (failures=5)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.005s

OK
F
======================================================================
FAIL: test_XMLProcessor (ClassEval_98_2.XMLProcessorTest.test_XMLProcessor)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_98_2.py", line 592, in test_XMLProcessor
    self.assertEqual(lst[0].text, 'APPLE')
AssertionError: 'apple_processed' != 'APPLE'
- apple_processed
+ APPLE


----------------------------------------------------------------------
Ran 1 test in 0.002s

FAILED (failures=1)
.....E
======================================================================
ERROR: test_read_xml_6 (ClassEval_98_3.XMLProcessorTestReadXml.test_read_xml_6)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_98_3.py", line 211, in test_read_xml_6
    root = self.processor.read_xml()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_98_3.py", line 28, in read_xml
    tree = ET.parse(self.file_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/lib/python3.12/xml/etree/ElementTree.py", line 1204, in parse
    tree.parse(source, parser)
  File "/opt/miniconda3/lib/python3.12/xml/etree/ElementTree.py", line 558, in parse
    source = open(source, "rb")
             ^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: ''

----------------------------------------------------------------------
Ran 6 tests in 0.007s

FAILED (errors=1)
......
----------------------------------------------------------------------
Ran 6 tests in 0.009s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.008s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.004s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.003s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.007s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.008s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.006s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.004s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.003s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.008s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.009s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.010s

OK
FFFFF.
======================================================================
FAIL: test_create_zip_file_1 (ClassEval_99_0.ZipFileProcessorTestCreateZipFile.test_create_zip_file_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_99_0.py", line 492, in test_create_zip_file_1
    self.assertTrue(success)
AssertionError: False is not true

======================================================================
FAIL: test_create_zip_file_2 (ClassEval_99_0.ZipFileProcessorTestCreateZipFile.test_create_zip_file_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_99_0.py", line 515, in test_create_zip_file_2
    self.assertTrue(success)
AssertionError: False is not true

======================================================================
FAIL: test_create_zip_file_3 (ClassEval_99_0.ZipFileProcessorTestCreateZipFile.test_create_zip_file_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_99_0.py", line 538, in test_create_zip_file_3
    self.assertTrue(success)
AssertionError: False is not true

======================================================================
FAIL: test_create_zip_file_4 (ClassEval_99_0.ZipFileProcessorTestCreateZipFile.test_create_zip_file_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_99_0.py", line 561, in test_create_zip_file_4
    self.assertTrue(success)
AssertionError: False is not true

======================================================================
FAIL: test_create_zip_file_5 (ClassEval_99_0.ZipFileProcessorTestCreateZipFile.test_create_zip_file_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_99_0.py", line 583, in test_create_zip_file_5
    self.assertTrue(success)
AssertionError: False is not true

----------------------------------------------------------------------
Ran 6 tests in 0.007s

FAILED (failures=5)
F
======================================================================
FAIL: test_ZipFileProcessor (ClassEval_99_0.ZipFileProcessorTest.test_ZipFileProcessor)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_99_0.py", line 623, in test_ZipFileProcessor
    self.assertTrue(success)
AssertionError: False is not true

----------------------------------------------------------------------
Ran 1 test in 0.002s

FAILED (failures=1)
EEEEE.
======================================================================
ERROR: test_read_zip_file_1 (ClassEval_99_1.ZipFileProcessorTestReadZipFile.test_read_zip_file_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_99_1.py", line 136, in test_read_zip_file_1
    os.rmdir(test_folder)
OSError: [Errno 66] Directory not empty: 'test_folder'

======================================================================
ERROR: test_read_zip_file_2 (ClassEval_99_1.ZipFileProcessorTestReadZipFile.test_read_zip_file_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_99_1.py", line 158, in test_read_zip_file_2
    os.rmdir(test_folder)
OSError: [Errno 66] Directory not empty: 'test_folder'

======================================================================
ERROR: test_read_zip_file_3 (ClassEval_99_1.ZipFileProcessorTestReadZipFile.test_read_zip_file_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_99_1.py", line 180, in test_read_zip_file_3
    os.rmdir(test_folder)
OSError: [Errno 66] Directory not empty: 'test_folder'

======================================================================
ERROR: test_read_zip_file_4 (ClassEval_99_1.ZipFileProcessorTestReadZipFile.test_read_zip_file_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_99_1.py", line 202, in test_read_zip_file_4
    os.rmdir(test_folder)
OSError: [Errno 66] Directory not empty: 'test_folder'

======================================================================
ERROR: test_read_zip_file_5 (ClassEval_99_1.ZipFileProcessorTestReadZipFile.test_read_zip_file_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_99_1.py", line 226, in test_read_zip_file_5
    os.rmdir(test_folder)
OSError: [Errno 66] Directory not empty: 'test_folder'

----------------------------------------------------------------------
Ran 6 tests in 0.010s

FAILED (errors=5)
EEEE..
======================================================================
ERROR: test_extract_all_1 (ClassEval_99_1.ZipFileProcessorTestExtractAll.test_extract_all_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_99_1.py", line 257, in test_extract_all_1
    os.rmdir(test_folder)
OSError: [Errno 66] Directory not empty: 'test_folder'

======================================================================
ERROR: test_extract_all_2 (ClassEval_99_1.ZipFileProcessorTestExtractAll.test_extract_all_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_99_1.py", line 280, in test_extract_all_2
    os.rmdir(test_folder)
OSError: [Errno 66] Directory not empty: 'test_folder'

======================================================================
ERROR: test_extract_all_3 (ClassEval_99_1.ZipFileProcessorTestExtractAll.test_extract_all_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_99_1.py", line 303, in test_extract_all_3
    os.rmdir(test_folder)
OSError: [Errno 66] Directory not empty: 'test_folder'

======================================================================
ERROR: test_extract_all_4 (ClassEval_99_1.ZipFileProcessorTestExtractAll.test_extract_all_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_99_1.py", line 326, in test_extract_all_4
    os.rmdir(test_folder)
OSError: [Errno 66] Directory not empty: 'test_folder'

----------------------------------------------------------------------
Ran 6 tests in 0.010s

FAILED (errors=4)
......
----------------------------------------------------------------------
Ran 6 tests in 0.011s

OK
FFFFF.
======================================================================
FAIL: test_create_zip_file_1 (ClassEval_99_1.ZipFileProcessorTestCreateZipFile.test_create_zip_file_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_99_1.py", line 498, in test_create_zip_file_1
    self.assertTrue(success)
AssertionError: False is not true

======================================================================
FAIL: test_create_zip_file_2 (ClassEval_99_1.ZipFileProcessorTestCreateZipFile.test_create_zip_file_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_99_1.py", line 521, in test_create_zip_file_2
    self.assertTrue(success)
AssertionError: False is not true

======================================================================
FAIL: test_create_zip_file_3 (ClassEval_99_1.ZipFileProcessorTestCreateZipFile.test_create_zip_file_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_99_1.py", line 544, in test_create_zip_file_3
    self.assertTrue(success)
AssertionError: False is not true

======================================================================
FAIL: test_create_zip_file_4 (ClassEval_99_1.ZipFileProcessorTestCreateZipFile.test_create_zip_file_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_99_1.py", line 567, in test_create_zip_file_4
    self.assertTrue(success)
AssertionError: False is not true

======================================================================
FAIL: test_create_zip_file_5 (ClassEval_99_1.ZipFileProcessorTestCreateZipFile.test_create_zip_file_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_99_1.py", line 589, in test_create_zip_file_5
    self.assertTrue(success)
AssertionError: False is not true

----------------------------------------------------------------------
Ran 6 tests in 0.007s

FAILED (failures=5)
F
======================================================================
FAIL: test_ZipFileProcessor (ClassEval_99_1.ZipFileProcessorTest.test_ZipFileProcessor)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_99_1.py", line 629, in test_ZipFileProcessor
    self.assertTrue(success)
AssertionError: False is not true

----------------------------------------------------------------------
Ran 1 test in 0.002s

FAILED (failures=1)
EEEEE.
======================================================================
ERROR: test_read_zip_file_1 (ClassEval_99_2.ZipFileProcessorTestReadZipFile.test_read_zip_file_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_99_2.py", line 111, in test_read_zip_file_1
    os.rmdir(test_folder)
OSError: [Errno 66] Directory not empty: 'test_folder'

======================================================================
ERROR: test_read_zip_file_2 (ClassEval_99_2.ZipFileProcessorTestReadZipFile.test_read_zip_file_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_99_2.py", line 133, in test_read_zip_file_2
    os.rmdir(test_folder)
OSError: [Errno 66] Directory not empty: 'test_folder'

======================================================================
ERROR: test_read_zip_file_3 (ClassEval_99_2.ZipFileProcessorTestReadZipFile.test_read_zip_file_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_99_2.py", line 155, in test_read_zip_file_3
    os.rmdir(test_folder)
OSError: [Errno 66] Directory not empty: 'test_folder'

======================================================================
ERROR: test_read_zip_file_4 (ClassEval_99_2.ZipFileProcessorTestReadZipFile.test_read_zip_file_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_99_2.py", line 177, in test_read_zip_file_4
    os.rmdir(test_folder)
OSError: [Errno 66] Directory not empty: 'test_folder'

======================================================================
ERROR: test_read_zip_file_5 (ClassEval_99_2.ZipFileProcessorTestReadZipFile.test_read_zip_file_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_99_2.py", line 201, in test_read_zip_file_5
    os.rmdir(test_folder)
OSError: [Errno 66] Directory not empty: 'test_folder'

----------------------------------------------------------------------
Ran 6 tests in 0.009s

FAILED (errors=5)
EEEE..
======================================================================
ERROR: test_extract_all_1 (ClassEval_99_2.ZipFileProcessorTestExtractAll.test_extract_all_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_99_2.py", line 232, in test_extract_all_1
    os.rmdir(test_folder)
OSError: [Errno 66] Directory not empty: 'test_folder'

======================================================================
ERROR: test_extract_all_2 (ClassEval_99_2.ZipFileProcessorTestExtractAll.test_extract_all_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_99_2.py", line 255, in test_extract_all_2
    os.rmdir(test_folder)
OSError: [Errno 66] Directory not empty: 'test_folder'

======================================================================
ERROR: test_extract_all_3 (ClassEval_99_2.ZipFileProcessorTestExtractAll.test_extract_all_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_99_2.py", line 278, in test_extract_all_3
    os.rmdir(test_folder)
OSError: [Errno 66] Directory not empty: 'test_folder'

======================================================================
ERROR: test_extract_all_4 (ClassEval_99_2.ZipFileProcessorTestExtractAll.test_extract_all_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_99_2.py", line 301, in test_extract_all_4
    os.rmdir(test_folder)
OSError: [Errno 66] Directory not empty: 'test_folder'

----------------------------------------------------------------------
Ran 6 tests in 0.010s

FAILED (errors=4)
......
----------------------------------------------------------------------
Ran 6 tests in 0.010s

OK
.....F
======================================================================
FAIL: test_create_zip_file_6 (ClassEval_99_2.ZipFileProcessorTestCreateZipFile.test_create_zip_file_6)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_99_2.py", line 574, in test_create_zip_file_6
    self.assertFalse(success)
AssertionError: True is not false

----------------------------------------------------------------------
Ran 6 tests in 0.011s

FAILED (failures=1)
.
----------------------------------------------------------------------
Ran 1 test in 0.004s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.008s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.012s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.012s

OK
.....F
======================================================================
FAIL: test_create_zip_file_6 (ClassEval_99_3.ZipFileProcessorTestCreateZipFile.test_create_zip_file_6)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_99_3.py", line 592, in test_create_zip_file_6
    self.assertFalse(success)
AssertionError: True is not false

----------------------------------------------------------------------
Ran 6 tests in 0.010s

FAILED (failures=1)
.
----------------------------------------------------------------------
Ran 1 test in 0.005s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.009s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.011s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.011s

OK
.....F
======================================================================
FAIL: test_create_zip_file_6 (ClassEval_99_4.ZipFileProcessorTestCreateZipFile.test_create_zip_file_6)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_99_4.py", line 569, in test_create_zip_file_6
    self.assertFalse(success)
AssertionError: True is not false

----------------------------------------------------------------------
Ran 6 tests in 0.011s

FAILED (failures=1)
.
----------------------------------------------------------------------
Ran 1 test in 0.004s

OK
