FFFFF.FF
======================================================================
FAIL: test_filter_1 (ClassEval_0_0.AccessGatewayFilterTestFilter.test_filter_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_0_0.py", line 108, in test_filter_1
    self.assertTrue(res)
AssertionError: False is not true

======================================================================
FAIL: test_filter_2 (ClassEval_0_0.AccessGatewayFilterTestFilter.test_filter_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_0_0.py", line 114, in test_filter_2
    self.assertTrue(res)
AssertionError: False is not true

======================================================================
FAIL: test_filter_3 (ClassEval_0_0.AccessGatewayFilterTestFilter.test_filter_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_0_0.py", line 120, in test_filter_3
    self.assertTrue(res)
AssertionError: False is not true

======================================================================
FAIL: test_filter_4 (ClassEval_0_0.AccessGatewayFilterTestFilter.test_filter_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_0_0.py", line 126, in test_filter_4
    self.assertTrue(res)
AssertionError: False is not true

======================================================================
FAIL: test_filter_5 (ClassEval_0_0.AccessGatewayFilterTestFilter.test_filter_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_0_0.py", line 135, in test_filter_5
    self.assertTrue(res)
AssertionError: False is not true

======================================================================
FAIL: test_filter_7 (ClassEval_0_0.AccessGatewayFilterTestFilter.test_filter_7)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_0_0.py", line 153, in test_filter_7
    self.assertIsNone(res)
AssertionError: False is not None

======================================================================
FAIL: test_filter_8 (ClassEval_0_0.AccessGatewayFilterTestFilter.test_filter_8)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_0_0.py", line 162, in test_filter_8
    self.assertTrue(res)
AssertionError: False is not true

----------------------------------------------------------------------
Ran 8 tests in 0.004s

FAILED (failures=7)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
....F
======================================================================
FAIL: test_get_jwt_user_5 (ClassEval_0_0.AccessGatewayFilterTestGetJwtUser.test_get_jwt_user_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_0_0.py", line 231, in test_get_jwt_user_5
    self.assertIsNone(res)
AssertionError: {'name': 'user1'} is not None

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=1)
F
======================================================================
FAIL: test_AccessGatewayFilter (ClassEval_0_0.AccessGatewayFilterTest.test_AccessGatewayFilter)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_0_0.py", line 239, in test_AccessGatewayFilter
    self.assertTrue(res)
AssertionError: False is not true

----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (failures=1)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.001s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.001s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.E...
======================================================================
ERROR: test_get_course_average_2 (ClassEval_4_0.AssessmentSystemTestGetCourseAverage.test_get_course_average_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_4_0.py", line 297, in test_get_course_average_2
    self.assertEqual(assessment_system.get_course_average('Physics'), 85)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_4_0.py", line 82, in get_course_average
    return sum(scores) / len(scores)
           ^^^^^^^^^^^
TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (errors=1)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.........
----------------------------------------------------------------------
Ran 9 tests in 0.001s

OK
FFFFF
======================================================================
FAIL: test_display_1 (ClassEval_5_0.AutomaticGuitarSimulatorTestDisplay.test_display_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_5_0.py", line 109, in test_display_1
    self.assertEqual(str, "Normal Guitar Playing -- Chord: C, Play Tune: 53231323")
AssertionError: None != 'Normal Guitar Playing -- Chord: C, Play Tune: 53231323'

======================================================================
FAIL: test_display_2 (ClassEval_5_0.AutomaticGuitarSimulatorTestDisplay.test_display_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_5_0.py", line 115, in test_display_2
    self.assertEqual(str, "Normal Guitar Playing -- Chord: Em, Play Tune: 43231323")
AssertionError: None != 'Normal Guitar Playing -- Chord: Em, Play Tune: 43231323'

======================================================================
FAIL: test_display_3 (ClassEval_5_0.AutomaticGuitarSimulatorTestDisplay.test_display_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_5_0.py", line 121, in test_display_3
    self.assertEqual(str, "Normal Guitar Playing -- Chord: F, Play Tune: 43231323")
AssertionError: None != 'Normal Guitar Playing -- Chord: F, Play Tune: 43231323'

======================================================================
FAIL: test_display_4 (ClassEval_5_0.AutomaticGuitarSimulatorTestDisplay.test_display_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_5_0.py", line 127, in test_display_4
    self.assertEqual(str, "Normal Guitar Playing -- Chord: G, Play Tune: 63231323")
AssertionError: None != 'Normal Guitar Playing -- Chord: G, Play Tune: 63231323'

======================================================================
FAIL: test_display_5 (ClassEval_5_0.AutomaticGuitarSimulatorTestDisplay.test_display_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_5_0.py", line 132, in test_display_5
    self.assertEqual(str, "Normal Guitar Playing -- Chord: , Play Tune: ")
AssertionError: None != 'Normal Guitar Playing -- Chord: , Play Tune: '

----------------------------------------------------------------------
Ran 5 tests in 0.003s

FAILED (failures=5)
F
======================================================================
FAIL: test_AutomaticGuitarSimulator (ClassEval_5_0.AutomaticGuitarSimulatorTest.test_AutomaticGuitarSimulator)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_5_0.py", line 144, in test_AutomaticGuitarSimulator
    self.assertEqual(str, "Normal Guitar Playing -- Chord: C, Play Tune: 53231323")
AssertionError: None != 'Normal Guitar Playing -- Chord: C, Play Tune: 53231323'

----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (failures=1)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.001s

OK
..
----------------------------------------------------------------------
Ran 2 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.003s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.001s

OK
..
----------------------------------------------------------------------
Ran 2 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.001s

OK
FFFFF
======================================================================
FAIL: test_get_available_slots (ClassEval_17_0.CalendarTestGetAvailableSlots.test_get_available_slots)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_17_0.py", line 313, in test_get_available_slots
    self.assertEqual(calendar.get_available_slots(datetime(2023, 1, 1)),
AssertionError: Lists differ: [(dat[15 chars]2023, 1, 1, 23, 0), datetime.datetime(2023, 1, 1, 23, 59, 59))] != [(dat[15 chars]2023, 1, 1, 23, 0), datetime.datetime(2023, 1, 2, 0, 0))]

First differing element 0:
(date[13 chars](2023, 1, 1, 23, 0), datetime.datetime(2023, 1, 1, 23, 59, 59))
(date[13 chars](2023, 1, 1, 23, 0), datetime.datetime(2023, 1, 2, 0, 0))

+ [(datetime.datetime(2023, 1, 1, 23, 0), datetime.datetime(2023, 1, 2, 0, 0))]
- [(datetime.datetime(2023, 1, 1, 23, 0),
-   datetime.datetime(2023, 1, 1, 23, 59, 59))]

======================================================================
FAIL: test_get_available_slots_2 (ClassEval_17_0.CalendarTestGetAvailableSlots.test_get_available_slots_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_17_0.py", line 320, in test_get_available_slots_2
    self.assertEqual(len(calendar.get_available_slots(datetime(2023, 1, 1))), 23)
AssertionError: 2 != 23

======================================================================
FAIL: test_get_available_slots_3 (ClassEval_17_0.CalendarTestGetAvailableSlots.test_get_available_slots_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_17_0.py", line 326, in test_get_available_slots_3
    self.assertEqual(len(calendar.get_available_slots(datetime(2023, 1, 1))), 24)
AssertionError: 1 != 24

======================================================================
FAIL: test_get_available_slots_4 (ClassEval_17_0.CalendarTestGetAvailableSlots.test_get_available_slots_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_17_0.py", line 332, in test_get_available_slots_4
    self.assertEqual(len(calendar.get_available_slots(datetime(2023, 1, 1))), 24)
AssertionError: 1 != 24

======================================================================
FAIL: test_get_available_slots_5 (ClassEval_17_0.CalendarTestGetAvailableSlots.test_get_available_slots_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_17_0.py", line 338, in test_get_available_slots_5
    self.assertEqual(len(calendar.get_available_slots(datetime(2023, 1, 1))), 24)
AssertionError: 1 != 24

----------------------------------------------------------------------
Ran 5 tests in 0.002s

FAILED (failures=5)
....F
======================================================================
FAIL: test_get_upcoming_events_5 (ClassEval_17_0.CalendarTestGetUpcomingEvents.test_get_upcoming_events_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_17_0.py", line 373, in test_get_upcoming_events_5
    self.assertEqual(calendar.get_upcoming_events(1), [
AssertionError: Lists differ: [] != [{'date': datetime.datetime(2024, 1, 2, 0,[129 chars] 2'}]

Second list contains 1 additional elements.
First extra element 0:
{'date': datetime.datetime(2024, 1, 2, 0, 0), 'start_time': datetime.datetime(2024, 1, 2, 1, 0), 'end_time': datetime.datetime(2024, 1, 2, 2, 0), 'description': 'New Year 2'}

- []
+ [{'date': datetime.datetime(2024, 1, 2, 0, 0),
+   'description': 'New Year 2',
+   'end_time': datetime.datetime(2024, 1, 2, 2, 0),
+   'start_time': datetime.datetime(2024, 1, 2, 1, 0)}]

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=1)
F
======================================================================
FAIL: test_main (ClassEval_17_0.CalendarTestMain.test_main)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_17_0.py", line 395, in test_main
    self.assertEqual(calendar.get_available_slots(datetime(2023, 1, 1)),
AssertionError: Lists differ: [(dat[15 chars]2023, 1, 1, 23, 0), datetime.datetime(2023, 1, 1, 23, 59, 59))] != [(dat[15 chars]2023, 1, 1, 23, 0), datetime.datetime(2023, 1, 2, 0, 0))]

First differing element 0:
(date[13 chars](2023, 1, 1, 23, 0), datetime.datetime(2023, 1, 1, 23, 59, 59))
(date[13 chars](2023, 1, 1, 23, 0), datetime.datetime(2023, 1, 2, 0, 0))

+ [(datetime.datetime(2023, 1, 1, 23, 0), datetime.datetime(2023, 1, 2, 0, 0))]
- [(datetime.datetime(2023, 1, 1, 23, 0),
-   datetime.datetime(2023, 1, 1, 23, 59, 59))]

----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (failures=1)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
F....
======================================================================
FAIL: test_send_message (ClassEval_20_0.ChatTestSendMessage.test_send_message)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_20_0.py", line 166, in test_send_message
    self.assertEqual(chat.users, {'John': [{'sender': 'John', 'receiver': 'Mary', 'message': 'Hello', 'timestamp': timestamp}], 'Mary': [{'sender': 'John', 'receiver': 'Mary', 'message': 'Hello', 'timestamp': timestamp}]})
AssertionError: {'John': [], 'Mary': [{'sender': 'John', 'receiver'[62 chars]5'}]} != {'John': [{'sender': 'John', 'receiver': 'Mary', 'm[156 chars]5'}]}
- {'John': [],
+ {'John': [{'message': 'Hello',
+            'receiver': 'Mary',
+            'sender': 'John',
+            'timestamp': '2025-04-22 01:28:25'}],
   'Mary': [{'message': 'Hello',
             'receiver': 'Mary',
             'sender': 'John',
             'timestamp': '2025-04-22 01:28:25'}]}

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=1)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.001s

OK
FF
======================================================================
FAIL: test_main (ClassEval_20_0.ChatTestMain.test_main)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_20_0.py", line 234, in test_main
    self.assertEqual(chat.users, {'John': [{'sender': 'John', 'receiver': 'Mary', 'message': 'Hello', 'timestamp': timestamp}], 'Mary': [{'sender': 'John', 'receiver': 'Mary', 'message': 'Hello', 'timestamp': timestamp}]})
AssertionError: {'John': [], 'Mary': [{'sender': 'John', 'receiver'[62 chars]5'}]} != {'John': [{'sender': 'John', 'receiver': 'Mary', 'm[156 chars]5'}]}
- {'John': [],
+ {'John': [{'message': 'Hello',
+            'receiver': 'Mary',
+            'sender': 'John',
+            'timestamp': '2025-04-22 01:28:25'}],
   'Mary': [{'message': 'Hello',
             'receiver': 'Mary',
             'sender': 'John',
             'timestamp': '2025-04-22 01:28:25'}]}

======================================================================
FAIL: test_main_2 (ClassEval_20_0.ChatTestMain.test_main_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_20_0.py", line 249, in test_main_2
    self.assertEqual(chat.users, {'John': [{'sender': 'John', 'receiver': 'Mary', 'message': 'Hello', 'timestamp': timestamp}], 'Mary': [{'sender': 'John', 'receiver': 'Mary', 'message': 'Hello', 'timestamp': timestamp}]})
AssertionError: {'John': [], 'Mary': [{'sender': 'John', 'receiver'[62 chars]5'}]} != {'John': [{'sender': 'John', 'receiver': 'Mary', 'm[156 chars]5'}]}
- {'John': [],
+ {'John': [{'message': 'Hello',
+            'receiver': 'Mary',
+            'sender': 'John',
+            'timestamp': '2025-04-22 01:28:25'}],
   'Mary': [{'message': 'Hello',
             'receiver': 'Mary',
             'sender': 'John',
             'timestamp': '2025-04-22 01:28:25'}]}

----------------------------------------------------------------------
Ran 2 tests in 0.002s

FAILED (failures=2)
......
----------------------------------------------------------------------
Ran 6 tests in 0.000s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.005s

OK
..F...
======================================================================
FAIL: test_check_course_conflict_3 (ClassEval_21_0.ClassroomTestCheckCourseConflict.test_check_course_conflict_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_21_0.py", line 236, in test_check_course_conflict_3
    self.assertFalse(result)
AssertionError: True is not false

----------------------------------------------------------------------
Ran 6 tests in 0.001s

FAILED (failures=1)
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
...
----------------------------------------------------------------------
Ran 3 tests in 0.000s

OK
EEE
======================================================================
ERROR: test_register_class (ClassEval_22_0.ClassRegistrationSystemTestRegisterClass.test_register_class)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_22_0.py", line 107, in test_register_class
    self.assertEqual(self.registration_system.register_class(student_name="John", class_name="CS101"), ["CS101"])
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_22_0.py", line 41, in register_class
    raise ValueError("Student not registered")
ValueError: Student not registered

======================================================================
ERROR: test_register_class2 (ClassEval_22_0.ClassRegistrationSystemTestRegisterClass.test_register_class2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_22_0.py", line 110, in test_register_class2
    self.registration_system.register_class(student_name="John", class_name="CS101")
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_22_0.py", line 41, in register_class
    raise ValueError("Student not registered")
ValueError: Student not registered

======================================================================
ERROR: test_register_class3 (ClassEval_22_0.ClassRegistrationSystemTestRegisterClass.test_register_class3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_22_0.py", line 115, in test_register_class3
    self.registration_system.register_class(student_name="John", class_name="CS101")
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_22_0.py", line 41, in register_class
    raise ValueError("Student not registered")
ValueError: Student not registered

----------------------------------------------------------------------
Ran 3 tests in 0.001s

FAILED (errors=3)
....
----------------------------------------------------------------------
Ran 4 tests in 0.000s

OK
..F
======================================================================
FAIL: test_get_all_major3 (ClassEval_22_0.ClassRegistrationSystemTestGetMajor.test_get_all_major3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_22_0.py", line 199, in test_get_all_major3
    self.assertEqual(majors, ["Computer Science", "Mathematics", "Physics"])
AssertionError: Lists differ: ['Physics', 'Computer Science', 'Mathematics'] != ['Computer Science', 'Mathematics', 'Physics']

First differing element 0:
'Physics'
'Computer Science'

- ['Physics', 'Computer Science', 'Mathematics']
?  -----------

+ ['Computer Science', 'Mathematics', 'Physics']
?                                   +++++++++++


----------------------------------------------------------------------
Ran 3 tests in 0.001s

FAILED (failures=1)
..
----------------------------------------------------------------------
Ran 2 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.002s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.001s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.002s

OK
E
======================================================================
ERROR: test_set_cookies (ClassEval_25_0.CookiesUtilTestSetCookies.test_set_cookies)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_25_0.py", line 191, in test_set_cookies
    self.cookies_util.set_cookies(request)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'CookiesUtil' object has no attribute 'set_cookies'. Did you mean: 'get_cookies'?

----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (errors=1)
.
----------------------------------------------------------------------
Ran 1 test in 0.001s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.001s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.001s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.001s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.F...
======================================================================
FAIL: test_clear_inbox_2 (ClassEval_36_0.EmailClientTestClearInbox.test_clear_inbox_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_36_0.py", line 253, in test_clear_inbox_2
    self.assertEqual(receiver.inbox, [{'size': 10},{'size': 20},{'size': 15}])
AssertionError: Lists differ: [{'size': 15}] != [{'size': 10}, {'size': 20}, {'size': 15}]

First differing element 0:
{'size': 15}
{'size': 10}

Second list contains 2 additional elements.
First extra element 1:
{'size': 20}

- [{'size': 15}]
+ [{'size': 10}, {'size': 20}, {'size': 15}]

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=1)
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
FFFFF
======================================================================
FAIL: test_calculate_calorie_intake (ClassEval_40_0.FitnessTrackerTestCaculateCalorieIntake.test_calculate_calorie_intake)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_40_0.py", line 130, in test_calculate_calorie_intake
    self.assertEqual(fitnessTracker.calculate_calorie_intake(), 630.3499999999999)
AssertionError: 2189.6 != 630.3499999999999

======================================================================
FAIL: test_calculate_calorie_intake_2 (ClassEval_40_0.FitnessTrackerTestCaculateCalorieIntake.test_calculate_calorie_intake_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_40_0.py", line 134, in test_calculate_calorie_intake_2
    self.assertEqual(fitnessTracker.calculate_calorie_intake(), 647.6999999999999)
AssertionError: 1924.8 != 647.6999999999999

======================================================================
FAIL: test_calculate_calorie_intake_3 (ClassEval_40_0.FitnessTrackerTestCaculateCalorieIntake.test_calculate_calorie_intake_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_40_0.py", line 138, in test_calculate_calorie_intake_3
    self.assertEqual(fitnessTracker.calculate_calorie_intake(), 697.2)
AssertionError: 2400.0 != 697.2

======================================================================
FAIL: test_calculate_calorie_intake_4 (ClassEval_40_0.FitnessTrackerTestCaculateCalorieIntake.test_calculate_calorie_intake_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_40_0.py", line 142, in test_calculate_calorie_intake_4
    self.assertEqual(fitnessTracker.calculate_calorie_intake(), 708.05)
AssertionError: 2198.0 != 708.05

======================================================================
FAIL: test_calculate_calorie_intake_5 (ClassEval_40_0.FitnessTrackerTestCaculateCalorieIntake.test_calculate_calorie_intake_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_40_0.py", line 146, in test_calculate_calorie_intake_5
    self.assertEqual(fitnessTracker.calculate_calorie_intake(), 786.9)
AssertionError: 2064.0 != 786.9

----------------------------------------------------------------------
Ran 5 tests in 0.002s

FAILED (failures=5)
F
======================================================================
FAIL: test_main (ClassEval_40_0.FitnessTrackerTestMain.test_main)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_40_0.py", line 154, in test_main
    self.assertEqual(fitnessTracker.calculate_calorie_intake(), 862.75)
AssertionError: 2422.0 != 862.75

----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (failures=1)
......
----------------------------------------------------------------------
Ran 6 tests in 0.000s

OK
...F..
======================================================================
FAIL: test_check_in_4 (ClassEval_42_0.HotelTestCheckIn.test_check_in_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_42_0.py", line 211, in test_check_in_4
    self.assertEqual(self.hotel.booked_rooms, {'double': {}, 'single': {'guest 1': 2}})
AssertionError: {'single': {'guest 1': 2}} != {'double': {}, 'single': {'guest 1': 2}}
- {'single': {'guest 1': 2}}
+ {'double': {}, 'single': {'guest 1': 2}}
?  ++++++++++++++


----------------------------------------------------------------------
Ran 6 tests in 0.001s

FAILED (failures=1)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
F
======================================================================
FAIL: test_main (ClassEval_42_0.HotelTestMain.test_main)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_42_0.py", line 293, in test_main
    self.assertEqual(self.hotel.booked_rooms, {'single': {}})
AssertionError: {} != {'single': {}}
- {}
+ {'single': {}}

----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (failures=1)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....F
======================================================================
FAIL: test_update_employee_6 (ClassEval_43_0.HRManagementSystemTestUpdateEmployee.test_update_employee_6)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_43_0.py", line 230, in test_update_employee_6
    self.assertEqual(hr_system.update_employee(1, {'Name': 'John', 'position': 'Manager', 'department': 'Sales', 'salary': 20000}), False)
AssertionError: True != False

----------------------------------------------------------------------
Ran 6 tests in 0.001s

FAILED (failures=1)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
..
----------------------------------------------------------------------
Ran 2 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
EEEEE
======================================================================
ERROR: test_matches_requirements (ClassEval_49_0.JobMarketplaceTestMatchesRequirements.test_matches_requirements)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_49_0.py", line 343, in test_matches_requirements
    self.assertEqual(jobMarketplace.matches_requirements({"name": "Tom", "skills": ['skill1', 'skill2'], "experience": "experience"}, ['skill1', 'skill2']), True)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_49_0.py", line 103, in matches_requirements
    for requirement in job['requirements']:
                       ~~~^^^^^^^^^^^^^^^^
TypeError: list indices must be integers or slices, not str

======================================================================
ERROR: test_matches_requirements_2 (ClassEval_49_0.JobMarketplaceTestMatchesRequirements.test_matches_requirements_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_49_0.py", line 347, in test_matches_requirements_2
    self.assertEqual(jobMarketplace.matches_requirements({"name": "Tom", "skills": ['skill1', 'skill2'], "experience": "experience"}, ['skill3', 'skill4']), False)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_49_0.py", line 103, in matches_requirements
    for requirement in job['requirements']:
                       ~~~^^^^^^^^^^^^^^^^
TypeError: list indices must be integers or slices, not str

======================================================================
ERROR: test_matches_requirements_3 (ClassEval_49_0.JobMarketplaceTestMatchesRequirements.test_matches_requirements_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_49_0.py", line 351, in test_matches_requirements_3
    self.assertEqual(jobMarketplace.matches_requirements({"name": "Tom", "skills": ['skill1', 'skill2'], "experience": "experience"}, ['skill5', 'skill6']), False)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_49_0.py", line 103, in matches_requirements
    for requirement in job['requirements']:
                       ~~~^^^^^^^^^^^^^^^^
TypeError: list indices must be integers or slices, not str

======================================================================
ERROR: test_matches_requirements_4 (ClassEval_49_0.JobMarketplaceTestMatchesRequirements.test_matches_requirements_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_49_0.py", line 355, in test_matches_requirements_4
    self.assertEqual(jobMarketplace.matches_requirements({"name": "Tom", "skills": ['skill1', 'skill2'], "experience": "experience"}, ['skill1', 'skill3']), False)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_49_0.py", line 103, in matches_requirements
    for requirement in job['requirements']:
                       ~~~^^^^^^^^^^^^^^^^
TypeError: list indices must be integers or slices, not str

======================================================================
ERROR: test_matches_requirements_5 (ClassEval_49_0.JobMarketplaceTestMatchesRequirements.test_matches_requirements_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_49_0.py", line 359, in test_matches_requirements_5
    self.assertEqual(jobMarketplace.matches_requirements({"name": "Tom", "skills": ['skill1', 'skill2'], "experience": "experience"}, ['skill1']), False)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_49_0.py", line 103, in matches_requirements
    for requirement in job['requirements']:
                       ~~~^^^^^^^^^^^^^^^^
TypeError: list indices must be integers or slices, not str

----------------------------------------------------------------------
Ran 5 tests in 0.002s

FAILED (errors=5)
E
======================================================================
ERROR: test_main (ClassEval_49_0.JobMarketplaceTestMain.test_main)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_49_0.py", line 376, in test_main
    self.assertEqual(jobMarketplace.matches_requirements({"name": "Tom", "skills": ['skill1', 'skill2'], "experience": "experience"}, ['skill1', 'skill2']), True)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_49_0.py", line 103, in matches_requirements
    for requirement in job['requirements']:
                       ~~~^^^^^^^^^^^^^^^^
TypeError: list indices must be integers or slices, not str

----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (errors=1)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.001s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.001s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.001s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.000s

OK
.FFF.
======================================================================
FAIL: test_play_2 (ClassEval_61_0.MusicPlayerTestPlay.test_play_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_61_0.py", line 248, in test_play_2
    self.assertEqual(musicPlayer.play(), None)
AssertionError: 'song2' != None

======================================================================
FAIL: test_play_3 (ClassEval_61_0.MusicPlayerTestPlay.test_play_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_61_0.py", line 253, in test_play_3
    self.assertEqual(musicPlayer.play(),False)
AssertionError: None != False

======================================================================
FAIL: test_play_4 (ClassEval_61_0.MusicPlayerTestPlay.test_play_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_61_0.py", line 259, in test_play_4
    self.assertEqual(musicPlayer.play(), "song1")
AssertionError: 'song3' != 'song1'
- song3
?     ^
+ song1
?     ^


----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=3)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
FFF..
======================================================================
FAIL: test_set_volume (ClassEval_61_0.MusicPlayerTestSetVolume.test_set_volume)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_61_0.py", line 358, in test_set_volume
    self.assertEqual(musicPlayer.set_volume(50), None)
AssertionError: True != None

======================================================================
FAIL: test_set_volume2 (ClassEval_61_0.MusicPlayerTestSetVolume.test_set_volume2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_61_0.py", line 363, in test_set_volume2
    self.assertEqual(musicPlayer.set_volume(100), None)
AssertionError: True != None

======================================================================
FAIL: test_set_volume3 (ClassEval_61_0.MusicPlayerTestSetVolume.test_set_volume3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_61_0.py", line 368, in test_set_volume3
    self.assertEqual(musicPlayer.set_volume(0), None)
AssertionError: True != None

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=3)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....F
======================================================================
FAIL: test_add_dish_6 (ClassEval_67_0.OrderTestAddDish.test_add_dish_6)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_67_0.py", line 179, in test_add_dish_6
    self.assertTrue(result)
AssertionError: False is not true

----------------------------------------------------------------------
Ran 6 tests in 0.001s

FAILED (failures=1)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
....E
======================================================================
ERROR: test_get_page_5 (ClassEval_68_0.PageUtilTestGetPage.test_get_page_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_68_0.py", line 155, in test_get_page_5
    actual_page = self.page_util.get_page(invalid_page_number)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_68_0.py", line 29, in get_page
    raise ValueError("Invalid page number")
ValueError: Invalid page number

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (errors=1)
....E
======================================================================
ERROR: test_get_page_info_5 (ClassEval_68_0.PageUtilTestGetPageInfo.test_get_page_info_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_68_0.py", line 224, in test_get_page_info_5
    actual_info = self.page_util.get_page_info(invalid_page_number)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_68_0.py", line 53, in get_page_info
    raise ValueError("Invalid page number")
ValueError: Invalid page number

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (errors=1)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
..EFE
======================================================================
ERROR: test_recv_3 (ClassEval_74_0.ServerTestRecv.test_recv_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_74_0.py", line 160, in test_recv_3
    flag = server.recv([88])
           ^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_74_0.py", line 54, in recv
    if info['addr'] in self.white_list:
       ~~~~^^^^^^^^
TypeError: list indices must be integers or slices, not str

======================================================================
ERROR: test_recv_5 (ClassEval_74_0.ServerTestRecv.test_recv_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_74_0.py", line 172, in test_recv_5
    flag = server.recv({"content": "abc"})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_74_0.py", line 54, in recv
    if info['addr'] in self.white_list:
       ~~~~^^^^^^^^
KeyError: 'addr'

======================================================================
FAIL: test_recv_4 (ClassEval_74_0.ServerTestRecv.test_recv_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_74_0.py", line 168, in test_recv_4
    self.assertEqual(flag, -1)
AssertionError: False != -1

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=1, errors=2)
.FFF.
======================================================================
FAIL: test_send_2 (ClassEval_74_0.ServerTestSend.test_send_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_74_0.py", line 186, in test_send_2
    self.assertEqual(flag, "info structure is not correct")
AssertionError: None != 'info structure is not correct'

======================================================================
FAIL: test_send_3 (ClassEval_74_0.ServerTestSend.test_send_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_74_0.py", line 191, in test_send_3
    self.assertEqual(flag, "info structure is not correct")
AssertionError: None != 'info structure is not correct'

======================================================================
FAIL: test_send_4 (ClassEval_74_0.ServerTestSend.test_send_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_74_0.py", line 196, in test_send_4
    self.assertEqual(flag, "info structure is not correct")
AssertionError: None != 'info structure is not correct'

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=3)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....F
======================================================================
FAIL: test_add_item_6 (ClassEval_75_0.ShoppingCartTestAddItem.test_add_item_6)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_75_0.py", line 113, in test_add_item_6
    self.assertEqual(shoppingcart.items, {"apple": {"price": 1, "quantity": 5}})
AssertionError: {'apple': {'price': 1, 'quantity': 10}} != {'apple': {'price': 1, 'quantity': 5}}
- {'apple': {'price': 1, 'quantity': 10}}
?                                    ^^

+ {'apple': {'price': 1, 'quantity': 5}}
?                                    ^


----------------------------------------------------------------------
Ran 6 tests in 0.001s

FAILED (failures=1)
......
----------------------------------------------------------------------
Ran 6 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.E...
======================================================================
ERROR: test_set_mode_2 (ClassEval_85_0.ThermostatTestSetMode.test_set_mode_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_85_0.py", line 186, in test_set_mode_2
    self.assertFalse(t.set_mode('test'))
                     ^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_85_0.py", line 50, in set_mode
    raise ValueError("Invalid mode. Mode should be 'heat' or 'cool'.")
ValueError: Invalid mode. Mode should be 'heat' or 'cool'.

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (errors=1)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
EE
======================================================================
ERROR: test_main (ClassEval_85_0.ThermostatTestMain.test_main)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_85_0.py", line 295, in test_main
    self.assertFalse(t.set_mode('test'))
                     ^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_85_0.py", line 50, in set_mode
    raise ValueError("Invalid mode. Mode should be 'heat' or 'cool'.")
ValueError: Invalid mode. Mode should be 'heat' or 'cool'.

----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (errors=1)
.F.FF
======================================================================
FAIL: test_add_item_2 (ClassEval_94_0.VendingMachineTestAddItem.test_add_item_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_94_0.py", line 90, in test_add_item_2
    self.assertEqual(vendingMachine.inventory, {'Coke': {'price': 1.25, 'quantity': 20}})
AssertionError: {'Coke': {'price': 1.25, 'quantity': 10}} != {'Coke': {'price': 1.25, 'quantity': 20}}
- {'Coke': {'price': 1.25, 'quantity': 10}}
?                                      ^

+ {'Coke': {'price': 1.25, 'quantity': 20}}
?                                      ^


======================================================================
FAIL: test_add_item_4 (ClassEval_94_0.VendingMachineTestAddItem.test_add_item_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_94_0.py", line 103, in test_add_item_4
    self.assertEqual(vendingMachine.inventory, {'Coke': {'price': 1.25, 'quantity': 10}, 'Pizza': {'price': 1.25, 'quantity': 20}})
AssertionError: {'Cok[15 chars].25, 'quantity': 10}, 'Pizza': {'price': 1.25, 'quantity': 10}} != {'Cok[15 chars].25, 'quantity': 10}, 'Pizza': {'price': 1.25, 'quantity': 20}}
  {'Coke': {'price': 1.25, 'quantity': 10},
-  'Pizza': {'price': 1.25, 'quantity': 10}}
?                                       ^

+  'Pizza': {'price': 1.25, 'quantity': 20}}
?                                       ^


======================================================================
FAIL: test_add_item_5 (ClassEval_94_0.VendingMachineTestAddItem.test_add_item_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_94_0.py", line 111, in test_add_item_5
    self.assertEqual(vendingMachine.inventory, {'Coke': {'price': 1.25, 'quantity': 20}, 'Pizza': {'price': 1.25, 'quantity': 20}})
AssertionError: {'Cok[15 chars].25, 'quantity': 10}, 'Pizza': {'price': 1.25, 'quantity': 10}} != {'Cok[15 chars].25, 'quantity': 20}, 'Pizza': {'price': 1.25, 'quantity': 20}}
- {'Coke': {'price': 1.25, 'quantity': 10},
?                                      ^

+ {'Coke': {'price': 1.25, 'quantity': 20},
?                                      ^

-  'Pizza': {'price': 1.25, 'quantity': 10}}
?                                       ^

+  'Pizza': {'price': 1.25, 'quantity': 20}}
?                                       ^


----------------------------------------------------------------------
Ran 5 tests in 0.002s

FAILED (failures=3)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
..
----------------------------------------------------------------------
Ran 2 tests in 0.001s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.001s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.E....
======================================================================
ERROR: test_query_2 (ClassEval_96_0.WeatherSystemTestQuery.test_query_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_96_0.py", line 129, in test_query_2
    self.assertEqual(weatherSystem.query(weather_list), False)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_96_0.py", line 38, in query
    raise ValueError(f"Weather information for {self.city} is not available")
ValueError: Weather information for Shanghai is not available

----------------------------------------------------------------------
Ran 6 tests in 0.001s

FAILED (errors=1)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
E...
======================================================================
ERROR: test_simulate_operation_1 (ClassEval_85_0.ThermostatTestSimulateOperation.test_simulate_operation_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_85_0.py", line 258, in test_simulate_operation_1
    self.assertEqual(t.simulate_operation(), 5)
                     ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_85_0.py", line 86, in simulate_operation
    time.sleep(1)
func_timeout.dafunc.FunctionTimedOut-3563152591195335679: Function run_unit_test (args=(<test_pipeline.AutoTest object at 0x11152a900>, 'ClassEval_85_0', 'ThermostatTestSimulateOperation', 'Llama4-maverick-instruct_greedy_Management_Systems')) (kwargs={}) timed out after 5.000000 seconds.


======================================================================
ERROR: test_simulate_operation_2 (ClassEval_85_0.ThermostatTestSimulateOperation.test_simulate_operation_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_85_0.py", line 264, in test_simulate_operation_2
    self.assertEqual(t.simulate_operation(), 6)
                     ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_85_0.py", line 86, in simulate_operation
    time.sleep(1)
func_timeout.dafunc.FunctionTimedOut-3563152591195335679: Function run_unit_test (args=(<test_pipeline.AutoTest object at 0x11152a900>, 'ClassEval_85_0', 'ThermostatTestSimulateOperation', 'Llama4-maverick-instruct_greedy_Management_Systems')) (kwargs={}) timed out after 5.000000 seconds.


----------------------------------------------------------------------
Ran 5 tests in 7.006s

FAILED (errors=2)
