EEEEE
======================================================================
ERROR: test_parse_arguments_1 (ClassEval_2_0.ArgumentParserTestParseArguments.test_parse_arguments_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_2_0.py", line 110, in test_parse_arguments_1
    result, missing_args = self.parser.parse_arguments(command_str)
    ^^^^^^^^^^^^^^^^^^^^
TypeError: cannot unpack non-iterable NoneType object

======================================================================
ERROR: test_parse_arguments_2 (ClassEval_2_0.ArgumentParserTestParseArguments.test_parse_arguments_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_2_0.py", line 123, in test_parse_arguments_2
    result, missing_args = self.parser.parse_arguments(command_str)
    ^^^^^^^^^^^^^^^^^^^^
TypeError: cannot unpack non-iterable NoneType object

======================================================================
ERROR: test_parse_arguments_3 (ClassEval_2_0.ArgumentParserTestParseArguments.test_parse_arguments_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_2_0.py", line 136, in test_parse_arguments_3
    result, missing_args = self.parser.parse_arguments(command_str)
    ^^^^^^^^^^^^^^^^^^^^
TypeError: cannot unpack non-iterable NoneType object

======================================================================
ERROR: test_parse_arguments_4 (ClassEval_2_0.ArgumentParserTestParseArguments.test_parse_arguments_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_2_0.py", line 146, in test_parse_arguments_4
    result, missing_args = self.parser.parse_arguments(command_str)
    ^^^^^^^^^^^^^^^^^^^^
TypeError: cannot unpack non-iterable NoneType object

======================================================================
ERROR: test_parse_arguments_5 (ClassEval_2_0.ArgumentParserTestParseArguments.test_parse_arguments_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_2_0.py", line 156, in test_parse_arguments_5
    result, missing_args = self.parser.parse_arguments(command_str)
    ^^^^^^^^^^^^^^^^^^^^
TypeError: cannot unpack non-iterable NoneType object

----------------------------------------------------------------------
Ran 5 tests in 0.002s

FAILED (errors=5)
FFFFF
======================================================================
FAIL: test_get_argument_1 (ClassEval_2_0.ArgumentParserTestGetArgument.test_get_argument_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_2_0.py", line 170, in test_get_argument_1
    self.assertEqual(result, "John")
AssertionError: None != 'John'

======================================================================
FAIL: test_get_argument_2 (ClassEval_2_0.ArgumentParserTestGetArgument.test_get_argument_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_2_0.py", line 176, in test_get_argument_2
    self.assertEqual(result, 25)
AssertionError: None != 25

======================================================================
FAIL: test_get_argument_3 (ClassEval_2_0.ArgumentParserTestGetArgument.test_get_argument_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_2_0.py", line 181, in test_get_argument_3
    self.assertEqual(result, True)
AssertionError: None != True

======================================================================
FAIL: test_get_argument_4 (ClassEval_2_0.ArgumentParserTestGetArgument.test_get_argument_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_2_0.py", line 186, in test_get_argument_4
    self.assertEqual(result, True)
AssertionError: None != True

======================================================================
FAIL: test_get_argument_5 (ClassEval_2_0.ArgumentParserTestGetArgument.test_get_argument_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_2_0.py", line 191, in test_get_argument_5
    self.assertEqual(result, "value")
AssertionError: None != 'value'

----------------------------------------------------------------------
Ran 5 tests in 0.002s

FAILED (failures=5)
FFFFF
======================================================================
FAIL: test_add_argument (ClassEval_2_0.ArgumentParserTestAddArgument.test_add_argument)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_2_0.py", line 203, in test_add_argument
    self.assertEqual(self.parser.required, {"age"})
AssertionError: Items in the second set but not the first:
'age'

======================================================================
FAIL: test_add_argument_2 (ClassEval_2_0.ArgumentParserTestAddArgument.test_add_argument_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_2_0.py", line 212, in test_add_argument_2
    self.assertEqual(self.parser.types, {"name": str, "age": int, "verbose": bool})
AssertionError: {} != {'name': <class 'str'>, 'age': <class 'int'>, 'verbose': <class 'bool'>}
- {}
+ {'age': <class 'int'>, 'name': <class 'str'>, 'verbose': <class 'bool'>}

======================================================================
FAIL: test_add_argument_3 (ClassEval_2_0.ArgumentParserTestAddArgument.test_add_argument_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_2_0.py", line 221, in test_add_argument_3
    self.assertEqual(self.parser.types, {"name": str, "age": int, "verbose": bool, "d": str})
AssertionError: {} != {'name': <class 'str'>, 'age': <class 'int[45 chars]tr'>}
- {}
+ {'age': <class 'int'>,
+  'd': <class 'str'>,
+  'name': <class 'str'>,
+  'verbose': <class 'bool'>}

======================================================================
FAIL: test_add_argument_4 (ClassEval_2_0.ArgumentParserTestAddArgument.test_add_argument_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_2_0.py", line 231, in test_add_argument_4
    self.assertEqual(self.parser.types, {"name": str, "age": int, "verbose": bool, "d": str, "option": str})
AssertionError: {} != {'name': <class 'str'>, 'age': <class 'int[70 chars]tr'>}
- {}
+ {'age': <class 'int'>,
+  'd': <class 'str'>,
+  'name': <class 'str'>,
+  'option': <class 'str'>,
+  'verbose': <class 'bool'>}

======================================================================
FAIL: test_add_argument_5 (ClassEval_2_0.ArgumentParserTestAddArgument.test_add_argument_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_2_0.py", line 242, in test_add_argument_5
    self.assertEqual(self.parser.types, {"name": str, "age": int, "verbose": bool, "d": str, "option": str, "option2": bool})
AssertionError: {} != {'name': <class 'str'>, 'age': <class 'int[97 chars]ol'>}
- {}
+ {'age': <class 'int'>,
+  'd': <class 'str'>,
+  'name': <class 'str'>,
+  'option': <class 'str'>,
+  'option2': <class 'bool'>,
+  'verbose': <class 'bool'>}

----------------------------------------------------------------------
Ran 5 tests in 0.003s

FAILED (failures=5)
EEEEE
======================================================================
ERROR: test_convert_type_1 (ClassEval_2_0.ArgumentParserTestConvertType.test_convert_type_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_2_0.py", line 252, in test_convert_type_1
    result = self.parser._convert_type("age", "25")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ArgumentParser._convert_type() takes 2 positional arguments but 3 were given

======================================================================
ERROR: test_convert_type_2 (ClassEval_2_0.ArgumentParserTestConvertType.test_convert_type_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_2_0.py", line 258, in test_convert_type_2
    result = self.parser._convert_type("age", "twenty-five")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ArgumentParser._convert_type() takes 2 positional arguments but 3 were given

======================================================================
ERROR: test_convert_type_3 (ClassEval_2_0.ArgumentParserTestConvertType.test_convert_type_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_2_0.py", line 263, in test_convert_type_3
    result = self.parser._convert_type("age", "25")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ArgumentParser._convert_type() takes 2 positional arguments but 3 were given

======================================================================
ERROR: test_convert_type_4 (ClassEval_2_0.ArgumentParserTestConvertType.test_convert_type_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_2_0.py", line 268, in test_convert_type_4
    result = self.parser._convert_type("verbose", "True")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ArgumentParser._convert_type() takes 2 positional arguments but 3 were given

======================================================================
ERROR: test_convert_type_5 (ClassEval_2_0.ArgumentParserTestConvertType.test_convert_type_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_2_0.py", line 273, in test_convert_type_5
    result = self.parser._convert_type("verbose", "False")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ArgumentParser._convert_type() takes 2 positional arguments but 3 were given

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (errors=5)
F
======================================================================
FAIL: test_main (ClassEval_2_0.ArgumentParserTestMain.test_main)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_2_0.py", line 285, in test_main
    self.assertEqual(parser.required, {'arg1'})
AssertionError: Items in the second set but not the first:
'arg1'

----------------------------------------------------------------------
Ran 1 test in 0.003s

FAILED (failures=1)
FFFFF
======================================================================
FAIL: test_setNum (ClassEval_6_0.AvgPartitionTestSetNum.test_setNum)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_6_0.py", line 45, in test_setNum
    self.assertEqual(a.setNum(), (2, 0))
AssertionError: None != (2, 0)

======================================================================
FAIL: test_setNum_2 (ClassEval_6_0.AvgPartitionTestSetNum.test_setNum_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_6_0.py", line 49, in test_setNum_2
    self.assertEqual(a.setNum(), (2, 1))
AssertionError: None != (2, 1)

======================================================================
FAIL: test_setNum_3 (ClassEval_6_0.AvgPartitionTestSetNum.test_setNum_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_6_0.py", line 53, in test_setNum_3
    self.assertEqual(a.setNum(), (1, 2))
AssertionError: None != (1, 2)

======================================================================
FAIL: test_setNum_4 (ClassEval_6_0.AvgPartitionTestSetNum.test_setNum_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_6_0.py", line 57, in test_setNum_4
    self.assertEqual(a.setNum(), (1, 1))
AssertionError: None != (1, 1)

======================================================================
FAIL: test_setNum_5 (ClassEval_6_0.AvgPartitionTestSetNum.test_setNum_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_6_0.py", line 61, in test_setNum_5
    self.assertEqual(a.setNum(), (1, 0))
AssertionError: None != (1, 0)

----------------------------------------------------------------------
Ran 5 tests in 0.002s

FAILED (failures=5)
FFFFF
======================================================================
FAIL: test_get (ClassEval_6_0.AvgPartitionTestGet.test_get)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_6_0.py", line 67, in test_get
    self.assertEqual(a.get(0), [1, 2])
AssertionError: None != [1, 2]

======================================================================
FAIL: test_get_2 (ClassEval_6_0.AvgPartitionTestGet.test_get_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_6_0.py", line 71, in test_get_2
    self.assertEqual(a.get(1), [3, 4])
AssertionError: None != [3, 4]

======================================================================
FAIL: test_get_3 (ClassEval_6_0.AvgPartitionTestGet.test_get_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_6_0.py", line 75, in test_get_3
    self.assertEqual(a.get(0), [1, 2, 3])
AssertionError: None != [1, 2, 3]

======================================================================
FAIL: test_get_4 (ClassEval_6_0.AvgPartitionTestGet.test_get_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_6_0.py", line 79, in test_get_4
    self.assertEqual(a.get(1), [4, 5])
AssertionError: None != [4, 5]

======================================================================
FAIL: test_get_5 (ClassEval_6_0.AvgPartitionTestGet.test_get_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_6_0.py", line 83, in test_get_5
    self.assertEqual(a.get(0), [1, 2])
AssertionError: None != [1, 2]

----------------------------------------------------------------------
Ran 5 tests in 0.002s

FAILED (failures=5)
F
======================================================================
FAIL: test_main (ClassEval_6_0.AvgPartitionTestMain.test_main)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_6_0.py", line 88, in test_main
    self.assertEqual(a.setNum(), (2, 0))
AssertionError: None != (2, 0)

----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (failures=1)
FFFFF
======================================================================
FAIL: test_clear_expr (ClassEval_7_0.BalancedBracketsTestClearExpr.test_clear_expr)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_7_0.py", line 57, in test_clear_expr
    self.assertEqual(b.expr, "()")
AssertionError: 'a(b)c' != '()'
- a(b)c
+ ()


======================================================================
FAIL: test_clear_expr_2 (ClassEval_7_0.BalancedBracketsTestClearExpr.test_clear_expr_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_7_0.py", line 62, in test_clear_expr_2
    self.assertEqual(b.expr, "(){}")
AssertionError: 'a(b){c}' != '(){}'
- a(b){c}
? - -  -
+ (){}


======================================================================
FAIL: test_clear_expr_3 (ClassEval_7_0.BalancedBracketsTestClearExpr.test_clear_expr_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_7_0.py", line 67, in test_clear_expr_3
    self.assertEqual(b.expr, "[](){}")
AssertionError: '[a](b){c}' != '[](){}'
- [a](b){c}
?  -  -  -
+ [](){}


======================================================================
FAIL: test_clear_expr_4 (ClassEval_7_0.BalancedBracketsTestClearExpr.test_clear_expr_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_7_0.py", line 72, in test_clear_expr_4
    self.assertEqual(b.expr, "[(){}")
AssertionError: '[a(b){c}' != '[(){}'
- [a(b){c}
?  - -  -
+ [(){}


======================================================================
FAIL: test_clear_expr_5 (ClassEval_7_0.BalancedBracketsTestClearExpr.test_clear_expr_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_7_0.py", line 77, in test_clear_expr_5
    self.assertEqual(b.expr, "(){}]")
AssertionError: 'a(b){c}]' != '(){}]'
- a(b){c}]
? - -  -
+ (){}]


----------------------------------------------------------------------
Ran 5 tests in 0.002s

FAILED (failures=5)
FFFFFFF
======================================================================
FAIL: test_check_balanced_brackets (ClassEval_7_0.BalancedBracketsTestCheckBalancedBrackets.test_check_balanced_brackets)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_7_0.py", line 83, in test_check_balanced_brackets
    self.assertEqual(b.check_balanced_brackets(), True)
AssertionError: None != True

======================================================================
FAIL: test_check_balanced_brackets_2 (ClassEval_7_0.BalancedBracketsTestCheckBalancedBrackets.test_check_balanced_brackets_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_7_0.py", line 87, in test_check_balanced_brackets_2
    self.assertEqual(b.check_balanced_brackets(), True)
AssertionError: None != True

======================================================================
FAIL: test_check_balanced_brackets_3 (ClassEval_7_0.BalancedBracketsTestCheckBalancedBrackets.test_check_balanced_brackets_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_7_0.py", line 91, in test_check_balanced_brackets_3
    self.assertEqual(b.check_balanced_brackets(), True)
AssertionError: None != True

======================================================================
FAIL: test_check_balanced_brackets_4 (ClassEval_7_0.BalancedBracketsTestCheckBalancedBrackets.test_check_balanced_brackets_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_7_0.py", line 95, in test_check_balanced_brackets_4
    self.assertEqual(b.check_balanced_brackets(), False)
AssertionError: None != False

======================================================================
FAIL: test_check_balanced_brackets_5 (ClassEval_7_0.BalancedBracketsTestCheckBalancedBrackets.test_check_balanced_brackets_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_7_0.py", line 99, in test_check_balanced_brackets_5
    self.assertEqual(b.check_balanced_brackets(), False)
AssertionError: None != False

======================================================================
FAIL: test_check_balanced_brackets_6 (ClassEval_7_0.BalancedBracketsTestCheckBalancedBrackets.test_check_balanced_brackets_6)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_7_0.py", line 103, in test_check_balanced_brackets_6
    self.assertEqual(b.check_balanced_brackets(), False)
AssertionError: None != False

======================================================================
FAIL: test_check_balanced_brackets_7 (ClassEval_7_0.BalancedBracketsTestCheckBalancedBrackets.test_check_balanced_brackets_7)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_7_0.py", line 107, in test_check_balanced_brackets_7
    self.assertEqual(b.check_balanced_brackets(), False)
AssertionError: None != False

----------------------------------------------------------------------
Ran 7 tests in 0.001s

FAILED (failures=7)
FFF
======================================================================
FAIL: test_main (ClassEval_7_0.BalancedBracketsTestMain.test_main)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_7_0.py", line 114, in test_main
    self.assertEqual(b.expr, "()")
AssertionError: 'a(b)c' != '()'
- a(b)c
+ ()


======================================================================
FAIL: test_main_2 (ClassEval_7_0.BalancedBracketsTestMain.test_main_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_7_0.py", line 120, in test_main_2
    self.assertEqual(b.expr, "[(){}")
AssertionError: '[a(b){c}' != '[(){}'
- [a(b){c}
?  - -  -
+ [(){}


======================================================================
FAIL: test_main_3 (ClassEval_7_0.BalancedBracketsTestMain.test_main_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_7_0.py", line 126, in test_main_3
    self.assertEqual(b.expr, "({}]")
AssertionError: 'a(b{c}]' != '({}]'
- a(b{c}]
? - - -
+ ({}]


----------------------------------------------------------------------
Ran 3 tests in 0.001s

FAILED (failures=3)
FFFFF
======================================================================
FAIL: test_match_in_pattern (ClassEval_15_0.BoyerMooreSearchTestMatchInPattern.test_match_in_pattern)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_15_0.py", line 64, in test_match_in_pattern
    self.assertEqual(boyerMooreSearch.match_in_pattern("A"), 0)
AssertionError: None != 0

======================================================================
FAIL: test_match_in_pattern_2 (ClassEval_15_0.BoyerMooreSearchTestMatchInPattern.test_match_in_pattern_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_15_0.py", line 68, in test_match_in_pattern_2
    self.assertEqual(boyerMooreSearch.match_in_pattern("B"), 3)
AssertionError: None != 3

======================================================================
FAIL: test_match_in_pattern_3 (ClassEval_15_0.BoyerMooreSearchTestMatchInPattern.test_match_in_pattern_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_15_0.py", line 72, in test_match_in_pattern_3
    self.assertEqual(boyerMooreSearch.match_in_pattern("C"), 5)
AssertionError: None != 5

======================================================================
FAIL: test_match_in_pattern_4 (ClassEval_15_0.BoyerMooreSearchTestMatchInPattern.test_match_in_pattern_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_15_0.py", line 76, in test_match_in_pattern_4
    self.assertEqual(boyerMooreSearch.match_in_pattern("D"), -1)
AssertionError: None != -1

======================================================================
FAIL: test_match_in_pattern_5 (ClassEval_15_0.BoyerMooreSearchTestMatchInPattern.test_match_in_pattern_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_15_0.py", line 80, in test_match_in_pattern_5
    self.assertEqual(boyerMooreSearch.match_in_pattern("E"), -1)
AssertionError: None != -1

----------------------------------------------------------------------
Ran 5 tests in 0.002s

FAILED (failures=5)
FFFFF
======================================================================
FAIL: test_mismatch_in_text (ClassEval_15_0.BoyerMooreSearchTestMismatchInText.test_mismatch_in_text)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_15_0.py", line 86, in test_mismatch_in_text
    self.assertEqual(boyerMooreSearch.mismatch_in_text(0), -1)
AssertionError: None != -1

======================================================================
FAIL: test_mismatch_in_text_2 (ClassEval_15_0.BoyerMooreSearchTestMismatchInText.test_mismatch_in_text_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_15_0.py", line 90, in test_mismatch_in_text_2
    self.assertEqual(boyerMooreSearch.mismatch_in_text(0), 2)
AssertionError: None != 2

======================================================================
FAIL: test_mismatch_in_text_3 (ClassEval_15_0.BoyerMooreSearchTestMismatchInText.test_mismatch_in_text_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_15_0.py", line 94, in test_mismatch_in_text_3
    self.assertEqual(boyerMooreSearch.mismatch_in_text(0), 2)
AssertionError: None != 2

======================================================================
FAIL: test_mismatch_in_text_4 (ClassEval_15_0.BoyerMooreSearchTestMismatchInText.test_mismatch_in_text_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_15_0.py", line 98, in test_mismatch_in_text_4
    self.assertEqual(boyerMooreSearch.mismatch_in_text(0), -1)
AssertionError: None != -1

======================================================================
FAIL: test_mismatch_in_text_5 (ClassEval_15_0.BoyerMooreSearchTestMismatchInText.test_mismatch_in_text_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_15_0.py", line 102, in test_mismatch_in_text_5
    self.assertEqual(boyerMooreSearch.mismatch_in_text(3), 5)
AssertionError: None != 5

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=5)
FFFFF
======================================================================
FAIL: test_bad_character_heuristic (ClassEval_15_0.BoyerMooreSearchTestBadCharacterHeuristic.test_bad_character_heuristic)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_15_0.py", line 108, in test_bad_character_heuristic
    self.assertEqual(boyerMooreSearch.bad_character_heuristic(), [0, 3])
AssertionError: None != [0, 3]

======================================================================
FAIL: test_bad_character_heuristic_2 (ClassEval_15_0.BoyerMooreSearchTestBadCharacterHeuristic.test_bad_character_heuristic_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_15_0.py", line 112, in test_bad_character_heuristic_2
    self.assertEqual(boyerMooreSearch.bad_character_heuristic(), [])
AssertionError: None != []

======================================================================
FAIL: test_bad_character_heuristic_3 (ClassEval_15_0.BoyerMooreSearchTestBadCharacterHeuristic.test_bad_character_heuristic_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_15_0.py", line 116, in test_bad_character_heuristic_3
    self.assertEqual(boyerMooreSearch.bad_character_heuristic(), [0, 1, 2, 3, 4, 5, 6])
AssertionError: None != [0, 1, 2, 3, 4, 5, 6]

======================================================================
FAIL: test_bad_character_heuristic_4 (ClassEval_15_0.BoyerMooreSearchTestBadCharacterHeuristic.test_bad_character_heuristic_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_15_0.py", line 120, in test_bad_character_heuristic_4
    self.assertEqual(boyerMooreSearch.bad_character_heuristic(), [0, 4])
AssertionError: None != [0, 4]

======================================================================
FAIL: test_bad_character_heuristic_5 (ClassEval_15_0.BoyerMooreSearchTestBadCharacterHeuristic.test_bad_character_heuristic_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_15_0.py", line 124, in test_bad_character_heuristic_5
    self.assertEqual(boyerMooreSearch.bad_character_heuristic(), [0])
AssertionError: None != [0]

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=5)
F
======================================================================
FAIL: test_main (ClassEval_15_0.BoyerMooreSearchTestMain.test_main)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_15_0.py", line 129, in test_main
    self.assertEqual(boyerMooreSearch.match_in_pattern("A"), 0)
AssertionError: None != 0

----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (failures=1)
FFEEE.
======================================================================
ERROR: test_convert_3 (ClassEval_27_0.CurrencyConverterTestConvert.test_convert_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_27_0.py", line 75, in test_convert_3
    self.assertAlmostEqual(res, 7.1999999999999)
  File "/opt/miniconda3/lib/python3.12/unittest/case.py", line 916, in assertAlmostEqual
    diff = abs(first - second)
               ~~~~~~^~~~~~~~
TypeError: unsupported operand type(s) for -: 'NoneType' and 'float'

======================================================================
ERROR: test_convert_4 (ClassEval_27_0.CurrencyConverterTestConvert.test_convert_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_27_0.py", line 80, in test_convert_4
    self.assertAlmostEqual(res, 46.08)
  File "/opt/miniconda3/lib/python3.12/unittest/case.py", line 916, in assertAlmostEqual
    diff = abs(first - second)
               ~~~~~~^~~~~~~~
TypeError: unsupported operand type(s) for -: 'NoneType' and 'float'

======================================================================
ERROR: test_convert_5 (ClassEval_27_0.CurrencyConverterTestConvert.test_convert_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_27_0.py", line 85, in test_convert_5
    self.assertAlmostEqual(res, 78.72)
  File "/opt/miniconda3/lib/python3.12/unittest/case.py", line 916, in assertAlmostEqual
    diff = abs(first - second)
               ~~~~~~^~~~~~~~
TypeError: unsupported operand type(s) for -: 'NoneType' and 'float'

======================================================================
FAIL: test_convert_1 (ClassEval_27_0.CurrencyConverterTestConvert.test_convert_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_27_0.py", line 65, in test_convert_1
    self.assertEqual(res, 10.0)
AssertionError: None != 10.0

======================================================================
FAIL: test_convert_2 (ClassEval_27_0.CurrencyConverterTestConvert.test_convert_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_27_0.py", line 70, in test_convert_2
    self.assertEqual(res, 64)
AssertionError: None != 64

----------------------------------------------------------------------
Ran 6 tests in 0.002s

FAILED (failures=2, errors=3)
FFFFF
======================================================================
FAIL: test_get_supported_currencies_1 (ClassEval_27_0.CurrencyConverterTestGetSupportedCurrencies.test_get_supported_currencies_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_27_0.py", line 97, in test_get_supported_currencies_1
    self.assertEqual(res, ['USD', 'EUR', 'GBP', 'JPY', 'CAD', 'AUD', 'CNY'])
AssertionError: None != ['USD', 'EUR', 'GBP', 'JPY', 'CAD', 'AUD', 'CNY']

======================================================================
FAIL: test_get_supported_currencies_2 (ClassEval_27_0.CurrencyConverterTestGetSupportedCurrencies.test_get_supported_currencies_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_27_0.py", line 102, in test_get_supported_currencies_2
    self.assertEqual(res, ['USD', 'EUR', 'GBP', 'JPY', 'CAD', 'AUD', 'CNY'])
AssertionError: None != ['USD', 'EUR', 'GBP', 'JPY', 'CAD', 'AUD', 'CNY']

======================================================================
FAIL: test_get_supported_currencies_3 (ClassEval_27_0.CurrencyConverterTestGetSupportedCurrencies.test_get_supported_currencies_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_27_0.py", line 107, in test_get_supported_currencies_3
    self.assertEqual(res, ['USD', 'EUR', 'GBP', 'JPY', 'CAD', 'AUD', 'CNY'])
AssertionError: None != ['USD', 'EUR', 'GBP', 'JPY', 'CAD', 'AUD', 'CNY']

======================================================================
FAIL: test_get_supported_currencies_4 (ClassEval_27_0.CurrencyConverterTestGetSupportedCurrencies.test_get_supported_currencies_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_27_0.py", line 112, in test_get_supported_currencies_4
    self.assertEqual(res, ['USD', 'EUR', 'GBP', 'JPY', 'CAD', 'AUD', 'CNY'])
AssertionError: None != ['USD', 'EUR', 'GBP', 'JPY', 'CAD', 'AUD', 'CNY']

======================================================================
FAIL: test_get_supported_currencies_5 (ClassEval_27_0.CurrencyConverterTestGetSupportedCurrencies.test_get_supported_currencies_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_27_0.py", line 117, in test_get_supported_currencies_5
    self.assertEqual(res, ['USD', 'EUR', 'GBP', 'JPY', 'CAD', 'AUD', 'CNY'])
AssertionError: None != ['USD', 'EUR', 'GBP', 'JPY', 'CAD', 'AUD', 'CNY']

----------------------------------------------------------------------
Ran 5 tests in 0.002s

FAILED (failures=5)
EEEEE.
======================================================================
ERROR: test_add_currency_rate_1 (ClassEval_27_0.CurrencyConverterTestAddCurrencyRate.test_add_currency_rate_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_27_0.py", line 124, in test_add_currency_rate_1
    self.assertEqual(cc.rates['KRW'], 1308.84)
                     ~~~~~~~~^^^^^^^
KeyError: 'KRW'

======================================================================
ERROR: test_add_currency_rate_2 (ClassEval_27_0.CurrencyConverterTestAddCurrencyRate.test_add_currency_rate_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_27_0.py", line 129, in test_add_currency_rate_2
    self.assertEqual(cc.rates['aaa'], 1.0)
                     ~~~~~~~~^^^^^^^
KeyError: 'aaa'

======================================================================
ERROR: test_add_currency_rate_3 (ClassEval_27_0.CurrencyConverterTestAddCurrencyRate.test_add_currency_rate_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_27_0.py", line 134, in test_add_currency_rate_3
    self.assertEqual(cc.rates['bbb'], 2.0)
                     ~~~~~~~~^^^^^^^
KeyError: 'bbb'

======================================================================
ERROR: test_add_currency_rate_4 (ClassEval_27_0.CurrencyConverterTestAddCurrencyRate.test_add_currency_rate_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_27_0.py", line 139, in test_add_currency_rate_4
    self.assertEqual(cc.rates['ccc'], 3.0)
                     ~~~~~~~~^^^^^^^
KeyError: 'ccc'

======================================================================
ERROR: test_add_currency_rate_5 (ClassEval_27_0.CurrencyConverterTestAddCurrencyRate.test_add_currency_rate_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_27_0.py", line 144, in test_add_currency_rate_5
    self.assertEqual(cc.rates['ddd'], 4.0)
                     ~~~~~~~~^^^^^^^
KeyError: 'ddd'

----------------------------------------------------------------------
Ran 6 tests in 0.002s

FAILED (errors=5)
FFFFF.
======================================================================
FAIL: test_update_currency_rate_1 (ClassEval_27_0.CurrencyConverterTestUpdateCurrencyRate.test_update_currency_rate_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_27_0.py", line 156, in test_update_currency_rate_1
    self.assertEqual(cc.rates['CNY'], 7.18)
AssertionError: 6.4 != 7.18

======================================================================
FAIL: test_update_currency_rate_2 (ClassEval_27_0.CurrencyConverterTestUpdateCurrencyRate.test_update_currency_rate_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_27_0.py", line 161, in test_update_currency_rate_2
    self.assertEqual(cc.rates['CNY'], 1.0)
AssertionError: 6.4 != 1.0

======================================================================
FAIL: test_update_currency_rate_3 (ClassEval_27_0.CurrencyConverterTestUpdateCurrencyRate.test_update_currency_rate_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_27_0.py", line 166, in test_update_currency_rate_3
    self.assertEqual(cc.rates['CNY'], 2.0)
AssertionError: 6.4 != 2.0

======================================================================
FAIL: test_update_currency_rate_4 (ClassEval_27_0.CurrencyConverterTestUpdateCurrencyRate.test_update_currency_rate_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_27_0.py", line 171, in test_update_currency_rate_4
    self.assertEqual(cc.rates['CNY'], 3.0)
AssertionError: 6.4 != 3.0

======================================================================
FAIL: test_update_currency_rate_5 (ClassEval_27_0.CurrencyConverterTestUpdateCurrencyRate.test_update_currency_rate_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_27_0.py", line 176, in test_update_currency_rate_5
    self.assertEqual(cc.rates['CNY'], 4.0)
AssertionError: 6.4 != 4.0

----------------------------------------------------------------------
Ran 6 tests in 0.001s

FAILED (failures=5)
F
======================================================================
FAIL: test_currencyconverter (ClassEval_27_0.CurrencyConverterTest.test_currencyconverter)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_27_0.py", line 188, in test_currencyconverter
    self.assertEqual(res, 10.0)
AssertionError: None != 10.0

----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (failures=1)
FFFFFFF
======================================================================
FAIL: test_caesar_decipher (ClassEval_32_0.DecryptionUtilsTestCaesarDecipher.test_caesar_decipher)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_32_0.py", line 47, in test_caesar_decipher
    self.assertEqual(d.caesar_decipher('ifmmp', 1), 'hello')
AssertionError: None != 'hello'

======================================================================
FAIL: test_caesar_decipher_2 (ClassEval_32_0.DecryptionUtilsTestCaesarDecipher.test_caesar_decipher_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_32_0.py", line 51, in test_caesar_decipher_2
    self.assertEqual(d.caesar_decipher('bcdyza', 27), 'abcxyz')
AssertionError: None != 'abcxyz'

======================================================================
FAIL: test_caesar_decipher_3 (ClassEval_32_0.DecryptionUtilsTestCaesarDecipher.test_caesar_decipher_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_32_0.py", line 55, in test_caesar_decipher_3
    self.assertEqual(d.caesar_decipher('bcd', 0), 'bcd')
AssertionError: None != 'bcd'

======================================================================
FAIL: test_caesar_decipher_4 (ClassEval_32_0.DecryptionUtilsTestCaesarDecipher.test_caesar_decipher_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_32_0.py", line 59, in test_caesar_decipher_4
    self.assertEqual(d.caesar_decipher('bcd', 26), 'bcd')
AssertionError: None != 'bcd'

======================================================================
FAIL: test_caesar_decipher_5 (ClassEval_32_0.DecryptionUtilsTestCaesarDecipher.test_caesar_decipher_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_32_0.py", line 63, in test_caesar_decipher_5
    self.assertEqual(d.caesar_decipher('bcd', -26), 'bcd')
AssertionError: None != 'bcd'

======================================================================
FAIL: test_caesar_decipher_6 (ClassEval_32_0.DecryptionUtilsTestCaesarDecipher.test_caesar_decipher_6)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_32_0.py", line 67, in test_caesar_decipher_6
    self.assertEqual(d.caesar_decipher('IFMMP', 1), 'HELLO')
AssertionError: None != 'HELLO'

======================================================================
FAIL: test_caesar_decipher_7 (ClassEval_32_0.DecryptionUtilsTestCaesarDecipher.test_caesar_decipher_7)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_32_0.py", line 71, in test_caesar_decipher_7
    self.assertEqual(d.caesar_decipher('123', 1), '123')
AssertionError: None != '123'

----------------------------------------------------------------------
Ran 7 tests in 0.002s

FAILED (failures=7)
FFFFFF
======================================================================
FAIL: test_vigenere_decipher (ClassEval_32_0.DecryptionUtilsTestVigenereDecipher.test_vigenere_decipher)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_32_0.py", line 77, in test_vigenere_decipher
    self.assertEqual(d.vigenere_decipher('ifmmp'), 'ybocl')
AssertionError: None != 'ybocl'

======================================================================
FAIL: test_vigenere_decipher_2 (ClassEval_32_0.DecryptionUtilsTestVigenereDecipher.test_vigenere_decipher_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_32_0.py", line 81, in test_vigenere_decipher_2
    self.assertEqual(d.vigenere_decipher('rijvs'), 'hello')
AssertionError: None != 'hello'

======================================================================
FAIL: test_vigenere_decipher_3 (ClassEval_32_0.DecryptionUtilsTestVigenereDecipher.test_vigenere_decipher_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_32_0.py", line 85, in test_vigenere_decipher_3
    self.assertEqual(d.vigenere_decipher('LpPjOjE'), 'AbCdEfG')
AssertionError: None != 'AbCdEfG'

======================================================================
FAIL: test_vigenere_decipher_4 (ClassEval_32_0.DecryptionUtilsTestVigenereDecipher.test_vigenere_decipher_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_32_0.py", line 89, in test_vigenere_decipher_4
    self.assertEqual(d.vigenere_decipher('bcd'), 'ryf')
AssertionError: None != 'ryf'

======================================================================
FAIL: test_vigenere_decipher_5 (ClassEval_32_0.DecryptionUtilsTestVigenereDecipher.test_vigenere_decipher_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_32_0.py", line 93, in test_vigenere_decipher_5
    self.assertEqual(d.vigenere_decipher('bcdaa'), 'ryfqw')
AssertionError: None != 'ryfqw'

======================================================================
FAIL: test_vigenere_decipher_6 (ClassEval_32_0.DecryptionUtilsTestVigenereDecipher.test_vigenere_decipher_6)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_32_0.py", line 97, in test_vigenere_decipher_6
    self.assertEqual(d.vigenere_decipher('123'), '123')
AssertionError: None != '123'

----------------------------------------------------------------------
Ran 6 tests in 0.002s

FAILED (failures=6)
FFFFF
======================================================================
FAIL: test_rail_fence_decipher (ClassEval_32_0.DecryptionUtilsTestRailFenceDecipher.test_rail_fence_decipher)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_32_0.py", line 103, in test_rail_fence_decipher
    self.assertEqual(d.rail_fence_decipher('Hoo!el,Wrdl l', 3), 'Hello, World!')
AssertionError: None != 'Hello, World!'

======================================================================
FAIL: test_rail_fence_decipher_2 (ClassEval_32_0.DecryptionUtilsTestRailFenceDecipher.test_rail_fence_decipher_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_32_0.py", line 107, in test_rail_fence_decipher_2
    self.assertEqual(d.rail_fence_decipher('Hoo!el,Wrdl l', 4), 'H!W reoldll,o')
AssertionError: None != 'H!W reoldll,o'

======================================================================
FAIL: test_rail_fence_decipher_3 (ClassEval_32_0.DecryptionUtilsTestRailFenceDecipher.test_rail_fence_decipher_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_32_0.py", line 111, in test_rail_fence_decipher_3
    self.assertEqual(d.rail_fence_decipher('Hoo!el,Wrdl l', 5), 'Holr d,!oeWll')
AssertionError: None != 'Holr d,!oeWll'

======================================================================
FAIL: test_rail_fence_decipher_4 (ClassEval_32_0.DecryptionUtilsTestRailFenceDecipher.test_rail_fence_decipher_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_32_0.py", line 115, in test_rail_fence_decipher_4
    self.assertEqual(d.rail_fence_decipher('Hoo!el,Wrdl l', 6), 'Holrll d,!oeW')
AssertionError: None != 'Holrll d,!oeW'

======================================================================
FAIL: test_rail_fence_decipher_5 (ClassEval_32_0.DecryptionUtilsTestRailFenceDecipher.test_rail_fence_decipher_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_32_0.py", line 119, in test_rail_fence_decipher_5
    self.assertEqual(d.rail_fence_decipher('Hoo!el,Wrdl l', 7), 'Hoe,rll dWl!o')
AssertionError: None != 'Hoe,rll dWl!o'

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=5)
F
======================================================================
FAIL: test_main (ClassEval_32_0.DecryptionUtilsTestMain.test_main)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_32_0.py", line 125, in test_main
    self.assertEqual(d.caesar_decipher('ifmmp', 1), 'hello')
AssertionError: None != 'hello'

----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (failures=1)
FFFFFF
======================================================================
FAIL: test_caesar_cipher (ClassEval_37_0.EncryptionUtilsTestCaesarCipher.test_caesar_cipher)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_37_0.py", line 46, in test_caesar_cipher
    self.assertEqual(encryption_utils.caesar_cipher("abc", 1), "bcd")
AssertionError: None != 'bcd'

======================================================================
FAIL: test_caesar_cipher_2 (ClassEval_37_0.EncryptionUtilsTestCaesarCipher.test_caesar_cipher_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_37_0.py", line 50, in test_caesar_cipher_2
    self.assertEqual(encryption_utils.caesar_cipher("WORLD", -2), "UMPJB")
AssertionError: None != 'UMPJB'

======================================================================
FAIL: test_caesar_cipher_3 (ClassEval_37_0.EncryptionUtilsTestCaesarCipher.test_caesar_cipher_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_37_0.py", line 54, in test_caesar_cipher_3
    self.assertEqual(encryption_utils.caesar_cipher("", 4), "")
AssertionError: None != ''

======================================================================
FAIL: test_caesar_cipher_4 (ClassEval_37_0.EncryptionUtilsTestCaesarCipher.test_caesar_cipher_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_37_0.py", line 58, in test_caesar_cipher_4
    self.assertEqual(encryption_utils.caesar_cipher("abcxyz", 26), "abcxyz")
AssertionError: None != 'abcxyz'

======================================================================
FAIL: test_caesar_cipher_5 (ClassEval_37_0.EncryptionUtilsTestCaesarCipher.test_caesar_cipher_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_37_0.py", line 62, in test_caesar_cipher_5
    self.assertEqual(encryption_utils.caesar_cipher("abcxyz", 27), "bcdyza")
AssertionError: None != 'bcdyza'

======================================================================
FAIL: test_caesar_cipher_6 (ClassEval_37_0.EncryptionUtilsTestCaesarCipher.test_caesar_cipher_6)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_37_0.py", line 66, in test_caesar_cipher_6
    self.assertEqual(encryption_utils.caesar_cipher("123", 27), "123")
AssertionError: None != '123'

----------------------------------------------------------------------
Ran 6 tests in 0.002s

FAILED (failures=6)
FFFFF
======================================================================
FAIL: test_vigenere_cipher (ClassEval_37_0.EncryptionUtilsTestVigenereCipher.test_vigenere_cipher)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_37_0.py", line 72, in test_vigenere_cipher
    self.assertEqual(encryption_utils.vigenere_cipher("abc"), "kfa")
AssertionError: None != 'kfa'

======================================================================
FAIL: test_vigenere_cipher_2 (ClassEval_37_0.EncryptionUtilsTestVigenereCipher.test_vigenere_cipher_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_37_0.py", line 76, in test_vigenere_cipher_2
    self.assertEqual(encryption_utils.vigenere_cipher("hello"), "rijvs")
AssertionError: None != 'rijvs'

======================================================================
FAIL: test_vigenere_cipher_3 (ClassEval_37_0.EncryptionUtilsTestVigenereCipher.test_vigenere_cipher_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_37_0.py", line 80, in test_vigenere_cipher_3
    self.assertEqual(encryption_utils.vigenere_cipher("AbCdEfG"), "LpPjOjE")
AssertionError: None != 'LpPjOjE'

======================================================================
FAIL: test_vigenere_cipher_4 (ClassEval_37_0.EncryptionUtilsTestVigenereCipher.test_vigenere_cipher_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_37_0.py", line 84, in test_vigenere_cipher_4
    self.assertEqual(encryption_utils.vigenere_cipher("Hello, World! 123"), "Rijvs, Uyvjn! 123")
AssertionError: None != 'Rijvs, Uyvjn! 123'

======================================================================
FAIL: test_vigenere_cipher_5 (ClassEval_37_0.EncryptionUtilsTestVigenereCipher.test_vigenere_cipher_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_37_0.py", line 88, in test_vigenere_cipher_5
    self.assertEqual(encryption_utils.vigenere_cipher(""), "")
AssertionError: None != ''

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=5)
FFFFFF
======================================================================
FAIL: test_rail_fence_cipher (ClassEval_37_0.EncryptionUtilsTestRailFenceCipher.test_rail_fence_cipher)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_37_0.py", line 94, in test_rail_fence_cipher
    self.assertEqual(encryption_utils.rail_fence_cipher("abc", 2), "acb")
AssertionError: None != 'acb'

======================================================================
FAIL: test_rail_fence_cipher_2 (ClassEval_37_0.EncryptionUtilsTestRailFenceCipher.test_rail_fence_cipher_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_37_0.py", line 98, in test_rail_fence_cipher_2
    self.assertEqual(encryption_utils.rail_fence_cipher("hello", 2), "hloel")
AssertionError: None != 'hloel'

======================================================================
FAIL: test_rail_fence_cipher_3 (ClassEval_37_0.EncryptionUtilsTestRailFenceCipher.test_rail_fence_cipher_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_37_0.py", line 102, in test_rail_fence_cipher_3
    self.assertEqual(encryption_utils.rail_fence_cipher("AbCdEfG", 2), "ACEGbdf")
AssertionError: None != 'ACEGbdf'

======================================================================
FAIL: test_rail_fence_cipher_4 (ClassEval_37_0.EncryptionUtilsTestRailFenceCipher.test_rail_fence_cipher_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_37_0.py", line 106, in test_rail_fence_cipher_4
    self.assertEqual(encryption_utils.rail_fence_cipher("Hello, World! 123", 2), "Hlo ol!13el,Wrd 2")
AssertionError: None != 'Hlo ol!13el,Wrd 2'

======================================================================
FAIL: test_rail_fence_cipher_5 (ClassEval_37_0.EncryptionUtilsTestRailFenceCipher.test_rail_fence_cipher_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_37_0.py", line 110, in test_rail_fence_cipher_5
    self.assertEqual(encryption_utils.rail_fence_cipher("", 2), "")
AssertionError: None != ''

======================================================================
FAIL: test_rail_fence_cipher_6 (ClassEval_37_0.EncryptionUtilsTestRailFenceCipher.test_rail_fence_cipher_6)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_37_0.py", line 114, in test_rail_fence_cipher_6
    self.assertEqual(encryption_utils.rail_fence_cipher("abcdefg", 3), "aebdfcg")
AssertionError: None != 'aebdfcg'

----------------------------------------------------------------------
Ran 6 tests in 0.001s

FAILED (failures=6)
F
======================================================================
FAIL: test_main (ClassEval_37_0.EncryptionUtilsTestMain.test_main)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_37_0.py", line 120, in test_main
    self.assertEqual(encryption_utils.caesar_cipher("abc", 1), "bcd")
AssertionError: None != 'bcd'

----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (failures=1)
FFFFF
======================================================================
FAIL: test_palindromic_length (ClassEval_55_0.ManacherTestPalindromicLength.test_palindromic_length)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_55_0.py", line 55, in test_palindromic_length
    self.assertEqual(manacher.palindromic_length(2, 1, 'a|b|a|b|a'), 2)
AssertionError: None != 2

======================================================================
FAIL: test_palindromic_length_2 (ClassEval_55_0.ManacherTestPalindromicLength.test_palindromic_length_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_55_0.py", line 58, in test_palindromic_length_2
    self.assertEqual(manacher.palindromic_length(2, 1, 'a|b|a|b|a|x|s|e'), 2)
AssertionError: None != 2

======================================================================
FAIL: test_palindromic_length_3 (ClassEval_55_0.ManacherTestPalindromicLength.test_palindromic_length_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_55_0.py", line 62, in test_palindromic_length_3
    self.assertEqual(manacher.palindromic_length(2, 3, 'a|b|a|b|a|x'), 0)
AssertionError: None != 0

======================================================================
FAIL: test_palindromic_length_4 (ClassEval_55_0.ManacherTestPalindromicLength.test_palindromic_length_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_55_0.py", line 66, in test_palindromic_length_4
    self.assertEqual(manacher.palindromic_length(9, 2, 'a|b|a|b|a|x'), 0)
AssertionError: None != 0

======================================================================
FAIL: test_palindromic_length_5 (ClassEval_55_0.ManacherTestPalindromicLength.test_palindromic_length_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_55_0.py", line 70, in test_palindromic_length_5
    self.assertEqual(manacher.palindromic_length(4, 1, 'a|b|a|b|a|x'), 4)
AssertionError: None != 4

----------------------------------------------------------------------
Ran 5 tests in 0.002s

FAILED (failures=5)
FFFFF
======================================================================
FAIL: test_palindromic_string (ClassEval_55_0.ManacherTestPalindromicString.test_palindromic_string)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_55_0.py", line 76, in test_palindromic_string
    self.assertEqual(manacher.palindromic_string(), 'ababa')
AssertionError: None != 'ababa'

======================================================================
FAIL: test_palindromic_string_2 (ClassEval_55_0.ManacherTestPalindromicString.test_palindromic_string_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_55_0.py", line 80, in test_palindromic_string_2
    self.assertEqual(manacher.palindromic_string(), 'ababa')
AssertionError: None != 'ababa'

======================================================================
FAIL: test_palindromic_string_3 (ClassEval_55_0.ManacherTestPalindromicString.test_palindromic_string_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_55_0.py", line 84, in test_palindromic_string_3
    self.assertEqual(manacher.palindromic_string(), 'ababa')
AssertionError: None != 'ababa'

======================================================================
FAIL: test_palindromic_string_4 (ClassEval_55_0.ManacherTestPalindromicString.test_palindromic_string_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_55_0.py", line 88, in test_palindromic_string_4
    self.assertEqual(manacher.palindromic_string(), 'ababa')
AssertionError: None != 'ababa'

======================================================================
FAIL: test_palindromic_string_5 (ClassEval_55_0.ManacherTestPalindromicString.test_palindromic_string_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_55_0.py", line 92, in test_palindromic_string_5
    self.assertEqual(manacher.palindromic_string(), 'aba')
AssertionError: None != 'aba'

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=5)
F
======================================================================
FAIL: test_main (ClassEval_55_0.ManacherTestMain.test_main)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_55_0.py", line 98, in test_main
    self.assertEqual(manacher.palindromic_length(2, 1, 'a|b|a|b|a'), 2)
AssertionError: None != 2

----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (failures=1)
FFFFF
======================================================================
FAIL: test_decimal_to_binary (ClassEval_64_0.NumberConverterTestDecimalToBinary.test_decimal_to_binary)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_64_0.py", line 65, in test_decimal_to_binary
    self.assertEqual('1010010110110111', NumberConverter.decimal_to_binary(42423))
AssertionError: '1010010110110111' != None

======================================================================
FAIL: test_decimal_to_binary_2 (ClassEval_64_0.NumberConverterTestDecimalToBinary.test_decimal_to_binary_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_64_0.py", line 68, in test_decimal_to_binary_2
    self.assertEqual('101001100010111', NumberConverter.decimal_to_binary(21271))
AssertionError: '101001100010111' != None

======================================================================
FAIL: test_decimal_to_binary_3 (ClassEval_64_0.NumberConverterTestDecimalToBinary.test_decimal_to_binary_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_64_0.py", line 71, in test_decimal_to_binary_3
    self.assertEqual('1010010111010111', NumberConverter.decimal_to_binary(42455))
AssertionError: '1010010111010111' != None

======================================================================
FAIL: test_decimal_to_binary_4 (ClassEval_64_0.NumberConverterTestDecimalToBinary.test_decimal_to_binary_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_64_0.py", line 74, in test_decimal_to_binary_4
    self.assertEqual('10100101110101011', NumberConverter.decimal_to_binary(84907))
AssertionError: '10100101110101011' != None

======================================================================
FAIL: test_decimal_to_binary_5 (ClassEval_64_0.NumberConverterTestDecimalToBinary.test_decimal_to_binary_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_64_0.py", line 77, in test_decimal_to_binary_5
    self.assertEqual('101001011101010111', NumberConverter.decimal_to_binary(169815))
AssertionError: '101001011101010111' != None

----------------------------------------------------------------------
Ran 5 tests in 0.002s

FAILED (failures=5)
FFFFF
======================================================================
FAIL: test_binary_to_decimal (ClassEval_64_0.NumberConverterTestBinaryToDecimal.test_binary_to_decimal)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_64_0.py", line 81, in test_binary_to_decimal
    self.assertEqual(42423, NumberConverter.binary_to_decimal('1010010110110111'))
AssertionError: 42423 != None

======================================================================
FAIL: test_binary_to_decimal_2 (ClassEval_64_0.NumberConverterTestBinaryToDecimal.test_binary_to_decimal_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_64_0.py", line 84, in test_binary_to_decimal_2
    self.assertEqual(10615, NumberConverter.binary_to_decimal('10100101110111'))
AssertionError: 10615 != None

======================================================================
FAIL: test_binary_to_decimal_3 (ClassEval_64_0.NumberConverterTestBinaryToDecimal.test_binary_to_decimal_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_64_0.py", line 87, in test_binary_to_decimal_3
    self.assertEqual(42455, NumberConverter.binary_to_decimal('1010010111010111'))
AssertionError: 42455 != None

======================================================================
FAIL: test_binary_to_decimal_4 (ClassEval_64_0.NumberConverterTestBinaryToDecimal.test_binary_to_decimal_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_64_0.py", line 90, in test_binary_to_decimal_4
    self.assertEqual(169819, NumberConverter.binary_to_decimal('101001011101011011'))
AssertionError: 169819 != None

======================================================================
FAIL: test_binary_to_decimal_5 (ClassEval_64_0.NumberConverterTestBinaryToDecimal.test_binary_to_decimal_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_64_0.py", line 93, in test_binary_to_decimal_5
    self.assertEqual(339639, NumberConverter.binary_to_decimal('1010010111010110111'))
AssertionError: 339639 != None

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=5)
FFFFF
======================================================================
FAIL: test_decimal_to_octal (ClassEval_64_0.NumberConvertTestDecimalToOctal.test_decimal_to_octal)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_64_0.py", line 97, in test_decimal_to_octal
    self.assertEqual('122667', NumberConverter.decimal_to_octal(42423))
AssertionError: '122667' != None

======================================================================
FAIL: test_decimal_to_octal_2 (ClassEval_64_0.NumberConvertTestDecimalToOctal.test_decimal_to_octal_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_64_0.py", line 100, in test_decimal_to_octal_2
    self.assertEqual('51427', NumberConverter.decimal_to_octal(21271))
AssertionError: '51427' != None

======================================================================
FAIL: test_decimal_to_octal_3 (ClassEval_64_0.NumberConvertTestDecimalToOctal.test_decimal_to_octal_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_64_0.py", line 103, in test_decimal_to_octal_3
    self.assertEqual('245653', NumberConverter.decimal_to_octal(84907))
AssertionError: '245653' != None

======================================================================
FAIL: test_decimal_to_octal_4 (ClassEval_64_0.NumberConvertTestDecimalToOctal.test_decimal_to_octal_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_64_0.py", line 106, in test_decimal_to_octal_4
    self.assertEqual('513527', NumberConverter.decimal_to_octal(169815))
AssertionError: '513527' != None

======================================================================
FAIL: test_decimal_to_octal_5 (ClassEval_64_0.NumberConvertTestDecimalToOctal.test_decimal_to_octal_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_64_0.py", line 109, in test_decimal_to_octal_5
    self.assertEqual('1227256', NumberConverter.decimal_to_octal(339630))
AssertionError: '1227256' != None

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=5)
FFFFF
======================================================================
FAIL: test_octal_to_decimal (ClassEval_64_0.NumberConvertTestOctalToDecimal.test_octal_to_decimal)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_64_0.py", line 113, in test_octal_to_decimal
    self.assertEqual(42423, NumberConverter.octal_to_decimal('122667'))
AssertionError: 42423 != None

======================================================================
FAIL: test_octal_to_decimal_2 (ClassEval_64_0.NumberConvertTestOctalToDecimal.test_octal_to_decimal_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_64_0.py", line 116, in test_octal_to_decimal_2
    self.assertEqual(21271, NumberConverter.octal_to_decimal('51427'))
AssertionError: 21271 != None

======================================================================
FAIL: test_octal_to_decimal_3 (ClassEval_64_0.NumberConvertTestOctalToDecimal.test_octal_to_decimal_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_64_0.py", line 119, in test_octal_to_decimal_3
    self.assertEqual(84907, NumberConverter.octal_to_decimal('245653'))
AssertionError: 84907 != None

======================================================================
FAIL: test_octal_to_decimal_4 (ClassEval_64_0.NumberConvertTestOctalToDecimal.test_octal_to_decimal_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_64_0.py", line 122, in test_octal_to_decimal_4
    self.assertEqual(169815, NumberConverter.octal_to_decimal('513527'))
AssertionError: 169815 != None

======================================================================
FAIL: test_octal_to_decimal_5 (ClassEval_64_0.NumberConvertTestOctalToDecimal.test_octal_to_decimal_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_64_0.py", line 125, in test_octal_to_decimal_5
    self.assertEqual(339630, NumberConverter.octal_to_decimal('1227256'))
AssertionError: 339630 != None

----------------------------------------------------------------------
Ran 5 tests in 0.002s

FAILED (failures=5)
FFFFF
======================================================================
FAIL: test_decimal_to_hex (ClassEval_64_0.NumberConvertTestDecimalToHex.test_decimal_to_hex)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_64_0.py", line 129, in test_decimal_to_hex
    self.assertEqual('a5b7', NumberConverter.decimal_to_hex(42423))
AssertionError: 'a5b7' != None

======================================================================
FAIL: test_decimal_to_hex_2 (ClassEval_64_0.NumberConvertTestDecimalToHex.test_decimal_to_hex_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_64_0.py", line 132, in test_decimal_to_hex_2
    self.assertEqual('5317', NumberConverter.decimal_to_hex(21271))
AssertionError: '5317' != None

======================================================================
FAIL: test_decimal_to_hex_3 (ClassEval_64_0.NumberConvertTestDecimalToHex.test_decimal_to_hex_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_64_0.py", line 135, in test_decimal_to_hex_3
    self.assertEqual('14bab', NumberConverter.decimal_to_hex(84907))
AssertionError: '14bab' != None

======================================================================
FAIL: test_decimal_to_hex_4 (ClassEval_64_0.NumberConvertTestDecimalToHex.test_decimal_to_hex_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_64_0.py", line 138, in test_decimal_to_hex_4
    self.assertEqual('29757', NumberConverter.decimal_to_hex(169815))
AssertionError: '29757' != None

======================================================================
FAIL: test_decimal_to_hex_5 (ClassEval_64_0.NumberConvertTestDecimalToHex.test_decimal_to_hex_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_64_0.py", line 141, in test_decimal_to_hex_5
    self.assertEqual('52eb7', NumberConverter.decimal_to_hex(339639))
AssertionError: '52eb7' != None

----------------------------------------------------------------------
Ran 5 tests in 0.002s

FAILED (failures=5)
FFFFF
======================================================================
FAIL: test_hex_to_decimal (ClassEval_64_0.NumberConvertTestHexToDecimal.test_hex_to_decimal)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_64_0.py", line 145, in test_hex_to_decimal
    self.assertEqual(42423, NumberConverter.hex_to_decimal('a5b7'))
AssertionError: 42423 != None

======================================================================
FAIL: test_hex_to_decimal_2 (ClassEval_64_0.NumberConvertTestHexToDecimal.test_hex_to_decimal_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_64_0.py", line 148, in test_hex_to_decimal_2
    self.assertEqual(21207, NumberConverter.hex_to_decimal('52d7'))
AssertionError: 21207 != None

======================================================================
FAIL: test_hex_to_decimal_3 (ClassEval_64_0.NumberConvertTestHexToDecimal.test_hex_to_decimal_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_64_0.py", line 151, in test_hex_to_decimal_3
    self.assertEqual(84627, NumberConverter.hex_to_decimal('14a93'))
AssertionError: 84627 != None

======================================================================
FAIL: test_hex_to_decimal_4 (ClassEval_64_0.NumberConvertTestHexToDecimal.test_hex_to_decimal_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_64_0.py", line 154, in test_hex_to_decimal_4
    self.assertEqual(170615, NumberConverter.hex_to_decimal('29a77'))
AssertionError: 170615 != None

======================================================================
FAIL: test_hex_to_decimal_5 (ClassEval_64_0.NumberConvertTestHexToDecimal.test_hex_to_decimal_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_64_0.py", line 157, in test_hex_to_decimal_5
    self.assertEqual(342647, NumberConverter.hex_to_decimal('53a77'))
AssertionError: 342647 != None

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=5)
F
======================================================================
FAIL: test_main (ClassEval_64_0.NumberConvertTestMain.test_main)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_64_0.py", line 161, in test_main
    self.assertEqual('1010010110110111', NumberConverter.decimal_to_binary(42423))
AssertionError: '1010010110110111' != None

----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (failures=1)
..FFF
======================================================================
FAIL: test_validate_name_3 (ClassEval_70_0.PersonRequestTestValidateName.test_validate_name_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_70_0.py", line 49, in test_validate_name_3
    self.assertEqual(pr.name, 'aaa')
AssertionError: None != 'aaa'

======================================================================
FAIL: test_validate_name_4 (ClassEval_70_0.PersonRequestTestValidateName.test_validate_name_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_70_0.py", line 53, in test_validate_name_4
    self.assertEqual(pr.name, 'bbb')
AssertionError: None != 'bbb'

======================================================================
FAIL: test_validate_name_5 (ClassEval_70_0.PersonRequestTestValidateName.test_validate_name_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_70_0.py", line 57, in test_validate_name_5
    self.assertEqual(pr.name, 'ccc')
AssertionError: None != 'ccc'

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=3)
.FFF.
======================================================================
FAIL: test_validate_sex_2 (ClassEval_70_0.PersonRequestTestValidateSex.test_validate_sex_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_70_0.py", line 67, in test_validate_sex_2
    self.assertEqual(pr.sex, "UGM")
AssertionError: None != 'UGM'

======================================================================
FAIL: test_validate_sex_3 (ClassEval_70_0.PersonRequestTestValidateSex.test_validate_sex_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_70_0.py", line 71, in test_validate_sex_3
    self.assertEqual(pr.sex, "Man")
AssertionError: None != 'Man'

======================================================================
FAIL: test_validate_sex_4 (ClassEval_70_0.PersonRequestTestValidateSex.test_validate_sex_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_70_0.py", line 75, in test_validate_sex_4
    self.assertEqual(pr.sex, "Woman")
AssertionError: None != 'Woman'

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=3)
...FF
======================================================================
FAIL: test_validate_phoneNumber_4 (ClassEval_70_0.PersonRequestTestValidatePhoneNumber.test_validate_phoneNumber_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_70_0.py", line 97, in test_validate_phoneNumber_4
    self.assertEqual(pr.phoneNumber, "12345678901")
AssertionError: None != '12345678901'

======================================================================
FAIL: test_validate_phoneNumber_5 (ClassEval_70_0.PersonRequestTestValidatePhoneNumber.test_validate_phoneNumber_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_70_0.py", line 101, in test_validate_phoneNumber_5
    self.assertEqual(pr.phoneNumber, "11111111111")
AssertionError: None != '11111111111'

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=2)
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
FFFFF
======================================================================
FAIL: test_add_stock (ClassEval_82_0.StockPortfolioTrackerTestAddStock.test_add_stock)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_82_0.py", line 91, in test_add_stock
    self.assertEqual(tracker.portfolio, [{'name': 'AAPL', 'price': 150.0, 'quantity': 10}])
AssertionError: Lists differ: [] != [{'name': 'AAPL', 'price': 150.0, 'quantity': 10}]

Second list contains 1 additional elements.
First extra element 0:
{'name': 'AAPL', 'price': 150.0, 'quantity': 10}

- []
+ [{'name': 'AAPL', 'price': 150.0, 'quantity': 10}]

======================================================================
FAIL: test_add_stock_2 (ClassEval_82_0.StockPortfolioTrackerTestAddStock.test_add_stock_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_82_0.py", line 97, in test_add_stock_2
    self.assertEqual(tracker.portfolio, [{'name': 'AAPL', 'price': 150.0, 'quantity': 20}])
AssertionError: Lists differ: [{'name': 'AAPL', 'price': 150.0, 'quantity': 10}] != [{'name': 'AAPL', 'price': 150.0, 'quantity': 20}]

First differing element 0:
{'name': 'AAPL', 'price': 150.0, 'quantity': 10}
{'name': 'AAPL', 'price': 150.0, 'quantity': 20}

- [{'name': 'AAPL', 'price': 150.0, 'quantity': 10}]
?                                               ^

+ [{'name': 'AAPL', 'price': 150.0, 'quantity': 20}]
?                                               ^


======================================================================
FAIL: test_add_stock_3 (ClassEval_82_0.StockPortfolioTrackerTestAddStock.test_add_stock_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_82_0.py", line 103, in test_add_stock_3
    self.assertEqual(tracker.portfolio, [{'name': 'AAPL', 'price': 150.0, 'quantity': 10},
AssertionError: Lists differ: [{'na[32 chars]antity': 10}] != [{'na[32 chars]antity': 10}, {'name': 'MSFT', 'price': 150.0, 'quantity': 10}]

Second list contains 1 additional elements.
First extra element 1:
{'name': 'MSFT', 'price': 150.0, 'quantity': 10}

- [{'name': 'AAPL', 'price': 150.0, 'quantity': 10}]
?                                                  ^

+ [{'name': 'AAPL', 'price': 150.0, 'quantity': 10},
?                                                  ^

+  {'name': 'MSFT', 'price': 150.0, 'quantity': 10}]

======================================================================
FAIL: test_add_stock_4 (ClassEval_82_0.StockPortfolioTrackerTestAddStock.test_add_stock_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_82_0.py", line 111, in test_add_stock_4
    self.assertEqual(tracker.portfolio, [{'name': 'AAPL', 'price': 150.0, 'quantity': 20},
AssertionError: Lists differ: [{'na[32 chars]antity': 10}] != [{'na[32 chars]antity': 20}, {'name': 'MSFT', 'price': 150.0, 'quantity': 10}]

First differing element 0:
{'name': 'AAPL', 'price': 150.0, 'quantity': 10}
{'name': 'AAPL', 'price': 150.0, 'quantity': 20}

Second list contains 1 additional elements.
First extra element 1:
{'name': 'MSFT', 'price': 150.0, 'quantity': 10}

- [{'name': 'AAPL', 'price': 150.0, 'quantity': 10}]
?                                               ^  ^

+ [{'name': 'AAPL', 'price': 150.0, 'quantity': 20},
?                                               ^  ^

+  {'name': 'MSFT', 'price': 150.0, 'quantity': 10}]

======================================================================
FAIL: test_add_stock_5 (ClassEval_82_0.StockPortfolioTrackerTestAddStock.test_add_stock_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_82_0.py", line 120, in test_add_stock_5
    self.assertEqual(tracker.portfolio, [{'name': 'AAPL', 'price': 150.0, 'quantity': 20},
AssertionError: Lists differ: [{'na[32 chars]antity': 10}] != [{'na[32 chars]antity': 20}, {'name': 'MSFT', 'price': 150.0, 'quantity': 20}]

First differing element 0:
{'name': 'AAPL', 'price': 150.0, 'quantity': 10}
{'name': 'AAPL', 'price': 150.0, 'quantity': 20}

Second list contains 1 additional elements.
First extra element 1:
{'name': 'MSFT', 'price': 150.0, 'quantity': 20}

- [{'name': 'AAPL', 'price': 150.0, 'quantity': 10}]
?                                               ^  ^

+ [{'name': 'AAPL', 'price': 150.0, 'quantity': 20},
?                                               ^  ^

+  {'name': 'MSFT', 'price': 150.0, 'quantity': 20}]

----------------------------------------------------------------------
Ran 5 tests in 0.004s

FAILED (failures=5)
FFFFF
======================================================================
FAIL: test_remove_stock (ClassEval_82_0.StockPortfolioTrackerTestRemoveStock.test_remove_stock)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_82_0.py", line 128, in test_remove_stock
    self.assertEqual(tracker.remove_stock({"name": "AAPL", "price": 150.0, "quantity": 10}), True)
AssertionError: None != True

======================================================================
FAIL: test_remove_stock_2 (ClassEval_82_0.StockPortfolioTrackerTestRemoveStock.test_remove_stock_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_82_0.py", line 135, in test_remove_stock_2
    self.assertEqual(tracker.remove_stock({"name": "AAPL", "price": 150.0, "quantity": 10}), True)
AssertionError: None != True

======================================================================
FAIL: test_remove_stock_3 (ClassEval_82_0.StockPortfolioTrackerTestRemoveStock.test_remove_stock_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_82_0.py", line 142, in test_remove_stock_3
    self.assertEqual(tracker.remove_stock({"name": "MSFT", "price": 150.0, "quantity": 20}), False)
AssertionError: None != False

======================================================================
FAIL: test_remove_stock_4 (ClassEval_82_0.StockPortfolioTrackerTestRemoveStock.test_remove_stock_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_82_0.py", line 149, in test_remove_stock_4
    self.assertEqual(tracker.remove_stock({"name": "MSFT", "price": 150.0, "quantity": 10}), False)
AssertionError: None != False

======================================================================
FAIL: test_remove_stock_5 (ClassEval_82_0.StockPortfolioTrackerTestRemoveStock.test_remove_stock_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_82_0.py", line 156, in test_remove_stock_5
    self.assertEqual(tracker.remove_stock({"name": "MSFT", "price": 150.0, "quantity": 10}), True)
AssertionError: None != True

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=5)
EEEEE
======================================================================
ERROR: test_buy_stock (ClassEval_82_0.StockPortfolioTrackerTestBuyStock.test_buy_stock)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_82_0.py", line 163, in test_buy_stock
    self.assertEqual(tracker.buy_stock({"name": "AAPL", "price": 150.0, "quantity": 10}), True)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: StockPortfolioTracker.buy_stock() missing 1 required positional argument: 'quantity'

======================================================================
ERROR: test_buy_stock_2 (ClassEval_82_0.StockPortfolioTrackerTestBuyStock.test_buy_stock_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_82_0.py", line 169, in test_buy_stock_2
    self.assertEqual(tracker.buy_stock({"name": "AAPL", "price": 150.0, "quantity": 10}), False)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: StockPortfolioTracker.buy_stock() missing 1 required positional argument: 'quantity'

======================================================================
ERROR: test_buy_stock_3 (ClassEval_82_0.StockPortfolioTrackerTestBuyStock.test_buy_stock_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_82_0.py", line 176, in test_buy_stock_3
    self.assertEqual(tracker.buy_stock({"name": "AAPL", "price": 150.0, "quantity": 10}), True)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: StockPortfolioTracker.buy_stock() missing 1 required positional argument: 'quantity'

======================================================================
ERROR: test_buy_stock_4 (ClassEval_82_0.StockPortfolioTrackerTestBuyStock.test_buy_stock_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_82_0.py", line 183, in test_buy_stock_4
    self.assertEqual(tracker.buy_stock({"name": "MSFT", "price": 150.0, "quantity": 10}), True)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: StockPortfolioTracker.buy_stock() missing 1 required positional argument: 'quantity'

======================================================================
ERROR: test_buy_stock_5 (ClassEval_82_0.StockPortfolioTrackerTestBuyStock.test_buy_stock_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_82_0.py", line 192, in test_buy_stock_5
    self.assertEqual(tracker.buy_stock({"name": "AAPL", "price": 150.0, "quantity": 10}), True)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: StockPortfolioTracker.buy_stock() missing 1 required positional argument: 'quantity'

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (errors=5)
EEEEE
======================================================================
ERROR: test_sell_stock (ClassEval_82_0.StockPortfolioTrackerTestSellStock.test_sell_stock)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_82_0.py", line 203, in test_sell_stock
    self.assertEqual(tracker.sell_stock({"name": "AAPL", "price": 150.0, "quantity": 9}), True)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: StockPortfolioTracker.sell_stock() missing 1 required positional argument: 'quantity'

======================================================================
ERROR: test_sell_stock_2 (ClassEval_82_0.StockPortfolioTrackerTestSellStock.test_sell_stock_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_82_0.py", line 210, in test_sell_stock_2
    self.assertEqual(tracker.sell_stock({"name": "AAPL", "price": 150.0, "quantity": 20}), False)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: StockPortfolioTracker.sell_stock() missing 1 required positional argument: 'quantity'

======================================================================
ERROR: test_sell_stock_3 (ClassEval_82_0.StockPortfolioTrackerTestSellStock.test_sell_stock_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_82_0.py", line 216, in test_sell_stock_3
    self.assertEqual(tracker.sell_stock({"name": "AAPL", "price": 150.0, "quantity": 10}), False)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: StockPortfolioTracker.sell_stock() missing 1 required positional argument: 'quantity'

======================================================================
ERROR: test_sell_stock_4 (ClassEval_82_0.StockPortfolioTrackerTestSellStock.test_sell_stock_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_82_0.py", line 223, in test_sell_stock_4
    self.assertEqual(tracker.sell_stock({"name": "AAPL", "price": 150.0, "quantity": 20}), True)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: StockPortfolioTracker.sell_stock() missing 1 required positional argument: 'quantity'

======================================================================
ERROR: test_sell_stock_5 (ClassEval_82_0.StockPortfolioTrackerTestSellStock.test_sell_stock_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_82_0.py", line 231, in test_sell_stock_5
    self.assertEqual(tracker.sell_stock({"name": "AAPL", "price": 150.0, "quantity": 20}), True)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: StockPortfolioTracker.sell_stock() missing 1 required positional argument: 'quantity'

----------------------------------------------------------------------
Ran 5 tests in 0.002s

FAILED (errors=5)
FFFFF
======================================================================
FAIL: test_calculate_portfolio_value (ClassEval_82_0.StockPortfolioTrackerTestCalculatePortfolioValue.test_calculate_portfolio_value)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_82_0.py", line 240, in test_calculate_portfolio_value
    self.assertEqual(tracker.calculate_portfolio_value(), 11500.0)
AssertionError: None != 11500.0

======================================================================
FAIL: test_calculate_portfolio_value_2 (ClassEval_82_0.StockPortfolioTrackerTestCalculatePortfolioValue.test_calculate_portfolio_value_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_82_0.py", line 246, in test_calculate_portfolio_value_2
    self.assertEqual(tracker.calculate_portfolio_value(), 13000.0)
AssertionError: None != 13000.0

======================================================================
FAIL: test_calculate_portfolio_value_3 (ClassEval_82_0.StockPortfolioTrackerTestCalculatePortfolioValue.test_calculate_portfolio_value_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_82_0.py", line 250, in test_calculate_portfolio_value_3
    self.assertEqual(tracker.calculate_portfolio_value(), 10000.0)
AssertionError: None != 10000.0

======================================================================
FAIL: test_calculate_portfolio_value_4 (ClassEval_82_0.StockPortfolioTrackerTestCalculatePortfolioValue.test_calculate_portfolio_value_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_82_0.py", line 255, in test_calculate_portfolio_value_4
    self.assertEqual(tracker.calculate_portfolio_value(), 10000.0)
AssertionError: None != 10000.0

======================================================================
FAIL: test_calculate_portfolio_value_5 (ClassEval_82_0.StockPortfolioTrackerTestCalculatePortfolioValue.test_calculate_portfolio_value_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_82_0.py", line 260, in test_calculate_portfolio_value_5
    self.assertEqual(tracker.calculate_portfolio_value(), 10000.0)
AssertionError: None != 10000.0

----------------------------------------------------------------------
Ran 5 tests in 0.002s

FAILED (failures=5)
FFFFF
======================================================================
FAIL: test_get_portfolio_summary (ClassEval_82_0.StockPortfolioTrackerTestGetPortfolioSummary.test_get_portfolio_summary)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_82_0.py", line 267, in test_get_portfolio_summary
    self.assertEqual(tracker.get_portfolio_summary(), (11500.0, [{'name': 'AAPL', 'value': 1500.0}]))
AssertionError: None != (11500.0, [{'name': 'AAPL', 'value': 1500.0}])

======================================================================
FAIL: test_get_portfolio_summary_2 (ClassEval_82_0.StockPortfolioTrackerTestGetPortfolioSummary.test_get_portfolio_summary_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_82_0.py", line 273, in test_get_portfolio_summary_2
    self.assertEqual(tracker.get_portfolio_summary(),
AssertionError: None != (13000.0, [{'name': 'AAPL', 'value': 1500[35 chars].0}])

======================================================================
FAIL: test_get_portfolio_summary_3 (ClassEval_82_0.StockPortfolioTrackerTestGetPortfolioSummary.test_get_portfolio_summary_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_82_0.py", line 278, in test_get_portfolio_summary_3
    self.assertEqual(tracker.get_portfolio_summary(), (10000.0, []))
AssertionError: None != (10000.0, [])

======================================================================
FAIL: test_get_portfolio_summary_4 (ClassEval_82_0.StockPortfolioTrackerTestGetPortfolioSummary.test_get_portfolio_summary_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_82_0.py", line 283, in test_get_portfolio_summary_4
    self.assertEqual(tracker.get_portfolio_summary(), (10000.0, [{'name': 'AAPL', 'value': 0.0}]))
AssertionError: None != (10000.0, [{'name': 'AAPL', 'value': 0.0}])

======================================================================
FAIL: test_get_portfolio_summary_5 (ClassEval_82_0.StockPortfolioTrackerTestGetPortfolioSummary.test_get_portfolio_summary_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_82_0.py", line 288, in test_get_portfolio_summary_5
    self.assertEqual(tracker.get_portfolio_summary(), (10000.0, [{'name': 'AAPL', 'value': 0.0}]))
AssertionError: None != (10000.0, [{'name': 'AAPL', 'value': 0.0}])

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=5)
FFFFF
======================================================================
FAIL: test_get_stock_value (ClassEval_82_0.StockPortfolioTrackerTestGetStockValue.test_get_stock_value)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_82_0.py", line 294, in test_get_stock_value
    self.assertEqual(tracker.get_stock_value({"name": "AAPL", "price": 150.0, "quantity": 10}), 1500.0)
AssertionError: None != 1500.0

======================================================================
FAIL: test_get_stock_value_2 (ClassEval_82_0.StockPortfolioTrackerTestGetStockValue.test_get_stock_value_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_82_0.py", line 298, in test_get_stock_value_2
    self.assertEqual(tracker.get_stock_value({"name": "AAPL", "price": 150.0, "quantity": 0}), 0.0)
AssertionError: None != 0.0

======================================================================
FAIL: test_get_stock_value_3 (ClassEval_82_0.StockPortfolioTrackerTestGetStockValue.test_get_stock_value_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_82_0.py", line 302, in test_get_stock_value_3
    self.assertEqual(tracker.get_stock_value({"name": "AAPL", "price": 0.0, "quantity": 10}), 0.0)
AssertionError: None != 0.0

======================================================================
FAIL: test_get_stock_value_4 (ClassEval_82_0.StockPortfolioTrackerTestGetStockValue.test_get_stock_value_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_82_0.py", line 306, in test_get_stock_value_4
    self.assertEqual(tracker.get_stock_value({"name": "AAPL", "price": 0.0, "quantity": 0}), 0.0)
AssertionError: None != 0.0

======================================================================
FAIL: test_get_stock_value_5 (ClassEval_82_0.StockPortfolioTrackerTestGetStockValue.test_get_stock_value_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_82_0.py", line 310, in test_get_stock_value_5
    self.assertEqual(tracker.get_stock_value({"name": "MSFL", "price": 150.0, "quantity": 2}), 300.0)
AssertionError: None != 300.0

----------------------------------------------------------------------
Ran 5 tests in 0.002s

FAILED (failures=5)
FFF
======================================================================
FAIL: test_main (ClassEval_82_0.StockPortfolioTrackerTestMain.test_main)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_82_0.py", line 317, in test_main
    self.assertEqual(tracker.portfolio, [{'name': 'AAPL', 'price': 150.0, 'quantity': 10}])
AssertionError: Lists differ: [] != [{'name': 'AAPL', 'price': 150.0, 'quantity': 10}]

Second list contains 1 additional elements.
First extra element 0:
{'name': 'AAPL', 'price': 150.0, 'quantity': 10}

- []
+ [{'name': 'AAPL', 'price': 150.0, 'quantity': 10}]

======================================================================
FAIL: test_main_2 (ClassEval_82_0.StockPortfolioTrackerTestMain.test_main_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_82_0.py", line 336, in test_main_2
    self.assertEqual(tracker.portfolio, [{'name': 'AAPL', 'price': 150.0, 'quantity': 10},
AssertionError: Lists differ: [{'na[32 chars]antity': 10}] != [{'na[32 chars]antity': 10}, {'name': 'MSFT', 'price': 150.0, 'quantity': 10}]

Second list contains 1 additional elements.
First extra element 1:
{'name': 'MSFT', 'price': 150.0, 'quantity': 10}

- [{'name': 'AAPL', 'price': 150.0, 'quantity': 10}]
?                                                  ^

+ [{'name': 'AAPL', 'price': 150.0, 'quantity': 10},
?                                                  ^

+  {'name': 'MSFT', 'price': 150.0, 'quantity': 10}]

======================================================================
FAIL: test_main_3 (ClassEval_82_0.StockPortfolioTrackerTestMain.test_main_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_82_0.py", line 352, in test_main_3
    self.assertEqual(tracker.get_stock_value({"name": "MSFT", "price": 150.0, "quantity": 10}), 1500.0)
AssertionError: None != 1500.0

----------------------------------------------------------------------
Ran 3 tests in 0.002s

FAILED (failures=3)
FFFFF.
======================================================================
FAIL: test_get_scheme_1 (ClassEval_90_0.URLHandlerTestGetScheme.test_get_scheme_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_90_0.py", line 66, in test_get_scheme_1
    self.assertEqual(temp, "https")
AssertionError: None != 'https'

======================================================================
FAIL: test_get_scheme_2 (ClassEval_90_0.URLHandlerTestGetScheme.test_get_scheme_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_90_0.py", line 72, in test_get_scheme_2
    self.assertEqual(temp, "https")
AssertionError: None != 'https'

======================================================================
FAIL: test_get_scheme_3 (ClassEval_90_0.URLHandlerTestGetScheme.test_get_scheme_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_90_0.py", line 77, in test_get_scheme_3
    self.assertEqual(temp, "https")
AssertionError: None != 'https'

======================================================================
FAIL: test_get_scheme_4 (ClassEval_90_0.URLHandlerTestGetScheme.test_get_scheme_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_90_0.py", line 82, in test_get_scheme_4
    self.assertEqual(temp, "aaa")
AssertionError: None != 'aaa'

======================================================================
FAIL: test_get_scheme_5 (ClassEval_90_0.URLHandlerTestGetScheme.test_get_scheme_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_90_0.py", line 87, in test_get_scheme_5
    self.assertEqual(temp, "bbb")
AssertionError: None != 'bbb'

----------------------------------------------------------------------
Ran 6 tests in 0.002s

FAILED (failures=5)
FFFFF.FF
======================================================================
FAIL: test_get_host_1 (ClassEval_90_0.URLHandlerTestGetHost.test_get_host_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_90_0.py", line 99, in test_get_host_1
    self.assertEqual(temp, "www.baidu.com")
AssertionError: None != 'www.baidu.com'

======================================================================
FAIL: test_get_host_2 (ClassEval_90_0.URLHandlerTestGetHost.test_get_host_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_90_0.py", line 105, in test_get_host_2
    self.assertEqual(temp, "www.bing.com")
AssertionError: None != 'www.bing.com'

======================================================================
FAIL: test_get_host_3 (ClassEval_90_0.URLHandlerTestGetHost.test_get_host_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_90_0.py", line 110, in test_get_host_3
    self.assertEqual(temp, "github.com")
AssertionError: None != 'github.com'

======================================================================
FAIL: test_get_host_4 (ClassEval_90_0.URLHandlerTestGetHost.test_get_host_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_90_0.py", line 115, in test_get_host_4
    self.assertEqual(temp, "aaa.com")
AssertionError: None != 'aaa.com'

======================================================================
FAIL: test_get_host_5 (ClassEval_90_0.URLHandlerTestGetHost.test_get_host_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_90_0.py", line 120, in test_get_host_5
    self.assertEqual(temp, "bbb.com")
AssertionError: None != 'bbb.com'

======================================================================
FAIL: test_get_host_7 (ClassEval_90_0.URLHandlerTestGetHost.test_get_host_7)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_90_0.py", line 130, in test_get_host_7
    self.assertEqual(temp, "bbb.com")
AssertionError: None != 'bbb.com'

======================================================================
FAIL: test_get_host_8 (ClassEval_90_0.URLHandlerTestGetHost.test_get_host_8)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_90_0.py", line 135, in test_get_host_8
    self.assertEqual(temp, "bbb.com")
AssertionError: None != 'bbb.com'

----------------------------------------------------------------------
Ran 8 tests in 0.002s

FAILED (failures=7)
FFFFF.
======================================================================
FAIL: test_get_path_1 (ClassEval_90_0.URLHandlerTestGetPath.test_get_path_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_90_0.py", line 142, in test_get_path_1
    self.assertEqual(temp, "/s?wd=aaa&rsv_spt=1#page")
AssertionError: None != '/s?wd=aaa&rsv_spt=1#page'

======================================================================
FAIL: test_get_path_2 (ClassEval_90_0.URLHandlerTestGetPath.test_get_path_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_90_0.py", line 148, in test_get_path_2
    self.assertEqual(temp,
AssertionError: None != '/search?pglt=41&q=humaneval&cvid=4dc2da2[88 chars]h-CN'

======================================================================
FAIL: test_get_path_3 (ClassEval_90_0.URLHandlerTestGetPath.test_get_path_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_90_0.py", line 154, in test_get_path_3
    self.assertEqual(temp, "/openai/human-eval")
AssertionError: None != '/openai/human-eval'

======================================================================
FAIL: test_get_path_4 (ClassEval_90_0.URLHandlerTestGetPath.test_get_path_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_90_0.py", line 159, in test_get_path_4
    self.assertEqual(temp, "/aaa/human-eval")
AssertionError: None != '/aaa/human-eval'

======================================================================
FAIL: test_get_path_5 (ClassEval_90_0.URLHandlerTestGetPath.test_get_path_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_90_0.py", line 164, in test_get_path_5
    self.assertEqual(temp, "/bbb/human-eval")
AssertionError: None != '/bbb/human-eval'

----------------------------------------------------------------------
Ran 6 tests in 0.002s

FAILED (failures=5)
FF.FFF
======================================================================
FAIL: test_get_query_params_1 (ClassEval_90_0.URLHandlerTestGetQueryParams.test_get_query_params_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_90_0.py", line 176, in test_get_query_params_1
    self.assertEqual(temp, {"wd": "aaa", "rsv_spt": "1"})
AssertionError: None != {'wd': 'aaa', 'rsv_spt': '1'}

======================================================================
FAIL: test_get_query_params_2 (ClassEval_90_0.URLHandlerTestGetQueryParams.test_get_query_params_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_90_0.py", line 182, in test_get_query_params_2
    self.assertEqual(temp, {"pglt": "41", "q": "humaneval", "cvid": "4dc2da2bb4bc429eb498c85245ae5253",
AssertionError: None != {'pglt': '41', 'q': 'humaneval', 'cvid': [105 chars]531'}

======================================================================
FAIL: test_get_query_params_4 (ClassEval_90_0.URLHandlerTestGetQueryParams.test_get_query_params_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_90_0.py", line 193, in test_get_query_params_4
    self.assertEqual(temp, {"wd": "bbb", "rsv_spt": "1"})
AssertionError: None != {'wd': 'bbb', 'rsv_spt': '1'}

======================================================================
FAIL: test_get_query_params_5 (ClassEval_90_0.URLHandlerTestGetQueryParams.test_get_query_params_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_90_0.py", line 198, in test_get_query_params_5
    self.assertEqual(temp, {"wd": "ccc", "rsv_spt": "1"})
AssertionError: None != {'wd': 'ccc', 'rsv_spt': '1'}

======================================================================
FAIL: test_get_query_params_6 (ClassEval_90_0.URLHandlerTestGetQueryParams.test_get_query_params_6)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_90_0.py", line 203, in test_get_query_params_6
    self.assertEqual(temp, {})
AssertionError: None != {}

----------------------------------------------------------------------
Ran 6 tests in 0.001s

FAILED (failures=5)
F.FFF
======================================================================
FAIL: test_get_fragment_1 (ClassEval_90_0.URLHandlerTestGetFragment.test_get_fragment_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_90_0.py", line 210, in test_get_fragment_1
    self.assertEqual(temp, "page")
AssertionError: None != 'page'

======================================================================
FAIL: test_get_fragment_3 (ClassEval_90_0.URLHandlerTestGetFragment.test_get_fragment_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_90_0.py", line 221, in test_get_fragment_3
    self.assertEqual(temp, "aaa")
AssertionError: None != 'aaa'

======================================================================
FAIL: test_get_fragment_4 (ClassEval_90_0.URLHandlerTestGetFragment.test_get_fragment_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_90_0.py", line 226, in test_get_fragment_4
    self.assertEqual(temp, "bbb")
AssertionError: None != 'bbb'

======================================================================
FAIL: test_get_fragment_5 (ClassEval_90_0.URLHandlerTestGetFragment.test_get_fragment_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_90_0.py", line 231, in test_get_fragment_5
    self.assertEqual(temp, "ccc")
AssertionError: None != 'ccc'

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=4)
F
======================================================================
FAIL: test_urlhandler (ClassEval_90_0.URLHandlerTest.test_urlhandler)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_90_0.py", line 238, in test_urlhandler
    self.assertEqual(temp, "https")
AssertionError: None != 'https'

----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (failures=1)
