.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
EEEEEE
======================================================================
ERROR: test_calculate_hand_value_1 (ClassEval_12_0.BlackjackGameTestCalculateHandValue.test_calculate_hand_value_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_12_0.py", line 76, in test_calculate_hand_value_1
    self.assertEqual(blackjackGame.calculate_hand_value(hand), 14)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'BlackjackGame' object has no attribute 'calculate_hand_value'

======================================================================
ERROR: test_calculate_hand_value_2 (ClassEval_12_0.BlackjackGameTestCalculateHandValue.test_calculate_hand_value_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_12_0.py", line 81, in test_calculate_hand_value_2
    self.assertEqual(blackjackGame.calculate_hand_value(hand), 25)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'BlackjackGame' object has no attribute 'calculate_hand_value'

======================================================================
ERROR: test_calculate_hand_value_3 (ClassEval_12_0.BlackjackGameTestCalculateHandValue.test_calculate_hand_value_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_12_0.py", line 86, in test_calculate_hand_value_3
    self.assertEqual(blackjackGame.calculate_hand_value(hand), 20)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'BlackjackGame' object has no attribute 'calculate_hand_value'

======================================================================
ERROR: test_calculate_hand_value_4 (ClassEval_12_0.BlackjackGameTestCalculateHandValue.test_calculate_hand_value_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_12_0.py", line 91, in test_calculate_hand_value_4
    self.assertEqual(blackjackGame.calculate_hand_value(hand), 25)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'BlackjackGame' object has no attribute 'calculate_hand_value'

======================================================================
ERROR: test_calculate_hand_value_5 (ClassEval_12_0.BlackjackGameTestCalculateHandValue.test_calculate_hand_value_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_12_0.py", line 96, in test_calculate_hand_value_5
    self.assertEqual(blackjackGame.calculate_hand_value(hand), 23)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'BlackjackGame' object has no attribute 'calculate_hand_value'

======================================================================
ERROR: test_calculate_hand_value_6 (ClassEval_12_0.BlackjackGameTestCalculateHandValue.test_calculate_hand_value_6)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_12_0.py", line 101, in test_calculate_hand_value_6
    self.assertEqual(blackjackGame.calculate_hand_value(hand), 20)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'BlackjackGame' object has no attribute 'calculate_hand_value'

----------------------------------------------------------------------
Ran 6 tests in 0.003s

FAILED (errors=6)
EEEEEE
======================================================================
ERROR: test_check_winner_1 (ClassEval_12_0.BlackjackGameTestCheckWinner.test_check_winner_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_12_0.py", line 112, in test_check_winner_1
    self.assertEqual(self.blackjackGame.check_winner(player_hand, dealer_hand), 'Dealer wins')
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'BlackjackGame' object has no attribute 'check_winner'

======================================================================
ERROR: test_check_winner_2 (ClassEval_12_0.BlackjackGameTestCheckWinner.test_check_winner_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_12_0.py", line 118, in test_check_winner_2
    self.assertEqual(self.blackjackGame.check_winner(player_hand, dealer_hand), 'Player wins')
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'BlackjackGame' object has no attribute 'check_winner'

======================================================================
ERROR: test_check_winner_3 (ClassEval_12_0.BlackjackGameTestCheckWinner.test_check_winner_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_12_0.py", line 124, in test_check_winner_3
    self.assertEqual(self.blackjackGame.check_winner(player_hand, dealer_hand), 'Dealer wins')
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'BlackjackGame' object has no attribute 'check_winner'

======================================================================
ERROR: test_check_winner_4 (ClassEval_12_0.BlackjackGameTestCheckWinner.test_check_winner_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_12_0.py", line 130, in test_check_winner_4
    self.assertEqual(self.blackjackGame.check_winner(player_hand, dealer_hand), 'Player wins')
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'BlackjackGame' object has no attribute 'check_winner'

======================================================================
ERROR: test_check_winner_5 (ClassEval_12_0.BlackjackGameTestCheckWinner.test_check_winner_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_12_0.py", line 136, in test_check_winner_5
    self.assertEqual(self.blackjackGame.check_winner(player_hand, dealer_hand), 'Dealer wins')
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'BlackjackGame' object has no attribute 'check_winner'

======================================================================
ERROR: test_check_winner_6 (ClassEval_12_0.BlackjackGameTestCheckWinner.test_check_winner_6)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_12_0.py", line 142, in test_check_winner_6
    self.assertEqual(self.blackjackGame.check_winner(player_hand, dealer_hand), 'Player wins')
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'BlackjackGame' object has no attribute 'check_winner'

----------------------------------------------------------------------
Ran 6 tests in 0.006s

FAILED (errors=6)
E
======================================================================
ERROR: test_main_1 (ClassEval_12_0.BlackjackGameTestMain.test_main_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_12_0.py", line 157, in test_main_1
    self.assertEqual(blackjackGame.check_winner(player_hand, dealer_hand), 'Dealer wins')
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'BlackjackGame' object has no attribute 'check_winner'

----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (errors=1)
EEEEE
======================================================================
ERROR: test_find_blank_1 (ClassEval_35_0.EightPuzzleTestFindBlank.test_find_blank_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_35_0.py", line 8, in test_find_blank_1
    eightPuzzle = EightPuzzle(state)
                  ^^^^^^^^^^^
NameError: name 'EightPuzzle' is not defined

======================================================================
ERROR: test_find_blank_2 (ClassEval_35_0.EightPuzzleTestFindBlank.test_find_blank_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_35_0.py", line 13, in test_find_blank_2
    eightPuzzle = EightPuzzle(state)
                  ^^^^^^^^^^^
NameError: name 'EightPuzzle' is not defined

======================================================================
ERROR: test_find_blank_3 (ClassEval_35_0.EightPuzzleTestFindBlank.test_find_blank_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_35_0.py", line 18, in test_find_blank_3
    eightPuzzle = EightPuzzle(state)
                  ^^^^^^^^^^^
NameError: name 'EightPuzzle' is not defined

======================================================================
ERROR: test_find_blank_4 (ClassEval_35_0.EightPuzzleTestFindBlank.test_find_blank_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_35_0.py", line 23, in test_find_blank_4
    eightPuzzle = EightPuzzle(state)
                  ^^^^^^^^^^^
NameError: name 'EightPuzzle' is not defined

======================================================================
ERROR: test_find_blank_5 (ClassEval_35_0.EightPuzzleTestFindBlank.test_find_blank_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_35_0.py", line 28, in test_find_blank_5
    eightPuzzle = EightPuzzle(state)
                  ^^^^^^^^^^^
NameError: name 'EightPuzzle' is not defined

----------------------------------------------------------------------
Ran 5 tests in 0.013s

FAILED (errors=5)
EEEEE
======================================================================
ERROR: test_move_1 (ClassEval_35_0.EightPuzzleTestMove.test_move_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_35_0.py", line 35, in setUp
    self.eightPuzzle = EightPuzzle(self.initial_state)
                       ^^^^^^^^^^^
NameError: name 'EightPuzzle' is not defined

======================================================================
ERROR: test_move_2 (ClassEval_35_0.EightPuzzleTestMove.test_move_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_35_0.py", line 35, in setUp
    self.eightPuzzle = EightPuzzle(self.initial_state)
                       ^^^^^^^^^^^
NameError: name 'EightPuzzle' is not defined

======================================================================
ERROR: test_move_3 (ClassEval_35_0.EightPuzzleTestMove.test_move_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_35_0.py", line 35, in setUp
    self.eightPuzzle = EightPuzzle(self.initial_state)
                       ^^^^^^^^^^^
NameError: name 'EightPuzzle' is not defined

======================================================================
ERROR: test_move_4 (ClassEval_35_0.EightPuzzleTestMove.test_move_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_35_0.py", line 35, in setUp
    self.eightPuzzle = EightPuzzle(self.initial_state)
                       ^^^^^^^^^^^
NameError: name 'EightPuzzle' is not defined

======================================================================
ERROR: test_move_5 (ClassEval_35_0.EightPuzzleTestMove.test_move_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_35_0.py", line 35, in setUp
    self.eightPuzzle = EightPuzzle(self.initial_state)
                       ^^^^^^^^^^^
NameError: name 'EightPuzzle' is not defined

----------------------------------------------------------------------
Ran 5 tests in 0.013s

FAILED (errors=5)
EEEEE
======================================================================
ERROR: test_get_possible_moves_1 (ClassEval_35_0.EightPuzzleTestGetPossibleMoves.test_get_possible_moves_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_35_0.py", line 65, in test_get_possible_moves_1
    eightPuzzle = EightPuzzle(None)
                  ^^^^^^^^^^^
NameError: name 'EightPuzzle' is not defined

======================================================================
ERROR: test_get_possible_moves_2 (ClassEval_35_0.EightPuzzleTestGetPossibleMoves.test_get_possible_moves_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_35_0.py", line 73, in test_get_possible_moves_2
    eightPuzzle = EightPuzzle(None)
                  ^^^^^^^^^^^
NameError: name 'EightPuzzle' is not defined

======================================================================
ERROR: test_get_possible_moves_3 (ClassEval_35_0.EightPuzzleTestGetPossibleMoves.test_get_possible_moves_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_35_0.py", line 81, in test_get_possible_moves_3
    eightPuzzle = EightPuzzle(None)
                  ^^^^^^^^^^^
NameError: name 'EightPuzzle' is not defined

======================================================================
ERROR: test_get_possible_moves_4 (ClassEval_35_0.EightPuzzleTestGetPossibleMoves.test_get_possible_moves_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_35_0.py", line 89, in test_get_possible_moves_4
    eightPuzzle = EightPuzzle(None)
                  ^^^^^^^^^^^
NameError: name 'EightPuzzle' is not defined

======================================================================
ERROR: test_get_possible_moves_5 (ClassEval_35_0.EightPuzzleTestGetPossibleMoves.test_get_possible_moves_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_35_0.py", line 97, in test_get_possible_moves_5
    eightPuzzle = EightPuzzle(None)
                  ^^^^^^^^^^^
NameError: name 'EightPuzzle' is not defined

----------------------------------------------------------------------
Ran 5 tests in 0.013s

FAILED (errors=5)
EEEEEE
======================================================================
ERROR: test_solve_1 (ClassEval_35_0.EightPuzzleTestSolve.test_solve_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_35_0.py", line 107, in test_solve_1
    eightPuzzle = EightPuzzle([[1, 2, 3], [4, 5, 6], [7, 0, 8]])
                  ^^^^^^^^^^^
NameError: name 'EightPuzzle' is not defined

======================================================================
ERROR: test_solve_2 (ClassEval_35_0.EightPuzzleTestSolve.test_solve_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_35_0.py", line 113, in test_solve_2
    eightPuzzle = EightPuzzle([[1, 2, 3], [4, 0, 6], [7, 5, 8]])
                  ^^^^^^^^^^^
NameError: name 'EightPuzzle' is not defined

======================================================================
ERROR: test_solve_3 (ClassEval_35_0.EightPuzzleTestSolve.test_solve_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_35_0.py", line 119, in test_solve_3
    eightPuzzle = EightPuzzle([[1, 2, 3], [0, 4, 5], [6, 7, 8]])
                  ^^^^^^^^^^^
NameError: name 'EightPuzzle' is not defined

======================================================================
ERROR: test_solve_4 (ClassEval_35_0.EightPuzzleTestSolve.test_solve_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_35_0.py", line 125, in test_solve_4
    eightPuzzle = EightPuzzle([[1, 2, 3], [4, 5, 6], [7, 8, 0]])
                  ^^^^^^^^^^^
NameError: name 'EightPuzzle' is not defined

======================================================================
ERROR: test_solve_5 (ClassEval_35_0.EightPuzzleTestSolve.test_solve_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_35_0.py", line 131, in test_solve_5
    eightPuzzle = EightPuzzle([[1, 2, 3], [4, 5, 6], [0, 7, 8]])
                  ^^^^^^^^^^^
NameError: name 'EightPuzzle' is not defined

======================================================================
ERROR: test_solve_6 (ClassEval_35_0.EightPuzzleTestSolve.test_solve_6)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_35_0.py", line 137, in test_solve_6
    eightPuzzle = EightPuzzle([[0, 0, 0], [0, 0, 0], [0, 0, 0]])
                  ^^^^^^^^^^^
NameError: name 'EightPuzzle' is not defined

----------------------------------------------------------------------
Ran 6 tests in 0.015s

FAILED (errors=6)
EEEEE
======================================================================
ERROR: test_make_move_1 (ClassEval_41_0.GomokuGameTestMakeMove.test_make_move_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_41_0.py", line 8, in setUp
    self.gomokuGame = GomokuGame(self.board_size)
                      ^^^^^^^^^^
NameError: name 'GomokuGame' is not defined

======================================================================
ERROR: test_make_move_2 (ClassEval_41_0.GomokuGameTestMakeMove.test_make_move_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_41_0.py", line 8, in setUp
    self.gomokuGame = GomokuGame(self.board_size)
                      ^^^^^^^^^^
NameError: name 'GomokuGame' is not defined

======================================================================
ERROR: test_make_move_3 (ClassEval_41_0.GomokuGameTestMakeMove.test_make_move_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_41_0.py", line 8, in setUp
    self.gomokuGame = GomokuGame(self.board_size)
                      ^^^^^^^^^^
NameError: name 'GomokuGame' is not defined

======================================================================
ERROR: test_make_move_4 (ClassEval_41_0.GomokuGameTestMakeMove.test_make_move_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_41_0.py", line 8, in setUp
    self.gomokuGame = GomokuGame(self.board_size)
                      ^^^^^^^^^^
NameError: name 'GomokuGame' is not defined

======================================================================
ERROR: test_make_move_5 (ClassEval_41_0.GomokuGameTestMakeMove.test_make_move_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_41_0.py", line 8, in setUp
    self.gomokuGame = GomokuGame(self.board_size)
                      ^^^^^^^^^^
NameError: name 'GomokuGame' is not defined

----------------------------------------------------------------------
Ran 5 tests in 0.011s

FAILED (errors=5)
EEEEE
======================================================================
ERROR: test_check_winner_1 (ClassEval_41_0.GomokuGameTestCheckWinner.test_check_winner_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_41_0.py", line 53, in test_check_winner_1
    gomokuGame = GomokuGame(10)
                 ^^^^^^^^^^
NameError: name 'GomokuGame' is not defined

======================================================================
ERROR: test_check_winner_2 (ClassEval_41_0.GomokuGameTestCheckWinner.test_check_winner_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_41_0.py", line 57, in test_check_winner_2
    gomokuGame = GomokuGame(10)
                 ^^^^^^^^^^
NameError: name 'GomokuGame' is not defined

======================================================================
ERROR: test_check_winner_3 (ClassEval_41_0.GomokuGameTestCheckWinner.test_check_winner_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_41_0.py", line 64, in test_check_winner_3
    gomokuGame = GomokuGame(10)
                 ^^^^^^^^^^
NameError: name 'GomokuGame' is not defined

======================================================================
ERROR: test_check_winner_4 (ClassEval_41_0.GomokuGameTestCheckWinner.test_check_winner_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_41_0.py", line 71, in test_check_winner_4
    gomokuGame = GomokuGame(10)
                 ^^^^^^^^^^
NameError: name 'GomokuGame' is not defined

======================================================================
ERROR: test_check_winner_5 (ClassEval_41_0.GomokuGameTestCheckWinner.test_check_winner_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_41_0.py", line 78, in test_check_winner_5
    gomokuGame = GomokuGame(10)
                 ^^^^^^^^^^
NameError: name 'GomokuGame' is not defined

----------------------------------------------------------------------
Ran 5 tests in 0.010s

FAILED (errors=5)
EEEEE
======================================================================
ERROR: test_check_five_in_a_row_1 (ClassEval_41_0.GomokuGameTestCheckFiveInARow.test_check_five_in_a_row_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_41_0.py", line 87, in setUp
    self.gomokuGame = GomokuGame(10)
                      ^^^^^^^^^^
NameError: name 'GomokuGame' is not defined

======================================================================
ERROR: test_check_five_in_a_row_2 (ClassEval_41_0.GomokuGameTestCheckFiveInARow.test_check_five_in_a_row_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_41_0.py", line 87, in setUp
    self.gomokuGame = GomokuGame(10)
                      ^^^^^^^^^^
NameError: name 'GomokuGame' is not defined

======================================================================
ERROR: test_check_five_in_a_row_3 (ClassEval_41_0.GomokuGameTestCheckFiveInARow.test_check_five_in_a_row_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_41_0.py", line 87, in setUp
    self.gomokuGame = GomokuGame(10)
                      ^^^^^^^^^^
NameError: name 'GomokuGame' is not defined

======================================================================
ERROR: test_check_five_in_a_row_4 (ClassEval_41_0.GomokuGameTestCheckFiveInARow.test_check_five_in_a_row_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_41_0.py", line 87, in setUp
    self.gomokuGame = GomokuGame(10)
                      ^^^^^^^^^^
NameError: name 'GomokuGame' is not defined

======================================================================
ERROR: test_check_five_in_a_row_5 (ClassEval_41_0.GomokuGameTestCheckFiveInARow.test_check_five_in_a_row_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_41_0.py", line 87, in setUp
    self.gomokuGame = GomokuGame(10)
                      ^^^^^^^^^^
NameError: name 'GomokuGame' is not defined

----------------------------------------------------------------------
Ran 5 tests in 0.011s

FAILED (errors=5)
E
======================================================================
ERROR: test_main (ClassEval_41_0.GomokuGameTestMain.test_main)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_41_0.py", line 109, in test_main
    gomokuGame = GomokuGame(10)
                 ^^^^^^^^^^
NameError: name 'GomokuGame' is not defined

----------------------------------------------------------------------
Ran 1 test in 0.002s

FAILED (errors=1)
EEEEE
======================================================================
ERROR: test_create_board_1 (ClassEval_54_0.MahjongConnectTestCreateBoard.test_create_board_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_54_0.py", line 8, in test_create_board_1
    mc = MahjongConnect([4, 4], ['a', 'b', 'c'])
         ^^^^^^^^^^^^^^
NameError: name 'MahjongConnect' is not defined. Did you mean: 'MahjongConnectTest'?

======================================================================
ERROR: test_create_board_2 (ClassEval_54_0.MahjongConnectTestCreateBoard.test_create_board_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_54_0.py", line 16, in test_create_board_2
    mc = MahjongConnect([2, 2], ['a', 'b', 'c'])
         ^^^^^^^^^^^^^^
NameError: name 'MahjongConnect' is not defined. Did you mean: 'MahjongConnectTest'?

======================================================================
ERROR: test_create_board_3 (ClassEval_54_0.MahjongConnectTestCreateBoard.test_create_board_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_54_0.py", line 24, in test_create_board_3
    mc = MahjongConnect([3, 3], ['a', 'b', 'c'])
         ^^^^^^^^^^^^^^
NameError: name 'MahjongConnect' is not defined. Did you mean: 'MahjongConnectTest'?

======================================================================
ERROR: test_create_board_4 (ClassEval_54_0.MahjongConnectTestCreateBoard.test_create_board_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_54_0.py", line 32, in test_create_board_4
    mc = MahjongConnect([1, 1], ['a', 'b', 'c'])
         ^^^^^^^^^^^^^^
NameError: name 'MahjongConnect' is not defined. Did you mean: 'MahjongConnectTest'?

======================================================================
ERROR: test_create_board_5 (ClassEval_54_0.MahjongConnectTestCreateBoard.test_create_board_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_54_0.py", line 40, in test_create_board_5
    mc = MahjongConnect([5, 5], ['a', 'b', 'c'])
         ^^^^^^^^^^^^^^
NameError: name 'MahjongConnect' is not defined. Did you mean: 'MahjongConnectTest'?

----------------------------------------------------------------------
Ran 5 tests in 0.010s

FAILED (errors=5)
EEEEEE
======================================================================
ERROR: test_is_valid_move_1 (ClassEval_54_0.MahjongConnectTestIsValidMove.test_is_valid_move_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_54_0.py", line 50, in test_is_valid_move_1
    mc = MahjongConnect([4, 4], ['a', 'b', 'c'])
         ^^^^^^^^^^^^^^
NameError: name 'MahjongConnect' is not defined. Did you mean: 'MahjongConnectTest'?

======================================================================
ERROR: test_is_valid_move_2 (ClassEval_54_0.MahjongConnectTestIsValidMove.test_is_valid_move_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_54_0.py", line 59, in test_is_valid_move_2
    mc = MahjongConnect([4, 4], ['a', 'b', 'c'])
         ^^^^^^^^^^^^^^
NameError: name 'MahjongConnect' is not defined. Did you mean: 'MahjongConnectTest'?

======================================================================
ERROR: test_is_valid_move_3 (ClassEval_54_0.MahjongConnectTestIsValidMove.test_is_valid_move_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_54_0.py", line 68, in test_is_valid_move_3
    mc = MahjongConnect([4, 4], ['a', 'b', 'c'])
         ^^^^^^^^^^^^^^
NameError: name 'MahjongConnect' is not defined. Did you mean: 'MahjongConnectTest'?

======================================================================
ERROR: test_is_valid_move_4 (ClassEval_54_0.MahjongConnectTestIsValidMove.test_is_valid_move_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_54_0.py", line 77, in test_is_valid_move_4
    mc = MahjongConnect([4, 4], ['a', 'b', 'c'])
         ^^^^^^^^^^^^^^
NameError: name 'MahjongConnect' is not defined. Did you mean: 'MahjongConnectTest'?

======================================================================
ERROR: test_is_valid_move_5 (ClassEval_54_0.MahjongConnectTestIsValidMove.test_is_valid_move_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_54_0.py", line 86, in test_is_valid_move_5
    mc = MahjongConnect([4, 4], ['a', 'b', 'c'])
         ^^^^^^^^^^^^^^
NameError: name 'MahjongConnect' is not defined. Did you mean: 'MahjongConnectTest'?

======================================================================
ERROR: test_is_valid_move_6 (ClassEval_54_0.MahjongConnectTestIsValidMove.test_is_valid_move_6)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_54_0.py", line 95, in test_is_valid_move_6
    mc = MahjongConnect([4, 4], ['a', 'b', 'c'])
         ^^^^^^^^^^^^^^
NameError: name 'MahjongConnect' is not defined. Did you mean: 'MahjongConnectTest'?

----------------------------------------------------------------------
Ran 6 tests in 0.014s

FAILED (errors=6)
EEEEEE
======================================================================
ERROR: test_has_path_1 (ClassEval_54_0.MahjongConnectTestHasPath.test_has_path_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_54_0.py", line 106, in test_has_path_1
    mc = MahjongConnect([4, 4], ['a', 'b', 'c'])
         ^^^^^^^^^^^^^^
NameError: name 'MahjongConnect' is not defined. Did you mean: 'MahjongConnectTest'?

======================================================================
ERROR: test_has_path_2 (ClassEval_54_0.MahjongConnectTestHasPath.test_has_path_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_54_0.py", line 115, in test_has_path_2
    mc = MahjongConnect([4, 4], ['a', 'b', 'c'])
         ^^^^^^^^^^^^^^
NameError: name 'MahjongConnect' is not defined. Did you mean: 'MahjongConnectTest'?

======================================================================
ERROR: test_has_path_3 (ClassEval_54_0.MahjongConnectTestHasPath.test_has_path_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_54_0.py", line 124, in test_has_path_3
    mc = MahjongConnect([4, 4], ['a', 'b', 'c'])
         ^^^^^^^^^^^^^^
NameError: name 'MahjongConnect' is not defined. Did you mean: 'MahjongConnectTest'?

======================================================================
ERROR: test_has_path_4 (ClassEval_54_0.MahjongConnectTestHasPath.test_has_path_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_54_0.py", line 133, in test_has_path_4
    mc = MahjongConnect([4, 4], ['a', 'b', 'c'])
         ^^^^^^^^^^^^^^
NameError: name 'MahjongConnect' is not defined. Did you mean: 'MahjongConnectTest'?

======================================================================
ERROR: test_has_path_5 (ClassEval_54_0.MahjongConnectTestHasPath.test_has_path_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_54_0.py", line 142, in test_has_path_5
    mc = MahjongConnect([4, 4], ['a', 'b', 'c'])
         ^^^^^^^^^^^^^^
NameError: name 'MahjongConnect' is not defined. Did you mean: 'MahjongConnectTest'?

======================================================================
ERROR: test_has_path_6 (ClassEval_54_0.MahjongConnectTestHasPath.test_has_path_6)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_54_0.py", line 151, in test_has_path_6
    mc = MahjongConnect([4, 4], ['a', 'b', 'c'])
         ^^^^^^^^^^^^^^
NameError: name 'MahjongConnect' is not defined. Did you mean: 'MahjongConnectTest'?

----------------------------------------------------------------------
Ran 6 tests in 0.012s

FAILED (errors=6)
EEEEE
======================================================================
ERROR: test_remove_icons_1 (ClassEval_54_0.MahjongConnectTestRemoveIcons.test_remove_icons_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_54_0.py", line 162, in test_remove_icons_1
    mc = MahjongConnect([4, 4], ['a', 'b', 'c'])
         ^^^^^^^^^^^^^^
NameError: name 'MahjongConnect' is not defined. Did you mean: 'MahjongConnectTest'?

======================================================================
ERROR: test_remove_icons_2 (ClassEval_54_0.MahjongConnectTestRemoveIcons.test_remove_icons_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_54_0.py", line 174, in test_remove_icons_2
    mc = MahjongConnect([4, 4], ['a', 'b', 'c'])
         ^^^^^^^^^^^^^^
NameError: name 'MahjongConnect' is not defined. Did you mean: 'MahjongConnectTest'?

======================================================================
ERROR: test_remove_icons_3 (ClassEval_54_0.MahjongConnectTestRemoveIcons.test_remove_icons_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_54_0.py", line 186, in test_remove_icons_3
    mc = MahjongConnect([4, 4], ['a', 'b', 'c'])
         ^^^^^^^^^^^^^^
NameError: name 'MahjongConnect' is not defined. Did you mean: 'MahjongConnectTest'?

======================================================================
ERROR: test_remove_icons_4 (ClassEval_54_0.MahjongConnectTestRemoveIcons.test_remove_icons_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_54_0.py", line 198, in test_remove_icons_4
    mc = MahjongConnect([4, 4], ['a', 'b', 'c'])
         ^^^^^^^^^^^^^^
NameError: name 'MahjongConnect' is not defined. Did you mean: 'MahjongConnectTest'?

======================================================================
ERROR: test_remove_icons_5 (ClassEval_54_0.MahjongConnectTestRemoveIcons.test_remove_icons_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_54_0.py", line 210, in test_remove_icons_5
    mc = MahjongConnect([4, 4], ['a', 'b', 'c'])
         ^^^^^^^^^^^^^^
NameError: name 'MahjongConnect' is not defined. Did you mean: 'MahjongConnectTest'?

----------------------------------------------------------------------
Ran 5 tests in 0.011s

FAILED (errors=5)
EEEEE
======================================================================
ERROR: test_is_game_over_1 (ClassEval_54_0.MahjongConnectTestIsGameOver.test_is_game_over_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_54_0.py", line 224, in test_is_game_over_1
    mc = MahjongConnect([4, 4], ['a', 'b', 'c'])
         ^^^^^^^^^^^^^^
NameError: name 'MahjongConnect' is not defined. Did you mean: 'MahjongConnectTest'?

======================================================================
ERROR: test_is_game_over_2 (ClassEval_54_0.MahjongConnectTestIsGameOver.test_is_game_over_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_54_0.py", line 233, in test_is_game_over_2
    mc = MahjongConnect([4, 4], ['a', 'b', 'c'])
         ^^^^^^^^^^^^^^
NameError: name 'MahjongConnect' is not defined. Did you mean: 'MahjongConnectTest'?

======================================================================
ERROR: test_is_game_over_3 (ClassEval_54_0.MahjongConnectTestIsGameOver.test_is_game_over_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_54_0.py", line 242, in test_is_game_over_3
    mc = MahjongConnect([4, 4], ['a', 'b', 'c'])
         ^^^^^^^^^^^^^^
NameError: name 'MahjongConnect' is not defined. Did you mean: 'MahjongConnectTest'?

======================================================================
ERROR: test_is_game_over_4 (ClassEval_54_0.MahjongConnectTestIsGameOver.test_is_game_over_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_54_0.py", line 251, in test_is_game_over_4
    mc = MahjongConnect([4, 4], ['a', 'b', 'c'])
         ^^^^^^^^^^^^^^
NameError: name 'MahjongConnect' is not defined. Did you mean: 'MahjongConnectTest'?

======================================================================
ERROR: test_is_game_over_5 (ClassEval_54_0.MahjongConnectTestIsGameOver.test_is_game_over_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_54_0.py", line 260, in test_is_game_over_5
    mc = MahjongConnect([4, 4], ['a', 'b', 'c'])
         ^^^^^^^^^^^^^^
NameError: name 'MahjongConnect' is not defined. Did you mean: 'MahjongConnectTest'?

----------------------------------------------------------------------
Ran 5 tests in 0.012s

FAILED (errors=5)
E
======================================================================
ERROR: test_mahjongconnect (ClassEval_54_0.MahjongConnectTest.test_mahjongconnect)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_54_0.py", line 271, in test_mahjongconnect
    mc = MahjongConnect([4, 4], ['a', 'b', 'c'])
         ^^^^^^^^^^^^^^
NameError: name 'MahjongConnect' is not defined. Did you mean: 'MahjongConnectTest'?

----------------------------------------------------------------------
Ran 1 test in 0.002s

FAILED (errors=1)
EEEEE
======================================================================
ERROR: test_generate_mine_sweeper_map (ClassEval_58_0.MinesweeperGameTestGenerateMineSweeperMap.test_generate_mine_sweeper_map)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_58_0.py", line 7, in test_generate_mine_sweeper_map
    minesweeper_game = MinesweeperGame(3, 2)
                       ^^^^^^^^^^^^^^^
NameError: name 'MinesweeperGame' is not defined

======================================================================
ERROR: test_generate_mine_sweeper_map_2 (ClassEval_58_0.MinesweeperGameTestGenerateMineSweeperMap.test_generate_mine_sweeper_map_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_58_0.py", line 18, in test_generate_mine_sweeper_map_2
    minesweeper_game = MinesweeperGame(3, 1)
                       ^^^^^^^^^^^^^^^
NameError: name 'MinesweeperGame' is not defined

======================================================================
ERROR: test_generate_mine_sweeper_map_3 (ClassEval_58_0.MinesweeperGameTestGenerateMineSweeperMap.test_generate_mine_sweeper_map_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_58_0.py", line 29, in test_generate_mine_sweeper_map_3
    minesweeper_game = MinesweeperGame(3, 0)
                       ^^^^^^^^^^^^^^^
NameError: name 'MinesweeperGame' is not defined

======================================================================
ERROR: test_generate_mine_sweeper_map_4 (ClassEval_58_0.MinesweeperGameTestGenerateMineSweeperMap.test_generate_mine_sweeper_map_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_58_0.py", line 40, in test_generate_mine_sweeper_map_4
    minesweeper_game = MinesweeperGame(5, 1)
                       ^^^^^^^^^^^^^^^
NameError: name 'MinesweeperGame' is not defined

======================================================================
ERROR: test_generate_mine_sweeper_map_5 (ClassEval_58_0.MinesweeperGameTestGenerateMineSweeperMap.test_generate_mine_sweeper_map_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_58_0.py", line 51, in test_generate_mine_sweeper_map_5
    minesweeper_game = MinesweeperGame(4, 1)
                       ^^^^^^^^^^^^^^^
NameError: name 'MinesweeperGame' is not defined

----------------------------------------------------------------------
Ran 5 tests in 0.020s

FAILED (errors=5)
EEEEE
======================================================================
ERROR: test_generate_playerMap (ClassEval_58_0.MinesweeperGameTestGeneratePlayerMap.test_generate_playerMap)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_58_0.py", line 63, in test_generate_playerMap
    minesweeper_game = MinesweeperGame(3, 2)
                       ^^^^^^^^^^^^^^^
NameError: name 'MinesweeperGame' is not defined

======================================================================
ERROR: test_generate_playerMap_2 (ClassEval_58_0.MinesweeperGameTestGeneratePlayerMap.test_generate_playerMap_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_58_0.py", line 67, in test_generate_playerMap_2
    minesweeper_game = MinesweeperGame(3, 1)
                       ^^^^^^^^^^^^^^^
NameError: name 'MinesweeperGame' is not defined

======================================================================
ERROR: test_generate_playerMap_3 (ClassEval_58_0.MinesweeperGameTestGeneratePlayerMap.test_generate_playerMap_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_58_0.py", line 71, in test_generate_playerMap_3
    minesweeper_game = MinesweeperGame(4, 2)
                       ^^^^^^^^^^^^^^^
NameError: name 'MinesweeperGame' is not defined

======================================================================
ERROR: test_generate_playerMap_4 (ClassEval_58_0.MinesweeperGameTestGeneratePlayerMap.test_generate_playerMap_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_58_0.py", line 75, in test_generate_playerMap_4
    minesweeper_game = MinesweeperGame(1, 4)
                       ^^^^^^^^^^^^^^^
NameError: name 'MinesweeperGame' is not defined

======================================================================
ERROR: test_generate_playerMap_5 (ClassEval_58_0.MinesweeperGameTestGeneratePlayerMap.test_generate_playerMap_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_58_0.py", line 79, in test_generate_playerMap_5
    minesweeper_game = MinesweeperGame(2, 5)
                       ^^^^^^^^^^^^^^^
NameError: name 'MinesweeperGame' is not defined

----------------------------------------------------------------------
Ran 5 tests in 0.024s

FAILED (errors=5)
EEEEE
======================================================================
ERROR: test_check_won (ClassEval_58_0.MinesweeperGameTestCheckWon.test_check_won)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_58_0.py", line 84, in test_check_won
    minesweeper_game = MinesweeperGame(3, 1)
                       ^^^^^^^^^^^^^^^
NameError: name 'MinesweeperGame' is not defined

======================================================================
ERROR: test_check_won_2 (ClassEval_58_0.MinesweeperGameTestCheckWon.test_check_won_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_58_0.py", line 90, in test_check_won_2
    minesweeper_game = MinesweeperGame(3, 1)
                       ^^^^^^^^^^^^^^^
NameError: name 'MinesweeperGame' is not defined

======================================================================
ERROR: test_check_won_3 (ClassEval_58_0.MinesweeperGameTestCheckWon.test_check_won_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_58_0.py", line 96, in test_check_won_3
    minesweeper_game = MinesweeperGame(3, 0)
                       ^^^^^^^^^^^^^^^
NameError: name 'MinesweeperGame' is not defined

======================================================================
ERROR: test_check_won_4 (ClassEval_58_0.MinesweeperGameTestCheckWon.test_check_won_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_58_0.py", line 102, in test_check_won_4
    minesweeper_game = MinesweeperGame(3, 1)
                       ^^^^^^^^^^^^^^^
NameError: name 'MinesweeperGame' is not defined

======================================================================
ERROR: test_check_won_5 (ClassEval_58_0.MinesweeperGameTestCheckWon.test_check_won_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_58_0.py", line 108, in test_check_won_5
    minesweeper_game = MinesweeperGame(3, 1)
                       ^^^^^^^^^^^^^^^
NameError: name 'MinesweeperGame' is not defined

----------------------------------------------------------------------
Ran 5 tests in 0.020s

FAILED (errors=5)
EEEEE
======================================================================
ERROR: test_sweep (ClassEval_58_0.MinesweeperGameTestSweep.test_sweep)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_58_0.py", line 115, in test_sweep
    minesweeper_game = MinesweeperGame(3, 1)
                       ^^^^^^^^^^^^^^^
NameError: name 'MinesweeperGame' is not defined

======================================================================
ERROR: test_sweep_2 (ClassEval_58_0.MinesweeperGameTestSweep.test_sweep_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_58_0.py", line 122, in test_sweep_2
    minesweeper_game = MinesweeperGame(3, 1)
                       ^^^^^^^^^^^^^^^
NameError: name 'MinesweeperGame' is not defined

======================================================================
ERROR: test_sweep_3 (ClassEval_58_0.MinesweeperGameTestSweep.test_sweep_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_58_0.py", line 129, in test_sweep_3
    minesweeper_game = MinesweeperGame(3, 1)
                       ^^^^^^^^^^^^^^^
NameError: name 'MinesweeperGame' is not defined

======================================================================
ERROR: test_sweep_4 (ClassEval_58_0.MinesweeperGameTestSweep.test_sweep_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_58_0.py", line 136, in test_sweep_4
    minesweeper_game = MinesweeperGame(3, 1)
                       ^^^^^^^^^^^^^^^
NameError: name 'MinesweeperGame' is not defined

======================================================================
ERROR: test_sweep_5 (ClassEval_58_0.MinesweeperGameTestSweep.test_sweep_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_58_0.py", line 143, in test_sweep_5
    minesweeper_game = MinesweeperGame(3, 1)
                       ^^^^^^^^^^^^^^^
NameError: name 'MinesweeperGame' is not defined

----------------------------------------------------------------------
Ran 5 tests in 0.020s

FAILED (errors=5)
EE
======================================================================
ERROR: test_minesweeper_main (ClassEval_58_0.MinesweeperGameTestMain.test_minesweeper_main)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_58_0.py", line 151, in test_minesweeper_main
    minesweeper_game = MinesweeperGame(3, 1)
                       ^^^^^^^^^^^^^^^
NameError: name 'MinesweeperGame' is not defined

======================================================================
ERROR: test_minesweeper_main_2 (ClassEval_58_0.MinesweeperGameTestMain.test_minesweeper_main_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_58_0.py", line 168, in test_minesweeper_main_2
    minesweeper_game = MinesweeperGame(3, 2)
                       ^^^^^^^^^^^^^^^
NameError: name 'MinesweeperGame' is not defined

----------------------------------------------------------------------
Ran 2 tests in 0.007s

FAILED (errors=2)
EEEEEEE
======================================================================
ERROR: test_init_game_1 (ClassEval_71_0.PushBoxGameTestInitGame.test_init_game_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_71_0.py", line 15, in setUp
    self.game = PushBoxGame(self.game_map)
                ^^^^^^^^^^^
NameError: name 'PushBoxGame' is not defined

======================================================================
ERROR: test_init_game_2 (ClassEval_71_0.PushBoxGameTestInitGame.test_init_game_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_71_0.py", line 15, in setUp
    self.game = PushBoxGame(self.game_map)
                ^^^^^^^^^^^
NameError: name 'PushBoxGame' is not defined

======================================================================
ERROR: test_init_game_3 (ClassEval_71_0.PushBoxGameTestInitGame.test_init_game_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_71_0.py", line 15, in setUp
    self.game = PushBoxGame(self.game_map)
                ^^^^^^^^^^^
NameError: name 'PushBoxGame' is not defined

======================================================================
ERROR: test_init_game_4 (ClassEval_71_0.PushBoxGameTestInitGame.test_init_game_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_71_0.py", line 15, in setUp
    self.game = PushBoxGame(self.game_map)
                ^^^^^^^^^^^
NameError: name 'PushBoxGame' is not defined

======================================================================
ERROR: test_init_game_5 (ClassEval_71_0.PushBoxGameTestInitGame.test_init_game_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_71_0.py", line 15, in setUp
    self.game = PushBoxGame(self.game_map)
                ^^^^^^^^^^^
NameError: name 'PushBoxGame' is not defined

======================================================================
ERROR: test_init_game_6 (ClassEval_71_0.PushBoxGameTestInitGame.test_init_game_6)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_71_0.py", line 15, in setUp
    self.game = PushBoxGame(self.game_map)
                ^^^^^^^^^^^
NameError: name 'PushBoxGame' is not defined

======================================================================
ERROR: test_init_game_7 (ClassEval_71_0.PushBoxGameTestInitGame.test_init_game_7)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_71_0.py", line 15, in setUp
    self.game = PushBoxGame(self.game_map)
                ^^^^^^^^^^^
NameError: name 'PushBoxGame' is not defined

----------------------------------------------------------------------
Ran 7 tests in 0.017s

FAILED (errors=7)
EE
======================================================================
ERROR: test_check_win_1 (ClassEval_71_0.PushBoxGameTestCheckWin.test_check_win_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_71_0.py", line 48, in setUp
    self.game = PushBoxGame(self.game_map)
                ^^^^^^^^^^^
NameError: name 'PushBoxGame' is not defined

======================================================================
ERROR: test_check_win_2 (ClassEval_71_0.PushBoxGameTestCheckWin.test_check_win_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_71_0.py", line 48, in setUp
    self.game = PushBoxGame(self.game_map)
                ^^^^^^^^^^^
NameError: name 'PushBoxGame' is not defined

----------------------------------------------------------------------
Ran 2 tests in 0.006s

FAILED (errors=2)
EEEEEEE
======================================================================
ERROR: test_move_1 (ClassEval_71_0.PushBoxGameTestMove.test_move_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_71_0.py", line 68, in setUp
    self.game = PushBoxGame(self.game_map)
                ^^^^^^^^^^^
NameError: name 'PushBoxGame' is not defined

======================================================================
ERROR: test_move_2 (ClassEval_71_0.PushBoxGameTestMove.test_move_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_71_0.py", line 68, in setUp
    self.game = PushBoxGame(self.game_map)
                ^^^^^^^^^^^
NameError: name 'PushBoxGame' is not defined

======================================================================
ERROR: test_move_3 (ClassEval_71_0.PushBoxGameTestMove.test_move_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_71_0.py", line 68, in setUp
    self.game = PushBoxGame(self.game_map)
                ^^^^^^^^^^^
NameError: name 'PushBoxGame' is not defined

======================================================================
ERROR: test_move_4 (ClassEval_71_0.PushBoxGameTestMove.test_move_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_71_0.py", line 68, in setUp
    self.game = PushBoxGame(self.game_map)
                ^^^^^^^^^^^
NameError: name 'PushBoxGame' is not defined

======================================================================
ERROR: test_move_5 (ClassEval_71_0.PushBoxGameTestMove.test_move_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_71_0.py", line 68, in setUp
    self.game = PushBoxGame(self.game_map)
                ^^^^^^^^^^^
NameError: name 'PushBoxGame' is not defined

======================================================================
ERROR: test_move_6 (ClassEval_71_0.PushBoxGameTestMove.test_move_6)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_71_0.py", line 68, in setUp
    self.game = PushBoxGame(self.game_map)
                ^^^^^^^^^^^
NameError: name 'PushBoxGame' is not defined

======================================================================
ERROR: test_move_7 (ClassEval_71_0.PushBoxGameTestMove.test_move_7)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_71_0.py", line 68, in setUp
    self.game = PushBoxGame(self.game_map)
                ^^^^^^^^^^^
NameError: name 'PushBoxGame' is not defined

----------------------------------------------------------------------
Ran 7 tests in 0.021s

FAILED (errors=7)
EEEEE
======================================================================
ERROR: test_attack (ClassEval_73_0.RPGCharacterTestAttack.test_attack)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_73_0.py", line 7, in test_attack
    character1 = RPGCharacter("John", 100, 20, 10)
                 ^^^^^^^^^^^^
NameError: name 'RPGCharacter' is not defined

======================================================================
ERROR: test_attack_2 (ClassEval_73_0.RPGCharacterTestAttack.test_attack_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_73_0.py", line 13, in test_attack_2
    character1 = RPGCharacter("John", 100, 20, 10)
                 ^^^^^^^^^^^^
NameError: name 'RPGCharacter' is not defined

======================================================================
ERROR: test_attack_3 (ClassEval_73_0.RPGCharacterTestAttack.test_attack_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_73_0.py", line 19, in test_attack_3
    character1 = RPGCharacter("John", 100, 20, 10)
                 ^^^^^^^^^^^^
NameError: name 'RPGCharacter' is not defined

======================================================================
ERROR: test_attack_4 (ClassEval_73_0.RPGCharacterTestAttack.test_attack_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_73_0.py", line 27, in test_attack_4
    character1 = RPGCharacter("John", 100, 20, 10)
                 ^^^^^^^^^^^^
NameError: name 'RPGCharacter' is not defined

======================================================================
ERROR: test_attack_5 (ClassEval_73_0.RPGCharacterTestAttack.test_attack_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_73_0.py", line 34, in test_attack_5
    character1 = RPGCharacter("John", 100, 20, 10)
                 ^^^^^^^^^^^^
NameError: name 'RPGCharacter' is not defined

----------------------------------------------------------------------
Ran 5 tests in 0.017s

FAILED (errors=5)
EEEEE
======================================================================
ERROR: test_heal_1 (ClassEval_73_0.RPGCharacterTestHeal.test_heal_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_73_0.py", line 43, in test_heal_1
    character = RPGCharacter("John", 90, 20, 10)
                ^^^^^^^^^^^^
NameError: name 'RPGCharacter' is not defined

======================================================================
ERROR: test_heal_2 (ClassEval_73_0.RPGCharacterTestHeal.test_heal_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_73_0.py", line 49, in test_heal_2
    character = RPGCharacter("John", 97, 20, 10)
                ^^^^^^^^^^^^
NameError: name 'RPGCharacter' is not defined

======================================================================
ERROR: test_heal_3 (ClassEval_73_0.RPGCharacterTestHeal.test_heal_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_73_0.py", line 54, in test_heal_3
    character = RPGCharacter("John", 100, 20, 10)
                ^^^^^^^^^^^^
NameError: name 'RPGCharacter' is not defined

======================================================================
ERROR: test_heal_4 (ClassEval_73_0.RPGCharacterTestHeal.test_heal_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_73_0.py", line 59, in test_heal_4
    character = RPGCharacter("John", 100, 20, 10)
                ^^^^^^^^^^^^
NameError: name 'RPGCharacter' is not defined

======================================================================
ERROR: test_heal_5 (ClassEval_73_0.RPGCharacterTestHeal.test_heal_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_73_0.py", line 65, in test_heal_5
    character = RPGCharacter("John", 100, 20, 10)
                ^^^^^^^^^^^^
NameError: name 'RPGCharacter' is not defined

----------------------------------------------------------------------
Ran 5 tests in 0.018s

FAILED (errors=5)
EEEEE
======================================================================
ERROR: test_gain_exp_1 (ClassEval_73_0.RPGCharacterTestGainExp.test_gain_exp_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_73_0.py", line 75, in test_gain_exp_1
    character = RPGCharacter("John", 100, 20, 10)
                ^^^^^^^^^^^^
NameError: name 'RPGCharacter' is not defined

======================================================================
ERROR: test_gain_exp_2 (ClassEval_73_0.RPGCharacterTestGainExp.test_gain_exp_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_73_0.py", line 82, in test_gain_exp_2
    character = RPGCharacter("John", 100, 20, 10)
                ^^^^^^^^^^^^
NameError: name 'RPGCharacter' is not defined

======================================================================
ERROR: test_gain_exp_3 (ClassEval_73_0.RPGCharacterTestGainExp.test_gain_exp_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_73_0.py", line 88, in test_gain_exp_3
    character = RPGCharacter("John", 100, 20, 10)
                ^^^^^^^^^^^^
NameError: name 'RPGCharacter' is not defined

======================================================================
ERROR: test_gain_exp_4 (ClassEval_73_0.RPGCharacterTestGainExp.test_gain_exp_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_73_0.py", line 94, in test_gain_exp_4
    character = RPGCharacter("John", 100, 20, 10)
                ^^^^^^^^^^^^
NameError: name 'RPGCharacter' is not defined

======================================================================
ERROR: test_gain_exp_5 (ClassEval_73_0.RPGCharacterTestGainExp.test_gain_exp_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_73_0.py", line 100, in test_gain_exp_5
    character = RPGCharacter("John", 100, 20, 10)
                ^^^^^^^^^^^^
NameError: name 'RPGCharacter' is not defined

----------------------------------------------------------------------
Ran 5 tests in 0.015s

FAILED (errors=5)
EEEEE
======================================================================
ERROR: test_level_up_1 (ClassEval_73_0.RPGCharacterTestLevelUp.test_level_up_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_73_0.py", line 108, in test_level_up_1
    character = RPGCharacter("John", 100, 20, 10)
                ^^^^^^^^^^^^
NameError: name 'RPGCharacter' is not defined

======================================================================
ERROR: test_level_up_2 (ClassEval_73_0.RPGCharacterTestLevelUp.test_level_up_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_73_0.py", line 118, in test_level_up_2
    character = RPGCharacter("John", 100, 20, 10, 100)
                ^^^^^^^^^^^^
NameError: name 'RPGCharacter' is not defined

======================================================================
ERROR: test_level_up_3 (ClassEval_73_0.RPGCharacterTestLevelUp.test_level_up_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_73_0.py", line 127, in test_level_up_3
    character = RPGCharacter("John", 100, 20, 10, 2)
                ^^^^^^^^^^^^
NameError: name 'RPGCharacter' is not defined

======================================================================
ERROR: test_level_up_4 (ClassEval_73_0.RPGCharacterTestLevelUp.test_level_up_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_73_0.py", line 136, in test_level_up_4
    character = RPGCharacter("John", 100, 20, 10, 3)
                ^^^^^^^^^^^^
NameError: name 'RPGCharacter' is not defined

======================================================================
ERROR: test_level_up_5 (ClassEval_73_0.RPGCharacterTestLevelUp.test_level_up_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_73_0.py", line 145, in test_level_up_5
    character = RPGCharacter("John", 100, 20, 10, 4)
                ^^^^^^^^^^^^
NameError: name 'RPGCharacter' is not defined

----------------------------------------------------------------------
Ran 5 tests in 0.017s

FAILED (errors=5)
EEEEE
======================================================================
ERROR: test_is_alive_1 (ClassEval_73_0.RPGCharacterTestIsAlive.test_is_alive_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_73_0.py", line 156, in test_is_alive_1
    character = RPGCharacter("John", 100, 20, 10)
                ^^^^^^^^^^^^
NameError: name 'RPGCharacter' is not defined

======================================================================
ERROR: test_is_alive_2 (ClassEval_73_0.RPGCharacterTestIsAlive.test_is_alive_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_73_0.py", line 160, in test_is_alive_2
    character = RPGCharacter("John", 0, 20, 10)
                ^^^^^^^^^^^^
NameError: name 'RPGCharacter' is not defined

======================================================================
ERROR: test_is_alive_3 (ClassEval_73_0.RPGCharacterTestIsAlive.test_is_alive_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_73_0.py", line 164, in test_is_alive_3
    character = RPGCharacter("John", -10, 20, 10)
                ^^^^^^^^^^^^
NameError: name 'RPGCharacter' is not defined

======================================================================
ERROR: test_is_alive_4 (ClassEval_73_0.RPGCharacterTestIsAlive.test_is_alive_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_73_0.py", line 168, in test_is_alive_4
    character = RPGCharacter("John", 1, 20, 10)
                ^^^^^^^^^^^^
NameError: name 'RPGCharacter' is not defined

======================================================================
ERROR: test_is_alive_5 (ClassEval_73_0.RPGCharacterTestIsAlive.test_is_alive_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_73_0.py", line 172, in test_is_alive_5
    character = RPGCharacter("John", 10, 20, 10)
                ^^^^^^^^^^^^
NameError: name 'RPGCharacter' is not defined

----------------------------------------------------------------------
Ran 5 tests in 0.022s

FAILED (errors=5)
E
======================================================================
ERROR: test_main (ClassEval_73_0.RPGCharacterTestMain.test_main)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_73_0.py", line 177, in test_main
    character1 = RPGCharacter("John", 100, 20, 10)
                 ^^^^^^^^^^^^
NameError: name 'RPGCharacter' is not defined

----------------------------------------------------------------------
Ran 1 test in 0.003s

FAILED (errors=1)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
F
======================================================================
FAIL: test_main (ClassEval_86_0.TicTacToeTestMain.test_main)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_86_0.py", line 211, in test_main
    self.assertFalse(ttt.check_winner())
AssertionError: 'Tie' is not false

----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (failures=1)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
E......
======================================================================
ERROR: test_answer_1 (ClassEval_89_0.TwentyFourPointGameTestAnswer.test_answer_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_89_0.py", line 99, in test_answer_1
    self.assertEqual(len(cards), 4)
                     ^^^^^^^^^^
TypeError: object of type 'bool' has no len()

----------------------------------------------------------------------
Ran 7 tests in 0.001s

FAILED (errors=1)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
