.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
EEEEE
======================================================================
ERROR: test_clear_expr (ClassEval_7_0.BalancedBracketsTestClearExpr.test_clear_expr)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_7_0.py", line 39, in test_clear_expr
    b.clear_expr()
    ^^^^^^^^^^^^
AttributeError: 'BalancedBrackets' object has no attribute 'clear_expr'

======================================================================
ERROR: test_clear_expr_2 (ClassEval_7_0.BalancedBracketsTestClearExpr.test_clear_expr_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_7_0.py", line 44, in test_clear_expr_2
    b.clear_expr()
    ^^^^^^^^^^^^
AttributeError: 'BalancedBrackets' object has no attribute 'clear_expr'

======================================================================
ERROR: test_clear_expr_3 (ClassEval_7_0.BalancedBracketsTestClearExpr.test_clear_expr_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_7_0.py", line 49, in test_clear_expr_3
    b.clear_expr()
    ^^^^^^^^^^^^
AttributeError: 'BalancedBrackets' object has no attribute 'clear_expr'

======================================================================
ERROR: test_clear_expr_4 (ClassEval_7_0.BalancedBracketsTestClearExpr.test_clear_expr_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_7_0.py", line 54, in test_clear_expr_4
    b.clear_expr()
    ^^^^^^^^^^^^
AttributeError: 'BalancedBrackets' object has no attribute 'clear_expr'

======================================================================
ERROR: test_clear_expr_5 (ClassEval_7_0.BalancedBracketsTestClearExpr.test_clear_expr_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_7_0.py", line 59, in test_clear_expr_5
    b.clear_expr()
    ^^^^^^^^^^^^
AttributeError: 'BalancedBrackets' object has no attribute 'clear_expr'

----------------------------------------------------------------------
Ran 5 tests in 0.006s

FAILED (errors=5)
.......
----------------------------------------------------------------------
Ran 7 tests in 0.000s

OK
EEE
======================================================================
ERROR: test_main (ClassEval_7_0.BalancedBracketsTestMain.test_main)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_7_0.py", line 96, in test_main
    b.clear_expr()
    ^^^^^^^^^^^^
AttributeError: 'BalancedBrackets' object has no attribute 'clear_expr'

======================================================================
ERROR: test_main_2 (ClassEval_7_0.BalancedBracketsTestMain.test_main_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_7_0.py", line 102, in test_main_2
    b.clear_expr()
    ^^^^^^^^^^^^
AttributeError: 'BalancedBrackets' object has no attribute 'clear_expr'

======================================================================
ERROR: test_main_3 (ClassEval_7_0.BalancedBracketsTestMain.test_main_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_7_0.py", line 108, in test_main_3
    b.clear_expr()
    ^^^^^^^^^^^^
AttributeError: 'BalancedBrackets' object has no attribute 'clear_expr'

----------------------------------------------------------------------
Ran 3 tests in 0.003s

FAILED (errors=3)
EEEEE
======================================================================
ERROR: test_clean_non_binary_chars (ClassEval_10_0.BinaryDataProcessorTestCleanNonBinaryChars.test_clean_non_binary_chars)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_10_0.py", line 10, in test_clean_non_binary_chars
    bdp = BinaryDataProcessor("01101000daf3e4r01100101011011000110110001101111")
          ^^^^^^^^^^^^^^^^^^^
NameError: name 'BinaryDataProcessor' is not defined. Did you mean: 'BinaryDataProcessorTestMain'?

======================================================================
ERROR: test_clean_non_binary_chars_2 (ClassEval_10_0.BinaryDataProcessorTestCleanNonBinaryChars.test_clean_non_binary_chars_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_10_0.py", line 14, in test_clean_non_binary_chars_2
    bdp = BinaryDataProcessor("01101000daf3e4r01100101011011addf0110001d1111")
          ^^^^^^^^^^^^^^^^^^^
NameError: name 'BinaryDataProcessor' is not defined. Did you mean: 'BinaryDataProcessorTestMain'?

======================================================================
ERROR: test_clean_non_binary_chars_3 (ClassEval_10_0.BinaryDataProcessorTestCleanNonBinaryChars.test_clean_non_binary_chars_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_10_0.py", line 18, in test_clean_non_binary_chars_3
    bdp = BinaryDataProcessor("0sd1000daf3e4r01100101011011addf0110001d1111")
          ^^^^^^^^^^^^^^^^^^^
NameError: name 'BinaryDataProcessor' is not defined. Did you mean: 'BinaryDataProcessorTestMain'?

======================================================================
ERROR: test_clean_non_binary_chars_4 (ClassEval_10_0.BinaryDataProcessorTestCleanNonBinaryChars.test_clean_non_binary_chars_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_10_0.py", line 22, in test_clean_non_binary_chars_4
    bdp = BinaryDataProcessor("sdsdf")
          ^^^^^^^^^^^^^^^^^^^
NameError: name 'BinaryDataProcessor' is not defined. Did you mean: 'BinaryDataProcessorTestMain'?

======================================================================
ERROR: test_clean_non_binary_chars_5 (ClassEval_10_0.BinaryDataProcessorTestCleanNonBinaryChars.test_clean_non_binary_chars_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_10_0.py", line 26, in test_clean_non_binary_chars_5
    bdp = BinaryDataProcessor("0")
          ^^^^^^^^^^^^^^^^^^^
NameError: name 'BinaryDataProcessor' is not defined. Did you mean: 'BinaryDataProcessorTestMain'?

----------------------------------------------------------------------
Ran 5 tests in 0.026s

FAILED (errors=5)
EEEEE
======================================================================
ERROR: test_calculate_binary_info (ClassEval_10_0.BinaryDataProcessorTestCalculateBinaryInfo.test_calculate_binary_info)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_10_0.py", line 31, in test_calculate_binary_info
    bdp = BinaryDataProcessor("0110100001100101011011000110110001101111")
          ^^^^^^^^^^^^^^^^^^^
NameError: name 'BinaryDataProcessor' is not defined. Did you mean: 'BinaryDataProcessorTestMain'?

======================================================================
ERROR: test_calculate_binary_info_2 (ClassEval_10_0.BinaryDataProcessorTestCalculateBinaryInfo.test_calculate_binary_info_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_10_0.py", line 35, in test_calculate_binary_info_2
    bdp = BinaryDataProcessor("0110100001100101011010011111")
          ^^^^^^^^^^^^^^^^^^^
NameError: name 'BinaryDataProcessor' is not defined. Did you mean: 'BinaryDataProcessorTestMain'?

======================================================================
ERROR: test_calculate_binary_info_3 (ClassEval_10_0.BinaryDataProcessorTestCalculateBinaryInfo.test_calculate_binary_info_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_10_0.py", line 39, in test_calculate_binary_info_3
    bdp = BinaryDataProcessor("01101001111100101011010011111")
          ^^^^^^^^^^^^^^^^^^^
NameError: name 'BinaryDataProcessor' is not defined. Did you mean: 'BinaryDataProcessorTestMain'?

======================================================================
ERROR: test_calculate_binary_info_4 (ClassEval_10_0.BinaryDataProcessorTestCalculateBinaryInfo.test_calculate_binary_info_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_10_0.py", line 43, in test_calculate_binary_info_4
    bdp = BinaryDataProcessor("011010011111001")
          ^^^^^^^^^^^^^^^^^^^
NameError: name 'BinaryDataProcessor' is not defined. Did you mean: 'BinaryDataProcessorTestMain'?

======================================================================
ERROR: test_calculate_binary_info_5 (ClassEval_10_0.BinaryDataProcessorTestCalculateBinaryInfo.test_calculate_binary_info_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_10_0.py", line 47, in test_calculate_binary_info_5
    bdp = BinaryDataProcessor("0110100111110010")
          ^^^^^^^^^^^^^^^^^^^
NameError: name 'BinaryDataProcessor' is not defined. Did you mean: 'BinaryDataProcessorTestMain'?

----------------------------------------------------------------------
Ran 5 tests in 0.021s

FAILED (errors=5)
EEEEE
======================================================================
ERROR: test_convert_to_ascii (ClassEval_10_0.BinaryDataProcessorTestConvertToAscii.test_convert_to_ascii)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_10_0.py", line 52, in test_convert_to_ascii
    bdp = BinaryDataProcessor("0110100001100101011011000110110001101111")
          ^^^^^^^^^^^^^^^^^^^
NameError: name 'BinaryDataProcessor' is not defined. Did you mean: 'BinaryDataProcessorTestMain'?

======================================================================
ERROR: test_convert_to_ascii_2 (ClassEval_10_0.BinaryDataProcessorTestConvertToAscii.test_convert_to_ascii_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_10_0.py", line 56, in test_convert_to_ascii_2
    bdp = BinaryDataProcessor("0110100000100101011011000110110001101111")
          ^^^^^^^^^^^^^^^^^^^
NameError: name 'BinaryDataProcessor' is not defined. Did you mean: 'BinaryDataProcessorTestMain'?

======================================================================
ERROR: test_convert_to_ascii_3 (ClassEval_10_0.BinaryDataProcessorTestConvertToAscii.test_convert_to_ascii_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_10_0.py", line 60, in test_convert_to_ascii_3
    bdp = BinaryDataProcessor("01101000011011010110001001101111")
          ^^^^^^^^^^^^^^^^^^^
NameError: name 'BinaryDataProcessor' is not defined. Did you mean: 'BinaryDataProcessorTestMain'?

======================================================================
ERROR: test_convert_to_ascii_4 (ClassEval_10_0.BinaryDataProcessorTestConvertToAscii.test_convert_to_ascii_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_10_0.py", line 64, in test_convert_to_ascii_4
    bdp = BinaryDataProcessor("01101000011001010110001001101111")
          ^^^^^^^^^^^^^^^^^^^
NameError: name 'BinaryDataProcessor' is not defined. Did you mean: 'BinaryDataProcessorTestMain'?

======================================================================
ERROR: test_convert_to_ascii_5 (ClassEval_10_0.BinaryDataProcessorTestConvertToAscii.test_convert_to_ascii_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_10_0.py", line 68, in test_convert_to_ascii_5
    bdp = BinaryDataProcessor("0110100001100101011011000110110001101111")
          ^^^^^^^^^^^^^^^^^^^
NameError: name 'BinaryDataProcessor' is not defined. Did you mean: 'BinaryDataProcessorTestMain'?

----------------------------------------------------------------------
Ran 5 tests in 0.022s

FAILED (errors=5)
EEEEE
======================================================================
ERROR: test_convert_to_utf8 (ClassEval_10_0.BinaryDataProcessorTestConvertToUtf8.test_convert_to_utf8)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_10_0.py", line 73, in test_convert_to_utf8
    bdp = BinaryDataProcessor("0110100001100101011011000110110001101111")
          ^^^^^^^^^^^^^^^^^^^
NameError: name 'BinaryDataProcessor' is not defined. Did you mean: 'BinaryDataProcessorTestMain'?

======================================================================
ERROR: test_convert_to_utf8_2 (ClassEval_10_0.BinaryDataProcessorTestConvertToUtf8.test_convert_to_utf8_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_10_0.py", line 77, in test_convert_to_utf8_2
    bdp = BinaryDataProcessor("0110100001100101011011000110110001101001")
          ^^^^^^^^^^^^^^^^^^^
NameError: name 'BinaryDataProcessor' is not defined. Did you mean: 'BinaryDataProcessorTestMain'?

======================================================================
ERROR: test_convert_to_utf8_3 (ClassEval_10_0.BinaryDataProcessorTestConvertToUtf8.test_convert_to_utf8_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_10_0.py", line 81, in test_convert_to_utf8_3
    bdp = BinaryDataProcessor("0110000001100101011011000110110001101111")
          ^^^^^^^^^^^^^^^^^^^
NameError: name 'BinaryDataProcessor' is not defined. Did you mean: 'BinaryDataProcessorTestMain'?

======================================================================
ERROR: test_convert_to_utf8_4 (ClassEval_10_0.BinaryDataProcessorTestConvertToUtf8.test_convert_to_utf8_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_10_0.py", line 85, in test_convert_to_utf8_4
    bdp = BinaryDataProcessor("0110101101100101011011000110110001101111")
          ^^^^^^^^^^^^^^^^^^^
NameError: name 'BinaryDataProcessor' is not defined. Did you mean: 'BinaryDataProcessorTestMain'?

======================================================================
ERROR: test_convert_to_utf8_5 (ClassEval_10_0.BinaryDataProcessorTestConvertToUtf8.test_convert_to_utf8_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_10_0.py", line 89, in test_convert_to_utf8_5
    bdp = BinaryDataProcessor("0110101101100100011011000110110001101111")
          ^^^^^^^^^^^^^^^^^^^
NameError: name 'BinaryDataProcessor' is not defined. Did you mean: 'BinaryDataProcessorTestMain'?

----------------------------------------------------------------------
Ran 5 tests in 0.019s

FAILED (errors=5)
E
======================================================================
ERROR: test_main (ClassEval_10_0.BinaryDataProcessorTestMain.test_main)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_10_0.py", line 94, in test_main
    bdp = BinaryDataProcessor("01101000daf3e4r01100101011011000110110001101111")
          ^^^^^^^^^^^^^^^^^^^
NameError: name 'BinaryDataProcessor' is not defined. Did you mean: 'BinaryDataProcessorTestMain'?

----------------------------------------------------------------------
Ran 1 test in 0.003s

FAILED (errors=1)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
FEEEF
======================================================================
ERROR: test_bad_character_heuristic_2 (ClassEval_15_0.BoyerMooreSearchTestBadCharacterHeuristic.test_bad_character_heuristic_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_15_0.py", line 127, in test_bad_character_heuristic_2
    self.assertEqual(boyerMooreSearch.bad_character_heuristic(), [])
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_15_0.py", line 56, in bad_character_heuristic
    skip = max(1, skip - self.bad_character_heuristic_helper(currentPos, badChar))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_15_0.py", line 68, in bad_character_heuristic_helper
    while i >= 0 and self.text[currentPos + i] == self.pattern[i]:
                     ~~~~~~~~~^^^^^^^^^^^^^^^^
IndexError: string index out of range

======================================================================
ERROR: test_bad_character_heuristic_3 (ClassEval_15_0.BoyerMooreSearchTestBadCharacterHeuristic.test_bad_character_heuristic_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_15_0.py", line 131, in test_bad_character_heuristic_3
    self.assertEqual(boyerMooreSearch.bad_character_heuristic(), [0, 1, 2, 3, 4, 5, 6])
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_15_0.py", line 51, in bad_character_heuristic
    if self.text[currentPos] == self.pattern[self.patLen - 1]:
                                ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
IndexError: string index out of range

======================================================================
ERROR: test_bad_character_heuristic_4 (ClassEval_15_0.BoyerMooreSearchTestBadCharacterHeuristic.test_bad_character_heuristic_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_15_0.py", line 135, in test_bad_character_heuristic_4
    self.assertEqual(boyerMooreSearch.bad_character_heuristic(), [0, 4])
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_15_0.py", line 56, in bad_character_heuristic
    skip = max(1, skip - self.bad_character_heuristic_helper(currentPos, badChar))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_15_0.py", line 68, in bad_character_heuristic_helper
    while i >= 0 and self.text[currentPos + i] == self.pattern[i]:
                     ~~~~~~~~~^^^^^^^^^^^^^^^^
IndexError: string index out of range

======================================================================
FAIL: test_bad_character_heuristic (ClassEval_15_0.BoyerMooreSearchTestBadCharacterHeuristic.test_bad_character_heuristic)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_15_0.py", line 123, in test_bad_character_heuristic
    self.assertEqual(boyerMooreSearch.bad_character_heuristic(), [0, 3])
AssertionError: Lists differ: [1, 4] != [0, 3]

First differing element 0:
1
0

- [1, 4]
+ [0, 3]

======================================================================
FAIL: test_bad_character_heuristic_5 (ClassEval_15_0.BoyerMooreSearchTestBadCharacterHeuristic.test_bad_character_heuristic_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_15_0.py", line 139, in test_bad_character_heuristic_5
    self.assertEqual(boyerMooreSearch.bad_character_heuristic(), [0])
AssertionError: Lists differ: [3] != [0]

First differing element 0:
3
0

- [3]
+ [0]

----------------------------------------------------------------------
Ran 5 tests in 0.004s

FAILED (failures=2, errors=3)
F
======================================================================
FAIL: test_main (ClassEval_15_0.BoyerMooreSearchTestMain.test_main)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_15_0.py", line 146, in test_main
    self.assertEqual(boyerMooreSearch.bad_character_heuristic(), [0, 3])
AssertionError: Lists differ: [1, 4] != [0, 3]

First differing element 0:
1
0

- [1, 4]
+ [0, 3]

----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (failures=1)
....E
======================================================================
ERROR: test_getitem_5 (ClassEval_18_0.CamelCaseMapTestGetitem.test_getitem_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_18_0.py", line 97, in test_getitem_5
    self.assertEqual(camelize_map.__getitem__('firstName'), 'John')
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_18_0.py", line 20, in __getitem__
    return self._data[self._convert_key(key)]
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'Firstname'

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (errors=1)
...F.
======================================================================
FAIL: test_setitem_4 (ClassEval_18_0.CamelCaseMapTestSetitem.test_setitem_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_18_0.py", line 123, in test_setitem_4
    self.assertEqual(camelize_map['first_name'], 'newname')
AssertionError: 'John' != 'newname'
- John
+ newname


----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=1)
...E.
======================================================================
ERROR: test_delitem_4 (ClassEval_18_0.CamelCaseMapTestDelitem.test_delitem_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_18_0.py", line 155, in test_delitem_4
    camelize_map.__delitem__('firstName')
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_18_0.py", line 37, in __delitem__
    del self._data[self._convert_key(key)]
        ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'Firstname'

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (errors=1)
FFFFF
======================================================================
FAIL: test_iter_1 (ClassEval_18_0.CamelCaseMapTestIter.test_iter_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_18_0.py", line 175, in test_iter_1
    self.assertEqual(key, lst[i])
AssertionError: 'FirstName' != 'firstName'
- FirstName
? ^
+ firstName
? ^


======================================================================
FAIL: test_iter_2 (ClassEval_18_0.CamelCaseMapTestIter.test_iter_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_18_0.py", line 187, in test_iter_2
    self.assertEqual(key, lst[i])
AssertionError: 'Firstname' != 'firstname'
- Firstname
? ^
+ firstname
? ^


======================================================================
FAIL: test_iter_3 (ClassEval_18_0.CamelCaseMapTestIter.test_iter_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_18_0.py", line 199, in test_iter_3
    self.assertEqual(key, lst[i])
AssertionError: 'FirstName' != 'firstName'
- FirstName
? ^
+ firstName
? ^


======================================================================
FAIL: test_iter_4 (ClassEval_18_0.CamelCaseMapTestIter.test_iter_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_18_0.py", line 210, in test_iter_4
    self.assertEqual(key, lst[i])
AssertionError: 'FirstName' != 'firstName'
- FirstName
? ^
+ firstName
? ^


======================================================================
FAIL: test_iter_5 (ClassEval_18_0.CamelCaseMapTestIter.test_iter_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_18_0.py", line 220, in test_iter_5
    self.assertEqual(key, lst[i])
AssertionError: 'FirstName' != 'firstName'
- FirstName
? ^
+ firstName
? ^


----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=5)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
FFFFFE
======================================================================
ERROR: test_convert_key_6 (ClassEval_18_0.CamelCaseMapTestConvertKey.test_convert_key_6)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_18_0.py", line 275, in test_convert_key_6
    self.assertEqual(camelize_map._convert_key(1234), 1234)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_18_0.py", line 59, in _convert_key
    return ''.join(word.capitalize() for word in key.split('_'))
                                                 ^^^^^^^^^
AttributeError: 'int' object has no attribute 'split'

======================================================================
FAIL: test_convert_key_1 (ClassEval_18_0.CamelCaseMapTestConvertKey.test_convert_key_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_18_0.py", line 255, in test_convert_key_1
    self.assertEqual(camelize_map._convert_key('aaa_bbb'), 'aaaBbb')
AssertionError: 'AaaBbb' != 'aaaBbb'
- AaaBbb
? ^
+ aaaBbb
? ^


======================================================================
FAIL: test_convert_key_2 (ClassEval_18_0.CamelCaseMapTestConvertKey.test_convert_key_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_18_0.py", line 259, in test_convert_key_2
    self.assertEqual(camelize_map._convert_key('first_name'), 'firstName')
AssertionError: 'FirstName' != 'firstName'
- FirstName
? ^
+ firstName
? ^


======================================================================
FAIL: test_convert_key_3 (ClassEval_18_0.CamelCaseMapTestConvertKey.test_convert_key_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_18_0.py", line 263, in test_convert_key_3
    self.assertEqual(camelize_map._convert_key('last_name'), 'lastName')
AssertionError: 'LastName' != 'lastName'
- LastName
? ^
+ lastName
? ^


======================================================================
FAIL: test_convert_key_4 (ClassEval_18_0.CamelCaseMapTestConvertKey.test_convert_key_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_18_0.py", line 267, in test_convert_key_4
    self.assertEqual(camelize_map._convert_key('ccc_ddd'), 'cccDdd')
AssertionError: 'CccDdd' != 'cccDdd'
- CccDdd
? ^
+ cccDdd
? ^


======================================================================
FAIL: test_convert_key_5 (ClassEval_18_0.CamelCaseMapTestConvertKey.test_convert_key_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_18_0.py", line 271, in test_convert_key_5
    self.assertEqual(camelize_map._convert_key('eee_fff'), 'eeeFff')
AssertionError: 'EeeFff' != 'eeeFff'
- EeeFff
? ^
+ eeeFff
? ^


----------------------------------------------------------------------
Ran 6 tests in 0.002s

FAILED (failures=5, errors=1)
FFFFF
======================================================================
FAIL: test_to_camel_case_1 (ClassEval_18_0.CamelCaseMapTestToCamelCase.test_to_camel_case_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_18_0.py", line 280, in test_to_camel_case_1
    self.assertEqual(CamelCaseMap._to_camel_case('aaa_bbb'), 'aaaBbb')
AssertionError: 'AaaBbb' != 'aaaBbb'
- AaaBbb
? ^
+ aaaBbb
? ^


======================================================================
FAIL: test_to_camel_case_2 (ClassEval_18_0.CamelCaseMapTestToCamelCase.test_to_camel_case_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_18_0.py", line 283, in test_to_camel_case_2
    self.assertEqual(CamelCaseMap._to_camel_case('first_name'), 'firstName')
AssertionError: 'FirstName' != 'firstName'
- FirstName
? ^
+ firstName
? ^


======================================================================
FAIL: test_to_camel_case_3 (ClassEval_18_0.CamelCaseMapTestToCamelCase.test_to_camel_case_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_18_0.py", line 286, in test_to_camel_case_3
    self.assertEqual(CamelCaseMap._to_camel_case('last_name'), 'lastName')
AssertionError: 'LastName' != 'lastName'
- LastName
? ^
+ lastName
? ^


======================================================================
FAIL: test_to_camel_case_4 (ClassEval_18_0.CamelCaseMapTestToCamelCase.test_to_camel_case_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_18_0.py", line 289, in test_to_camel_case_4
    self.assertEqual(CamelCaseMap._to_camel_case('ccc_ddd'), 'cccDdd')
AssertionError: 'CccDdd' != 'cccDdd'
- CccDdd
? ^
+ cccDdd
? ^


======================================================================
FAIL: test_to_camel_case_5 (ClassEval_18_0.CamelCaseMapTestToCamelCase.test_to_camel_case_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_18_0.py", line 292, in test_to_camel_case_5
    self.assertEqual(CamelCaseMap._to_camel_case('eee_fff'), 'eeeFff')
AssertionError: 'EeeFff' != 'eeeFff'
- EeeFff
? ^
+ eeeFff
? ^


----------------------------------------------------------------------
Ran 5 tests in 0.002s

FAILED (failures=5)
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
F.FFF.
======================================================================
FAIL: test_convert_1 (ClassEval_27_0.CurrencyConverterTestConvert.test_convert_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_27_0.py", line 71, in test_convert_1
    self.assertEqual(res, 10.0)
AssertionError: 409.6 != 10.0

======================================================================
FAIL: test_convert_3 (ClassEval_27_0.CurrencyConverterTestConvert.test_convert_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_27_0.py", line 81, in test_convert_3
    self.assertAlmostEqual(res, 7.1999999999999)
AssertionError: 568.8888888888889 != 7.1999999999999 within 7 places (561.688888888889 difference)

======================================================================
FAIL: test_convert_4 (ClassEval_27_0.CurrencyConverterTestConvert.test_convert_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_27_0.py", line 86, in test_convert_4
    self.assertAlmostEqual(res, 46.08)
AssertionError: 88.88888888888889 != 46.08 within 7 places (42.80888888888889 difference)

======================================================================
FAIL: test_convert_5 (ClassEval_27_0.CurrencyConverterTestConvert.test_convert_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_27_0.py", line 91, in test_convert_5
    self.assertAlmostEqual(res, 78.72)
AssertionError: 52.03252032520325 != 78.72 within 7 places (26.687479674796748 difference)

----------------------------------------------------------------------
Ran 6 tests in 0.001s

FAILED (failures=4)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.000s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.000s

OK
F
======================================================================
FAIL: test_currencyconverter (ClassEval_27_0.CurrencyConverterTest.test_currencyconverter)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_27_0.py", line 194, in test_currencyconverter
    self.assertEqual(res, 10.0)
AssertionError: 409.6 != 10.0

----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (failures=1)
.......
----------------------------------------------------------------------
Ran 7 tests in 0.000s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.000s

OK
EEEEE
======================================================================
ERROR: test_rail_fence_decipher (ClassEval_32_0.DecryptionUtilsTestRailFenceDecipher.test_rail_fence_decipher)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_32_0.py", line 139, in test_rail_fence_decipher
    self.assertEqual(d.rail_fence_decipher('Hoo!el,Wrdl l', 3), 'Hello, World!')
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_32_0.py", line 74, in rail_fence_decipher
    plaintext[row] += char
    ~~~~~~~~~^^^^^
IndexError: list index out of range

======================================================================
ERROR: test_rail_fence_decipher_2 (ClassEval_32_0.DecryptionUtilsTestRailFenceDecipher.test_rail_fence_decipher_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_32_0.py", line 143, in test_rail_fence_decipher_2
    self.assertEqual(d.rail_fence_decipher('Hoo!el,Wrdl l', 4), 'H!W reoldll,o')
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_32_0.py", line 69, in rail_fence_decipher
    plaintext[row] += chr((ord(char) - ord('a') - row) % 26 + ord('a'))
    ~~~~~~~~~^^^^^
IndexError: list index out of range

======================================================================
ERROR: test_rail_fence_decipher_3 (ClassEval_32_0.DecryptionUtilsTestRailFenceDecipher.test_rail_fence_decipher_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_32_0.py", line 147, in test_rail_fence_decipher_3
    self.assertEqual(d.rail_fence_decipher('Hoo!el,Wrdl l', 5), 'Holr d,!oeWll')
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_32_0.py", line 74, in rail_fence_decipher
    plaintext[row] += char
    ~~~~~~~~~^^^^^
IndexError: list index out of range

======================================================================
ERROR: test_rail_fence_decipher_4 (ClassEval_32_0.DecryptionUtilsTestRailFenceDecipher.test_rail_fence_decipher_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_32_0.py", line 151, in test_rail_fence_decipher_4
    self.assertEqual(d.rail_fence_decipher('Hoo!el,Wrdl l', 6), 'Holrll d,!oeW')
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_32_0.py", line 69, in rail_fence_decipher
    plaintext[row] += chr((ord(char) - ord('a') - row) % 26 + ord('a'))
    ~~~~~~~~~^^^^^
IndexError: list index out of range

======================================================================
ERROR: test_rail_fence_decipher_5 (ClassEval_32_0.DecryptionUtilsTestRailFenceDecipher.test_rail_fence_decipher_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_32_0.py", line 155, in test_rail_fence_decipher_5
    self.assertEqual(d.rail_fence_decipher('Hoo!el,Wrdl l', 7), 'Hoe,rll dWl!o')
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_32_0.py", line 69, in rail_fence_decipher
    plaintext[row] += chr((ord(char) - ord('a') - row) % 26 + ord('a'))
    ~~~~~~~~~^^^^^
IndexError: list index out of range

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (errors=5)
E
======================================================================
ERROR: test_main (ClassEval_32_0.DecryptionUtilsTestMain.test_main)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_32_0.py", line 163, in test_main
    self.assertEqual(d.rail_fence_decipher('Hoo!el,Wrdl l', 3), 'Hello, World!')
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_32_0.py", line 74, in rail_fence_decipher
    plaintext[row] += char
    ~~~~~~~~~^^^^^
IndexError: list index out of range

----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (errors=1)
......
----------------------------------------------------------------------
Ran 6 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
......E
======================================================================
ERROR: test_interpolate_1d_7 (ClassEval_46_0.InterpolationTestInterpolate1d.test_interpolate_1d_7)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_46_0.py", line 61, in test_interpolate_1d_7
    self.assertEqual(interpolation.interpolate_1d([], [], [[], []]), [])
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_46_0.py", line 22, in interpolate_1d
    if xi < min(x) or xi > max(x):
            ^^^^^^
ValueError: min() iterable argument is empty

----------------------------------------------------------------------
Ran 7 tests in 0.001s

FAILED (errors=1)
EEEEE
======================================================================
ERROR: test_interpolate_2d (ClassEval_46_0.InterpolationTestInterpolate2d.test_interpolate_2d)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_46_0.py", line 68, in test_interpolate_2d
    interpolation.interpolate_2d([1, 2, 3], [1, 2, 3], [[1, 2, 3], [4, 5, 6], [7, 8, 9]], [1.5, 2.5],
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Interpolation' object has no attribute 'interpolate_2d'. Did you mean: 'interpolate_1d'?

======================================================================
ERROR: test_interpolate_2d_2 (ClassEval_46_0.InterpolationTestInterpolate2d.test_interpolate_2d_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_46_0.py", line 74, in test_interpolate_2d_2
    interpolation.interpolate_2d([1, 2, 3], [1, 2, 3], [[1, 2, 3], [4, 5, 6], [7, 8, 9]], [1.5, 2.5], [3, 4]),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Interpolation' object has no attribute 'interpolate_2d'. Did you mean: 'interpolate_1d'?

======================================================================
ERROR: test_interpolate_2d_3 (ClassEval_46_0.InterpolationTestInterpolate2d.test_interpolate_2d_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_46_0.py", line 80, in test_interpolate_2d_3
    interpolation.interpolate_2d([1, 2, 3], [1, 2, 3], [[1, 2, 3], [4, 5, 6], [7, 8, 9]], [3, 4], [1.5, 2.5]),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Interpolation' object has no attribute 'interpolate_2d'. Did you mean: 'interpolate_1d'?

======================================================================
ERROR: test_interpolate_2d_4 (ClassEval_46_0.InterpolationTestInterpolate2d.test_interpolate_2d_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_46_0.py", line 86, in test_interpolate_2d_4
    interpolation.interpolate_2d([1, 2, 3], [1, 2, 3], [[1, 2, 3], [4, 5, 6], [7, 8, 9]], [3, 4], [3, 4]),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Interpolation' object has no attribute 'interpolate_2d'. Did you mean: 'interpolate_1d'?

======================================================================
ERROR: test_interpolate_2d_5 (ClassEval_46_0.InterpolationTestInterpolate2d.test_interpolate_2d_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_46_0.py", line 92, in test_interpolate_2d_5
    interpolation.interpolate_2d([1, 2, 3], [1, 2, 3], [[1, 2, 3], [4, 5, 6], [7, 8, 9]], [1.5, 2.5],
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Interpolation' object has no attribute 'interpolate_2d'. Did you mean: 'interpolate_1d'?

----------------------------------------------------------------------
Ran 5 tests in 0.005s

FAILED (errors=5)
E
======================================================================
ERROR: test_main (ClassEval_46_0.InterpolationTestMain.test_main)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_46_0.py", line 101, in test_main
    interpolation.interpolate_2d([1, 2, 3], [1, 2, 3], [[1, 2, 3], [4, 5, 6], [7, 8, 9]], [1.5, 2.5],
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Interpolation' object has no attribute 'interpolate_2d'. Did you mean: 'interpolate_1d'?

----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (errors=1)
EEEEE
======================================================================
ERROR: test_is_valid_1 (ClassEval_47_0.IPAddressTestIsValid.test_is_valid_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_47_0.py", line 8, in test_is_valid_1
    ipaddress = IPAddress("10.10.10.10")
                ^^^^^^^^^
NameError: name 'IPAddress' is not defined. Did you mean: 'IPAddressTest'?

======================================================================
ERROR: test_is_valid_2 (ClassEval_47_0.IPAddressTestIsValid.test_is_valid_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_47_0.py", line 12, in test_is_valid_2
    ipaddress = IPAddress("-1.10.10.10")
                ^^^^^^^^^
NameError: name 'IPAddress' is not defined. Did you mean: 'IPAddressTest'?

======================================================================
ERROR: test_is_valid_3 (ClassEval_47_0.IPAddressTestIsValid.test_is_valid_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_47_0.py", line 16, in test_is_valid_3
    ipaddress = IPAddress("10.10.10")
                ^^^^^^^^^
NameError: name 'IPAddress' is not defined. Did you mean: 'IPAddressTest'?

======================================================================
ERROR: test_is_valid_4 (ClassEval_47_0.IPAddressTestIsValid.test_is_valid_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_47_0.py", line 20, in test_is_valid_4
    ipaddress = IPAddress("a.10.10.10")
                ^^^^^^^^^
NameError: name 'IPAddress' is not defined. Did you mean: 'IPAddressTest'?

======================================================================
ERROR: test_is_valid_5 (ClassEval_47_0.IPAddressTestIsValid.test_is_valid_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_47_0.py", line 24, in test_is_valid_5
    ipaddress = IPAddress("300.10.10.10")
                ^^^^^^^^^
NameError: name 'IPAddress' is not defined. Did you mean: 'IPAddressTest'?

----------------------------------------------------------------------
Ran 5 tests in 0.011s

FAILED (errors=5)
EEEEE
======================================================================
ERROR: test_get_octets_1 (ClassEval_47_0.IPAddressTestGetOctets.test_get_octets_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_47_0.py", line 30, in test_get_octets_1
    ipaddress = IPAddress("10.10.10.10")
                ^^^^^^^^^
NameError: name 'IPAddress' is not defined. Did you mean: 'IPAddressTest'?

======================================================================
ERROR: test_get_octets_2 (ClassEval_47_0.IPAddressTestGetOctets.test_get_octets_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_47_0.py", line 34, in test_get_octets_2
    ipaddress = IPAddress("a.10.10.10")
                ^^^^^^^^^
NameError: name 'IPAddress' is not defined. Did you mean: 'IPAddressTest'?

======================================================================
ERROR: test_get_octets_3 (ClassEval_47_0.IPAddressTestGetOctets.test_get_octets_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_47_0.py", line 38, in test_get_octets_3
    ipaddress = IPAddress("-1.10.10.10")
                ^^^^^^^^^
NameError: name 'IPAddress' is not defined. Did you mean: 'IPAddressTest'?

======================================================================
ERROR: test_get_octets_4 (ClassEval_47_0.IPAddressTestGetOctets.test_get_octets_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_47_0.py", line 42, in test_get_octets_4
    ipaddress = IPAddress("300.10.10.10")
                ^^^^^^^^^
NameError: name 'IPAddress' is not defined. Did you mean: 'IPAddressTest'?

======================================================================
ERROR: test_get_octets_5 (ClassEval_47_0.IPAddressTestGetOctets.test_get_octets_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_47_0.py", line 46, in test_get_octets_5
    ipaddress = IPAddress(".10.10.10")
                ^^^^^^^^^
NameError: name 'IPAddress' is not defined. Did you mean: 'IPAddressTest'?

----------------------------------------------------------------------
Ran 5 tests in 0.010s

FAILED (errors=5)
EEEEE
======================================================================
ERROR: test_get_binary_1 (ClassEval_47_0.IPAddressTestGetBinary.test_get_binary_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_47_0.py", line 52, in test_get_binary_1
    ipaddress = IPAddress("10.10.10.10")
                ^^^^^^^^^
NameError: name 'IPAddress' is not defined. Did you mean: 'IPAddressTest'?

======================================================================
ERROR: test_get_binary_2 (ClassEval_47_0.IPAddressTestGetBinary.test_get_binary_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_47_0.py", line 56, in test_get_binary_2
    ipaddress = IPAddress("a.10.10.10")
                ^^^^^^^^^
NameError: name 'IPAddress' is not defined. Did you mean: 'IPAddressTest'?

======================================================================
ERROR: test_get_binary_3 (ClassEval_47_0.IPAddressTestGetBinary.test_get_binary_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_47_0.py", line 60, in test_get_binary_3
    ipaddress = IPAddress("-1.10.10.10")
                ^^^^^^^^^
NameError: name 'IPAddress' is not defined. Did you mean: 'IPAddressTest'?

======================================================================
ERROR: test_get_binary_4 (ClassEval_47_0.IPAddressTestGetBinary.test_get_binary_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_47_0.py", line 64, in test_get_binary_4
    ipaddress = IPAddress("300.10.10.10")
                ^^^^^^^^^
NameError: name 'IPAddress' is not defined. Did you mean: 'IPAddressTest'?

======================================================================
ERROR: test_get_binary_5 (ClassEval_47_0.IPAddressTestGetBinary.test_get_binary_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_47_0.py", line 68, in test_get_binary_5
    ipaddress = IPAddress(".10.10.10")
                ^^^^^^^^^
NameError: name 'IPAddress' is not defined. Did you mean: 'IPAddressTest'?

----------------------------------------------------------------------
Ran 5 tests in 0.012s

FAILED (errors=5)
E
======================================================================
ERROR: test_IPAddress (ClassEval_47_0.IPAddressTest.test_IPAddress)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_47_0.py", line 74, in test_IPAddress
    ipaddress = IPAddress("10.10.10.10")
                ^^^^^^^^^
NameError: name 'IPAddress' is not defined. Did you mean: 'IPAddressTest'?

----------------------------------------------------------------------
Ran 1 test in 0.003s

FAILED (errors=1)
FFFEF
======================================================================
ERROR: test_palindromic_length_4 (ClassEval_55_0.ManacherTestPalindromicLength.test_palindromic_length_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_55_0.py", line 63, in test_palindromic_length_4
    self.assertEqual(manacher.palindromic_length(9, 2, 'a|b|a|b|a|x'), 0)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_55_0.py", line 26, in palindromic_length
    return self.palindromic_length(center - 1, diff, string) + 1
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'

======================================================================
FAIL: test_palindromic_length (ClassEval_55_0.ManacherTestPalindromicLength.test_palindromic_length)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_55_0.py", line 52, in test_palindromic_length
    self.assertEqual(manacher.palindromic_length(2, 1, 'a|b|a|b|a'), 2)
AssertionError: None != 2

======================================================================
FAIL: test_palindromic_length_2 (ClassEval_55_0.ManacherTestPalindromicLength.test_palindromic_length_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_55_0.py", line 55, in test_palindromic_length_2
    self.assertEqual(manacher.palindromic_length(2, 1, 'a|b|a|b|a|x|s|e'), 2)
AssertionError: None != 2

======================================================================
FAIL: test_palindromic_length_3 (ClassEval_55_0.ManacherTestPalindromicLength.test_palindromic_length_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_55_0.py", line 59, in test_palindromic_length_3
    self.assertEqual(manacher.palindromic_length(2, 3, 'a|b|a|b|a|x'), 0)
AssertionError: None != 0

======================================================================
FAIL: test_palindromic_length_5 (ClassEval_55_0.ManacherTestPalindromicLength.test_palindromic_length_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_55_0.py", line 67, in test_palindromic_length_5
    self.assertEqual(manacher.palindromic_length(4, 1, 'a|b|a|b|a|x'), 4)
AssertionError: None != 4

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=4, errors=1)
EEEEE
======================================================================
ERROR: test_palindromic_string (ClassEval_55_0.ManacherTestPalindromicString.test_palindromic_string)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_55_0.py", line 73, in test_palindromic_string
    self.assertEqual(manacher.palindromic_string(), 'ababa')
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_55_0.py", line 42, in palindromic_string
    if length > max_length:
       ^^^^^^^^^^^^^^^^^^^
TypeError: '>' not supported between instances of 'NoneType' and 'int'

======================================================================
ERROR: test_palindromic_string_2 (ClassEval_55_0.ManacherTestPalindromicString.test_palindromic_string_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_55_0.py", line 77, in test_palindromic_string_2
    self.assertEqual(manacher.palindromic_string(), 'ababa')
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_55_0.py", line 42, in palindromic_string
    if length > max_length:
       ^^^^^^^^^^^^^^^^^^^
TypeError: '>' not supported between instances of 'NoneType' and 'int'

======================================================================
ERROR: test_palindromic_string_3 (ClassEval_55_0.ManacherTestPalindromicString.test_palindromic_string_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_55_0.py", line 81, in test_palindromic_string_3
    self.assertEqual(manacher.palindromic_string(), 'ababa')
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_55_0.py", line 42, in palindromic_string
    if length > max_length:
       ^^^^^^^^^^^^^^^^^^^
TypeError: '>' not supported between instances of 'NoneType' and 'int'

======================================================================
ERROR: test_palindromic_string_4 (ClassEval_55_0.ManacherTestPalindromicString.test_palindromic_string_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_55_0.py", line 85, in test_palindromic_string_4
    self.assertEqual(manacher.palindromic_string(), 'ababa')
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_55_0.py", line 42, in palindromic_string
    if length > max_length:
       ^^^^^^^^^^^^^^^^^^^
TypeError: '>' not supported between instances of 'NoneType' and 'int'

======================================================================
ERROR: test_palindromic_string_5 (ClassEval_55_0.ManacherTestPalindromicString.test_palindromic_string_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_55_0.py", line 89, in test_palindromic_string_5
    self.assertEqual(manacher.palindromic_string(), 'aba')
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_55_0.py", line 42, in palindromic_string
    if length > max_length:
       ^^^^^^^^^^^^^^^^^^^
TypeError: '>' not supported between instances of 'NoneType' and 'int'

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (errors=5)
F
======================================================================
FAIL: test_main (ClassEval_55_0.ManacherTestMain.test_main)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_55_0.py", line 95, in test_main
    self.assertEqual(manacher.palindromic_length(2, 1, 'a|b|a|b|a'), 2)
AssertionError: None != 2

----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (failures=1)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
F.F.F
======================================================================
FAIL: test_decimal_to_hex (ClassEval_64_0.NumberConvertTestDecimalToHex.test_decimal_to_hex)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_64_0.py", line 188, in test_decimal_to_hex
    self.assertEqual('a5b7', NumberConverter.decimal_to_hex(42423))
AssertionError: 'a5b7' != 'A5B7'
- a5b7
+ A5B7


======================================================================
FAIL: test_decimal_to_hex_3 (ClassEval_64_0.NumberConvertTestDecimalToHex.test_decimal_to_hex_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_64_0.py", line 194, in test_decimal_to_hex_3
    self.assertEqual('14bab', NumberConverter.decimal_to_hex(84907))
AssertionError: '14bab' != '14BAB'
- 14bab
+ 14BAB


======================================================================
FAIL: test_decimal_to_hex_5 (ClassEval_64_0.NumberConvertTestDecimalToHex.test_decimal_to_hex_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_64_0.py", line 200, in test_decimal_to_hex_5
    self.assertEqual('52eb7', NumberConverter.decimal_to_hex(339639))
AssertionError: '52eb7' != '52EB7'
- 52eb7
+ 52EB7


----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=3)
EEEEE
======================================================================
ERROR: test_hex_to_decimal (ClassEval_64_0.NumberConvertTestHexToDecimal.test_hex_to_decimal)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_64_0.py", line 204, in test_hex_to_decimal
    self.assertEqual(42423, NumberConverter.hex_to_decimal('a5b7'))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_64_0.py", line 116, in hex_to_decimal
    decimal_num = decimal_num * 16 + hex_dict[digit]
                                     ~~~~~~~~^^^^^^^
KeyError: 'a'

======================================================================
ERROR: test_hex_to_decimal_2 (ClassEval_64_0.NumberConvertTestHexToDecimal.test_hex_to_decimal_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_64_0.py", line 207, in test_hex_to_decimal_2
    self.assertEqual(21207, NumberConverter.hex_to_decimal('52d7'))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_64_0.py", line 116, in hex_to_decimal
    decimal_num = decimal_num * 16 + hex_dict[digit]
                                     ~~~~~~~~^^^^^^^
KeyError: 'd'

======================================================================
ERROR: test_hex_to_decimal_3 (ClassEval_64_0.NumberConvertTestHexToDecimal.test_hex_to_decimal_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_64_0.py", line 210, in test_hex_to_decimal_3
    self.assertEqual(84627, NumberConverter.hex_to_decimal('14a93'))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_64_0.py", line 116, in hex_to_decimal
    decimal_num = decimal_num * 16 + hex_dict[digit]
                                     ~~~~~~~~^^^^^^^
KeyError: 'a'

======================================================================
ERROR: test_hex_to_decimal_4 (ClassEval_64_0.NumberConvertTestHexToDecimal.test_hex_to_decimal_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_64_0.py", line 213, in test_hex_to_decimal_4
    self.assertEqual(170615, NumberConverter.hex_to_decimal('29a77'))
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_64_0.py", line 116, in hex_to_decimal
    decimal_num = decimal_num * 16 + hex_dict[digit]
                                     ~~~~~~~~^^^^^^^
KeyError: 'a'

======================================================================
ERROR: test_hex_to_decimal_5 (ClassEval_64_0.NumberConvertTestHexToDecimal.test_hex_to_decimal_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_64_0.py", line 216, in test_hex_to_decimal_5
    self.assertEqual(342647, NumberConverter.hex_to_decimal('53a77'))
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_64_0.py", line 116, in hex_to_decimal
    decimal_num = decimal_num * 16 + hex_dict[digit]
                                     ~~~~~~~~^^^^^^^
KeyError: 'a'

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (errors=5)
F
======================================================================
FAIL: test_main (ClassEval_64_0.NumberConvertTestMain.test_main)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_64_0.py", line 224, in test_main
    self.assertEqual('a5b7', NumberConverter.decimal_to_hex(42423))
AssertionError: 'a5b7' != 'A5B7'
- a5b7
+ A5B7


----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (failures=1)
EEEEFE
======================================================================
ERROR: test_format_1 (ClassEval_65_0.NumberWordFormatterTestFormat.test_format_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_65_0.py", line 104, in test_format_1
    self.assertEqual(formatter.format(123456),
                     ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_65_0.py", line 38, in format
    decimal_part = " AND " + self.trans_two(decimal_part) + " CENTS"
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_65_0.py", line 63, in trans_two
    elif s[0] == "0":
         ~^^^
IndexError: string index out of range

======================================================================
ERROR: test_format_2 (ClassEval_65_0.NumberWordFormatterTestFormat.test_format_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_65_0.py", line 109, in test_format_2
    self.assertEqual(formatter.format(1000), "ONE THOUSAND ONLY")
                     ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_65_0.py", line 34, in format
    integer_part = self.trans_three(integer_part[-3:]) + " " + self.parse_more(len(integer_part) // 3) + " " + self.trans_three(integer_part[:-3])
                                                                                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_65_0.py", line 78, in trans_three
    elif s[1] == "0":
         ~^^^
IndexError: string index out of range

======================================================================
ERROR: test_format_3 (ClassEval_65_0.NumberWordFormatterTestFormat.test_format_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_65_0.py", line 113, in test_format_3
    self.assertEqual(formatter.format(1000000), "ONE MILLION ONLY")
                     ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_65_0.py", line 38, in format
    decimal_part = " AND " + self.trans_two(decimal_part) + " CENTS"
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_65_0.py", line 63, in trans_two
    elif s[0] == "0":
         ~^^^
IndexError: string index out of range

======================================================================
ERROR: test_format_4 (ClassEval_65_0.NumberWordFormatterTestFormat.test_format_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_65_0.py", line 117, in test_format_4
    self.assertEqual(formatter.format(1.23), "ONE AND CENTS TWENTY THREE ONLY")
                     ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_65_0.py", line 36, in format
    integer_part = self.trans_three(integer_part)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_65_0.py", line 78, in trans_three
    elif s[1] == "0":
         ~^^^
IndexError: string index out of range

======================================================================
ERROR: test_format_6 (ClassEval_65_0.NumberWordFormatterTestFormat.test_format_6)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_65_0.py", line 125, in test_format_6
    self.assertEqual(formatter.format(None), "")
                     ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_65_0.py", line 28, in format
    elif x < 0:
         ^^^^^
TypeError: '<' not supported between instances of 'NoneType' and 'int'

======================================================================
FAIL: test_format_5 (ClassEval_65_0.NumberWordFormatterTestFormat.test_format_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_65_0.py", line 121, in test_format_5
    self.assertEqual(formatter.format(0), "ZERO ONLY")
AssertionError: 'ZERO' != 'ZERO ONLY'
- ZERO
+ ZERO ONLY


----------------------------------------------------------------------
Ran 6 tests in 0.002s

FAILED (failures=1, errors=5)
EEEEFE
======================================================================
ERROR: test_format_string_1 (ClassEval_65_0.NumberWordFormatterTestFormatString.test_format_string_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_65_0.py", line 131, in test_format_string_1
    self.assertEqual(formatter.format_string('123456'),
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_65_0.py", line 53, in format_string
    return self.format(int(x))
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_65_0.py", line 38, in format
    decimal_part = " AND " + self.trans_two(decimal_part) + " CENTS"
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_65_0.py", line 63, in trans_two
    elif s[0] == "0":
         ~^^^
IndexError: string index out of range

======================================================================
ERROR: test_format_string_2 (ClassEval_65_0.NumberWordFormatterTestFormatString.test_format_string_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_65_0.py", line 136, in test_format_string_2
    self.assertEqual(formatter.format_string('1000'), "ONE THOUSAND ONLY")
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_65_0.py", line 53, in format_string
    return self.format(int(x))
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_65_0.py", line 34, in format
    integer_part = self.trans_three(integer_part[-3:]) + " " + self.parse_more(len(integer_part) // 3) + " " + self.trans_three(integer_part[:-3])
                                                                                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_65_0.py", line 78, in trans_three
    elif s[1] == "0":
         ~^^^
IndexError: string index out of range

======================================================================
ERROR: test_format_string_3 (ClassEval_65_0.NumberWordFormatterTestFormatString.test_format_string_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_65_0.py", line 140, in test_format_string_3
    self.assertEqual(formatter.format_string('1000000'), "ONE MILLION ONLY")
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_65_0.py", line 53, in format_string
    return self.format(int(x))
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_65_0.py", line 38, in format
    decimal_part = " AND " + self.trans_two(decimal_part) + " CENTS"
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_65_0.py", line 63, in trans_two
    elif s[0] == "0":
         ~^^^
IndexError: string index out of range

======================================================================
ERROR: test_format_string_4 (ClassEval_65_0.NumberWordFormatterTestFormatString.test_format_string_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_65_0.py", line 144, in test_format_string_4
    self.assertEqual(formatter.format_string('1.23'), "ONE AND CENTS TWENTY THREE ONLY")
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_65_0.py", line 51, in format_string
    return self.format(int(integer_part)) + " POINT " + self.format(int(decimal_part))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_65_0.py", line 36, in format
    integer_part = self.trans_three(integer_part)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_65_0.py", line 78, in trans_three
    elif s[1] == "0":
         ~^^^
IndexError: string index out of range

======================================================================
ERROR: test_format_string_6 (ClassEval_65_0.NumberWordFormatterTestFormatString.test_format_string_6)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_65_0.py", line 152, in test_format_string_6
    self.assertEqual(formatter.format_string('10'), "TEN ONLY")
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_65_0.py", line 53, in format_string
    return self.format(int(x))
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_65_0.py", line 38, in format
    decimal_part = " AND " + self.trans_two(decimal_part) + " CENTS"
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_65_0.py", line 63, in trans_two
    elif s[0] == "0":
         ~^^^
IndexError: string index out of range

======================================================================
FAIL: test_format_string_5 (ClassEval_65_0.NumberWordFormatterTestFormatString.test_format_string_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_65_0.py", line 148, in test_format_string_5
    self.assertEqual(formatter.format_string('0'), "ZERO ONLY")
AssertionError: 'ZERO' != 'ZERO ONLY'
- ZERO
+ ZERO ONLY


----------------------------------------------------------------------
Ran 6 tests in 0.003s

FAILED (failures=1, errors=5)
FFF.FF
======================================================================
FAIL: test_trans_two_1 (ClassEval_65_0.NumberWordFormatterTestTransTwo.test_trans_two_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_65_0.py", line 158, in test_trans_two_1
    self.assertEqual(formatter.trans_two("23"), "TWENTY THREE")
AssertionError: 'TWO FORTY' != 'TWENTY THREE'
- TWO FORTY
+ TWENTY THREE


======================================================================
FAIL: test_trans_two_2 (ClassEval_65_0.NumberWordFormatterTestTransTwo.test_trans_two_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_65_0.py", line 162, in test_trans_two_2
    self.assertEqual(formatter.trans_two("10"), "TEN")
AssertionError: 'ONE TEN' != 'TEN'
- ONE TEN
+ TEN


======================================================================
FAIL: test_trans_two_3 (ClassEval_65_0.NumberWordFormatterTestTransTwo.test_trans_two_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_65_0.py", line 166, in test_trans_two_3
    self.assertEqual(formatter.trans_two("05"), "FIVE")
AssertionError: 'SIXTY' != 'FIVE'
- SIXTY
+ FIVE


======================================================================
FAIL: test_trans_two_5 (ClassEval_65_0.NumberWordFormatterTestTransTwo.test_trans_two_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_65_0.py", line 174, in test_trans_two_5
    self.assertEqual(formatter.trans_two("01"), "ONE")
AssertionError: 'TWENTY' != 'ONE'
- TWENTY
+ ONE


======================================================================
FAIL: test_trans_two_6 (ClassEval_65_0.NumberWordFormatterTestTransTwo.test_trans_two_6)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_65_0.py", line 178, in test_trans_two_6
    self.assertEqual(formatter.trans_two("80"), "EIGHTY")
AssertionError: 'EIGHT TEN' != 'EIGHTY'
- EIGHT TEN
+ EIGHTY


----------------------------------------------------------------------
Ran 6 tests in 0.002s

FAILED (failures=5)
F.FFF
======================================================================
FAIL: test_trans_three_1 (ClassEval_65_0.NumberWordFormatterTestTransThree.test_trans_three_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_65_0.py", line 184, in test_trans_three_1
    self.assertEqual(formatter.trans_three("123"), "ONE HUNDRED AND TWENTY THREE")
AssertionError: 'ONE HUNDRED AND TWO FORTY' != 'ONE HUNDRED AND TWENTY THREE'
- ONE HUNDRED AND TWO FORTY
?                   ^^^^^
+ ONE HUNDRED AND TWENTY THREE
?                   ^^  ++++++


======================================================================
FAIL: test_trans_three_3 (ClassEval_65_0.NumberWordFormatterTestTransThree.test_trans_three_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_65_0.py", line 192, in test_trans_three_3
    self.assertEqual(formatter.trans_three("007"), "SEVEN")
AssertionError: 'EIGHTY' != 'SEVEN'
- EIGHTY
+ SEVEN


======================================================================
FAIL: test_trans_three_4 (ClassEval_65_0.NumberWordFormatterTestTransThree.test_trans_three_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_65_0.py", line 196, in test_trans_three_4
    self.assertEqual(formatter.trans_three("001"), "ONE")
AssertionError: 'TWENTY' != 'ONE'
- TWENTY
+ ONE


======================================================================
FAIL: test_trans_three_5 (ClassEval_65_0.NumberWordFormatterTestTransThree.test_trans_three_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_65_0.py", line 200, in test_trans_three_5
    self.assertEqual(formatter.trans_three("006"), "SIX")
AssertionError: 'SEVENTY' != 'SIX'
- SEVENTY
+ SIX


----------------------------------------------------------------------
Ran 5 tests in 0.002s

FAILED (failures=4)
....
----------------------------------------------------------------------
Ran 4 tests in 0.000s

OK
E
======================================================================
ERROR: test_NumberWordFormatter (ClassEval_65_0.NumberWordFormatterTest.test_NumberWordFormatter)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_65_0.py", line 224, in test_NumberWordFormatter
    self.assertEqual(formatter.format(123456),
                     ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_65_0.py", line 38, in format
    decimal_part = " AND " + self.trans_two(decimal_part) + " CENTS"
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_65_0.py", line 63, in trans_two
    elif s[0] == "0":
         ~^^^
IndexError: string index out of range

----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (errors=1)
EFEEEE.FEEE
======================================================================
ERROR: test_replace_1 (ClassEval_66_0.NumericEntityUnescaperTestReplace.test_replace_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_66_0.py", line 55, in test_replace_1
    res = unescaper.replace("&#65;&#66;&#67;")
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_66_0.py", line 29, in replace
    code = int(entity)
           ^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '#65'

======================================================================
ERROR: test_replace_11 (ClassEval_66_0.NumericEntityUnescaperTestReplace.test_replace_11)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_66_0.py", line 105, in test_replace_11
    res = unescaper.replace("&#c1d;&#66;&#67;")
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_66_0.py", line 29, in replace
    code = int(entity)
           ^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '#c1d'

======================================================================
ERROR: test_replace_2 (ClassEval_66_0.NumericEntityUnescaperTestReplace.test_replace_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_66_0.py", line 60, in test_replace_2
    res = unescaper.replace("&#65;&#65;&#65;")
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_66_0.py", line 29, in replace
    code = int(entity)
           ^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '#65'

======================================================================
ERROR: test_replace_3 (ClassEval_66_0.NumericEntityUnescaperTestReplace.test_replace_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_66_0.py", line 65, in test_replace_3
    res = unescaper.replace("&#66;&#66;&#66;")
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_66_0.py", line 29, in replace
    code = int(entity)
           ^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '#66'

======================================================================
ERROR: test_replace_4 (ClassEval_66_0.NumericEntityUnescaperTestReplace.test_replace_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_66_0.py", line 70, in test_replace_4
    res = unescaper.replace("&#67;&#67;&#67;")
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_66_0.py", line 29, in replace
    code = int(entity)
           ^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '#67'

======================================================================
ERROR: test_replace_7 (ClassEval_66_0.NumericEntityUnescaperTestReplace.test_replace_7)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_66_0.py", line 85, in test_replace_7
    res = unescaper.replace("&#X65;&#66;&#67;")
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_66_0.py", line 29, in replace
    code = int(entity)
           ^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '#X65'

======================================================================
ERROR: test_replace_8 (ClassEval_66_0.NumericEntityUnescaperTestReplace.test_replace_8)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_66_0.py", line 90, in test_replace_8
    res = unescaper.replace("&#???;&#66;&#67;")
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_66_0.py", line 29, in replace
    code = int(entity)
           ^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '#???'

======================================================================
ERROR: test_replace_9 (ClassEval_66_0.NumericEntityUnescaperTestReplace.test_replace_9)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_66_0.py", line 95, in test_replace_9
    res = unescaper.replace("&#67;&#67;&#67;;")
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_66_0.py", line 29, in replace
    code = int(entity)
           ^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '#67'

======================================================================
FAIL: test_replace_10 (ClassEval_66_0.NumericEntityUnescaperTestReplace.test_replace_10)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_66_0.py", line 101, in test_replace_10
    self.assertEqual(res, "")
AssertionError: '&#X' != ''
- &#X


======================================================================
FAIL: test_replace_6 (ClassEval_66_0.NumericEntityUnescaperTestReplace.test_replace_6)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_66_0.py", line 81, in test_replace_6
    self.assertEqual(res, "")
AssertionError: '&#' != ''
- &#


----------------------------------------------------------------------
Ran 11 tests in 0.002s

FAILED (failures=2, errors=8)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
E
======================================================================
ERROR: test_numericentityunescaper (ClassEval_66_0.unescaperTest.test_numericentityunescaper)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_66_0.py", line 139, in test_numericentityunescaper
    res = unescaper.replace("&#65;&#66;&#67;")
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_66_0.py", line 29, in replace
    code = int(entity)
           ^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '#65'

----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (errors=1)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
EEEEE
======================================================================
ERROR: test_findall_1 (ClassEval_72_0.RegexUtilsTestFindall.test_findall_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_72_0.py", line 42, in test_findall_1
    res = ru.findall(r'\b\d{3}-\d{3}-\d{4}\b', "123-456-7890 abiguygusu 876-286-9876 kjgufwycs 987-762-9767")
          ^^^^^^^^^^
AttributeError: 'RegexUtils' object has no attribute 'findall'

======================================================================
ERROR: test_findall_2 (ClassEval_72_0.RegexUtilsTestFindall.test_findall_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_72_0.py", line 47, in test_findall_2
    res = ru.findall(r'\b\d{3}-\d{3}-\d{4}\b', "abiguygusu  kjgufwycs 987-762-9767")
          ^^^^^^^^^^
AttributeError: 'RegexUtils' object has no attribute 'findall'

======================================================================
ERROR: test_findall_3 (ClassEval_72_0.RegexUtilsTestFindall.test_findall_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_72_0.py", line 52, in test_findall_3
    res = ru.findall(r'\b\d{3}-\d{3}-\d{4}\b', "abiguygusu  kjgufwycs ")
          ^^^^^^^^^^
AttributeError: 'RegexUtils' object has no attribute 'findall'

======================================================================
ERROR: test_findall_4 (ClassEval_72_0.RegexUtilsTestFindall.test_findall_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_72_0.py", line 57, in test_findall_4
    res = ru.findall(r'\b\d{3}-\d{3}-\d{4}\b', "abiguygusu  111-111-1111 kjgufwycs 987-762-9767")
          ^^^^^^^^^^
AttributeError: 'RegexUtils' object has no attribute 'findall'

======================================================================
ERROR: test_findall_5 (ClassEval_72_0.RegexUtilsTestFindall.test_findall_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_72_0.py", line 62, in test_findall_5
    res = ru.findall(r'\b\d{3}-\d{3}-\d{4}\b', "abiguygusu  111-111-111a kjgufwycs 987-762-9767")
          ^^^^^^^^^^
AttributeError: 'RegexUtils' object has no attribute 'findall'

----------------------------------------------------------------------
Ran 5 tests in 0.003s

FAILED (errors=5)
EEEEE
======================================================================
ERROR: test_split_1 (ClassEval_72_0.RegexUtilsTestSplit.test_split_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_72_0.py", line 69, in test_split_1
    res = ru.split(r'\b\d{3}-\d{3}-\d{4}\b', "123-456-7890 abiguygusu 876-286-9876 kjgufwycs 987-762-9767")
          ^^^^^^^^
AttributeError: 'RegexUtils' object has no attribute 'split'

======================================================================
ERROR: test_split_2 (ClassEval_72_0.RegexUtilsTestSplit.test_split_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_72_0.py", line 74, in test_split_2
    res = ru.split(r'\b\d{3}-\d{3}-\d{4}\b', "1234567890 abiguygusu 8762869876 kjgufwycs 9877629767")
          ^^^^^^^^
AttributeError: 'RegexUtils' object has no attribute 'split'

======================================================================
ERROR: test_split_3 (ClassEval_72_0.RegexUtilsTestSplit.test_split_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_72_0.py", line 79, in test_split_3
    res = ru.split(r'\b\d{3}-\d{3}-\d{4}\b', "111-111-1111 abiguygusu 876-286-9876 kjgufwycs 987-762-9767")
          ^^^^^^^^
AttributeError: 'RegexUtils' object has no attribute 'split'

======================================================================
ERROR: test_split_4 (ClassEval_72_0.RegexUtilsTestSplit.test_split_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_72_0.py", line 84, in test_split_4
    res = ru.split(r'\b\d{3}-\d{3}-\d{4}\b', "123456-7890 abiguygusu 876-286-9876 kjgufwycs 987-762-9767")
          ^^^^^^^^
AttributeError: 'RegexUtils' object has no attribute 'split'

======================================================================
ERROR: test_split_5 (ClassEval_72_0.RegexUtilsTestSplit.test_split_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_72_0.py", line 89, in test_split_5
    res = ru.split(r'\b\d{3}-\d{3}-\d{4}\b', "123-456-789a abiguygusu 876-286-9876 kjgufwycs 987-762-9767")
          ^^^^^^^^
AttributeError: 'RegexUtils' object has no attribute 'split'

----------------------------------------------------------------------
Ran 5 tests in 0.002s

FAILED (errors=5)
EEEEE
======================================================================
ERROR: test_sub_1 (ClassEval_72_0.RegexUtilsTestSub.test_sub_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_72_0.py", line 96, in test_sub_1
    res = ru.sub(r'\b\d{3}-\d{3}-\d{4}\b', 'phone num',
          ^^^^^^
AttributeError: 'RegexUtils' object has no attribute 'sub'

======================================================================
ERROR: test_sub_2 (ClassEval_72_0.RegexUtilsTestSub.test_sub_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_72_0.py", line 102, in test_sub_2
    res = ru.sub(r'\b\d{3}-\d{3}-\d{4}\b', 'phone num',
          ^^^^^^
AttributeError: 'RegexUtils' object has no attribute 'sub'

======================================================================
ERROR: test_sub_3 (ClassEval_72_0.RegexUtilsTestSub.test_sub_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_72_0.py", line 108, in test_sub_3
    res = ru.sub(r'\b\d{3}-\d{3}-\d{4}\b', 'phone num',
          ^^^^^^
AttributeError: 'RegexUtils' object has no attribute 'sub'

======================================================================
ERROR: test_sub_4 (ClassEval_72_0.RegexUtilsTestSub.test_sub_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_72_0.py", line 114, in test_sub_4
    res = ru.sub(r'\b\d{3}-\d{3}-\d{4}\b', 'phone num',
          ^^^^^^
AttributeError: 'RegexUtils' object has no attribute 'sub'

======================================================================
ERROR: test_sub_5 (ClassEval_72_0.RegexUtilsTestSub.test_sub_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_72_0.py", line 120, in test_sub_5
    res = ru.sub(r'\b\d{3}-\d{3}-\d{4}\b', 'phone num',
          ^^^^^^
AttributeError: 'RegexUtils' object has no attribute 'sub'

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (errors=5)
EEEEE
======================================================================
ERROR: test_generate_email_pattern_1 (ClassEval_72_0.RegexUtilsTestGenerateEmailPattern.test_generate_email_pattern_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_72_0.py", line 128, in test_generate_email_pattern_1
    pat = ru.generate_email_pattern()
          ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'RegexUtils' object has no attribute 'generate_email_pattern'

======================================================================
ERROR: test_generate_email_pattern_2 (ClassEval_72_0.RegexUtilsTestGenerateEmailPattern.test_generate_email_pattern_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_72_0.py", line 134, in test_generate_email_pattern_2
    pat = ru.generate_email_pattern()
          ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'RegexUtils' object has no attribute 'generate_email_pattern'

======================================================================
ERROR: test_generate_email_pattern_3 (ClassEval_72_0.RegexUtilsTestGenerateEmailPattern.test_generate_email_pattern_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_72_0.py", line 140, in test_generate_email_pattern_3
    pat = ru.generate_email_pattern()
          ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'RegexUtils' object has no attribute 'generate_email_pattern'

======================================================================
ERROR: test_generate_email_pattern_4 (ClassEval_72_0.RegexUtilsTestGenerateEmailPattern.test_generate_email_pattern_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_72_0.py", line 146, in test_generate_email_pattern_4
    pat = ru.generate_email_pattern()
          ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'RegexUtils' object has no attribute 'generate_email_pattern'

======================================================================
ERROR: test_generate_email_pattern_5 (ClassEval_72_0.RegexUtilsTestGenerateEmailPattern.test_generate_email_pattern_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_72_0.py", line 152, in test_generate_email_pattern_5
    pat = ru.generate_email_pattern()
          ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'RegexUtils' object has no attribute 'generate_email_pattern'

----------------------------------------------------------------------
Ran 5 tests in 0.002s

FAILED (errors=5)
EEEEE
======================================================================
ERROR: test_generate_phone_number_pattern_1 (ClassEval_72_0.RegexUtilsTestGeneratePhoneNumberPattern.test_generate_phone_number_pattern_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_72_0.py", line 160, in test_generate_phone_number_pattern_1
    pat = ru.generate_phone_number_pattern()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'RegexUtils' object has no attribute 'generate_phone_number_pattern'

======================================================================
ERROR: test_generate_phone_number_pattern_2 (ClassEval_72_0.RegexUtilsTestGeneratePhoneNumberPattern.test_generate_phone_number_pattern_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_72_0.py", line 166, in test_generate_phone_number_pattern_2
    pat = ru.generate_phone_number_pattern()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'RegexUtils' object has no attribute 'generate_phone_number_pattern'

======================================================================
ERROR: test_generate_phone_number_pattern_3 (ClassEval_72_0.RegexUtilsTestGeneratePhoneNumberPattern.test_generate_phone_number_pattern_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_72_0.py", line 172, in test_generate_phone_number_pattern_3
    pat = ru.generate_phone_number_pattern()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'RegexUtils' object has no attribute 'generate_phone_number_pattern'

======================================================================
ERROR: test_generate_phone_number_pattern_4 (ClassEval_72_0.RegexUtilsTestGeneratePhoneNumberPattern.test_generate_phone_number_pattern_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_72_0.py", line 178, in test_generate_phone_number_pattern_4
    pat = ru.generate_phone_number_pattern()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'RegexUtils' object has no attribute 'generate_phone_number_pattern'

======================================================================
ERROR: test_generate_phone_number_pattern_5 (ClassEval_72_0.RegexUtilsTestGeneratePhoneNumberPattern.test_generate_phone_number_pattern_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_72_0.py", line 184, in test_generate_phone_number_pattern_5
    pat = ru.generate_phone_number_pattern()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'RegexUtils' object has no attribute 'generate_phone_number_pattern'

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (errors=5)
EEEEE
======================================================================
ERROR: test_generate_split_sentences_pattern_1 (ClassEval_72_0.RegexUtilsTestGenerateSplitSentencesPattern.test_generate_split_sentences_pattern_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_72_0.py", line 192, in test_generate_split_sentences_pattern_1
    pat = ru.generate_split_sentences_pattern()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'RegexUtils' object has no attribute 'generate_split_sentences_pattern'

======================================================================
ERROR: test_generate_split_sentences_pattern_2 (ClassEval_72_0.RegexUtilsTestGenerateSplitSentencesPattern.test_generate_split_sentences_pattern_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_72_0.py", line 198, in test_generate_split_sentences_pattern_2
    pat = ru.generate_split_sentences_pattern()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'RegexUtils' object has no attribute 'generate_split_sentences_pattern'

======================================================================
ERROR: test_generate_split_sentences_pattern_3 (ClassEval_72_0.RegexUtilsTestGenerateSplitSentencesPattern.test_generate_split_sentences_pattern_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_72_0.py", line 204, in test_generate_split_sentences_pattern_3
    pat = ru.generate_split_sentences_pattern()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'RegexUtils' object has no attribute 'generate_split_sentences_pattern'

======================================================================
ERROR: test_generate_split_sentences_pattern_4 (ClassEval_72_0.RegexUtilsTestGenerateSplitSentencesPattern.test_generate_split_sentences_pattern_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_72_0.py", line 210, in test_generate_split_sentences_pattern_4
    pat = ru.generate_split_sentences_pattern()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'RegexUtils' object has no attribute 'generate_split_sentences_pattern'

======================================================================
ERROR: test_generate_split_sentences_pattern_5 (ClassEval_72_0.RegexUtilsTestGenerateSplitSentencesPattern.test_generate_split_sentences_pattern_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_72_0.py", line 216, in test_generate_split_sentences_pattern_5
    pat = ru.generate_split_sentences_pattern()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'RegexUtils' object has no attribute 'generate_split_sentences_pattern'

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (errors=5)
EEEEE
======================================================================
ERROR: test_split_sentences_1 (ClassEval_72_0.RegexUtilsTestSplitSentences.test_split_sentences_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_72_0.py", line 224, in test_split_sentences_1
    res = ru.split_sentences("Aaa. Bbbb? Ccc!")
          ^^^^^^^^^^^^^^^^^^
AttributeError: 'RegexUtils' object has no attribute 'split_sentences'

======================================================================
ERROR: test_split_sentences_2 (ClassEval_72_0.RegexUtilsTestSplitSentences.test_split_sentences_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_72_0.py", line 229, in test_split_sentences_2
    res = ru.split_sentences("Aaa.Bbbb? Ccc!")
          ^^^^^^^^^^^^^^^^^^
AttributeError: 'RegexUtils' object has no attribute 'split_sentences'

======================================================================
ERROR: test_split_sentences_3 (ClassEval_72_0.RegexUtilsTestSplitSentences.test_split_sentences_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_72_0.py", line 234, in test_split_sentences_3
    res = ru.split_sentences("Aaa. bbbb? Ccc!")
          ^^^^^^^^^^^^^^^^^^
AttributeError: 'RegexUtils' object has no attribute 'split_sentences'

======================================================================
ERROR: test_split_sentences_4 (ClassEval_72_0.RegexUtilsTestSplitSentences.test_split_sentences_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_72_0.py", line 239, in test_split_sentences_4
    res = ru.split_sentences("Aaa. bbbb, Ccc!")
          ^^^^^^^^^^^^^^^^^^
AttributeError: 'RegexUtils' object has no attribute 'split_sentences'

======================================================================
ERROR: test_split_sentences_5 (ClassEval_72_0.RegexUtilsTestSplitSentences.test_split_sentences_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_72_0.py", line 244, in test_split_sentences_5
    res = ru.split_sentences("Aaa, Bbbb? Ccc!")
          ^^^^^^^^^^^^^^^^^^
AttributeError: 'RegexUtils' object has no attribute 'split_sentences'

----------------------------------------------------------------------
Ran 5 tests in 0.005s

FAILED (errors=5)
EEEEE
======================================================================
ERROR: test_validate_phone_number_1 (ClassEval_72_0.RegexUtilsTestValidatePhoneNumber.test_validate_phone_number_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_72_0.py", line 251, in test_validate_phone_number_1
    res = ru.validate_phone_number("123-456-7890")
          ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'RegexUtils' object has no attribute 'validate_phone_number'

======================================================================
ERROR: test_validate_phone_number_2 (ClassEval_72_0.RegexUtilsTestValidatePhoneNumber.test_validate_phone_number_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_72_0.py", line 256, in test_validate_phone_number_2
    res = ru.validate_phone_number("1234567890")
          ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'RegexUtils' object has no attribute 'validate_phone_number'

======================================================================
ERROR: test_validate_phone_number_3 (ClassEval_72_0.RegexUtilsTestValidatePhoneNumber.test_validate_phone_number_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_72_0.py", line 261, in test_validate_phone_number_3
    res = ru.validate_phone_number("a23-456-7890")
          ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'RegexUtils' object has no attribute 'validate_phone_number'

======================================================================
ERROR: test_validate_phone_number_4 (ClassEval_72_0.RegexUtilsTestValidatePhoneNumber.test_validate_phone_number_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_72_0.py", line 266, in test_validate_phone_number_4
    res = ru.validate_phone_number("123-456-789")
          ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'RegexUtils' object has no attribute 'validate_phone_number'

======================================================================
ERROR: test_validate_phone_number_5 (ClassEval_72_0.RegexUtilsTestValidatePhoneNumber.test_validate_phone_number_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_72_0.py", line 271, in test_validate_phone_number_5
    res = ru.validate_phone_number("1234-56-789")
          ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'RegexUtils' object has no attribute 'validate_phone_number'

----------------------------------------------------------------------
Ran 5 tests in 0.004s

FAILED (errors=5)
EEEEE
======================================================================
ERROR: test_extract_email_1 (ClassEval_72_0.RegexUtilsTestExtractEmail.test_extract_email_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_72_0.py", line 278, in test_extract_email_1
    res = ru.extract_email("abcdefg@163.com ygusyfysy@126.com wljduyuv@qq.com")
          ^^^^^^^^^^^^^^^^
AttributeError: 'RegexUtils' object has no attribute 'extract_email'

======================================================================
ERROR: test_extract_email_2 (ClassEval_72_0.RegexUtilsTestExtractEmail.test_extract_email_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_72_0.py", line 283, in test_extract_email_2
    res = ru.extract_email("abcdefg@.com ygusyfysy@126.com wljduyuv@qq.com")
          ^^^^^^^^^^^^^^^^
AttributeError: 'RegexUtils' object has no attribute 'extract_email'

======================================================================
ERROR: test_extract_email_3 (ClassEval_72_0.RegexUtilsTestExtractEmail.test_extract_email_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_72_0.py", line 288, in test_extract_email_3
    res = ru.extract_email("abcdefgiscom ygusyfysy@126.com wljduyuv@qq.com")
          ^^^^^^^^^^^^^^^^
AttributeError: 'RegexUtils' object has no attribute 'extract_email'

======================================================================
ERROR: test_extract_email_4 (ClassEval_72_0.RegexUtilsTestExtractEmail.test_extract_email_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_72_0.py", line 293, in test_extract_email_4
    res = ru.extract_email("abcdefgiscom ygusyfysy126.com wljduyuv@qq.com")
          ^^^^^^^^^^^^^^^^
AttributeError: 'RegexUtils' object has no attribute 'extract_email'

======================================================================
ERROR: test_extract_email_5 (ClassEval_72_0.RegexUtilsTestExtractEmail.test_extract_email_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_72_0.py", line 298, in test_extract_email_5
    res = ru.extract_email("abcdefgiscom ygusyfysy@.com wljduyuv@qq.com")
          ^^^^^^^^^^^^^^^^
AttributeError: 'RegexUtils' object has no attribute 'extract_email'

----------------------------------------------------------------------
Ran 5 tests in 0.005s

FAILED (errors=5)
E
======================================================================
ERROR: test_regexutils (ClassEval_72_0.RegexUtilsTest.test_regexutils)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_72_0.py", line 308, in test_regexutils
    res = ru.findall(r'\b\d{3}-\d{3}-\d{4}\b', "123-456-7890 abiguygusu 876-286-9876 kjgufwycs 987-762-9767")
          ^^^^^^^^^^
AttributeError: 'RegexUtils' object has no attribute 'findall'

----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (errors=1)
F.FFF
======================================================================
FAIL: test_split_sentences_1 (ClassEval_78_0.SplitSentenceTestSplitSentences.test_split_sentences_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_78_0.py", line 49, in test_split_sentences_1
    self.assertEqual(lst, ['aaa aaaa.', 'bb bbbb bbb?', 'cccc cccc.', 'dd ddd?'])
AssertionError: Lists differ: ['aaa aaaa. bb bbbb bbb? cccc cccc. dd ddd?'] != ['aaa aaaa.', 'bb bbbb bbb?', 'cccc cccc.', 'dd ddd?']

First differing element 0:
'aaa aaaa. bb bbbb bbb? cccc cccc. dd ddd?'
'aaa aaaa.'

Second list contains 3 additional elements.
First extra element 1:
'bb bbbb bbb?'

- ['aaa aaaa. bb bbbb bbb? cccc cccc. dd ddd?']
?            ^            ^          ^

+ ['aaa aaaa.', 'bb bbbb bbb?', 'cccc cccc.', 'dd ddd?']
?            ^^^^            ^^^^          ^^^^


======================================================================
FAIL: test_split_sentences_3 (ClassEval_78_0.SplitSentenceTestSplitSentences.test_split_sentences_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_78_0.py", line 59, in test_split_sentences_3
    self.assertEqual(lst, ['Who is A.B.C.?', 'He is a teacher.'])
AssertionError: Lists differ: ['Who is A.B.C.? He is a teacher.'] != ['Who is A.B.C.?', 'He is a teacher.']

First differing element 0:
'Who is A.B.C.? He is a teacher.'
'Who is A.B.C.?'

Second list contains 1 additional elements.
First extra element 1:
'He is a teacher.'

- ['Who is A.B.C.? He is a teacher.']
?                 ^

+ ['Who is A.B.C.?', 'He is a teacher.']
?                 ^^^^


======================================================================
FAIL: test_split_sentences_4 (ClassEval_78_0.SplitSentenceTestSplitSentences.test_split_sentences_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_78_0.py", line 64, in test_split_sentences_4
    self.assertEqual(lst, ['aaa aaaa.', 'bb bbbb bbb?', 'cccc cccc.'])
AssertionError: Lists differ: ['aaa aaaa. bb bbbb bbb? cccc cccc.'] != ['aaa aaaa.', 'bb bbbb bbb?', 'cccc cccc.']

First differing element 0:
'aaa aaaa. bb bbbb bbb? cccc cccc.'
'aaa aaaa.'

Second list contains 2 additional elements.
First extra element 1:
'bb bbbb bbb?'

- ['aaa aaaa. bb bbbb bbb? cccc cccc.']
?            ^            ^

+ ['aaa aaaa.', 'bb bbbb bbb?', 'cccc cccc.']
?            ^^^^            ^^^^


======================================================================
FAIL: test_split_sentences_5 (ClassEval_78_0.SplitSentenceTestSplitSentences.test_split_sentences_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_78_0.py", line 69, in test_split_sentences_5
    self.assertEqual(lst, ['aaa aaaa.', 'bb bbbb bbb?'])
AssertionError: Lists differ: ['aaa aaaa. bb bbbb bbb?'] != ['aaa aaaa.', 'bb bbbb bbb?']

First differing element 0:
'aaa aaaa. bb bbbb bbb?'
'aaa aaaa.'

Second list contains 1 additional elements.
First extra element 1:
'bb bbbb bbb?'

- ['aaa aaaa. bb bbbb bbb?']
?            ^

+ ['aaa aaaa.', 'bb bbbb bbb?']
?            ^^^^


----------------------------------------------------------------------
Ran 5 tests in 0.002s

FAILED (failures=4)
.FF.F
======================================================================
FAIL: test_count_words_2 (ClassEval_78_0.SplitSentenceTestCountWords.test_count_words_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_78_0.py", line 81, in test_count_words_2
    self.assertEqual(cnt, 2)
AssertionError: 3 != 2

======================================================================
FAIL: test_count_words_3 (ClassEval_78_0.SplitSentenceTestCountWords.test_count_words_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_78_0.py", line 86, in test_count_words_3
    self.assertEqual(cnt, 1)
AssertionError: 2 != 1

======================================================================
FAIL: test_count_words_5 (ClassEval_78_0.SplitSentenceTestCountWords.test_count_words_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_78_0.py", line 96, in test_count_words_5
    self.assertEqual(cnt, 2)
AssertionError: 3 != 2

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=3)
F.FFF
======================================================================
FAIL: test_process_text_file_1 (ClassEval_78_0.SplitSentenceTestProcessTextFile.test_process_text_file_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_78_0.py", line 103, in test_process_text_file_1
    self.assertEqual(cnt, 4)
AssertionError: 11 != 4

======================================================================
FAIL: test_process_text_file_3 (ClassEval_78_0.SplitSentenceTestProcessTextFile.test_process_text_file_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_78_0.py", line 113, in test_process_text_file_3
    self.assertEqual(cnt, 5)
AssertionError: 7 != 5

======================================================================
FAIL: test_process_text_file_4 (ClassEval_78_0.SplitSentenceTestProcessTextFile.test_process_text_file_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_78_0.py", line 118, in test_process_text_file_4
    self.assertEqual(cnt, 4)
AssertionError: 9 != 4

======================================================================
FAIL: test_process_text_file_5 (ClassEval_78_0.SplitSentenceTestProcessTextFile.test_process_text_file_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_78_0.py", line 123, in test_process_text_file_5
    self.assertEqual(cnt, 3)
AssertionError: 5 != 3

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=4)
F
======================================================================
FAIL: test_SplitSentence (ClassEval_78_0.SplitSentenceTest.test_SplitSentence)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_78_0.py", line 130, in test_SplitSentence
    self.assertEqual(lst, ['aaa aaaa.', 'bb bbbb bbb?', 'cccc cccc.', 'dd ddd?'])
AssertionError: Lists differ: ['aaa aaaa. bb bbbb bbb? cccc cccc. dd ddd?'] != ['aaa aaaa.', 'bb bbbb bbb?', 'cccc cccc.', 'dd ddd?']

First differing element 0:
'aaa aaaa. bb bbbb bbb? cccc cccc. dd ddd?'
'aaa aaaa.'

Second list contains 3 additional elements.
First extra element 1:
'bb bbbb bbb?'

- ['aaa aaaa. bb bbbb bbb? cccc cccc. dd ddd?']
?            ^            ^          ^

+ ['aaa aaaa.', 'bb bbbb bbb?', 'cccc cccc.', 'dd ddd?']
?            ^^^^            ^^^^          ^^^^


----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (failures=1)
EEEEE
======================================================================
ERROR: test_add_stock (ClassEval_82_0.StockPortfolioTrackerTestAddStock.test_add_stock)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_82_0.py", line 8, in test_add_stock
    tracker = StockPortfolioTracker(10000.0)
              ^^^^^^^^^^^^^^^^^^^^^
NameError: name 'StockPortfolioTracker' is not defined. Did you mean: 'StockPortfolioTrackerTestMain'?

======================================================================
ERROR: test_add_stock_2 (ClassEval_82_0.StockPortfolioTrackerTestAddStock.test_add_stock_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_82_0.py", line 13, in test_add_stock_2
    tracker = StockPortfolioTracker(10000.0)
              ^^^^^^^^^^^^^^^^^^^^^
NameError: name 'StockPortfolioTracker' is not defined. Did you mean: 'StockPortfolioTrackerTestMain'?

======================================================================
ERROR: test_add_stock_3 (ClassEval_82_0.StockPortfolioTrackerTestAddStock.test_add_stock_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_82_0.py", line 19, in test_add_stock_3
    tracker = StockPortfolioTracker(10000.0)
              ^^^^^^^^^^^^^^^^^^^^^
NameError: name 'StockPortfolioTracker' is not defined. Did you mean: 'StockPortfolioTrackerTestMain'?

======================================================================
ERROR: test_add_stock_4 (ClassEval_82_0.StockPortfolioTrackerTestAddStock.test_add_stock_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_82_0.py", line 26, in test_add_stock_4
    tracker = StockPortfolioTracker(10000.0)
              ^^^^^^^^^^^^^^^^^^^^^
NameError: name 'StockPortfolioTracker' is not defined. Did you mean: 'StockPortfolioTrackerTestMain'?

======================================================================
ERROR: test_add_stock_5 (ClassEval_82_0.StockPortfolioTrackerTestAddStock.test_add_stock_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_82_0.py", line 34, in test_add_stock_5
    tracker = StockPortfolioTracker(10000.0)
              ^^^^^^^^^^^^^^^^^^^^^
NameError: name 'StockPortfolioTracker' is not defined. Did you mean: 'StockPortfolioTrackerTestMain'?

----------------------------------------------------------------------
Ran 5 tests in 0.015s

FAILED (errors=5)
EEEEE
======================================================================
ERROR: test_remove_stock (ClassEval_82_0.StockPortfolioTrackerTestRemoveStock.test_remove_stock)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_82_0.py", line 45, in test_remove_stock
    tracker = StockPortfolioTracker(10000.0)
              ^^^^^^^^^^^^^^^^^^^^^
NameError: name 'StockPortfolioTracker' is not defined. Did you mean: 'StockPortfolioTrackerTestMain'?

======================================================================
ERROR: test_remove_stock_2 (ClassEval_82_0.StockPortfolioTrackerTestRemoveStock.test_remove_stock_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_82_0.py", line 51, in test_remove_stock_2
    tracker = StockPortfolioTracker(10000.0)
              ^^^^^^^^^^^^^^^^^^^^^
NameError: name 'StockPortfolioTracker' is not defined. Did you mean: 'StockPortfolioTrackerTestMain'?

======================================================================
ERROR: test_remove_stock_3 (ClassEval_82_0.StockPortfolioTrackerTestRemoveStock.test_remove_stock_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_82_0.py", line 58, in test_remove_stock_3
    tracker = StockPortfolioTracker(10000.0)
              ^^^^^^^^^^^^^^^^^^^^^
NameError: name 'StockPortfolioTracker' is not defined. Did you mean: 'StockPortfolioTrackerTestMain'?

======================================================================
ERROR: test_remove_stock_4 (ClassEval_82_0.StockPortfolioTrackerTestRemoveStock.test_remove_stock_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_82_0.py", line 66, in test_remove_stock_4
    tracker = StockPortfolioTracker(10000.0)
              ^^^^^^^^^^^^^^^^^^^^^
NameError: name 'StockPortfolioTracker' is not defined. Did you mean: 'StockPortfolioTrackerTestMain'?

======================================================================
ERROR: test_remove_stock_5 (ClassEval_82_0.StockPortfolioTrackerTestRemoveStock.test_remove_stock_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_82_0.py", line 72, in test_remove_stock_5
    tracker = StockPortfolioTracker(10000.0)
              ^^^^^^^^^^^^^^^^^^^^^
NameError: name 'StockPortfolioTracker' is not defined. Did you mean: 'StockPortfolioTrackerTestMain'?

----------------------------------------------------------------------
Ran 5 tests in 0.022s

FAILED (errors=5)
EEEEE
======================================================================
ERROR: test_buy_stock (ClassEval_82_0.StockPortfolioTrackerTestBuyStock.test_buy_stock)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_82_0.py", line 81, in test_buy_stock
    tracker = StockPortfolioTracker(10000.0)
              ^^^^^^^^^^^^^^^^^^^^^
NameError: name 'StockPortfolioTracker' is not defined. Did you mean: 'StockPortfolioTrackerTestMain'?

======================================================================
ERROR: test_buy_stock_2 (ClassEval_82_0.StockPortfolioTrackerTestBuyStock.test_buy_stock_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_82_0.py", line 87, in test_buy_stock_2
    tracker = StockPortfolioTracker(1000.0)
              ^^^^^^^^^^^^^^^^^^^^^
NameError: name 'StockPortfolioTracker' is not defined. Did you mean: 'StockPortfolioTrackerTestMain'?

======================================================================
ERROR: test_buy_stock_3 (ClassEval_82_0.StockPortfolioTrackerTestBuyStock.test_buy_stock_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_82_0.py", line 93, in test_buy_stock_3
    tracker = StockPortfolioTracker(10000.0)
              ^^^^^^^^^^^^^^^^^^^^^
NameError: name 'StockPortfolioTracker' is not defined. Did you mean: 'StockPortfolioTrackerTestMain'?

======================================================================
ERROR: test_buy_stock_4 (ClassEval_82_0.StockPortfolioTrackerTestBuyStock.test_buy_stock_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_82_0.py", line 100, in test_buy_stock_4
    tracker = StockPortfolioTracker(10000.0)
              ^^^^^^^^^^^^^^^^^^^^^
NameError: name 'StockPortfolioTracker' is not defined. Did you mean: 'StockPortfolioTrackerTestMain'?

======================================================================
ERROR: test_buy_stock_5 (ClassEval_82_0.StockPortfolioTrackerTestBuyStock.test_buy_stock_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_82_0.py", line 109, in test_buy_stock_5
    tracker = StockPortfolioTracker(10000.0)
              ^^^^^^^^^^^^^^^^^^^^^
NameError: name 'StockPortfolioTracker' is not defined. Did you mean: 'StockPortfolioTrackerTestMain'?

----------------------------------------------------------------------
Ran 5 tests in 0.022s

FAILED (errors=5)
EEEEE
======================================================================
ERROR: test_sell_stock (ClassEval_82_0.StockPortfolioTrackerTestSellStock.test_sell_stock)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_82_0.py", line 120, in test_sell_stock
    tracker = StockPortfolioTracker(10000.0)
              ^^^^^^^^^^^^^^^^^^^^^
NameError: name 'StockPortfolioTracker' is not defined. Did you mean: 'StockPortfolioTrackerTestMain'?

======================================================================
ERROR: test_sell_stock_2 (ClassEval_82_0.StockPortfolioTrackerTestSellStock.test_sell_stock_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_82_0.py", line 127, in test_sell_stock_2
    tracker = StockPortfolioTracker(10000.0)
              ^^^^^^^^^^^^^^^^^^^^^
NameError: name 'StockPortfolioTracker' is not defined. Did you mean: 'StockPortfolioTrackerTestMain'?

======================================================================
ERROR: test_sell_stock_3 (ClassEval_82_0.StockPortfolioTrackerTestSellStock.test_sell_stock_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_82_0.py", line 134, in test_sell_stock_3
    tracker = StockPortfolioTracker(10000.0)
              ^^^^^^^^^^^^^^^^^^^^^
NameError: name 'StockPortfolioTracker' is not defined. Did you mean: 'StockPortfolioTrackerTestMain'?

======================================================================
ERROR: test_sell_stock_4 (ClassEval_82_0.StockPortfolioTrackerTestSellStock.test_sell_stock_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_82_0.py", line 140, in test_sell_stock_4
    tracker = StockPortfolioTracker(10000.0)
              ^^^^^^^^^^^^^^^^^^^^^
NameError: name 'StockPortfolioTracker' is not defined. Did you mean: 'StockPortfolioTrackerTestMain'?

======================================================================
ERROR: test_sell_stock_5 (ClassEval_82_0.StockPortfolioTrackerTestSellStock.test_sell_stock_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_82_0.py", line 147, in test_sell_stock_5
    tracker = StockPortfolioTracker(10000.0)
              ^^^^^^^^^^^^^^^^^^^^^
NameError: name 'StockPortfolioTracker' is not defined. Did you mean: 'StockPortfolioTrackerTestMain'?

----------------------------------------------------------------------
Ran 5 tests in 0.023s

FAILED (errors=5)
EEEEE
======================================================================
ERROR: test_calculate_portfolio_value (ClassEval_82_0.StockPortfolioTrackerTestCalculatePortfolioValue.test_calculate_portfolio_value)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_82_0.py", line 157, in test_calculate_portfolio_value
    tracker = StockPortfolioTracker(10000.0)
              ^^^^^^^^^^^^^^^^^^^^^
NameError: name 'StockPortfolioTracker' is not defined. Did you mean: 'StockPortfolioTrackerTestMain'?

======================================================================
ERROR: test_calculate_portfolio_value_2 (ClassEval_82_0.StockPortfolioTrackerTestCalculatePortfolioValue.test_calculate_portfolio_value_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_82_0.py", line 162, in test_calculate_portfolio_value_2
    tracker = StockPortfolioTracker(10000.0)
              ^^^^^^^^^^^^^^^^^^^^^
NameError: name 'StockPortfolioTracker' is not defined. Did you mean: 'StockPortfolioTrackerTestMain'?

======================================================================
ERROR: test_calculate_portfolio_value_3 (ClassEval_82_0.StockPortfolioTrackerTestCalculatePortfolioValue.test_calculate_portfolio_value_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_82_0.py", line 168, in test_calculate_portfolio_value_3
    tracker = StockPortfolioTracker(10000.0)
              ^^^^^^^^^^^^^^^^^^^^^
NameError: name 'StockPortfolioTracker' is not defined. Did you mean: 'StockPortfolioTrackerTestMain'?

======================================================================
ERROR: test_calculate_portfolio_value_4 (ClassEval_82_0.StockPortfolioTrackerTestCalculatePortfolioValue.test_calculate_portfolio_value_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_82_0.py", line 172, in test_calculate_portfolio_value_4
    tracker = StockPortfolioTracker(10000.0)
              ^^^^^^^^^^^^^^^^^^^^^
NameError: name 'StockPortfolioTracker' is not defined. Did you mean: 'StockPortfolioTrackerTestMain'?

======================================================================
ERROR: test_calculate_portfolio_value_5 (ClassEval_82_0.StockPortfolioTrackerTestCalculatePortfolioValue.test_calculate_portfolio_value_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_82_0.py", line 177, in test_calculate_portfolio_value_5
    tracker = StockPortfolioTracker(10000.0)
              ^^^^^^^^^^^^^^^^^^^^^
NameError: name 'StockPortfolioTracker' is not defined. Did you mean: 'StockPortfolioTrackerTestMain'?

----------------------------------------------------------------------
Ran 5 tests in 0.018s

FAILED (errors=5)
EEEEE
======================================================================
ERROR: test_get_portfolio_summary (ClassEval_82_0.StockPortfolioTrackerTestGetPortfolioSummary.test_get_portfolio_summary)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_82_0.py", line 184, in test_get_portfolio_summary
    tracker = StockPortfolioTracker(10000.0)
              ^^^^^^^^^^^^^^^^^^^^^
NameError: name 'StockPortfolioTracker' is not defined. Did you mean: 'StockPortfolioTrackerTestMain'?

======================================================================
ERROR: test_get_portfolio_summary_2 (ClassEval_82_0.StockPortfolioTrackerTestGetPortfolioSummary.test_get_portfolio_summary_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_82_0.py", line 189, in test_get_portfolio_summary_2
    tracker = StockPortfolioTracker(10000.0)
              ^^^^^^^^^^^^^^^^^^^^^
NameError: name 'StockPortfolioTracker' is not defined. Did you mean: 'StockPortfolioTrackerTestMain'?

======================================================================
ERROR: test_get_portfolio_summary_3 (ClassEval_82_0.StockPortfolioTrackerTestGetPortfolioSummary.test_get_portfolio_summary_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_82_0.py", line 196, in test_get_portfolio_summary_3
    tracker = StockPortfolioTracker(10000.0)
              ^^^^^^^^^^^^^^^^^^^^^
NameError: name 'StockPortfolioTracker' is not defined. Did you mean: 'StockPortfolioTrackerTestMain'?

======================================================================
ERROR: test_get_portfolio_summary_4 (ClassEval_82_0.StockPortfolioTrackerTestGetPortfolioSummary.test_get_portfolio_summary_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_82_0.py", line 200, in test_get_portfolio_summary_4
    tracker = StockPortfolioTracker(10000.0)
              ^^^^^^^^^^^^^^^^^^^^^
NameError: name 'StockPortfolioTracker' is not defined. Did you mean: 'StockPortfolioTrackerTestMain'?

======================================================================
ERROR: test_get_portfolio_summary_5 (ClassEval_82_0.StockPortfolioTrackerTestGetPortfolioSummary.test_get_portfolio_summary_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_82_0.py", line 205, in test_get_portfolio_summary_5
    tracker = StockPortfolioTracker(10000.0)
              ^^^^^^^^^^^^^^^^^^^^^
NameError: name 'StockPortfolioTracker' is not defined. Did you mean: 'StockPortfolioTrackerTestMain'?

----------------------------------------------------------------------
Ran 5 tests in 0.019s

FAILED (errors=5)
EEEEE
======================================================================
ERROR: test_get_stock_value (ClassEval_82_0.StockPortfolioTrackerTestGetStockValue.test_get_stock_value)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_82_0.py", line 212, in test_get_stock_value
    tracker = StockPortfolioTracker(10000.0)
              ^^^^^^^^^^^^^^^^^^^^^
NameError: name 'StockPortfolioTracker' is not defined. Did you mean: 'StockPortfolioTrackerTestMain'?

======================================================================
ERROR: test_get_stock_value_2 (ClassEval_82_0.StockPortfolioTrackerTestGetStockValue.test_get_stock_value_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_82_0.py", line 216, in test_get_stock_value_2
    tracker = StockPortfolioTracker(10000.0)
              ^^^^^^^^^^^^^^^^^^^^^
NameError: name 'StockPortfolioTracker' is not defined. Did you mean: 'StockPortfolioTrackerTestMain'?

======================================================================
ERROR: test_get_stock_value_3 (ClassEval_82_0.StockPortfolioTrackerTestGetStockValue.test_get_stock_value_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_82_0.py", line 220, in test_get_stock_value_3
    tracker = StockPortfolioTracker(10000.0)
              ^^^^^^^^^^^^^^^^^^^^^
NameError: name 'StockPortfolioTracker' is not defined. Did you mean: 'StockPortfolioTrackerTestMain'?

======================================================================
ERROR: test_get_stock_value_4 (ClassEval_82_0.StockPortfolioTrackerTestGetStockValue.test_get_stock_value_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_82_0.py", line 224, in test_get_stock_value_4
    tracker = StockPortfolioTracker(10000.0)
              ^^^^^^^^^^^^^^^^^^^^^
NameError: name 'StockPortfolioTracker' is not defined. Did you mean: 'StockPortfolioTrackerTestMain'?

======================================================================
ERROR: test_get_stock_value_5 (ClassEval_82_0.StockPortfolioTrackerTestGetStockValue.test_get_stock_value_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_82_0.py", line 228, in test_get_stock_value_5
    tracker = StockPortfolioTracker(10000.0)
              ^^^^^^^^^^^^^^^^^^^^^
NameError: name 'StockPortfolioTracker' is not defined. Did you mean: 'StockPortfolioTrackerTestMain'?

----------------------------------------------------------------------
Ran 5 tests in 0.022s

FAILED (errors=5)
EEE
======================================================================
ERROR: test_main (ClassEval_82_0.StockPortfolioTrackerTestMain.test_main)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_82_0.py", line 234, in test_main
    tracker = StockPortfolioTracker(10000.0)
              ^^^^^^^^^^^^^^^^^^^^^
NameError: name 'StockPortfolioTracker' is not defined. Did you mean: 'StockPortfolioTrackerTestMain'?

======================================================================
ERROR: test_main_2 (ClassEval_82_0.StockPortfolioTrackerTestMain.test_main_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_82_0.py", line 252, in test_main_2
    tracker = StockPortfolioTracker(10000.0)
              ^^^^^^^^^^^^^^^^^^^^^
NameError: name 'StockPortfolioTracker' is not defined. Did you mean: 'StockPortfolioTrackerTestMain'?

======================================================================
ERROR: test_main_3 (ClassEval_82_0.StockPortfolioTrackerTestMain.test_main_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_82_0.py", line 268, in test_main_3
    tracker = StockPortfolioTracker(10000.0)
              ^^^^^^^^^^^^^^^^^^^^^
NameError: name 'StockPortfolioTracker' is not defined. Did you mean: 'StockPortfolioTrackerTestMain'?

----------------------------------------------------------------------
Ran 3 tests in 0.013s

FAILED (errors=3)
EEEEE
======================================================================
ERROR: test_get_current_time_1 (ClassEval_87_0.TimeUtilsTestGetCurrentTime.test_get_current_time_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_87_0.py", line 9, in test_get_current_time_1
    timeutils = TimeUtils()
                ^^^^^^^^^
NameError: name 'TimeUtils' is not defined. Did you mean: 'TimeUtilsTest'?

======================================================================
ERROR: test_get_current_time_2 (ClassEval_87_0.TimeUtilsTestGetCurrentTime.test_get_current_time_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_87_0.py", line 13, in test_get_current_time_2
    timeutils = TimeUtils()
                ^^^^^^^^^
NameError: name 'TimeUtils' is not defined. Did you mean: 'TimeUtilsTest'?

======================================================================
ERROR: test_get_current_time_3 (ClassEval_87_0.TimeUtilsTestGetCurrentTime.test_get_current_time_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_87_0.py", line 17, in test_get_current_time_3
    timeutils = TimeUtils()
                ^^^^^^^^^
NameError: name 'TimeUtils' is not defined. Did you mean: 'TimeUtilsTest'?

======================================================================
ERROR: test_get_current_time_4 (ClassEval_87_0.TimeUtilsTestGetCurrentTime.test_get_current_time_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_87_0.py", line 21, in test_get_current_time_4
    timeutils = TimeUtils()
                ^^^^^^^^^
NameError: name 'TimeUtils' is not defined. Did you mean: 'TimeUtilsTest'?

======================================================================
ERROR: test_get_current_time_5 (ClassEval_87_0.TimeUtilsTestGetCurrentTime.test_get_current_time_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_87_0.py", line 25, in test_get_current_time_5
    timeutils = TimeUtils()
                ^^^^^^^^^
NameError: name 'TimeUtils' is not defined. Did you mean: 'TimeUtilsTest'?

----------------------------------------------------------------------
Ran 5 tests in 0.016s

FAILED (errors=5)
EEEEE
======================================================================
ERROR: test_get_current_date_1 (ClassEval_87_0.TimeUtilsTestGetCurrentDate.test_get_current_date_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_87_0.py", line 31, in test_get_current_date_1
    timeutils = TimeUtils()
                ^^^^^^^^^
NameError: name 'TimeUtils' is not defined. Did you mean: 'TimeUtilsTest'?

======================================================================
ERROR: test_get_current_date_2 (ClassEval_87_0.TimeUtilsTestGetCurrentDate.test_get_current_date_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_87_0.py", line 35, in test_get_current_date_2
    timeutils = TimeUtils()
                ^^^^^^^^^
NameError: name 'TimeUtils' is not defined. Did you mean: 'TimeUtilsTest'?

======================================================================
ERROR: test_get_current_date_3 (ClassEval_87_0.TimeUtilsTestGetCurrentDate.test_get_current_date_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_87_0.py", line 39, in test_get_current_date_3
    timeutils = TimeUtils()
                ^^^^^^^^^
NameError: name 'TimeUtils' is not defined. Did you mean: 'TimeUtilsTest'?

======================================================================
ERROR: test_get_current_date_4 (ClassEval_87_0.TimeUtilsTestGetCurrentDate.test_get_current_date_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_87_0.py", line 43, in test_get_current_date_4
    timeutils = TimeUtils()
                ^^^^^^^^^
NameError: name 'TimeUtils' is not defined. Did you mean: 'TimeUtilsTest'?

======================================================================
ERROR: test_get_current_date_5 (ClassEval_87_0.TimeUtilsTestGetCurrentDate.test_get_current_date_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_87_0.py", line 47, in test_get_current_date_5
    timeutils = TimeUtils()
                ^^^^^^^^^
NameError: name 'TimeUtils' is not defined. Did you mean: 'TimeUtilsTest'?

----------------------------------------------------------------------
Ran 5 tests in 0.011s

FAILED (errors=5)
EEEEE
======================================================================
ERROR: test_add_seconds_1 (ClassEval_87_0.TimeUtilsTestAddSeconds.test_add_seconds_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_87_0.py", line 53, in test_add_seconds_1
    timeutils = TimeUtils()
                ^^^^^^^^^
NameError: name 'TimeUtils' is not defined. Did you mean: 'TimeUtilsTest'?

======================================================================
ERROR: test_add_seconds_2 (ClassEval_87_0.TimeUtilsTestAddSeconds.test_add_seconds_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_87_0.py", line 58, in test_add_seconds_2
    timeutils = TimeUtils()
                ^^^^^^^^^
NameError: name 'TimeUtils' is not defined. Did you mean: 'TimeUtilsTest'?

======================================================================
ERROR: test_add_seconds_3 (ClassEval_87_0.TimeUtilsTestAddSeconds.test_add_seconds_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_87_0.py", line 63, in test_add_seconds_3
    timeutils = TimeUtils()
                ^^^^^^^^^
NameError: name 'TimeUtils' is not defined. Did you mean: 'TimeUtilsTest'?

======================================================================
ERROR: test_add_seconds_4 (ClassEval_87_0.TimeUtilsTestAddSeconds.test_add_seconds_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_87_0.py", line 68, in test_add_seconds_4
    timeutils = TimeUtils()
                ^^^^^^^^^
NameError: name 'TimeUtils' is not defined. Did you mean: 'TimeUtilsTest'?

======================================================================
ERROR: test_add_seconds_5 (ClassEval_87_0.TimeUtilsTestAddSeconds.test_add_seconds_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_87_0.py", line 73, in test_add_seconds_5
    timeutils = TimeUtils()
                ^^^^^^^^^
NameError: name 'TimeUtils' is not defined. Did you mean: 'TimeUtilsTest'?

----------------------------------------------------------------------
Ran 5 tests in 0.010s

FAILED (errors=5)
EEEEE
======================================================================
ERROR: test_string_to_datetime_1 (ClassEval_87_0.TimeUtilsTestStringToDatetime.test_string_to_datetime_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_87_0.py", line 80, in test_string_to_datetime_1
    timeutils = TimeUtils()
                ^^^^^^^^^
NameError: name 'TimeUtils' is not defined. Did you mean: 'TimeUtilsTest'?

======================================================================
ERROR: test_string_to_datetime_2 (ClassEval_87_0.TimeUtilsTestStringToDatetime.test_string_to_datetime_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_87_0.py", line 84, in test_string_to_datetime_2
    timeutils = TimeUtils()
                ^^^^^^^^^
NameError: name 'TimeUtils' is not defined. Did you mean: 'TimeUtilsTest'?

======================================================================
ERROR: test_string_to_datetime_3 (ClassEval_87_0.TimeUtilsTestStringToDatetime.test_string_to_datetime_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_87_0.py", line 88, in test_string_to_datetime_3
    timeutils = TimeUtils()
                ^^^^^^^^^
NameError: name 'TimeUtils' is not defined. Did you mean: 'TimeUtilsTest'?

======================================================================
ERROR: test_string_to_datetime_4 (ClassEval_87_0.TimeUtilsTestStringToDatetime.test_string_to_datetime_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_87_0.py", line 92, in test_string_to_datetime_4
    timeutils = TimeUtils()
                ^^^^^^^^^
NameError: name 'TimeUtils' is not defined. Did you mean: 'TimeUtilsTest'?

======================================================================
ERROR: test_string_to_datetime_5 (ClassEval_87_0.TimeUtilsTestStringToDatetime.test_string_to_datetime_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_87_0.py", line 96, in test_string_to_datetime_5
    timeutils = TimeUtils()
                ^^^^^^^^^
NameError: name 'TimeUtils' is not defined. Did you mean: 'TimeUtilsTest'?

----------------------------------------------------------------------
Ran 5 tests in 0.010s

FAILED (errors=5)
EEEEE
======================================================================
ERROR: test_datetime_to_string_1 (ClassEval_87_0.TimeUtilsTestDatetimeToString.test_datetime_to_string_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_87_0.py", line 102, in test_datetime_to_string_1
    timeutils = TimeUtils()
                ^^^^^^^^^
NameError: name 'TimeUtils' is not defined. Did you mean: 'TimeUtilsTest'?

======================================================================
ERROR: test_datetime_to_string_2 (ClassEval_87_0.TimeUtilsTestDatetimeToString.test_datetime_to_string_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_87_0.py", line 107, in test_datetime_to_string_2
    timeutils = TimeUtils()
                ^^^^^^^^^
NameError: name 'TimeUtils' is not defined. Did you mean: 'TimeUtilsTest'?

======================================================================
ERROR: test_datetime_to_string_3 (ClassEval_87_0.TimeUtilsTestDatetimeToString.test_datetime_to_string_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_87_0.py", line 112, in test_datetime_to_string_3
    timeutils = TimeUtils()
                ^^^^^^^^^
NameError: name 'TimeUtils' is not defined. Did you mean: 'TimeUtilsTest'?

======================================================================
ERROR: test_datetime_to_string_4 (ClassEval_87_0.TimeUtilsTestDatetimeToString.test_datetime_to_string_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_87_0.py", line 117, in test_datetime_to_string_4
    timeutils = TimeUtils()
                ^^^^^^^^^
NameError: name 'TimeUtils' is not defined. Did you mean: 'TimeUtilsTest'?

======================================================================
ERROR: test_datetime_to_string_5 (ClassEval_87_0.TimeUtilsTestDatetimeToString.test_datetime_to_string_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_87_0.py", line 122, in test_datetime_to_string_5
    timeutils = TimeUtils()
                ^^^^^^^^^
NameError: name 'TimeUtils' is not defined. Did you mean: 'TimeUtilsTest'?

----------------------------------------------------------------------
Ran 5 tests in 0.015s

FAILED (errors=5)
EEEEE
======================================================================
ERROR: test_get_minutes_1 (ClassEval_87_0.TimeUtilsTestGetMinutes.test_get_minutes_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_87_0.py", line 129, in test_get_minutes_1
    timeutils = TimeUtils()
                ^^^^^^^^^
NameError: name 'TimeUtils' is not defined. Did you mean: 'TimeUtilsTest'?

======================================================================
ERROR: test_get_minutes_2 (ClassEval_87_0.TimeUtilsTestGetMinutes.test_get_minutes_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_87_0.py", line 133, in test_get_minutes_2
    timeutils = TimeUtils()
                ^^^^^^^^^
NameError: name 'TimeUtils' is not defined. Did you mean: 'TimeUtilsTest'?

======================================================================
ERROR: test_get_minutes_3 (ClassEval_87_0.TimeUtilsTestGetMinutes.test_get_minutes_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_87_0.py", line 137, in test_get_minutes_3
    timeutils = TimeUtils()
                ^^^^^^^^^
NameError: name 'TimeUtils' is not defined. Did you mean: 'TimeUtilsTest'?

======================================================================
ERROR: test_get_minutes_4 (ClassEval_87_0.TimeUtilsTestGetMinutes.test_get_minutes_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_87_0.py", line 141, in test_get_minutes_4
    timeutils = TimeUtils()
                ^^^^^^^^^
NameError: name 'TimeUtils' is not defined. Did you mean: 'TimeUtilsTest'?

======================================================================
ERROR: test_get_minutes_5 (ClassEval_87_0.TimeUtilsTestGetMinutes.test_get_minutes_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_87_0.py", line 145, in test_get_minutes_5
    timeutils = TimeUtils()
                ^^^^^^^^^
NameError: name 'TimeUtils' is not defined. Did you mean: 'TimeUtilsTest'?

----------------------------------------------------------------------
Ran 5 tests in 0.014s

FAILED (errors=5)
EEEEE
======================================================================
ERROR: test_get_format_time_1 (ClassEval_87_0.TimeUtilsTestGetFormatTime.test_get_format_time_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_87_0.py", line 151, in test_get_format_time_1
    timeutils = TimeUtils()
                ^^^^^^^^^
NameError: name 'TimeUtils' is not defined. Did you mean: 'TimeUtilsTest'?

======================================================================
ERROR: test_get_format_time_2 (ClassEval_87_0.TimeUtilsTestGetFormatTime.test_get_format_time_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_87_0.py", line 155, in test_get_format_time_2
    timeutils = TimeUtils()
                ^^^^^^^^^
NameError: name 'TimeUtils' is not defined. Did you mean: 'TimeUtilsTest'?

======================================================================
ERROR: test_get_format_time_3 (ClassEval_87_0.TimeUtilsTestGetFormatTime.test_get_format_time_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_87_0.py", line 159, in test_get_format_time_3
    timeutils = TimeUtils()
                ^^^^^^^^^
NameError: name 'TimeUtils' is not defined. Did you mean: 'TimeUtilsTest'?

======================================================================
ERROR: test_get_format_time_4 (ClassEval_87_0.TimeUtilsTestGetFormatTime.test_get_format_time_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_87_0.py", line 163, in test_get_format_time_4
    timeutils = TimeUtils()
                ^^^^^^^^^
NameError: name 'TimeUtils' is not defined. Did you mean: 'TimeUtilsTest'?

======================================================================
ERROR: test_get_format_time_5 (ClassEval_87_0.TimeUtilsTestGetFormatTime.test_get_format_time_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_87_0.py", line 167, in test_get_format_time_5
    timeutils = TimeUtils()
                ^^^^^^^^^
NameError: name 'TimeUtils' is not defined. Did you mean: 'TimeUtilsTest'?

----------------------------------------------------------------------
Ran 5 tests in 0.015s

FAILED (errors=5)
E
======================================================================
ERROR: test_timeutils (ClassEval_87_0.TimeUtilsTest.test_timeutils)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_87_0.py", line 173, in test_timeutils
    timeutils = TimeUtils()
                ^^^^^^^^^
NameError: name 'TimeUtils' is not defined. Did you mean: 'TimeUtilsTest'?

----------------------------------------------------------------------
Ran 1 test in 0.003s

FAILED (errors=1)
EEEEEE
======================================================================
ERROR: test_get_scheme_1 (ClassEval_90_0.URLHandlerTestGetScheme.test_get_scheme_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_90_0.py", line 8, in test_get_scheme_1
    urlhandler = URLHandler("https://www.baidu.com/s?wd=aaa&rsv_spt=1#page")
                 ^^^^^^^^^^
NameError: name 'URLHandler' is not defined. Did you mean: 'URLHandlerTest'?

======================================================================
ERROR: test_get_scheme_2 (ClassEval_90_0.URLHandlerTestGetScheme.test_get_scheme_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_90_0.py", line 13, in test_get_scheme_2
    urlhandler = URLHandler(
                 ^^^^^^^^^^
NameError: name 'URLHandler' is not defined. Did you mean: 'URLHandlerTest'?

======================================================================
ERROR: test_get_scheme_3 (ClassEval_90_0.URLHandlerTestGetScheme.test_get_scheme_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_90_0.py", line 19, in test_get_scheme_3
    urlhandler = URLHandler("https://github.com/openai/human-eval")
                 ^^^^^^^^^^
NameError: name 'URLHandler' is not defined. Did you mean: 'URLHandlerTest'?

======================================================================
ERROR: test_get_scheme_4 (ClassEval_90_0.URLHandlerTestGetScheme.test_get_scheme_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_90_0.py", line 24, in test_get_scheme_4
    urlhandler = URLHandler("aaa://github.com/openai/human-eval")
                 ^^^^^^^^^^
NameError: name 'URLHandler' is not defined. Did you mean: 'URLHandlerTest'?

======================================================================
ERROR: test_get_scheme_5 (ClassEval_90_0.URLHandlerTestGetScheme.test_get_scheme_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_90_0.py", line 29, in test_get_scheme_5
    urlhandler = URLHandler("bbb://github.com/openai/human-eval")
                 ^^^^^^^^^^
NameError: name 'URLHandler' is not defined. Did you mean: 'URLHandlerTest'?

======================================================================
ERROR: test_get_scheme_6 (ClassEval_90_0.URLHandlerTestGetScheme.test_get_scheme_6)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_90_0.py", line 34, in test_get_scheme_6
    urlhandler = URLHandler("abcdefg")
                 ^^^^^^^^^^
NameError: name 'URLHandler' is not defined. Did you mean: 'URLHandlerTest'?

----------------------------------------------------------------------
Ran 6 tests in 0.015s

FAILED (errors=6)
EEEEEEEE
======================================================================
ERROR: test_get_host_1 (ClassEval_90_0.URLHandlerTestGetHost.test_get_host_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_90_0.py", line 41, in test_get_host_1
    urlhandler = URLHandler("https://www.baidu.com/s?wd=aaa&rsv_spt=1#page")
                 ^^^^^^^^^^
NameError: name 'URLHandler' is not defined. Did you mean: 'URLHandlerTest'?

======================================================================
ERROR: test_get_host_2 (ClassEval_90_0.URLHandlerTestGetHost.test_get_host_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_90_0.py", line 46, in test_get_host_2
    urlhandler = URLHandler(
                 ^^^^^^^^^^
NameError: name 'URLHandler' is not defined. Did you mean: 'URLHandlerTest'?

======================================================================
ERROR: test_get_host_3 (ClassEval_90_0.URLHandlerTestGetHost.test_get_host_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_90_0.py", line 52, in test_get_host_3
    urlhandler = URLHandler("https://github.com/openai/human-eval")
                 ^^^^^^^^^^
NameError: name 'URLHandler' is not defined. Did you mean: 'URLHandlerTest'?

======================================================================
ERROR: test_get_host_4 (ClassEval_90_0.URLHandlerTestGetHost.test_get_host_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_90_0.py", line 57, in test_get_host_4
    urlhandler = URLHandler("https://aaa.com/openai/human-eval")
                 ^^^^^^^^^^
NameError: name 'URLHandler' is not defined. Did you mean: 'URLHandlerTest'?

======================================================================
ERROR: test_get_host_5 (ClassEval_90_0.URLHandlerTestGetHost.test_get_host_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_90_0.py", line 62, in test_get_host_5
    urlhandler = URLHandler("https://bbb.com/openai/human-eval")
                 ^^^^^^^^^^
NameError: name 'URLHandler' is not defined. Did you mean: 'URLHandlerTest'?

======================================================================
ERROR: test_get_host_6 (ClassEval_90_0.URLHandlerTestGetHost.test_get_host_6)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_90_0.py", line 67, in test_get_host_6
    urlhandler = URLHandler("abcdefg")
                 ^^^^^^^^^^
NameError: name 'URLHandler' is not defined. Did you mean: 'URLHandlerTest'?

======================================================================
ERROR: test_get_host_7 (ClassEval_90_0.URLHandlerTestGetHost.test_get_host_7)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_90_0.py", line 72, in test_get_host_7
    urlhandler = URLHandler("https://bbb.com")
                 ^^^^^^^^^^
NameError: name 'URLHandler' is not defined. Did you mean: 'URLHandlerTest'?

======================================================================
ERROR: test_get_host_8 (ClassEval_90_0.URLHandlerTestGetHost.test_get_host_8)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_90_0.py", line 77, in test_get_host_8
    urlhandler = URLHandler("https://bbb.com/")
                 ^^^^^^^^^^
NameError: name 'URLHandler' is not defined. Did you mean: 'URLHandlerTest'?

----------------------------------------------------------------------
Ran 8 tests in 0.018s

FAILED (errors=8)
EEEEEE
======================================================================
ERROR: test_get_path_1 (ClassEval_90_0.URLHandlerTestGetPath.test_get_path_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_90_0.py", line 84, in test_get_path_1
    urlhandler = URLHandler("https://www.baidu.com/s?wd=aaa&rsv_spt=1#page")
                 ^^^^^^^^^^
NameError: name 'URLHandler' is not defined. Did you mean: 'URLHandlerTest'?

======================================================================
ERROR: test_get_path_2 (ClassEval_90_0.URLHandlerTestGetPath.test_get_path_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_90_0.py", line 89, in test_get_path_2
    urlhandler = URLHandler(
                 ^^^^^^^^^^
NameError: name 'URLHandler' is not defined. Did you mean: 'URLHandlerTest'?

======================================================================
ERROR: test_get_path_3 (ClassEval_90_0.URLHandlerTestGetPath.test_get_path_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_90_0.py", line 96, in test_get_path_3
    urlhandler = URLHandler("https://github.com/openai/human-eval")
                 ^^^^^^^^^^
NameError: name 'URLHandler' is not defined. Did you mean: 'URLHandlerTest'?

======================================================================
ERROR: test_get_path_4 (ClassEval_90_0.URLHandlerTestGetPath.test_get_path_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_90_0.py", line 101, in test_get_path_4
    urlhandler = URLHandler("https://github.com/aaa/human-eval")
                 ^^^^^^^^^^
NameError: name 'URLHandler' is not defined. Did you mean: 'URLHandlerTest'?

======================================================================
ERROR: test_get_path_5 (ClassEval_90_0.URLHandlerTestGetPath.test_get_path_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_90_0.py", line 106, in test_get_path_5
    urlhandler = URLHandler("https://github.com/bbb/human-eval")
                 ^^^^^^^^^^
NameError: name 'URLHandler' is not defined. Did you mean: 'URLHandlerTest'?

======================================================================
ERROR: test_get_path_6 (ClassEval_90_0.URLHandlerTestGetPath.test_get_path_6)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_90_0.py", line 111, in test_get_path_6
    urlhandler = URLHandler("abcdefg")
                 ^^^^^^^^^^
NameError: name 'URLHandler' is not defined. Did you mean: 'URLHandlerTest'?

----------------------------------------------------------------------
Ran 6 tests in 0.014s

FAILED (errors=6)
EEEEEE
======================================================================
ERROR: test_get_query_params_1 (ClassEval_90_0.URLHandlerTestGetQueryParams.test_get_query_params_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_90_0.py", line 118, in test_get_query_params_1
    urlhandler = URLHandler("https://www.baidu.com/s?wd=aaa&rsv_spt=1#page")
                 ^^^^^^^^^^
NameError: name 'URLHandler' is not defined. Did you mean: 'URLHandlerTest'?

======================================================================
ERROR: test_get_query_params_2 (ClassEval_90_0.URLHandlerTestGetQueryParams.test_get_query_params_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_90_0.py", line 123, in test_get_query_params_2
    urlhandler = URLHandler(
                 ^^^^^^^^^^
NameError: name 'URLHandler' is not defined. Did you mean: 'URLHandlerTest'?

======================================================================
ERROR: test_get_query_params_3 (ClassEval_90_0.URLHandlerTestGetQueryParams.test_get_query_params_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_90_0.py", line 130, in test_get_query_params_3
    urlhandler = URLHandler("https://github.com/openai/human-eval")
                 ^^^^^^^^^^
NameError: name 'URLHandler' is not defined. Did you mean: 'URLHandlerTest'?

======================================================================
ERROR: test_get_query_params_4 (ClassEval_90_0.URLHandlerTestGetQueryParams.test_get_query_params_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_90_0.py", line 135, in test_get_query_params_4
    urlhandler = URLHandler("https://www.baidu.com/s?wd=bbb&rsv_spt=1#page")
                 ^^^^^^^^^^
NameError: name 'URLHandler' is not defined. Did you mean: 'URLHandlerTest'?

======================================================================
ERROR: test_get_query_params_5 (ClassEval_90_0.URLHandlerTestGetQueryParams.test_get_query_params_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_90_0.py", line 140, in test_get_query_params_5
    urlhandler = URLHandler("https://www.baidu.com/s?wd=ccc&rsv_spt=1#page")
                 ^^^^^^^^^^
NameError: name 'URLHandler' is not defined. Did you mean: 'URLHandlerTest'?

======================================================================
ERROR: test_get_query_params_6 (ClassEval_90_0.URLHandlerTestGetQueryParams.test_get_query_params_6)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_90_0.py", line 145, in test_get_query_params_6
    urlhandler = URLHandler("https://www.baidu.com/s?&#page")
                 ^^^^^^^^^^
NameError: name 'URLHandler' is not defined. Did you mean: 'URLHandlerTest'?

----------------------------------------------------------------------
Ran 6 tests in 0.013s

FAILED (errors=6)
EEEEE
======================================================================
ERROR: test_get_fragment_1 (ClassEval_90_0.URLHandlerTestGetFragment.test_get_fragment_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_90_0.py", line 152, in test_get_fragment_1
    urlhandler = URLHandler("https://www.baidu.com/s?wd=aaa&rsv_spt=1#page")
                 ^^^^^^^^^^
NameError: name 'URLHandler' is not defined. Did you mean: 'URLHandlerTest'?

======================================================================
ERROR: test_get_fragment_2 (ClassEval_90_0.URLHandlerTestGetFragment.test_get_fragment_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_90_0.py", line 157, in test_get_fragment_2
    urlhandler = URLHandler(
                 ^^^^^^^^^^
NameError: name 'URLHandler' is not defined. Did you mean: 'URLHandlerTest'?

======================================================================
ERROR: test_get_fragment_3 (ClassEval_90_0.URLHandlerTestGetFragment.test_get_fragment_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_90_0.py", line 163, in test_get_fragment_3
    urlhandler = URLHandler("https://www.baidu.com/s?wd=aaa&rsv_spt=1#aaa")
                 ^^^^^^^^^^
NameError: name 'URLHandler' is not defined. Did you mean: 'URLHandlerTest'?

======================================================================
ERROR: test_get_fragment_4 (ClassEval_90_0.URLHandlerTestGetFragment.test_get_fragment_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_90_0.py", line 168, in test_get_fragment_4
    urlhandler = URLHandler("https://www.baidu.com/s?wd=aaa&rsv_spt=1#bbb")
                 ^^^^^^^^^^
NameError: name 'URLHandler' is not defined. Did you mean: 'URLHandlerTest'?

======================================================================
ERROR: test_get_fragment_5 (ClassEval_90_0.URLHandlerTestGetFragment.test_get_fragment_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_90_0.py", line 173, in test_get_fragment_5
    urlhandler = URLHandler("https://www.baidu.com/s?wd=aaa&rsv_spt=1#ccc")
                 ^^^^^^^^^^
NameError: name 'URLHandler' is not defined. Did you mean: 'URLHandlerTest'?

----------------------------------------------------------------------
Ran 5 tests in 0.010s

FAILED (errors=5)
E
======================================================================
ERROR: test_urlhandler (ClassEval_90_0.URLHandlerTest.test_urlhandler)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_90_0.py", line 180, in test_urlhandler
    urlhandler = URLHandler("https://www.baidu.com/s?wd=aaa&rsv_spt=1#page")
                 ^^^^^^^^^^
NameError: name 'URLHandler' is not defined. Did you mean: 'URLHandlerTest'?

----------------------------------------------------------------------
Ran 1 test in 0.002s

FAILED (errors=1)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
F.FFFFF
======================================================================
FAIL: test_parse_1 (ClassEval_91_0.UrlPathTestParse.test_parse_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_91_0.py", line 81, in test_parse_1
    self.assertEqual(url_path.segments, ['foo', 'bar'])
AssertionError: Lists differ: ['', 'foo', 'bar'] != ['foo', 'bar']

First differing element 0:
''
'foo'

First list contains 1 additional elements.
First extra element 2:
'bar'

- ['', 'foo', 'bar']
?  ----

+ ['foo', 'bar']

======================================================================
FAIL: test_parse_3 (ClassEval_91_0.UrlPathTestParse.test_parse_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_91_0.py", line 93, in test_parse_3
    self.assertEqual(url_path.segments, ['123', '456'])
AssertionError: Lists differ: ['', '123', '456'] != ['123', '456']

First differing element 0:
''
'123'

First list contains 1 additional elements.
First extra element 2:
'456'

- ['', '123', '456']
?  ----

+ ['123', '456']

======================================================================
FAIL: test_parse_4 (ClassEval_91_0.UrlPathTestParse.test_parse_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_91_0.py", line 99, in test_parse_4
    self.assertEqual(url_path.segments, ['123', '456', '789'])
AssertionError: Lists differ: ['', '123', '456', '789'] != ['123', '456', '789']

First differing element 0:
''
'123'

First list contains 1 additional elements.
First extra element 3:
'789'

- ['', '123', '456', '789']
?  ----

+ ['123', '456', '789']

======================================================================
FAIL: test_parse_5 (ClassEval_91_0.UrlPathTestParse.test_parse_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_91_0.py", line 105, in test_parse_5
    self.assertEqual(url_path.segments, ['foo', 'bar'])
AssertionError: Lists differ: ['', 'foo', 'bar'] != ['foo', 'bar']

First differing element 0:
''
'foo'

First list contains 1 additional elements.
First extra element 2:
'bar'

- ['', 'foo', 'bar']
?  ----

+ ['foo', 'bar']

======================================================================
FAIL: test_parse_6 (ClassEval_91_0.UrlPathTestParse.test_parse_6)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_91_0.py", line 112, in test_parse_6
    self.assertEqual(url_path.with_end_tag, False)
AssertionError: True != False

======================================================================
FAIL: test_parse_7 (ClassEval_91_0.UrlPathTestParse.test_parse_7)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_91_0.py", line 117, in test_parse_7
    self.assertEqual(url_path.segments, [])
AssertionError: Lists differ: ['', ''] != []

First list contains 2 additional elements.
First extra element 0:
''

- ['', '']
+ []

----------------------------------------------------------------------
Ran 7 tests in 0.002s

FAILED (failures=6)
......
----------------------------------------------------------------------
Ran 6 tests in 0.000s

OK
F
======================================================================
FAIL: test_urlpath (ClassEval_91_0.UrlPathTest.test_urlpath)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_91_0.py", line 156, in test_urlpath
    self.assertEqual(url_path.segments, ['foo', 'bar'])
AssertionError: Lists differ: ['', 'foo', 'bar'] != ['foo', 'bar']

First differing element 0:
''
'foo'

First list contains 1 additional elements.
First extra element 2:
'bar'

- ['', 'foo', 'bar']
?  ----

+ ['foo', 'bar']

----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (failures=1)
