EE
======================================================================
ERROR: test_create_table_1 (ClassEval_14_0.BookManagementDBTestCreateTable.test_create_table_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_14_0.py", line 10, in setUp
    self.db = BookManagementDB(self.db_name)
              ^^^^^^^^^^^^^^^^
NameError: name 'BookManagementDB' is not defined

======================================================================
ERROR: test_create_table_2 (ClassEval_14_0.BookManagementDBTestCreateTable.test_create_table_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_14_0.py", line 10, in setUp
    self.db = BookManagementDB(self.db_name)
              ^^^^^^^^^^^^^^^^
NameError: name 'BookManagementDB' is not defined

----------------------------------------------------------------------
Ran 2 tests in 0.012s

FAILED (errors=2)
E
======================================================================
ERROR: test_add_book (ClassEval_14_0.BookManagementDBTestAddBook.test_add_book)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_14_0.py", line 39, in setUp
    self.db = BookManagementDB(self.db_name)
              ^^^^^^^^^^^^^^^^
NameError: name 'BookManagementDB' is not defined

----------------------------------------------------------------------
Ran 1 test in 0.004s

FAILED (errors=1)
E
======================================================================
ERROR: test_remove_book (ClassEval_14_0.BookManagementDBTestRemoveBook.test_remove_book)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_14_0.py", line 66, in setUp
    self.db = BookManagementDB(self.db_name)
              ^^^^^^^^^^^^^^^^
NameError: name 'BookManagementDB' is not defined

----------------------------------------------------------------------
Ran 1 test in 0.006s

FAILED (errors=1)
E
======================================================================
ERROR: test_borrow_book (ClassEval_14_0.BookManagementDBTestBorrowBook.test_borrow_book)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_14_0.py", line 90, in setUp
    self.db = BookManagementDB(self.db_name)
              ^^^^^^^^^^^^^^^^
NameError: name 'BookManagementDB' is not defined

----------------------------------------------------------------------
Ran 1 test in 0.004s

FAILED (errors=1)
E
======================================================================
ERROR: test_return_book (ClassEval_14_0.BookManagementDBTestReturnBook.test_return_book)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_14_0.py", line 114, in setUp
    self.db = BookManagementDB(self.db_name)
              ^^^^^^^^^^^^^^^^
NameError: name 'BookManagementDB' is not defined

----------------------------------------------------------------------
Ran 1 test in 0.004s

FAILED (errors=1)
E
======================================================================
ERROR: test_search_books (ClassEval_14_0.BookManagementDBTestSearchBooks.test_search_books)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_14_0.py", line 139, in setUp
    self.db = BookManagementDB(self.db_name)
              ^^^^^^^^^^^^^^^^
NameError: name 'BookManagementDB' is not defined

----------------------------------------------------------------------
Ran 1 test in 0.005s

FAILED (errors=1)
EEEEE
======================================================================
ERROR: test_create_table_1 (ClassEval_28_0.DatabaseProcessorTestCreateTable.test_create_table_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_28_0.py", line 11, in setUp
    self.processor = DatabaseProcessor(self.database_name)
                     ^^^^^^^^^^^^^^^^^
NameError: name 'DatabaseProcessor' is not defined. Did you mean: 'DatabaseProcessorTest'?

======================================================================
ERROR: test_create_table_2 (ClassEval_28_0.DatabaseProcessorTestCreateTable.test_create_table_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_28_0.py", line 11, in setUp
    self.processor = DatabaseProcessor(self.database_name)
                     ^^^^^^^^^^^^^^^^^
NameError: name 'DatabaseProcessor' is not defined. Did you mean: 'DatabaseProcessorTest'?

======================================================================
ERROR: test_create_table_3 (ClassEval_28_0.DatabaseProcessorTestCreateTable.test_create_table_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_28_0.py", line 11, in setUp
    self.processor = DatabaseProcessor(self.database_name)
                     ^^^^^^^^^^^^^^^^^
NameError: name 'DatabaseProcessor' is not defined. Did you mean: 'DatabaseProcessorTest'?

======================================================================
ERROR: test_create_table_4 (ClassEval_28_0.DatabaseProcessorTestCreateTable.test_create_table_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_28_0.py", line 11, in setUp
    self.processor = DatabaseProcessor(self.database_name)
                     ^^^^^^^^^^^^^^^^^
NameError: name 'DatabaseProcessor' is not defined. Did you mean: 'DatabaseProcessorTest'?

======================================================================
ERROR: test_create_table_5 (ClassEval_28_0.DatabaseProcessorTestCreateTable.test_create_table_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_28_0.py", line 11, in setUp
    self.processor = DatabaseProcessor(self.database_name)
                     ^^^^^^^^^^^^^^^^^
NameError: name 'DatabaseProcessor' is not defined. Did you mean: 'DatabaseProcessorTest'?

----------------------------------------------------------------------
Ran 5 tests in 0.009s

FAILED (errors=5)
EEEEE
======================================================================
ERROR: test_insert_into_database_1 (ClassEval_28_0.DatabaseProcessorTestInsertIntoDatabase.test_insert_into_database_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_28_0.py", line 89, in setUp
    self.processor = DatabaseProcessor(self.database_name)
                     ^^^^^^^^^^^^^^^^^
NameError: name 'DatabaseProcessor' is not defined. Did you mean: 'DatabaseProcessorTest'?

======================================================================
ERROR: test_insert_into_database_2 (ClassEval_28_0.DatabaseProcessorTestInsertIntoDatabase.test_insert_into_database_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_28_0.py", line 89, in setUp
    self.processor = DatabaseProcessor(self.database_name)
                     ^^^^^^^^^^^^^^^^^
NameError: name 'DatabaseProcessor' is not defined. Did you mean: 'DatabaseProcessorTest'?

======================================================================
ERROR: test_insert_into_database_3 (ClassEval_28_0.DatabaseProcessorTestInsertIntoDatabase.test_insert_into_database_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_28_0.py", line 89, in setUp
    self.processor = DatabaseProcessor(self.database_name)
                     ^^^^^^^^^^^^^^^^^
NameError: name 'DatabaseProcessor' is not defined. Did you mean: 'DatabaseProcessorTest'?

======================================================================
ERROR: test_insert_into_database_4 (ClassEval_28_0.DatabaseProcessorTestInsertIntoDatabase.test_insert_into_database_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_28_0.py", line 89, in setUp
    self.processor = DatabaseProcessor(self.database_name)
                     ^^^^^^^^^^^^^^^^^
NameError: name 'DatabaseProcessor' is not defined. Did you mean: 'DatabaseProcessorTest'?

======================================================================
ERROR: test_insert_into_database_5 (ClassEval_28_0.DatabaseProcessorTestInsertIntoDatabase.test_insert_into_database_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_28_0.py", line 89, in setUp
    self.processor = DatabaseProcessor(self.database_name)
                     ^^^^^^^^^^^^^^^^^
NameError: name 'DatabaseProcessor' is not defined. Did you mean: 'DatabaseProcessorTest'?

----------------------------------------------------------------------
Ran 5 tests in 0.011s

FAILED (errors=5)
EEEEE
======================================================================
ERROR: test_search_database_1 (ClassEval_28_0.DatabaseProcessorTestSearchDatabase.test_search_database_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_28_0.py", line 187, in setUp
    self.processor = DatabaseProcessor(self.database_name)
                     ^^^^^^^^^^^^^^^^^
NameError: name 'DatabaseProcessor' is not defined. Did you mean: 'DatabaseProcessorTest'?

======================================================================
ERROR: test_search_database_2 (ClassEval_28_0.DatabaseProcessorTestSearchDatabase.test_search_database_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_28_0.py", line 187, in setUp
    self.processor = DatabaseProcessor(self.database_name)
                     ^^^^^^^^^^^^^^^^^
NameError: name 'DatabaseProcessor' is not defined. Did you mean: 'DatabaseProcessorTest'?

======================================================================
ERROR: test_search_database_3 (ClassEval_28_0.DatabaseProcessorTestSearchDatabase.test_search_database_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_28_0.py", line 187, in setUp
    self.processor = DatabaseProcessor(self.database_name)
                     ^^^^^^^^^^^^^^^^^
NameError: name 'DatabaseProcessor' is not defined. Did you mean: 'DatabaseProcessorTest'?

======================================================================
ERROR: test_search_database_4 (ClassEval_28_0.DatabaseProcessorTestSearchDatabase.test_search_database_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_28_0.py", line 187, in setUp
    self.processor = DatabaseProcessor(self.database_name)
                     ^^^^^^^^^^^^^^^^^
NameError: name 'DatabaseProcessor' is not defined. Did you mean: 'DatabaseProcessorTest'?

======================================================================
ERROR: test_search_database_5 (ClassEval_28_0.DatabaseProcessorTestSearchDatabase.test_search_database_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_28_0.py", line 187, in setUp
    self.processor = DatabaseProcessor(self.database_name)
                     ^^^^^^^^^^^^^^^^^
NameError: name 'DatabaseProcessor' is not defined. Did you mean: 'DatabaseProcessorTest'?

----------------------------------------------------------------------
Ran 5 tests in 0.009s

FAILED (errors=5)
EEEEE
======================================================================
ERROR: test_delete_from_database_1 (ClassEval_28_0.DatabaseProcessorTestDeteleFromDatabase.test_delete_from_database_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_28_0.py", line 264, in setUp
    self.processor = DatabaseProcessor(self.database_name)
                     ^^^^^^^^^^^^^^^^^
NameError: name 'DatabaseProcessor' is not defined. Did you mean: 'DatabaseProcessorTest'?

======================================================================
ERROR: test_delete_from_database_2 (ClassEval_28_0.DatabaseProcessorTestDeteleFromDatabase.test_delete_from_database_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_28_0.py", line 264, in setUp
    self.processor = DatabaseProcessor(self.database_name)
                     ^^^^^^^^^^^^^^^^^
NameError: name 'DatabaseProcessor' is not defined. Did you mean: 'DatabaseProcessorTest'?

======================================================================
ERROR: test_delete_from_database_3 (ClassEval_28_0.DatabaseProcessorTestDeteleFromDatabase.test_delete_from_database_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_28_0.py", line 264, in setUp
    self.processor = DatabaseProcessor(self.database_name)
                     ^^^^^^^^^^^^^^^^^
NameError: name 'DatabaseProcessor' is not defined. Did you mean: 'DatabaseProcessorTest'?

======================================================================
ERROR: test_delete_from_database_4 (ClassEval_28_0.DatabaseProcessorTestDeteleFromDatabase.test_delete_from_database_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_28_0.py", line 264, in setUp
    self.processor = DatabaseProcessor(self.database_name)
                     ^^^^^^^^^^^^^^^^^
NameError: name 'DatabaseProcessor' is not defined. Did you mean: 'DatabaseProcessorTest'?

======================================================================
ERROR: test_delete_from_database_5 (ClassEval_28_0.DatabaseProcessorTestDeteleFromDatabase.test_delete_from_database_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_28_0.py", line 264, in setUp
    self.processor = DatabaseProcessor(self.database_name)
                     ^^^^^^^^^^^^^^^^^
NameError: name 'DatabaseProcessor' is not defined. Did you mean: 'DatabaseProcessorTest'?

----------------------------------------------------------------------
Ran 5 tests in 0.010s

FAILED (errors=5)
E
======================================================================
ERROR: test_DatabaseProcessor (ClassEval_28_0.DatabaseProcessorTest.test_DatabaseProcessor)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_28_0.py", line 377, in setUp
    self.processor = DatabaseProcessor(self.database_name)
                     ^^^^^^^^^^^^^^^^^
NameError: name 'DatabaseProcessor' is not defined. Did you mean: 'DatabaseProcessorTest'?

----------------------------------------------------------------------
Ran 1 test in 0.002s

FAILED (errors=1)
EEEEE
======================================================================
ERROR: test_insert_ticket_1 (ClassEval_60_0.MovieTicketDBTestInsertTicket.test_insert_ticket_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_60_0.py", line 10, in setUp
    self.db = MovieTicketDB(self.db_name)
              ^^^^^^^^^^^^^
NameError: name 'MovieTicketDB' is not defined. Did you mean: 'MovieTicketDBTest'?

======================================================================
ERROR: test_insert_ticket_2 (ClassEval_60_0.MovieTicketDBTestInsertTicket.test_insert_ticket_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_60_0.py", line 10, in setUp
    self.db = MovieTicketDB(self.db_name)
              ^^^^^^^^^^^^^
NameError: name 'MovieTicketDB' is not defined. Did you mean: 'MovieTicketDBTest'?

======================================================================
ERROR: test_insert_ticket_3 (ClassEval_60_0.MovieTicketDBTestInsertTicket.test_insert_ticket_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_60_0.py", line 10, in setUp
    self.db = MovieTicketDB(self.db_name)
              ^^^^^^^^^^^^^
NameError: name 'MovieTicketDB' is not defined. Did you mean: 'MovieTicketDBTest'?

======================================================================
ERROR: test_insert_ticket_4 (ClassEval_60_0.MovieTicketDBTestInsertTicket.test_insert_ticket_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_60_0.py", line 10, in setUp
    self.db = MovieTicketDB(self.db_name)
              ^^^^^^^^^^^^^
NameError: name 'MovieTicketDB' is not defined. Did you mean: 'MovieTicketDBTest'?

======================================================================
ERROR: test_insert_ticket_5 (ClassEval_60_0.MovieTicketDBTestInsertTicket.test_insert_ticket_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_60_0.py", line 10, in setUp
    self.db = MovieTicketDB(self.db_name)
              ^^^^^^^^^^^^^
NameError: name 'MovieTicketDB' is not defined. Did you mean: 'MovieTicketDBTest'?

----------------------------------------------------------------------
Ran 5 tests in 0.011s

FAILED (errors=5)
EEEEE
======================================================================
ERROR: test_search_tickets_by_customer_1 (ClassEval_60_0.MovieTicketDBTestSearchTicketsByCustomer.test_search_tickets_by_customer_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_60_0.py", line 70, in setUp
    self.db = MovieTicketDB(self.db_name)
              ^^^^^^^^^^^^^
NameError: name 'MovieTicketDB' is not defined. Did you mean: 'MovieTicketDBTest'?

======================================================================
ERROR: test_search_tickets_by_customer_2 (ClassEval_60_0.MovieTicketDBTestSearchTicketsByCustomer.test_search_tickets_by_customer_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_60_0.py", line 70, in setUp
    self.db = MovieTicketDB(self.db_name)
              ^^^^^^^^^^^^^
NameError: name 'MovieTicketDB' is not defined. Did you mean: 'MovieTicketDBTest'?

======================================================================
ERROR: test_search_tickets_by_customer_3 (ClassEval_60_0.MovieTicketDBTestSearchTicketsByCustomer.test_search_tickets_by_customer_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_60_0.py", line 70, in setUp
    self.db = MovieTicketDB(self.db_name)
              ^^^^^^^^^^^^^
NameError: name 'MovieTicketDB' is not defined. Did you mean: 'MovieTicketDBTest'?

======================================================================
ERROR: test_search_tickets_by_customer_4 (ClassEval_60_0.MovieTicketDBTestSearchTicketsByCustomer.test_search_tickets_by_customer_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_60_0.py", line 70, in setUp
    self.db = MovieTicketDB(self.db_name)
              ^^^^^^^^^^^^^
NameError: name 'MovieTicketDB' is not defined. Did you mean: 'MovieTicketDBTest'?

======================================================================
ERROR: test_search_tickets_by_customer_5 (ClassEval_60_0.MovieTicketDBTestSearchTicketsByCustomer.test_search_tickets_by_customer_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_60_0.py", line 70, in setUp
    self.db = MovieTicketDB(self.db_name)
              ^^^^^^^^^^^^^
NameError: name 'MovieTicketDB' is not defined. Did you mean: 'MovieTicketDBTest'?

----------------------------------------------------------------------
Ran 5 tests in 0.011s

FAILED (errors=5)
EEEEE
======================================================================
ERROR: test_delete_ticket_1 (ClassEval_60_0.MovieTicketDBTestDeleteTicket.test_delete_ticket_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_60_0.py", line 130, in setUp
    self.db = MovieTicketDB(self.db_name)
              ^^^^^^^^^^^^^
NameError: name 'MovieTicketDB' is not defined. Did you mean: 'MovieTicketDBTest'?

======================================================================
ERROR: test_delete_ticket_2 (ClassEval_60_0.MovieTicketDBTestDeleteTicket.test_delete_ticket_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_60_0.py", line 130, in setUp
    self.db = MovieTicketDB(self.db_name)
              ^^^^^^^^^^^^^
NameError: name 'MovieTicketDB' is not defined. Did you mean: 'MovieTicketDBTest'?

======================================================================
ERROR: test_delete_ticket_3 (ClassEval_60_0.MovieTicketDBTestDeleteTicket.test_delete_ticket_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_60_0.py", line 130, in setUp
    self.db = MovieTicketDB(self.db_name)
              ^^^^^^^^^^^^^
NameError: name 'MovieTicketDB' is not defined. Did you mean: 'MovieTicketDBTest'?

======================================================================
ERROR: test_delete_ticket_4 (ClassEval_60_0.MovieTicketDBTestDeleteTicket.test_delete_ticket_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_60_0.py", line 130, in setUp
    self.db = MovieTicketDB(self.db_name)
              ^^^^^^^^^^^^^
NameError: name 'MovieTicketDB' is not defined. Did you mean: 'MovieTicketDBTest'?

======================================================================
ERROR: test_delete_ticket_5 (ClassEval_60_0.MovieTicketDBTestDeleteTicket.test_delete_ticket_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_60_0.py", line 130, in setUp
    self.db = MovieTicketDB(self.db_name)
              ^^^^^^^^^^^^^
NameError: name 'MovieTicketDB' is not defined. Did you mean: 'MovieTicketDBTest'?

----------------------------------------------------------------------
Ran 5 tests in 0.011s

FAILED (errors=5)
E
======================================================================
ERROR: test_MovieTicketDB (ClassEval_60_0.MovieTicketDBTest.test_MovieTicketDB)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_60_0.py", line 185, in setUp
    self.db = MovieTicketDB(self.db_name)
              ^^^^^^^^^^^^^
NameError: name 'MovieTicketDB' is not defined. Did you mean: 'MovieTicketDBTest'?

----------------------------------------------------------------------
Ran 1 test in 0.003s

FAILED (errors=1)
EEEEEE
======================================================================
ERROR: test_select_1 (ClassEval_79_0.SQLGeneratorTestSelect.test_select_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_79_0.py", line 7, in test_select_1
    sql = SQLGenerator('table1')
          ^^^^^^^^^^^^
NameError: name 'SQLGenerator' is not defined

======================================================================
ERROR: test_select_2 (ClassEval_79_0.SQLGeneratorTestSelect.test_select_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_79_0.py", line 12, in test_select_2
    sql = SQLGenerator('table1')
          ^^^^^^^^^^^^
NameError: name 'SQLGenerator' is not defined

======================================================================
ERROR: test_select_3 (ClassEval_79_0.SQLGeneratorTestSelect.test_select_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_79_0.py", line 17, in test_select_3
    sql = SQLGenerator('table1')
          ^^^^^^^^^^^^
NameError: name 'SQLGenerator' is not defined

======================================================================
ERROR: test_select_4 (ClassEval_79_0.SQLGeneratorTestSelect.test_select_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_79_0.py", line 22, in test_select_4
    sql = SQLGenerator('table1')
          ^^^^^^^^^^^^
NameError: name 'SQLGenerator' is not defined

======================================================================
ERROR: test_select_5 (ClassEval_79_0.SQLGeneratorTestSelect.test_select_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_79_0.py", line 27, in test_select_5
    sql = SQLGenerator('table1')
          ^^^^^^^^^^^^
NameError: name 'SQLGenerator' is not defined

======================================================================
ERROR: test_select_6 (ClassEval_79_0.SQLGeneratorTestSelect.test_select_6)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_79_0.py", line 32, in test_select_6
    sql = SQLGenerator('table1')
          ^^^^^^^^^^^^
NameError: name 'SQLGenerator' is not defined

----------------------------------------------------------------------
Ran 6 tests in 0.087s

FAILED (errors=6)
EEEEE
======================================================================
ERROR: test_insert (ClassEval_79_0.SQLGeneratorTestInsert.test_insert)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_79_0.py", line 40, in test_insert
    sql = SQLGenerator('table1')
          ^^^^^^^^^^^^
NameError: name 'SQLGenerator' is not defined

======================================================================
ERROR: test_insert_2 (ClassEval_79_0.SQLGeneratorTestInsert.test_insert_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_79_0.py", line 45, in test_insert_2
    sql = SQLGenerator('table1')
          ^^^^^^^^^^^^
NameError: name 'SQLGenerator' is not defined

======================================================================
ERROR: test_insert_3 (ClassEval_79_0.SQLGeneratorTestInsert.test_insert_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_79_0.py", line 50, in test_insert_3
    sql = SQLGenerator('table1')
          ^^^^^^^^^^^^
NameError: name 'SQLGenerator' is not defined

======================================================================
ERROR: test_insert_4 (ClassEval_79_0.SQLGeneratorTestInsert.test_insert_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_79_0.py", line 56, in test_insert_4
    sql = SQLGenerator('table1')
          ^^^^^^^^^^^^
NameError: name 'SQLGenerator' is not defined

======================================================================
ERROR: test_insert_5 (ClassEval_79_0.SQLGeneratorTestInsert.test_insert_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_79_0.py", line 63, in test_insert_5
    sql = SQLGenerator('table1')
          ^^^^^^^^^^^^
NameError: name 'SQLGenerator' is not defined

----------------------------------------------------------------------
Ran 5 tests in 0.023s

FAILED (errors=5)
EEEEE
======================================================================
ERROR: test_update (ClassEval_79_0.SQLGeneratorTestUpdate.test_update)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_79_0.py", line 71, in test_update
    sql = SQLGenerator('table1')
          ^^^^^^^^^^^^
NameError: name 'SQLGenerator' is not defined

======================================================================
ERROR: test_update_2 (ClassEval_79_0.SQLGeneratorTestUpdate.test_update_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_79_0.py", line 77, in test_update_2
    sql = SQLGenerator('table1')
          ^^^^^^^^^^^^
NameError: name 'SQLGenerator' is not defined

======================================================================
ERROR: test_update_3 (ClassEval_79_0.SQLGeneratorTestUpdate.test_update_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_79_0.py", line 84, in test_update_3
    sql = SQLGenerator('table1')
          ^^^^^^^^^^^^
NameError: name 'SQLGenerator' is not defined

======================================================================
ERROR: test_update_4 (ClassEval_79_0.SQLGeneratorTestUpdate.test_update_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_79_0.py", line 91, in test_update_4
    sql = SQLGenerator('table1')
          ^^^^^^^^^^^^
NameError: name 'SQLGenerator' is not defined

======================================================================
ERROR: test_update_5 (ClassEval_79_0.SQLGeneratorTestUpdate.test_update_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_79_0.py", line 98, in test_update_5
    sql = SQLGenerator('table1')
          ^^^^^^^^^^^^
NameError: name 'SQLGenerator' is not defined

----------------------------------------------------------------------
Ran 5 tests in 0.024s

FAILED (errors=5)
EEEEE
======================================================================
ERROR: test_delete (ClassEval_79_0.SQLGeneratorTestDelete.test_delete)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_79_0.py", line 107, in test_delete
    sql = SQLGenerator('table1')
          ^^^^^^^^^^^^
NameError: name 'SQLGenerator' is not defined

======================================================================
ERROR: test_delete_2 (ClassEval_79_0.SQLGeneratorTestDelete.test_delete_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_79_0.py", line 112, in test_delete_2
    sql = SQLGenerator('table1')
          ^^^^^^^^^^^^
NameError: name 'SQLGenerator' is not defined

======================================================================
ERROR: test_delete_3 (ClassEval_79_0.SQLGeneratorTestDelete.test_delete_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_79_0.py", line 117, in test_delete_3
    sql = SQLGenerator('table1')
          ^^^^^^^^^^^^
NameError: name 'SQLGenerator' is not defined

======================================================================
ERROR: test_delete_4 (ClassEval_79_0.SQLGeneratorTestDelete.test_delete_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_79_0.py", line 122, in test_delete_4
    sql = SQLGenerator('table1')
          ^^^^^^^^^^^^
NameError: name 'SQLGenerator' is not defined

======================================================================
ERROR: test_delete_5 (ClassEval_79_0.SQLGeneratorTestDelete.test_delete_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_79_0.py", line 128, in test_delete_5
    sql = SQLGenerator('table1')
          ^^^^^^^^^^^^
NameError: name 'SQLGenerator' is not defined

----------------------------------------------------------------------
Ran 5 tests in 0.018s

FAILED (errors=5)
EEEEE
======================================================================
ERROR: test_select_female_under_age (ClassEval_79_0.SQLGeneratorTestSelectFemaleUnderAge.test_select_female_under_age)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_79_0.py", line 135, in test_select_female_under_age
    sql = SQLGenerator('table1')
          ^^^^^^^^^^^^
NameError: name 'SQLGenerator' is not defined

======================================================================
ERROR: test_select_female_under_age_2 (ClassEval_79_0.SQLGeneratorTestSelectFemaleUnderAge.test_select_female_under_age_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_79_0.py", line 140, in test_select_female_under_age_2
    sql = SQLGenerator('table1')
          ^^^^^^^^^^^^
NameError: name 'SQLGenerator' is not defined

======================================================================
ERROR: test_select_female_under_age_3 (ClassEval_79_0.SQLGeneratorTestSelectFemaleUnderAge.test_select_female_under_age_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_79_0.py", line 145, in test_select_female_under_age_3
    sql = SQLGenerator('table1')
          ^^^^^^^^^^^^
NameError: name 'SQLGenerator' is not defined

======================================================================
ERROR: test_select_female_under_age_4 (ClassEval_79_0.SQLGeneratorTestSelectFemaleUnderAge.test_select_female_under_age_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_79_0.py", line 150, in test_select_female_under_age_4
    sql = SQLGenerator('table1')
          ^^^^^^^^^^^^
NameError: name 'SQLGenerator' is not defined

======================================================================
ERROR: test_select_female_under_age_5 (ClassEval_79_0.SQLGeneratorTestSelectFemaleUnderAge.test_select_female_under_age_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_79_0.py", line 155, in test_select_female_under_age_5
    sql = SQLGenerator('table1')
          ^^^^^^^^^^^^
NameError: name 'SQLGenerator' is not defined

----------------------------------------------------------------------
Ran 5 tests in 0.020s

FAILED (errors=5)
EEEEE
======================================================================
ERROR: test_select_by_age_range (ClassEval_79_0.SQLGeneratorTestSelectByAgeRange.test_select_by_age_range)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_79_0.py", line 161, in test_select_by_age_range
    sql = SQLGenerator('table1')
          ^^^^^^^^^^^^
NameError: name 'SQLGenerator' is not defined

======================================================================
ERROR: test_select_by_age_range_2 (ClassEval_79_0.SQLGeneratorTestSelectByAgeRange.test_select_by_age_range_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_79_0.py", line 166, in test_select_by_age_range_2
    sql = SQLGenerator('table1')
          ^^^^^^^^^^^^
NameError: name 'SQLGenerator' is not defined

======================================================================
ERROR: test_select_by_age_range_3 (ClassEval_79_0.SQLGeneratorTestSelectByAgeRange.test_select_by_age_range_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_79_0.py", line 171, in test_select_by_age_range_3
    sql = SQLGenerator('table1')
          ^^^^^^^^^^^^
NameError: name 'SQLGenerator' is not defined

======================================================================
ERROR: test_select_by_age_range_4 (ClassEval_79_0.SQLGeneratorTestSelectByAgeRange.test_select_by_age_range_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_79_0.py", line 176, in test_select_by_age_range_4
    sql = SQLGenerator('table1')
          ^^^^^^^^^^^^
NameError: name 'SQLGenerator' is not defined

======================================================================
ERROR: test_select_by_age_range_5 (ClassEval_79_0.SQLGeneratorTestSelectByAgeRange.test_select_by_age_range_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_79_0.py", line 181, in test_select_by_age_range_5
    sql = SQLGenerator('table1')
          ^^^^^^^^^^^^
NameError: name 'SQLGenerator' is not defined

----------------------------------------------------------------------
Ran 5 tests in 0.019s

FAILED (errors=5)
E
======================================================================
ERROR: test_main (ClassEval_79_0.SQLGeneratorTestMain.test_main)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_79_0.py", line 188, in test_main
    sql = SQLGenerator('table1')
          ^^^^^^^^^^^^
NameError: name 'SQLGenerator' is not defined

----------------------------------------------------------------------
Ran 1 test in 0.004s

FAILED (errors=1)
EEEEE
======================================================================
ERROR: test_insert_student_1 (ClassEval_83_0.StudentDatabaseProcessorTestInsertStudent.test_insert_student_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_83_0.py", line 8, in setUp
    self.processor = StudentDatabaseProcessor("test_database.db")
                     ^^^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'StudentDatabaseProcessor' is not defined. Did you mean: 'StudentDatabaseProcessorTest'?

======================================================================
ERROR: test_insert_student_2 (ClassEval_83_0.StudentDatabaseProcessorTestInsertStudent.test_insert_student_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_83_0.py", line 8, in setUp
    self.processor = StudentDatabaseProcessor("test_database.db")
                     ^^^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'StudentDatabaseProcessor' is not defined. Did you mean: 'StudentDatabaseProcessorTest'?

======================================================================
ERROR: test_insert_student_3 (ClassEval_83_0.StudentDatabaseProcessorTestInsertStudent.test_insert_student_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_83_0.py", line 8, in setUp
    self.processor = StudentDatabaseProcessor("test_database.db")
                     ^^^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'StudentDatabaseProcessor' is not defined. Did you mean: 'StudentDatabaseProcessorTest'?

======================================================================
ERROR: test_insert_student_4 (ClassEval_83_0.StudentDatabaseProcessorTestInsertStudent.test_insert_student_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_83_0.py", line 8, in setUp
    self.processor = StudentDatabaseProcessor("test_database.db")
                     ^^^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'StudentDatabaseProcessor' is not defined. Did you mean: 'StudentDatabaseProcessorTest'?

======================================================================
ERROR: test_insert_student_5 (ClassEval_83_0.StudentDatabaseProcessorTestInsertStudent.test_insert_student_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_83_0.py", line 8, in setUp
    self.processor = StudentDatabaseProcessor("test_database.db")
                     ^^^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'StudentDatabaseProcessor' is not defined. Did you mean: 'StudentDatabaseProcessorTest'?

----------------------------------------------------------------------
Ran 5 tests in 0.007s

FAILED (errors=5)
EEEEE
======================================================================
ERROR: test_search_student_by_name_1 (ClassEval_83_0.StudentDatabaseProcessorTestSearchStudentByName.test_search_student_by_name_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_83_0.py", line 110, in setUp
    self.processor = StudentDatabaseProcessor("test_database.db")
                     ^^^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'StudentDatabaseProcessor' is not defined. Did you mean: 'StudentDatabaseProcessorTest'?

======================================================================
ERROR: test_search_student_by_name_2 (ClassEval_83_0.StudentDatabaseProcessorTestSearchStudentByName.test_search_student_by_name_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_83_0.py", line 110, in setUp
    self.processor = StudentDatabaseProcessor("test_database.db")
                     ^^^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'StudentDatabaseProcessor' is not defined. Did you mean: 'StudentDatabaseProcessorTest'?

======================================================================
ERROR: test_search_student_by_name_3 (ClassEval_83_0.StudentDatabaseProcessorTestSearchStudentByName.test_search_student_by_name_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_83_0.py", line 110, in setUp
    self.processor = StudentDatabaseProcessor("test_database.db")
                     ^^^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'StudentDatabaseProcessor' is not defined. Did you mean: 'StudentDatabaseProcessorTest'?

======================================================================
ERROR: test_search_student_by_name_4 (ClassEval_83_0.StudentDatabaseProcessorTestSearchStudentByName.test_search_student_by_name_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_83_0.py", line 110, in setUp
    self.processor = StudentDatabaseProcessor("test_database.db")
                     ^^^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'StudentDatabaseProcessor' is not defined. Did you mean: 'StudentDatabaseProcessorTest'?

======================================================================
ERROR: test_search_student_by_name_5 (ClassEval_83_0.StudentDatabaseProcessorTestSearchStudentByName.test_search_student_by_name_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_83_0.py", line 110, in setUp
    self.processor = StudentDatabaseProcessor("test_database.db")
                     ^^^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'StudentDatabaseProcessor' is not defined. Did you mean: 'StudentDatabaseProcessorTest'?

----------------------------------------------------------------------
Ran 5 tests in 0.006s

FAILED (errors=5)
EEEEE
======================================================================
ERROR: test_delete_student_by_name_1 (ClassEval_83_0.StudentDatabaseProcessorTestDeleteStudentByName.test_delete_student_by_name_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_83_0.py", line 192, in setUp
    self.processor = StudentDatabaseProcessor("test_database.db")
                     ^^^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'StudentDatabaseProcessor' is not defined. Did you mean: 'StudentDatabaseProcessorTest'?

======================================================================
ERROR: test_delete_student_by_name_2 (ClassEval_83_0.StudentDatabaseProcessorTestDeleteStudentByName.test_delete_student_by_name_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_83_0.py", line 192, in setUp
    self.processor = StudentDatabaseProcessor("test_database.db")
                     ^^^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'StudentDatabaseProcessor' is not defined. Did you mean: 'StudentDatabaseProcessorTest'?

======================================================================
ERROR: test_delete_student_by_name_3 (ClassEval_83_0.StudentDatabaseProcessorTestDeleteStudentByName.test_delete_student_by_name_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_83_0.py", line 192, in setUp
    self.processor = StudentDatabaseProcessor("test_database.db")
                     ^^^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'StudentDatabaseProcessor' is not defined. Did you mean: 'StudentDatabaseProcessorTest'?

======================================================================
ERROR: test_delete_student_by_name_4 (ClassEval_83_0.StudentDatabaseProcessorTestDeleteStudentByName.test_delete_student_by_name_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_83_0.py", line 192, in setUp
    self.processor = StudentDatabaseProcessor("test_database.db")
                     ^^^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'StudentDatabaseProcessor' is not defined. Did you mean: 'StudentDatabaseProcessorTest'?

======================================================================
ERROR: test_delete_student_by_name_5 (ClassEval_83_0.StudentDatabaseProcessorTestDeleteStudentByName.test_delete_student_by_name_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_83_0.py", line 192, in setUp
    self.processor = StudentDatabaseProcessor("test_database.db")
                     ^^^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'StudentDatabaseProcessor' is not defined. Did you mean: 'StudentDatabaseProcessorTest'?

----------------------------------------------------------------------
Ran 5 tests in 0.005s

FAILED (errors=5)
E
======================================================================
ERROR: test_StudentDatabaseProcessor (ClassEval_83_0.StudentDatabaseProcessorTest.test_StudentDatabaseProcessor)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_83_0.py", line 299, in setUp
    self.processor = StudentDatabaseProcessor("test_database.db")
                     ^^^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'StudentDatabaseProcessor' is not defined. Did you mean: 'StudentDatabaseProcessorTest'?

----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (errors=1)
FFFFF
======================================================================
FAIL: test_insert_user_1 (ClassEval_92_0.UserLoginDBTestInsertUser.test_insert_user_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_92_0.py", line 95, in test_insert_user_1
    self.assertEqual(user[0], 'user1')
AssertionError: ('user1', 'pass1') != 'user1'

======================================================================
FAIL: test_insert_user_2 (ClassEval_92_0.UserLoginDBTestInsertUser.test_insert_user_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_92_0.py", line 102, in test_insert_user_2
    self.assertEqual(user[0], 'user2')
AssertionError: ('user2', 'pass2') != 'user2'

======================================================================
FAIL: test_insert_user_3 (ClassEval_92_0.UserLoginDBTestInsertUser.test_insert_user_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_92_0.py", line 109, in test_insert_user_3
    self.assertEqual(user[0], 'user3')
AssertionError: ('user3', 'pass3') != 'user3'

======================================================================
FAIL: test_insert_user_4 (ClassEval_92_0.UserLoginDBTestInsertUser.test_insert_user_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_92_0.py", line 116, in test_insert_user_4
    self.assertEqual(user[0], 'user4')
AssertionError: ('user4', 'pass4') != 'user4'

======================================================================
FAIL: test_insert_user_5 (ClassEval_92_0.UserLoginDBTestInsertUser.test_insert_user_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_92_0.py", line 123, in test_insert_user_5
    self.assertEqual(user[0], 'user5')
AssertionError: ('user5', 'pass5') != 'user5'

----------------------------------------------------------------------
Ran 5 tests in 0.020s

FAILED (failures=5)
FFFFF
======================================================================
FAIL: test_search_user_by_username_1 (ClassEval_92_0.UserLoginDBTestSearchUserByUsername.test_search_user_by_username_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_92_0.py", line 152, in test_search_user_by_username_1
    self.assertEqual(user[0], 'user1')
AssertionError: ('user1', 'pass1') != 'user1'

======================================================================
FAIL: test_search_user_by_username_2 (ClassEval_92_0.UserLoginDBTestSearchUserByUsername.test_search_user_by_username_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_92_0.py", line 159, in test_search_user_by_username_2
    self.assertEqual(user[0], 'user2')
AssertionError: ('user2', 'pass2') != 'user2'

======================================================================
FAIL: test_search_user_by_username_3 (ClassEval_92_0.UserLoginDBTestSearchUserByUsername.test_search_user_by_username_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_92_0.py", line 166, in test_search_user_by_username_3
    self.assertEqual(user[0], 'user3')
AssertionError: ('user3', 'pass3') != 'user3'

======================================================================
FAIL: test_search_user_by_username_4 (ClassEval_92_0.UserLoginDBTestSearchUserByUsername.test_search_user_by_username_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_92_0.py", line 173, in test_search_user_by_username_4
    self.assertEqual(user[0], 'user4')
AssertionError: ('user4', 'pass4') != 'user4'

======================================================================
FAIL: test_search_user_by_username_5 (ClassEval_92_0.UserLoginDBTestSearchUserByUsername.test_search_user_by_username_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_92_0.py", line 180, in test_search_user_by_username_5
    self.assertEqual(user[0], 'user5')
AssertionError: ('user5', 'pass5') != 'user5'

----------------------------------------------------------------------
Ran 5 tests in 0.020s

FAILED (failures=5)
FFFFF
======================================================================
FAIL: test_delete_user_by_username_1 (ClassEval_92_0.UserLoginDBTestDeleteUserByUsername.test_delete_user_by_username_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_92_0.py", line 209, in test_delete_user_by_username_1
    self.assertIsNone(user)
AssertionError: [] is not None

======================================================================
FAIL: test_delete_user_by_username_2 (ClassEval_92_0.UserLoginDBTestDeleteUserByUsername.test_delete_user_by_username_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_92_0.py", line 215, in test_delete_user_by_username_2
    self.assertIsNone(user)
AssertionError: [] is not None

======================================================================
FAIL: test_delete_user_by_username_3 (ClassEval_92_0.UserLoginDBTestDeleteUserByUsername.test_delete_user_by_username_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_92_0.py", line 221, in test_delete_user_by_username_3
    self.assertIsNone(user)
AssertionError: [] is not None

======================================================================
FAIL: test_delete_user_by_username_4 (ClassEval_92_0.UserLoginDBTestDeleteUserByUsername.test_delete_user_by_username_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_92_0.py", line 227, in test_delete_user_by_username_4
    self.assertIsNone(user)
AssertionError: [] is not None

======================================================================
FAIL: test_delete_user_by_username_5 (ClassEval_92_0.UserLoginDBTestDeleteUserByUsername.test_delete_user_by_username_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_92_0.py", line 233, in test_delete_user_by_username_5
    self.assertIsNone(user)
AssertionError: [] is not None

----------------------------------------------------------------------
Ran 5 tests in 0.022s

FAILED (failures=5)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.018s

OK
F
======================================================================
FAIL: test_UserLoginDB (ClassEval_92_0.UserLoginDBTest.test_UserLoginDB)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_92_0.py", line 307, in test_UserLoginDB
    self.assertEqual(user[0], 'user1')
AssertionError: ('user1', 'pass1') != 'user1'

----------------------------------------------------------------------
Ran 1 test in 0.004s

FAILED (failures=1)
