.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
...FF
======================================================================
FAIL: test_find_longest_word_4 (ClassEval_53_0.LongestWordTestFindLongestWord.test_find_longest_word_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_53_0.py", line 106, in test_find_longest_word_4
    self.assertEqual('apple', longestWord.find_longest_word(sentence))
AssertionError: 'apple' != 'Apple'
- apple
? ^
+ Apple
? ^


======================================================================
FAIL: test_find_longest_word_5 (ClassEval_53_0.LongestWordTestFindLongestWord.test_find_longest_word_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_53_0.py", line 113, in test_find_longest_word_5
    self.assertEqual('apple', longestWord.find_longest_word(sentence))
AssertionError: 'apple' != 'Apple'
- apple
? ^
+ Apple
? ^


----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=2)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
...FF
======================================================================
FAIL: test_find_longest_word_4 (ClassEval_53_1.LongestWordTestFindLongestWord.test_find_longest_word_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_53_1.py", line 105, in test_find_longest_word_4
    self.assertEqual('apple', longestWord.find_longest_word(sentence))
AssertionError: 'apple' != 'Apple'
- apple
? ^
+ Apple
? ^


======================================================================
FAIL: test_find_longest_word_5 (ClassEval_53_1.LongestWordTestFindLongestWord.test_find_longest_word_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_53_1.py", line 112, in test_find_longest_word_5
    self.assertEqual('apple', longestWord.find_longest_word(sentence))
AssertionError: 'apple' != 'Apple'
- apple
? ^
+ Apple
? ^


----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=2)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
...FF
======================================================================
FAIL: test_find_longest_word_4 (ClassEval_53_2.LongestWordTestFindLongestWord.test_find_longest_word_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_53_2.py", line 104, in test_find_longest_word_4
    self.assertEqual('apple', longestWord.find_longest_word(sentence))
AssertionError: 'apple' != 'Apple'
- apple
? ^
+ Apple
? ^


======================================================================
FAIL: test_find_longest_word_5 (ClassEval_53_2.LongestWordTestFindLongestWord.test_find_longest_word_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_53_2.py", line 111, in test_find_longest_word_5
    self.assertEqual('apple', longestWord.find_longest_word(sentence))
AssertionError: 'apple' != 'Apple'
- apple
? ^
+ Apple
? ^


----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=2)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
...FF
======================================================================
FAIL: test_find_longest_word_4 (ClassEval_53_3.LongestWordTestFindLongestWord.test_find_longest_word_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_53_3.py", line 109, in test_find_longest_word_4
    self.assertEqual('apple', longestWord.find_longest_word(sentence))
AssertionError: 'apple' != 'Apple'
- apple
? ^
+ Apple
? ^


======================================================================
FAIL: test_find_longest_word_5 (ClassEval_53_3.LongestWordTestFindLongestWord.test_find_longest_word_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_53_3.py", line 116, in test_find_longest_word_5
    self.assertEqual('apple', longestWord.find_longest_word(sentence))
AssertionError: 'apple' != 'Apple'
- apple
? ^
+ Apple
? ^


----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=2)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
...FF
======================================================================
FAIL: test_find_longest_word_4 (ClassEval_53_4.LongestWordTestFindLongestWord.test_find_longest_word_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_53_4.py", line 104, in test_find_longest_word_4
    self.assertEqual('apple', longestWord.find_longest_word(sentence))
AssertionError: 'apple' != 'Apple'
- apple
? ^
+ Apple
? ^


======================================================================
FAIL: test_find_longest_word_5 (ClassEval_53_4.LongestWordTestFindLongestWord.test_find_longest_word_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_53_4.py", line 111, in test_find_longest_word_5
    self.assertEqual('apple', longestWord.find_longest_word(sentence))
AssertionError: 'apple' != 'Apple'
- apple
? ^
+ Apple
? ^


----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=2)
E
======================================================================
ERROR: test_construct_stop_word_list (ClassEval_62_1.NLPDataProcessorTestConstruct.test_construct_stop_word_list)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_62_1.py", line 7, in setUp
    self.processor = NLPDataProcessor()
                     ^^^^^^^^^^^^^^^^
NameError: name 'NLPDataProcessor' is not defined

----------------------------------------------------------------------
Ran 1 test in 0.006s

FAILED (errors=1)
EEEEE
======================================================================
ERROR: test_remove_stop_words (ClassEval_62_1.NLPDataProcessorTestRemove.test_remove_stop_words)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_62_1.py", line 16, in setUp
    self.processor = NLPDataProcessor()
                     ^^^^^^^^^^^^^^^^
NameError: name 'NLPDataProcessor' is not defined

======================================================================
ERROR: test_remove_stop_words_2 (ClassEval_62_1.NLPDataProcessorTestRemove.test_remove_stop_words_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_62_1.py", line 16, in setUp
    self.processor = NLPDataProcessor()
                     ^^^^^^^^^^^^^^^^
NameError: name 'NLPDataProcessor' is not defined

======================================================================
ERROR: test_remove_stop_words_3 (ClassEval_62_1.NLPDataProcessorTestRemove.test_remove_stop_words_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_62_1.py", line 16, in setUp
    self.processor = NLPDataProcessor()
                     ^^^^^^^^^^^^^^^^
NameError: name 'NLPDataProcessor' is not defined

======================================================================
ERROR: test_remove_stop_words_4 (ClassEval_62_1.NLPDataProcessorTestRemove.test_remove_stop_words_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_62_1.py", line 16, in setUp
    self.processor = NLPDataProcessor()
                     ^^^^^^^^^^^^^^^^
NameError: name 'NLPDataProcessor' is not defined

======================================================================
ERROR: test_remove_stop_words_5 (ClassEval_62_1.NLPDataProcessorTestRemove.test_remove_stop_words_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_62_1.py", line 16, in setUp
    self.processor = NLPDataProcessor()
                     ^^^^^^^^^^^^^^^^
NameError: name 'NLPDataProcessor' is not defined

----------------------------------------------------------------------
Ran 5 tests in 0.021s

FAILED (errors=5)
EEEEE
======================================================================
ERROR: test_process (ClassEval_62_1.NLPDataProcessorTestProcess.test_process)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_62_1.py", line 53, in setUp
    self.processor = NLPDataProcessor()
                     ^^^^^^^^^^^^^^^^
NameError: name 'NLPDataProcessor' is not defined

======================================================================
ERROR: test_process_with_empty_string_list (ClassEval_62_1.NLPDataProcessorTestProcess.test_process_with_empty_string_list)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_62_1.py", line 53, in setUp
    self.processor = NLPDataProcessor()
                     ^^^^^^^^^^^^^^^^
NameError: name 'NLPDataProcessor' is not defined

======================================================================
ERROR: test_process_with_single_word_sentences (ClassEval_62_1.NLPDataProcessorTestProcess.test_process_with_single_word_sentences)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_62_1.py", line 53, in setUp
    self.processor = NLPDataProcessor()
                     ^^^^^^^^^^^^^^^^
NameError: name 'NLPDataProcessor' is not defined

======================================================================
ERROR: test_process_with_stop_words_only (ClassEval_62_1.NLPDataProcessorTestProcess.test_process_with_stop_words_only)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_62_1.py", line 53, in setUp
    self.processor = NLPDataProcessor()
                     ^^^^^^^^^^^^^^^^
NameError: name 'NLPDataProcessor' is not defined

======================================================================
ERROR: test_process_with_stop_words_only_2 (ClassEval_62_1.NLPDataProcessorTestProcess.test_process_with_stop_words_only_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_62_1.py", line 53, in setUp
    self.processor = NLPDataProcessor()
                     ^^^^^^^^^^^^^^^^
NameError: name 'NLPDataProcessor' is not defined

----------------------------------------------------------------------
Ran 5 tests in 0.023s

FAILED (errors=5)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.001s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.001s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.001s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.001s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.001s

OK
EE...E
======================================================================
ERROR: test_text2int (ClassEval_97_0.Words2NumbersTestText2Int.test_text2int)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_97_0.py", line 82, in test_text2int
    self.assertEqual(w2n.text2int("thirty-two"), "32")
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_97_0.py", line 53, in text2int
    raise Exception("Illegal word: " + word)
Exception: Illegal word: thirty-two

======================================================================
ERROR: test_text2int2 (ClassEval_97_0.Words2NumbersTestText2Int.test_text2int2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_97_0.py", line 86, in test_text2int2
    self.assertEqual(w2n.text2int("one hundred and twenty-three"), "123")
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_97_0.py", line 53, in text2int
    raise Exception("Illegal word: " + word)
Exception: Illegal word: twenty-three

======================================================================
ERROR: test_text2int6 (ClassEval_97_0.Words2NumbersTestText2Int.test_text2int6)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_97_0.py", line 102, in test_text2int6
    self.assertEqual(w2n.text2int("one million one hundred sixty-ninth"), "1000169")
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_97_0.py", line 53, in text2int
    raise Exception("Illegal word: " + word)
Exception: Illegal word: sixty-nin

----------------------------------------------------------------------
Ran 6 tests in 0.002s

FAILED (errors=3)
F.F..F
======================================================================
FAIL: test_is_valid_input (ClassEval_97_0.Words2NumbersTestIsValidInput.test_is_valid_input)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_97_0.py", line 107, in test_is_valid_input
    self.assertTrue(w2n.is_valid_input("twenty-five thousand three hundred and forty-two"))
AssertionError: False is not true

======================================================================
FAIL: test_is_valid_input3 (ClassEval_97_0.Words2NumbersTestIsValidInput.test_is_valid_input3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_97_0.py", line 115, in test_is_valid_input3
    self.assertTrue(w2n.is_valid_input("twenty-fifth thousand three hundred and forty-second"))
AssertionError: False is not true

======================================================================
FAIL: test_is_valid_input6 (ClassEval_97_0.Words2NumbersTestIsValidInput.test_is_valid_input6)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_97_0.py", line 127, in test_is_valid_input6
    self.assertTrue(w2n.is_valid_input("fifteenth hundred"))
AssertionError: False is not true

----------------------------------------------------------------------
Ran 6 tests in 0.001s

FAILED (failures=3)
EE...E
======================================================================
ERROR: test_text2int (ClassEval_97_1.Words2NumbersTestText2Int.test_text2int)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_97_1.py", line 73, in test_text2int
    self.assertEqual(w2n.text2int("thirty-two"), "32")
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_97_1.py", line 48, in text2int
    raise Exception("Illegal word: " + word)
Exception: Illegal word: thirty-two

======================================================================
ERROR: test_text2int2 (ClassEval_97_1.Words2NumbersTestText2Int.test_text2int2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_97_1.py", line 77, in test_text2int2
    self.assertEqual(w2n.text2int("one hundred and twenty-three"), "123")
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_97_1.py", line 48, in text2int
    raise Exception("Illegal word: " + word)
Exception: Illegal word: twenty-three

======================================================================
ERROR: test_text2int6 (ClassEval_97_1.Words2NumbersTestText2Int.test_text2int6)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_97_1.py", line 93, in test_text2int6
    self.assertEqual(w2n.text2int("one million one hundred sixty-ninth"), "1000169")
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_97_1.py", line 48, in text2int
    raise Exception("Illegal word: " + word)
Exception: Illegal word: sixty-nin

----------------------------------------------------------------------
Ran 6 tests in 0.002s

FAILED (errors=3)
F.F..F
======================================================================
FAIL: test_is_valid_input (ClassEval_97_1.Words2NumbersTestIsValidInput.test_is_valid_input)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_97_1.py", line 98, in test_is_valid_input
    self.assertTrue(w2n.is_valid_input("twenty-five thousand three hundred and forty-two"))
AssertionError: False is not true

======================================================================
FAIL: test_is_valid_input3 (ClassEval_97_1.Words2NumbersTestIsValidInput.test_is_valid_input3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_97_1.py", line 106, in test_is_valid_input3
    self.assertTrue(w2n.is_valid_input("twenty-fifth thousand three hundred and forty-second"))
AssertionError: False is not true

======================================================================
FAIL: test_is_valid_input6 (ClassEval_97_1.Words2NumbersTestIsValidInput.test_is_valid_input6)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_97_1.py", line 118, in test_is_valid_input6
    self.assertTrue(w2n.is_valid_input("fifteenth hundred"))
AssertionError: False is not true

----------------------------------------------------------------------
Ran 6 tests in 0.001s

FAILED (failures=3)
EE...E
======================================================================
ERROR: test_text2int (ClassEval_97_2.Words2NumbersTestText2Int.test_text2int)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_97_2.py", line 75, in test_text2int
    self.assertEqual(w2n.text2int("thirty-two"), "32")
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_97_2.py", line 49, in text2int
    raise ValueError("Illegal word: %s" % word)
ValueError: Illegal word: thirty-two

======================================================================
ERROR: test_text2int2 (ClassEval_97_2.Words2NumbersTestText2Int.test_text2int2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_97_2.py", line 79, in test_text2int2
    self.assertEqual(w2n.text2int("one hundred and twenty-three"), "123")
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_97_2.py", line 49, in text2int
    raise ValueError("Illegal word: %s" % word)
ValueError: Illegal word: twenty-three

======================================================================
ERROR: test_text2int6 (ClassEval_97_2.Words2NumbersTestText2Int.test_text2int6)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_97_2.py", line 95, in test_text2int6
    self.assertEqual(w2n.text2int("one million one hundred sixty-ninth"), "1000169")
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_97_2.py", line 49, in text2int
    raise ValueError("Illegal word: %s" % word)
ValueError: Illegal word: sixty-nin

----------------------------------------------------------------------
Ran 6 tests in 0.001s

FAILED (errors=3)
F.F..F
======================================================================
FAIL: test_is_valid_input (ClassEval_97_2.Words2NumbersTestIsValidInput.test_is_valid_input)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_97_2.py", line 100, in test_is_valid_input
    self.assertTrue(w2n.is_valid_input("twenty-five thousand three hundred and forty-two"))
AssertionError: False is not true

======================================================================
FAIL: test_is_valid_input3 (ClassEval_97_2.Words2NumbersTestIsValidInput.test_is_valid_input3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_97_2.py", line 108, in test_is_valid_input3
    self.assertTrue(w2n.is_valid_input("twenty-fifth thousand three hundred and forty-second"))
AssertionError: False is not true

======================================================================
FAIL: test_is_valid_input6 (ClassEval_97_2.Words2NumbersTestIsValidInput.test_is_valid_input6)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_97_2.py", line 120, in test_is_valid_input6
    self.assertTrue(w2n.is_valid_input("fifteenth hundred"))
AssertionError: False is not true

----------------------------------------------------------------------
Ran 6 tests in 0.001s

FAILED (failures=3)
EE...E
======================================================================
ERROR: test_text2int (ClassEval_97_3.Words2NumbersTestText2Int.test_text2int)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_97_3.py", line 95, in test_text2int
    self.assertEqual(w2n.text2int("thirty-two"), "32")
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_97_3.py", line 67, in text2int
    raise Exception("Invalid word: %s" % word)
Exception: Invalid word: thirty-two

======================================================================
ERROR: test_text2int2 (ClassEval_97_3.Words2NumbersTestText2Int.test_text2int2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_97_3.py", line 99, in test_text2int2
    self.assertEqual(w2n.text2int("one hundred and twenty-three"), "123")
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_97_3.py", line 67, in text2int
    raise Exception("Invalid word: %s" % word)
Exception: Invalid word: twenty-three

======================================================================
ERROR: test_text2int6 (ClassEval_97_3.Words2NumbersTestText2Int.test_text2int6)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_97_3.py", line 115, in test_text2int6
    self.assertEqual(w2n.text2int("one million one hundred sixty-ninth"), "1000169")
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_97_3.py", line 67, in text2int
    raise Exception("Invalid word: %s" % word)
Exception: Invalid word: sixty-nin

----------------------------------------------------------------------
Ran 6 tests in 0.002s

FAILED (errors=3)
F.F...
======================================================================
FAIL: test_is_valid_input (ClassEval_97_3.Words2NumbersTestIsValidInput.test_is_valid_input)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_97_3.py", line 120, in test_is_valid_input
    self.assertTrue(w2n.is_valid_input("twenty-five thousand three hundred and forty-two"))
AssertionError: False is not true

======================================================================
FAIL: test_is_valid_input3 (ClassEval_97_3.Words2NumbersTestIsValidInput.test_is_valid_input3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_97_3.py", line 128, in test_is_valid_input3
    self.assertTrue(w2n.is_valid_input("twenty-fifth thousand three hundred and forty-second"))
AssertionError: False is not true

----------------------------------------------------------------------
Ran 6 tests in 0.001s

FAILED (failures=2)
FF...F
======================================================================
FAIL: test_text2int (ClassEval_97_4.Words2NumbersTestText2Int.test_text2int)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_97_4.py", line 82, in test_text2int
    self.assertEqual(w2n.text2int("thirty-two"), "32")
AssertionError: 'Invalid input' != '32'
- Invalid input
+ 32


======================================================================
FAIL: test_text2int2 (ClassEval_97_4.Words2NumbersTestText2Int.test_text2int2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_97_4.py", line 86, in test_text2int2
    self.assertEqual(w2n.text2int("one hundred and twenty-three"), "123")
AssertionError: 'Invalid input' != '123'
- Invalid input
+ 123


======================================================================
FAIL: test_text2int6 (ClassEval_97_4.Words2NumbersTestText2Int.test_text2int6)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_97_4.py", line 102, in test_text2int6
    self.assertEqual(w2n.text2int("one million one hundred sixty-ninth"), "1000169")
AssertionError: 'Invalid input' != '1000169'
- Invalid input
+ 1000169


----------------------------------------------------------------------
Ran 6 tests in 0.002s

FAILED (failures=3)
F.F..F
======================================================================
FAIL: test_is_valid_input (ClassEval_97_4.Words2NumbersTestIsValidInput.test_is_valid_input)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_97_4.py", line 107, in test_is_valid_input
    self.assertTrue(w2n.is_valid_input("twenty-five thousand three hundred and forty-two"))
AssertionError: False is not true

======================================================================
FAIL: test_is_valid_input3 (ClassEval_97_4.Words2NumbersTestIsValidInput.test_is_valid_input3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_97_4.py", line 115, in test_is_valid_input3
    self.assertTrue(w2n.is_valid_input("twenty-fifth thousand three hundred and forty-second"))
AssertionError: False is not true

======================================================================
FAIL: test_is_valid_input6 (ClassEval_97_4.Words2NumbersTestIsValidInput.test_is_valid_input6)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_97_4.py", line 127, in test_is_valid_input6
    self.assertTrue(w2n.is_valid_input("fifteenth hundred"))
AssertionError: False is not true

----------------------------------------------------------------------
Ran 6 tests in 0.001s

FAILED (failures=3)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.003s

OK
...FF
======================================================================
FAIL: test_find_longest_word_4 (ClassEval_53_0.LongestWordTestFindLongestWord)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_53_0.py", line 147, in test_find_longest_word_4
    self.assertEqual('apple', longestWord.find_longest_word(sentence))
AssertionError: 'apple' != 'Apple'
- apple
? ^
+ Apple
? ^


======================================================================
FAIL: test_find_longest_word_5 (ClassEval_53_0.LongestWordTestFindLongestWord)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_53_0.py", line 154, in test_find_longest_word_5
    self.assertEqual('apple', longestWord.find_longest_word(sentence))
AssertionError: 'apple' != 'Apple'
- apple
? ^
+ Apple
? ^


----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=2)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
...FF
======================================================================
FAIL: test_find_longest_word_4 (ClassEval_53_1.LongestWordTestFindLongestWord)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_53_1.py", line 145, in test_find_longest_word_4
    self.assertEqual('apple', longestWord.find_longest_word(sentence))
AssertionError: 'apple' != 'Apple'
- apple
? ^
+ Apple
? ^


======================================================================
FAIL: test_find_longest_word_5 (ClassEval_53_1.LongestWordTestFindLongestWord)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_53_1.py", line 152, in test_find_longest_word_5
    self.assertEqual('apple', longestWord.find_longest_word(sentence))
AssertionError: 'apple' != 'Apple'
- apple
? ^
+ Apple
? ^


----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=2)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
...FF
======================================================================
FAIL: test_find_longest_word_4 (ClassEval_53_2.LongestWordTestFindLongestWord)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_53_2.py", line 143, in test_find_longest_word_4
    self.assertEqual('apple', longestWord.find_longest_word(sentence))
AssertionError: 'apple' != 'Apple'
- apple
? ^
+ Apple
? ^


======================================================================
FAIL: test_find_longest_word_5 (ClassEval_53_2.LongestWordTestFindLongestWord)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_53_2.py", line 150, in test_find_longest_word_5
    self.assertEqual('apple', longestWord.find_longest_word(sentence))
AssertionError: 'apple' != 'Apple'
- apple
? ^
+ Apple
? ^


----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=2)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
...FF
======================================================================
FAIL: test_find_longest_word_4 (ClassEval_53_3.LongestWordTestFindLongestWord)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_53_3.py", line 153, in test_find_longest_word_4
    self.assertEqual('apple', longestWord.find_longest_word(sentence))
AssertionError: 'apple' != 'Apple'
- apple
? ^
+ Apple
? ^


======================================================================
FAIL: test_find_longest_word_5 (ClassEval_53_3.LongestWordTestFindLongestWord)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_53_3.py", line 160, in test_find_longest_word_5
    self.assertEqual('apple', longestWord.find_longest_word(sentence))
AssertionError: 'apple' != 'Apple'
- apple
? ^
+ Apple
? ^


----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=2)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
...FF
======================================================================
FAIL: test_find_longest_word_4 (ClassEval_53_4.LongestWordTestFindLongestWord)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_53_4.py", line 143, in test_find_longest_word_4
    self.assertEqual('apple', longestWord.find_longest_word(sentence))
AssertionError: 'apple' != 'Apple'
- apple
? ^
+ Apple
? ^


======================================================================
FAIL: test_find_longest_word_5 (ClassEval_53_4.LongestWordTestFindLongestWord)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_53_4.py", line 150, in test_find_longest_word_5
    self.assertEqual('apple', longestWord.find_longest_word(sentence))
AssertionError: 'apple' != 'Apple'
- apple
? ^
+ Apple
? ^


----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=2)
E
======================================================================
ERROR: test_construct_stop_word_list (ClassEval_62_1.NLPDataProcessorTestConstruct)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_62_1.py", line 7, in setUp
    self.processor = NLPDataProcessor()
NameError: name 'NLPDataProcessor' is not defined

----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (errors=1)
EEEEE
======================================================================
ERROR: test_remove_stop_words (ClassEval_62_1.NLPDataProcessorTestRemove)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_62_1.py", line 16, in setUp
    self.processor = NLPDataProcessor()
NameError: name 'NLPDataProcessor' is not defined

======================================================================
ERROR: test_remove_stop_words_2 (ClassEval_62_1.NLPDataProcessorTestRemove)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_62_1.py", line 16, in setUp
    self.processor = NLPDataProcessor()
NameError: name 'NLPDataProcessor' is not defined

======================================================================
ERROR: test_remove_stop_words_3 (ClassEval_62_1.NLPDataProcessorTestRemove)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_62_1.py", line 16, in setUp
    self.processor = NLPDataProcessor()
NameError: name 'NLPDataProcessor' is not defined

======================================================================
ERROR: test_remove_stop_words_4 (ClassEval_62_1.NLPDataProcessorTestRemove)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_62_1.py", line 16, in setUp
    self.processor = NLPDataProcessor()
NameError: name 'NLPDataProcessor' is not defined

======================================================================
ERROR: test_remove_stop_words_5 (ClassEval_62_1.NLPDataProcessorTestRemove)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_62_1.py", line 16, in setUp
    self.processor = NLPDataProcessor()
NameError: name 'NLPDataProcessor' is not defined

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (errors=5)
EEEEE
======================================================================
ERROR: test_process (ClassEval_62_1.NLPDataProcessorTestProcess)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_62_1.py", line 53, in setUp
    self.processor = NLPDataProcessor()
NameError: name 'NLPDataProcessor' is not defined

======================================================================
ERROR: test_process_with_empty_string_list (ClassEval_62_1.NLPDataProcessorTestProcess)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_62_1.py", line 53, in setUp
    self.processor = NLPDataProcessor()
NameError: name 'NLPDataProcessor' is not defined

======================================================================
ERROR: test_process_with_single_word_sentences (ClassEval_62_1.NLPDataProcessorTestProcess)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_62_1.py", line 53, in setUp
    self.processor = NLPDataProcessor()
NameError: name 'NLPDataProcessor' is not defined

======================================================================
ERROR: test_process_with_stop_words_only (ClassEval_62_1.NLPDataProcessorTestProcess)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_62_1.py", line 53, in setUp
    self.processor = NLPDataProcessor()
NameError: name 'NLPDataProcessor' is not defined

======================================================================
ERROR: test_process_with_stop_words_only_2 (ClassEval_62_1.NLPDataProcessorTestProcess)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_62_1.py", line 53, in setUp
    self.processor = NLPDataProcessor()
NameError: name 'NLPDataProcessor' is not defined

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (errors=5)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.001s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.001s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.001s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.001s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.001s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.001s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.000s

OK
EE...E
======================================================================
ERROR: test_text2int (ClassEval_97_0.Words2NumbersTestText2Int)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_97_0.py", line 155, in test_text2int
    self.assertEqual(w2n.text2int("thirty-two"), "32")
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_97_0.py", line 104, in text2int
    raise Exception("Illegal word: " + word)
Exception: Illegal word: thirty-two

======================================================================
ERROR: test_text2int2 (ClassEval_97_0.Words2NumbersTestText2Int)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_97_0.py", line 159, in test_text2int2
    self.assertEqual(w2n.text2int("one hundred and twenty-three"), "123")
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_97_0.py", line 104, in text2int
    raise Exception("Illegal word: " + word)
Exception: Illegal word: twenty-three

======================================================================
ERROR: test_text2int6 (ClassEval_97_0.Words2NumbersTestText2Int)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_97_0.py", line 175, in test_text2int6
    self.assertEqual(w2n.text2int("one million one hundred sixty-ninth"), "1000169")
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_97_0.py", line 104, in text2int
    raise Exception("Illegal word: " + word)
Exception: Illegal word: sixty-nin

----------------------------------------------------------------------
Ran 6 tests in 0.001s

FAILED (errors=3)
F.F..F
======================================================================
FAIL: test_is_valid_input (ClassEval_97_0.Words2NumbersTestIsValidInput)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_97_0.py", line 180, in test_is_valid_input
    self.assertTrue(w2n.is_valid_input("twenty-five thousand three hundred and forty-two"))
AssertionError: False is not true

======================================================================
FAIL: test_is_valid_input3 (ClassEval_97_0.Words2NumbersTestIsValidInput)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_97_0.py", line 188, in test_is_valid_input3
    self.assertTrue(w2n.is_valid_input("twenty-fifth thousand three hundred and forty-second"))
AssertionError: False is not true

======================================================================
FAIL: test_is_valid_input6 (ClassEval_97_0.Words2NumbersTestIsValidInput)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_97_0.py", line 200, in test_is_valid_input6
    self.assertTrue(w2n.is_valid_input("fifteenth hundred"))
AssertionError: False is not true

----------------------------------------------------------------------
Ran 6 tests in 0.001s

FAILED (failures=3)
EE...E
======================================================================
ERROR: test_text2int (ClassEval_97_1.Words2NumbersTestText2Int)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_97_1.py", line 137, in test_text2int
    self.assertEqual(w2n.text2int("thirty-two"), "32")
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_97_1.py", line 94, in text2int
    raise Exception("Illegal word: " + word)
Exception: Illegal word: thirty-two

======================================================================
ERROR: test_text2int2 (ClassEval_97_1.Words2NumbersTestText2Int)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_97_1.py", line 141, in test_text2int2
    self.assertEqual(w2n.text2int("one hundred and twenty-three"), "123")
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_97_1.py", line 94, in text2int
    raise Exception("Illegal word: " + word)
Exception: Illegal word: twenty-three

======================================================================
ERROR: test_text2int6 (ClassEval_97_1.Words2NumbersTestText2Int)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_97_1.py", line 157, in test_text2int6
    self.assertEqual(w2n.text2int("one million one hundred sixty-ninth"), "1000169")
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_97_1.py", line 94, in text2int
    raise Exception("Illegal word: " + word)
Exception: Illegal word: sixty-nin

----------------------------------------------------------------------
Ran 6 tests in 0.001s

FAILED (errors=3)
F.F..F
======================================================================
FAIL: test_is_valid_input (ClassEval_97_1.Words2NumbersTestIsValidInput)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_97_1.py", line 162, in test_is_valid_input
    self.assertTrue(w2n.is_valid_input("twenty-five thousand three hundred and forty-two"))
AssertionError: False is not true

======================================================================
FAIL: test_is_valid_input3 (ClassEval_97_1.Words2NumbersTestIsValidInput)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_97_1.py", line 170, in test_is_valid_input3
    self.assertTrue(w2n.is_valid_input("twenty-fifth thousand three hundred and forty-second"))
AssertionError: False is not true

======================================================================
FAIL: test_is_valid_input6 (ClassEval_97_1.Words2NumbersTestIsValidInput)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_97_1.py", line 182, in test_is_valid_input6
    self.assertTrue(w2n.is_valid_input("fifteenth hundred"))
AssertionError: False is not true

----------------------------------------------------------------------
Ran 6 tests in 0.001s

FAILED (failures=3)
EE...E
======================================================================
ERROR: test_text2int (ClassEval_97_2.Words2NumbersTestText2Int)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_97_2.py", line 141, in test_text2int
    self.assertEqual(w2n.text2int("thirty-two"), "32")
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_97_2.py", line 96, in text2int
    raise ValueError("Illegal word: %s" % word)
ValueError: Illegal word: thirty-two

======================================================================
ERROR: test_text2int2 (ClassEval_97_2.Words2NumbersTestText2Int)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_97_2.py", line 145, in test_text2int2
    self.assertEqual(w2n.text2int("one hundred and twenty-three"), "123")
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_97_2.py", line 96, in text2int
    raise ValueError("Illegal word: %s" % word)
ValueError: Illegal word: twenty-three

======================================================================
ERROR: test_text2int6 (ClassEval_97_2.Words2NumbersTestText2Int)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_97_2.py", line 161, in test_text2int6
    self.assertEqual(w2n.text2int("one million one hundred sixty-ninth"), "1000169")
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_97_2.py", line 96, in text2int
    raise ValueError("Illegal word: %s" % word)
ValueError: Illegal word: sixty-nin

----------------------------------------------------------------------
Ran 6 tests in 0.001s

FAILED (errors=3)
F.F..F
======================================================================
FAIL: test_is_valid_input (ClassEval_97_2.Words2NumbersTestIsValidInput)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_97_2.py", line 166, in test_is_valid_input
    self.assertTrue(w2n.is_valid_input("twenty-five thousand three hundred and forty-two"))
AssertionError: False is not true

======================================================================
FAIL: test_is_valid_input3 (ClassEval_97_2.Words2NumbersTestIsValidInput)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_97_2.py", line 174, in test_is_valid_input3
    self.assertTrue(w2n.is_valid_input("twenty-fifth thousand three hundred and forty-second"))
AssertionError: False is not true

======================================================================
FAIL: test_is_valid_input6 (ClassEval_97_2.Words2NumbersTestIsValidInput)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_97_2.py", line 186, in test_is_valid_input6
    self.assertTrue(w2n.is_valid_input("fifteenth hundred"))
AssertionError: False is not true

----------------------------------------------------------------------
Ran 6 tests in 0.001s

FAILED (failures=3)
EE...E
======================================================================
ERROR: test_text2int (ClassEval_97_3.Words2NumbersTestText2Int)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_97_3.py", line 181, in test_text2int
    self.assertEqual(w2n.text2int("thirty-two"), "32")
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_97_3.py", line 132, in text2int
    raise Exception("Invalid word: %s" % word)
Exception: Invalid word: thirty-two

======================================================================
ERROR: test_text2int2 (ClassEval_97_3.Words2NumbersTestText2Int)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_97_3.py", line 185, in test_text2int2
    self.assertEqual(w2n.text2int("one hundred and twenty-three"), "123")
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_97_3.py", line 132, in text2int
    raise Exception("Invalid word: %s" % word)
Exception: Invalid word: twenty-three

======================================================================
ERROR: test_text2int6 (ClassEval_97_3.Words2NumbersTestText2Int)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_97_3.py", line 201, in test_text2int6
    self.assertEqual(w2n.text2int("one million one hundred sixty-ninth"), "1000169")
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_97_3.py", line 132, in text2int
    raise Exception("Invalid word: %s" % word)
Exception: Invalid word: sixty-nin

----------------------------------------------------------------------
Ran 6 tests in 0.002s

FAILED (errors=3)
F.F...
======================================================================
FAIL: test_is_valid_input (ClassEval_97_3.Words2NumbersTestIsValidInput)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_97_3.py", line 206, in test_is_valid_input
    self.assertTrue(w2n.is_valid_input("twenty-five thousand three hundred and forty-two"))
AssertionError: False is not true

======================================================================
FAIL: test_is_valid_input3 (ClassEval_97_3.Words2NumbersTestIsValidInput)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_97_3.py", line 214, in test_is_valid_input3
    self.assertTrue(w2n.is_valid_input("twenty-fifth thousand three hundred and forty-second"))
AssertionError: False is not true

----------------------------------------------------------------------
Ran 6 tests in 0.001s

FAILED (failures=2)
FF...F
======================================================================
FAIL: test_text2int (ClassEval_97_4.Words2NumbersTestText2Int)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_97_4.py", line 155, in test_text2int
    self.assertEqual(w2n.text2int("thirty-two"), "32")
AssertionError: 'Invalid input' != '32'
- Invalid input
+ 32


======================================================================
FAIL: test_text2int2 (ClassEval_97_4.Words2NumbersTestText2Int)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_97_4.py", line 159, in test_text2int2
    self.assertEqual(w2n.text2int("one hundred and twenty-three"), "123")
AssertionError: 'Invalid input' != '123'
- Invalid input
+ 123


======================================================================
FAIL: test_text2int6 (ClassEval_97_4.Words2NumbersTestText2Int)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_97_4.py", line 175, in test_text2int6
    self.assertEqual(w2n.text2int("one million one hundred sixty-ninth"), "1000169")
AssertionError: 'Invalid input' != '1000169'
- Invalid input
+ 1000169


----------------------------------------------------------------------
Ran 6 tests in 0.001s

FAILED (failures=3)
F.F..F
======================================================================
FAIL: test_is_valid_input (ClassEval_97_4.Words2NumbersTestIsValidInput)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_97_4.py", line 180, in test_is_valid_input
    self.assertTrue(w2n.is_valid_input("twenty-five thousand three hundred and forty-two"))
AssertionError: False is not true

======================================================================
FAIL: test_is_valid_input3 (ClassEval_97_4.Words2NumbersTestIsValidInput)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_97_4.py", line 188, in test_is_valid_input3
    self.assertTrue(w2n.is_valid_input("twenty-fifth thousand three hundred and forty-second"))
AssertionError: False is not true

======================================================================
FAIL: test_is_valid_input6 (ClassEval_97_4.Words2NumbersTestIsValidInput)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_97_4.py", line 200, in test_is_valid_input6
    self.assertTrue(w2n.is_valid_input("fifteenth hundred"))
AssertionError: False is not true

----------------------------------------------------------------------
Ran 6 tests in 0.001s

FAILED (failures=3)
